### ISSUE TITLE
Analytics Framework and ionic2

### ISSUE THREAD

**Issue by remithomas** [arnesson/cordova-plugin-firebase#1]
Hi!
Could I use the plugin with ionic2 ? ever tested?

The plugin has Analytics Firebase Framework (as I have seen in plugin.xml). If I can use this librairy (?) your are the first plugin integrate it !

**Comment by robertarnesson** [comment]
I have not tested but I see no reason for why it would not work. Right now only FCM is implemented but analytics will follow

**Comment by robertarnesson** [comment]
just added analytics (credit to @chuckv01). feel free to test it!

**Comment by remithomas** [comment]
I have just tested! This is perfect ! Firebase Analytics is integrated ! 
thanks a lot !

**Comment by philipphalder** [comment]
could you share your implementation code?
thanks

**Comment by robertarnesson** [comment]
Just install the plugin, thats all you need to do.
