### ISSUE TITLE
"FirebaseRemoteConfig: Fetch failed! Server responded with an error." without calling or configuring anything related to firebase remote config

### ISSUE THREAD

**Issue by guylando** [arnesson/cordova-plugin-firebase#1010]
Used standard installation of the firebase plugin version 2.0.5 and yet I see in logcat in android device attempts of the app to contact firebase remote config which result in the error below because its not configured. Why are those attempts made automatically without me calling anything?

```
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig: Fetch failed! Server responded with an error.     
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig: com.google.android.gms.internal.firebase_remote_config.zzd: 403 Forbidden  
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig: {
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig:   "code": 403,
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig:   "errors": [
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig:     {
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig:       "domain": "usageLimits",
02-19 15:55:25.119  1924  7067 E FirebaseRemoteConfig:       "message": "Firebase Remote Config API has not been used in project ...
```

**Comment by jamilxt** [comment]
Did you solve this problem? @guylando

**Comment by guylando** [comment]
@jamilxt after looking harder, found that there WAS something related to firebase remote config. Even if you set debug config it is already using remote config.

**Comment by jamilxt** [comment]
Yeah, It's because of new rules given by Google to enable API for remote config. https://firebase.google.com/support/release-notes/android . But the thing is: even though my api is enabled, I am getting the error. :(

**Comment by guylando** [comment]
It is a network error so try to turn a sniffer and capture the network request which gets an error response and then you might see the exact error message google sends in the response

**Comment by jamilxt** [comment]
Is there any library for that? can you please give me something to dig in?

**Comment by guylando** [comment]
You need to find a way to intercept the traffic. Since its probably https traffic, you probably should use a proxy like burp and install his root ca certificate on the device. To make the device connect to burp you can either use:
https://play.google.com/store/apps/details?id=org.proxydroid&hl=en
or https://support.portswigger.net/customer/portal/articles/2899081-using-burp-s-invisible-proxy-settings-to-test-a-non-proxy-aware-thick-client-application
which was suggested here https://support.portswigger.net/customer/portal/questions/17325237-how-can-i-test-native-application-through-burp-suite-
or use emulator and configure the emulator proxy settings.

Please write back which method worked for you, will be interesting to know

**Comment by jamilxt** [comment]
@guylando Thank you so much. I will give it a try then and let you know.

**Comment by QuartzSupport** [comment]
Hi @jamilxt, did you resolve it ?
I'm facing the same problem, Remote Config API is enabled but still getting 403 errors.

**Comment by QuartzSupport** [comment]
Ok, for me the Android API key was restricted to certain SDKs (Maps, etc.).
I had to add Remote Config to the authorized APIs for the key (Google APIs console).

**Comment by jamilxt** [comment]
> Ok, for me the Android API key was restricted to certain SDKs (Maps, etc.).
> I had to add Remote Config to the authorized APIs for the key (Google APIs console).

My problem is not solved yet.
How to do that?

**Comment by QuartzSupport** [comment]
You can find the Google APIs console here : https://console.developers.google.com/apis/credentials
Then, you have to select your "Android key (auto created by Google Service)" and remove restrictions or add "Firebase Remote Config" to the ones set.

![image](https://user-images.githubusercontent.com/49270994/55560873-731e8d80-56f1-11e9-8529-d47850b7c020.png)

**Comment by jamilxt** [comment]
@QuartzSupport Do I've to change anything on my App? I am getting same error.

**Comment by QuartzSupport** [comment]
Do you have latest Remote Config version ? I also downloaded the “google-services.json” file again.

If error still persists, contact Firebase support ;) 

( <https://firebase.google.com/support/release-notes/android> https://firebase.google.com/support/release-notes/android)

 

 

De : Jamilur Rahman <notifications@github.com> 
Envoyé : jeudi 4 avril 2019 16:07
À : arnesson/cordova-plugin-firebase <cordova-plugin-firebase@noreply.github.com>
Cc : QuartzSupport <support.quartz@snef.fr>; Mention <mention@noreply.github.com>
Objet : Re: [arnesson/cordova-plugin-firebase] "FirebaseRemoteConfig: Fetch failed! Server responded with an error." without calling or configuring anything related to firebase remote config (#1010)

 

@QuartzSupport <https://imsva91-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fQuartzSupport&umid=A697ADCF-85B4-F405-8FB2-E871337B75AD&auth=eec30552ffa3a26ff0518f7e2c2b941edd490436-73394938bd3693376480e63dadd8f3048674861a>  Do I've to change anything on my App? I am getting same error.
