### ISSUE TITLE
Firebase web goes offline when using Cordova Plugin Firebase together

### ISSUE THREAD

**Issue by juanbernabo** [arnesson/cordova-plugin-firebase#102]
Hi guys,

I'm experiencing a little disconcerting problem. We have a web app working with firebase web and when
we tried to integrate with Cordova Plugin Firebase, the moment that cordova initializes and we get the token for notifications our firebase connection goes offline. When we force the app to go to background it's connection status goes online and when we get it to foreground again it goes to offline... pretty wierd.

Someone had something like this before?
How can we solve this?

Thanks,
Juan.

**Comment by philipphalder** [comment]
With Firebase Web - do you mean the firebase-js-sdk?
i think i am facing the same issue. happy if someone could help :)

**Comment by robertarnesson** [comment]
what do you use from the web sdk that is not available though the plugin? its probably not a good idea to use both sdk's at the same time. the best solution would be to integrate any missing features into this plugin so that you don't need to use both.

**Comment by Suven** [comment]
Hey,

just wanted to mention that I am also using both with version 0.1.9 of this plugin and never faced this issue.

I am using the push-stuff of the plugin and auth + db from the js-sdk.

**Comment by khayalan-mathew** [comment]
@robertarnesson We need all the commands for the realtime-database... 
Im not sure if im experiencing the same issue but logging events dont work at my device so i think so :)

**Comment by juanbernabo** [comment]
@robertarnesson I'm using all the database and auth part, my app is a webapp that can be used also embeded in cordova so I cannot use all native cordova stuff.

**Comment by toddmedema** [comment]
Chiming in here, setting our app up for the first time. Our app is a web + Android + iOS app, and it looks like this plugin breaks / doesn't work on web?

Can we please fix that / make this work on web too? Not too thrilled about having to deal with multiple firebase libraries (I'm sure nobody here is), and it seems like a pretty straightforward fix - have the Android / iOS specific functions (like notifications) become stubs / empty functions when not available. Could even have the use pass in a param on initialization or run a special function (ie `FirebasePlugin.disableNativeFunctionality()`), would still be much better than trying to work with two plugins

**Comment by soumak77** [comment]
closing for cleanup, please re-open if this is still an issue
