### ISSUE TITLE
Cannot run on iOS 12.2 but works without any problems on android and iOS 10.3.3 

### ISSUE THREAD

**Issue by Hassan1984** [arnesson/cordova-plugin-firebase#1041]
Hej Guys 

I have a cordova app with  cordova-plugin-firebase version: 2.0.5. The plugin is working fine on android and on iOS 10.3.3. The notifications are received without any problems both from firebase and our notification server.  

The problem is with iOS 12. On iOS 12.2 the app starts up fine, runs the grantpersmission code and the user is prompted with grant permission dialogue but when trying to acquire token as following:

`        window.FirebasePlugin.getToken(function (token) {
            backend_registration(token);
            console.log(token);
        }, function (error) {
            console.error(error);
        });`

the getToken/onTokenRefresh callback is never called and the app crashes. If I comment the code out for registering the app for push the app doesnt crash.  

Cordova-cli: 7.1.0
Cordova-ios: 4.5.5

[XcodeLog.txt](https://github.com/arnesson/cordova-plugin-firebase/files/3067765/XcodeLog.txt)

**Comment by globules-io** [comment]
hey sorry to say that the issue is on your end. It works here on iOS12.2 except I'm still getting foreground notifications when the app is running but other than that, it works.
cli@7.1 + iOS@5.0.0 
Maybe upgrade to iOS@5.0.0 ?

**Comment by Hassan1984** [comment]
@globules-io Already tried with ios 5.0.0 with no success. The wierd thing is it works on ios 10.3.3

**Comment by globules-io** [comment]
Have you set your Firebase/APNs properly ?

**Comment by Hassan1984** [comment]
Yes i think so. It would not work in iOS 10.3.3 if firebase was not setup right. I have set it up with certificates (p12) for both development and production.

**Comment by globules-io** [comment]
Then I'm pretty sure you did not set your build system in Xcode to legacy

**Comment by Hassan1984** [comment]
Yes i build it with legacy build system and GoogleService-info.plist copied to resources folder too.

**Comment by globules-io** [comment]
`[Firebase/InstanceID][I-IID003014] Error while reading embedded
mobileprovision Error Domain=NSCocoaErrorDomain Code=260 "The file
“embedded.mobileprovision” couldnʼt be opened because there is no such
file." UserInfo={NSFilePath=/var/containers/Bundle/Application/
A81F8DFB-0FC0-401E-8256-C9224728F710/MyApp.app/
embedded.mobileprovision, NSUnderlyingError=0x280cb1cb0 {Error
Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by globules-io** [comment]
Pretty sure your issue is related to provisioning...

**Comment by Hassan1984** [comment]
I am using the same provisioning profiles in iOS 10 and iOS 12.

**Comment by Hassan1984** [comment]
Just logged in to my apple developer account and can see that my provisioning profiles are expired. Just activated them again. Do I need to download and import the provisioning profiles again on my mac?

**Comment by globules-io** [comment]
They need to be in your keychain yes

**Comment by Hassan1984** [comment]
But why is app on 10.3.3 working with the same provisioning profiles. Can it be that at the time I built the app on 10.3.3 that my provisioning profiles was still active?

**Comment by Hassan1984** [comment]
Just built the app again on 10.3.3 and it still works with same provisioning profiles.

**Comment by Hassan1984** [comment]
Still the same behavior after importing the provisioning profiles. Works fine on iOS 10 and crashes in iOS 12

**Comment by globules-io** [comment]
You probably didn't regenerate the APN Development SSL Certificate & Production SSL Certificate from https://developer.apple.com/account/ios/identifier/bundle/edit/

**Comment by yearsalary** [comment]
> `[Firebase/InstanceID][I-IID003014] Error while reading embedded mobileprovision Error Domain=NSCocoaErrorDomain Code=260 "The file “embedded.mobileprovision” couldnʼt be opened because there is no such file." UserInfo={NSFilePath=/var/containers/Bundle/Application/ A81F8DFB-0FC0-401E-8256-C9224728F710/MyApp.app/ embedded.mobileprovision, NSUnderlyingError=0x280cb1cb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

[https://github.com/arnesson/cordova-plugin-firebase/issues/970#issuecomment-453819328](url)
this is worked for me

**Comment by Hassan1984** [comment]
I have changed to use authentication key instead of certificate and the behavior is still the same. Works in iOS 10 but not in iOS 12. Built with legacy build system. Remote notifications enabled. And push notification enabled.

**Comment by Hassan1984** [comment]
I got it working. I appreciate you guys took your time to hep me. Thank you very much.

**Comment by Hassan1984** [comment]
I can get the notification to work partially when the app is in background. 
If i send the notification payload as following: 

`{
  "to": "your device token",
  "priority": "high",
  "data": {
    "message": "2",
    "title": "1"
  },
  "notification": {
    "title": "1",
    "body": "2",
    "priority": "high"
  }
}`

then the app receives the notification in notification tray. If clicked on notification then the app opens up and execute some code. 

The other way is as following:

`{
  "to": "Your device token",
  "content_available": true,
  "priority": "high",
  "data": {
    "message": "",
    "title": ""
  }
}`

then the app receives the notification silently but the code is first executed when one opens up the app.

Haven't find any solution for when app receives notification silently and executes code at once without opening the app.
