### ISSUE TITLE
window.FirebasePlugin is undefined

### ISSUE THREAD

**Issue by Sjoerrdd** [arnesson/cordova-plugin-firebase#1049]
**Describe the bug**
I'm using this plugin in an Cordova project with Vue.JS

**To Reproduce**
1. Install the plugin
2. Console.log(window.FirebasePlugin) in mounted() (mounted is the vuejs ready listener)

**Expected behavior**
It has to work

**Console Logs**
Uncaught (in promise) TypeError: Cannot read property 'onTokenRefresh' of undefined
    at VueComponent.tokencheck (Login.vue?7463:89)
    at VueComponent._callee2$ (Login.vue?7463:82)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:271)
    at Generator.prototype.(:8100/anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (asyncToGenerator.js?3b8d:5)
    at _next (asyncToGenerator.js?3b8d:27)
**Plugin Version**
Run `cordova plugin list` to find out what version of cordova-plugin-firebase you are running with

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 0.60.48

**Smartphone (please complete the following information):**
 - Device: Galaxy S10+
 - OS: Android 9
 - Browser Samsung Internet
 - Version Latest

**Comment by ryanmtaylor** [comment]
Just curious, it shouldn't be defined for the web browser only for phones – is that your issue?

**Comment by Sjoerrdd** [comment]
That's possible, I'll try it friday ;) 
Thank you @ryanmtaylor

**Comment by A6Brgeuka** [comment]
Try to remove your app from device and install again.
I guess you need to reinstall your app once you added a plugin

**Comment by Sjoerrdd** [comment]
Thank you
