### ISSUE TITLE
Unable to expand notifications from android notification drawer

### ISSUE THREAD

**Issue by iamntg** [arnesson/cordova-plugin-firebase#105]
Hi,

Is there any ways to expand the notifications messages if it is larger or multiline?
something like the Gmail notifications.

please check the example
![06-android-50-lock-screen-expanded-100530536-large idge](https://cloud.githubusercontent.com/assets/19806010/20523783/c665e596-b0dc-11e6-96dd-37a9f21dd1e7.jpg)

**Comment by Tertiush** [comment]
Did you ever get a fix for this? I'm having a similar issue, my text does not fit and is cut off in the title. thanks

**Comment by soumak77** [comment]
closing for cleanup, please re-open if this is still an issue
