### ISSUE TITLE
Firebase Analytics and Cloud Messaging with Capacitor

### ISSUE THREAD

**Issue by mrahmadt** [arnesson/cordova-plugin-firebase#1054]
Hello Everyone

I'm trying to setup Firebase Analytics and FCM using Capacitor, any chance someone did this before? can you share with me your experience? does this plugin work with capacitor/ionic 4?

Thanks

**Comment by stewwan** [comment]
Just released this for analytics, for those who are struggled

https://github.com/stewwan/capacitor-analytics

**Comment by mrahmadt** [comment]
Just to update everyone, Capacitor now supports FCM for iOS and Android without any external plugin

https://capacitor.ionicframework.com/docs/guides/push-notifications-firebase
