### ISSUE TITLE
token = null on android

### ISSUE THREAD

**Issue by jvwelzen** [arnesson/cordova-plugin-firebase#106]
when i build the app using sencha touch 2.3.1with PGB ios is working fine but on android the token remains null

also if i examen the .apk file it seems that google-services.json does not exist in the .apk file

**Comment by robertarnesson** [comment]
PGB is not supported. see the docs.

**Comment by jvwelzen** [comment]
Notes about PhoneGap Build

Hooks does not work with PhoneGap Build. This means you will have to manually make sure the configuration files are included. One way to do that is to make a private fork of this plugin and replace the placeholder config files (see src/ios and src/android) with your actual ones.

**Comment by jvwelzen** [comment]
I have made a fork and replaced the config files, on ios it seems to be working fine

**Comment by robertarnesson** [comment]
everything that the hook script would normally do you have to do yourself

**Comment by jvwelzen** [comment]
why is GoogleService-Info.plist placed in the right place and google-services.json doesn't

**Comment by jvwelzen** [comment]
seems that the google-services.json was in the right place, but you also have to hard code your android app id and your web api key in the plugin.xml
