### ISSUE TITLE
Not working on cocoon

### ISSUE THREAD

**Issue by letmaik** [arnesson/cordova-plugin-firebase#107]
I'm having trouble getting this to work on cocoon.io.  Without it, it works, but with it I get error messages like `11-14 22:07:06.642 W/FA (12263): Measurement Service called with unknown id version: @2131230845`.

See also this discussion in the cocoon forums:
https://forums.cocoon.io/t/firebase-analytics-plugin-not-working/4159

I'm not really sure on which end the problem lies, so a positive confirmation of this working in cocoon would be good. Or otherwise, any hint what the problem could be would also be great.

**Comment by robertarnesson** [comment]
are you building locally or using their equivalent of phonegap build? if the latter i suspect that they also do not support hooks and you'd have to manually copy config files in place and hard code your firebase app id and api key in plugin.xml

**Comment by letmaik** [comment]
I'm using the cloud build thing. But it looks like they do support hooks, see https://forums.cocoon.io/t/how-can-i-compile-in-cocoon-with-plugins/4001/3

**Comment by letmaik** [comment]
It seems that contrary to what they say, cocoon currently can't do hooks (see [forum](https://forums.cocoon.io/t/hooks-not-working/4372/1)). So I tried your suggestion and hard-coding the values in plugin.xml and that works. It is not necessary to copy the json file over, at least on Android (haven't used cocoon for ios).
