### ISSUE TITLE
Cannot find symbol import android.support.v4.app.NotificationManagerCompat

### ISSUE THREAD

**Issue by mishkeTz** [arnesson/cordova-plugin-firebase#1082]
Hi,
Few days ago I had a problem described in #1058 when building an app, and I fixed it when I followed the steps they suggested. But today when I tried to build for the release I got another error and I can't find the solution for it.

> Task :app:compileReleaseJavaWithJavac FAILED
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:9: error: cannot find symbol
import android.support.v4.app.NotificationManagerCompat;
                             ^
  symbol:   class NotificationManagerCompat
  location: package android.support.v4.app
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:11: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:358: error: cannot find symbol
                    NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(context);
                    ^
  symbol: class NotificationManagerCompat
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:358: error: cannot find symbol
                    NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(context);
                                                                          ^
  symbol: variable NotificationManagerCompat
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:144: error: package NotificationCompat does not exist
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                              ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:144: error: package NotificationCompat does not exist
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                                                                                   ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:153: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_MAX);
                                 ^
  symbol:   variable NotificationCompat
  location: class FirebasePluginMessagingService
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:149: error: package NotificationCompat does not exist
                    .setStyle(new NotificationCompat.BigTextStyle().bigText(messageBody))
                                                    ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:148: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                                   ^
  symbol:   variable NotificationCompat
  location: class FirebasePluginMessagingService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 13s
33 actionable tasks: 5 executed, 28 up-to-date
(node:6280) UnhandledPromiseRejectionWarning: Error: D:\Cordova\MyApp\platforms\android\gradlew: Command failed with exit code 1 Error output:
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:9: error: cannot find symbol
import android.support.v4.app.NotificationManagerCompat;
                             ^
  symbol:   class NotificationManagerCompat
  location: package android.support.v4.app
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:11: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                           ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:358: error: cannot find symbol
                    NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(context);
                    ^
  symbol: class NotificationManagerCompat
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:358: error: cannot find symbol
                    NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(context);
                                                                          ^
  symbol: variable NotificationManagerCompat
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:144: error: package NotificationCompat does not exist
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                              ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:144: error: package NotificationCompat does not exist
            NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, channelId);
                                                                                   ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:153: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_MAX);
                                 ^
  symbol:   variable NotificationCompat
  location: class FirebasePluginMessagingService
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:149: error: package NotificationCompat does not exist
                    .setStyle(new NotificationCompat.BigTextStyle().bigText(messageBody))
                                                    ^
D:\Cordova\MyApp\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:148: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                                   ^
  symbol:   variable NotificationCompat
  location: class FirebasePluginMessagingService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 13s
at ChildProcess.whenDone (D:\Cordova\MyApp\node_modules\cordova-common\src\superspawn.js:135:23)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at ChildProcess.cp.emit (D:\Cordova\MyApp\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:915:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:6280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by madzgo** [comment]
Go to platforms/android/cordova-plugin-firebase/<your app name>-build.gradle
and change
`compile 'com.google.firebase:firebase-auth:+'`
to
`compile 'com.google.firebase:firebase-auth:16.+'`

**Comment by peterpeterparker** [comment]
I faced that error too today. Related in https://github.com/arnesson/cordova-plugin-firebase/issues/1081

**Comment by Swamp3** [comment]
Had to add support for androidx and it started working again.

**Comment by mishkeTz** [comment]
@madzgo That didn't work for me. I was able to fix it with this hook [#1083 (comment)](https://github.com/arnesson/cordova-plugin-firebase/issues/1083#issuecomment-503224816)

This worked for me.

**Comment by bipoza** [comment]
> @madzgo That didn't work for me. I was able to fix it with this hook [#1083 (comment)](https://github.com/arnesson/cordova-plugin-firebase/issues/1083#issuecomment-503224816)
> 
> This worked for me.

Thank you @mishkeTz , really work again.

**Comment by bookwarmdev** [comment]
You should add Androidx plugin to your project but running:

cordova plugin add cordova-plugin-androidx-adapter

https://github.com/dpa99c/cordova-plugin-androidx-adapter

**Comment by abdullahredmi** [comment]
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0.aar\22aa073af2ef0accc73c2c9bd5dbe95e\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or 23 actionable tasks: 1 executed, 22 up-to-date
--debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Command finished with error code 1: D:\Base\mobileapp\platforms\android\gradlew cdvBuildDebug,-b,D:\Base\mobileapp\platforms\android\build.gradle
D:\Base\mobileapp\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0.aar\22aa073af2ef0accc73c2c9bd5dbe95e\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Error: D:\Base\mobileapp\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\User\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0.aar\22aa073af2ef0accc73c2c9bd5dbe95e\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
    at ChildProcess.whenDone (D:\Base\mobileapp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:135:23)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (D:\Base\mobileapp\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
