### ISSUE TITLE
plugin not compatible with cordova-plugin-code-push

### ISSUE THREAD

**Issue by hugoblanc** [arnesson/cordova-plugin-firebase#1086]
**Describe the bug**
This plugin is not working with [cordova-plugin-code-push](https://github.com/microsoft/cordova-plugin-code-push)

Build fail on android (not tested ios)

**To Reproduce**
1. start new ionic/cordova project
2. ionic cordova plugin add cordova-plugin-code-push
3. ionic cordova plugin add cordova-plugin-firebase
4. ionic cordova build android

**Expected behavior**
A working build

**Build failed**

`Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.`
`> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1,2.3]"`

`but isn't being resolved to that version. Behavior exhibited by the library will be unknown.`
`Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2.3.`

  `The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the artsitive dependencies that lead to the art
  ifact with the issue.`

  `-- Project 'app' depends onto net.minidev:json-smart@2.3`
  `-- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@5.1`

**Plugin Version**
`cordova plugin list` 

> code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-android-fingerprint-auth 1.5.0 "FingerprintAuth"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.0.2 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.19 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-lib 4.0.1 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-pin-dialog 0.1.3 "PinDialog"
cordova-plugin-qrscanner 2.6.2 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

**Desktop (please complete the following information):**

> Ionic:

  >  ionic (Ionic CLI)  : 4.2.0 (C:\Users\hugob\AppData\Local\Yarn\Data\global\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

> Cordova:

   > cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 20 other plugins)

> System:

 > (C:\Users\hugob\AppData\Local\Android\android-sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

**Smartphone (please complete the following information):**

Plugins are independently working well (code-push alone or firebase alone)

**Comment by lislamov** [comment]
according to [https://github.com/microsoft/react-native-code-push/issues/1448#issuecomment-501936547](https://github.com/microsoft/react-native-code-push/issues/1448#issuecomment-501936547)

This worked for me.
Modify this line to your *.gradle in the /platforms/android/cordova-plugin-code-push/

compile 'com.nimbusds:nimbus-jose-jwt:5.1' ->
compile('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

**Comment by hugoblanc** [comment]
Didn't expect to find solution into react issue. Thanks a lot, it's working
