### ISSUE TITLE
push not received on ios 9.3.5 on background

### ISSUE THREAD

**Issue by jvwelzen** [arnesson/cordova-plugin-firebase#109]
push message is not displayed when running on ios 9.3.5 on background.

when I open the app after the push message the onNotificationOpen is triggert 

on ios 10.1.1 it's working fine.

also onNotificationOpen  is not triggert on android when in the foreground

**Comment by jvwelzen** [comment]
nevermind upgraded my iphone to 10.1.1 and still not working :-(

some thing to sort out

**Comment by abubakarsaeed** [comment]
Add this code to your didFinishLaunchingWithOptions function in AppDelegate.m file in Xcode:

if ([application respondsToSelector:@selector(isRegisteredForRemoteNotifications)])
    {
        // for iOS>8
        [application registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];
        [application registerForRemoteNotifications];
    }

Hope it works!
