### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by raducostea** [arnesson/cordova-plugin-firebase#11]
I am getting the following error when i try to compile:

> GoogleIPhoneUtilities(GIPReachability.o)
> duplicate symbol _OBJC_IVAR_$_GIPReachability.monitoring_ in:
>     /Users/radumac/ionic/ionic-ctm/platforms/ios/CTM App/Plugins/phonegap-plugin-push/GCM/Libraries/libGIP_Reachability.a(GIPReachability.o)
>     CTM App/Plugins/cordova-plugin-firebase/GoogleIPhoneUtilities.framework/GoogleIPhoneUtilities(GIPReachability.o)
> duplicate symbol _OBJC_IVAR_$_GIPReachability.hostName_ in:
>     /Users/radumac/ionic/ionic-ctm/platforms/ios/CTM App/Plugins/phonegap-plugin-push/GCM/Libraries/libGIP_Reachability.a(GIPReachability.o)
>     CTM App/Plugins/cordova-plugin-firebase/GoogleIPhoneUtilities.framework/GoogleIPhoneUtilities(GIPReachability.o)
> ld: 504 duplicate symbols for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am using:
Node version: v4.4.1
Cordova version: 6.2.0
Xcode 7.3
Build version 7D175

**Comment by neosekar** [comment]
Once i build android , i got build failed with this message

**UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
 FAILED
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.**

**Comment by victorcpereira** [comment]
I've got the same message as @neosekar.

**Comment by robertarnesson** [comment]
what other plugins are you using?

**Comment by robertarnesson** [comment]
it looks like @raducostea is using push plugin which is not compatible with this plugin since they do the same thing. IE use this plugin for push notifications as well and remove push plugin

**Comment by victorcpereira** [comment]
I'm using Ionic with the following plugins:

- cordova-plugin-crosswalk-webview 1.5.0 "Crosswalk WebView Engine"
- cordova-plugin-customurlscheme 4.2.0 "Custom URL scheme"
- cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
- cordova-plugin-splashscreen 3.1.0 "Splashscreen"
- cordova-plugin-statusbar 2.1.3 "StatusBar"
- cordova-plugin-whitelist 1.2.2 "Whitelist"
- cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
- phonegap-facebook-plugin 0.12.0 "Facebook Connect"

**Comment by robertarnesson** [comment]
I'd guess you have a duplicate dependency somewhere, see my comment in https://github.com/arnesson/cordova-plugin-firebase/issues/9

**Comment by neosekar** [comment]
I am using cordova google plus plugin  along with firebase plugin . In android build, it returns duplicate google_app_id in strings.xml and build has failed.

**Comment by alexbuijs** [comment]
The builds also fail with duplicate google_app_id in strings.xml in Android with the phonegap-plugin-push plugin installed.

**Comment by robertarnesson** [comment]
@alexbuijs this plugin is not compatible with phonegap-plugin-push plugin
