### ISSUE TITLE
Is it possible to tirigger a slient push

### ISSUE THREAD

**Issue by jvwelzen** [arnesson/cordova-plugin-firebase#110]
I read on iOs that it should be possible to trigger a silent push, but it's only working in the foreground, or only triggers when in the foreground

**Comment by robertarnesson** [comment]
you can set sound: false and vibrate: false in the notification payload when you send it from your backend.

**Comment by t2wu** [comment]
I'm trying it on iOS. It seems like I receive the silent notification on the native part. But the code doesn't get ran in JavaScript unless I start setting breakpoints in the native code. It may have been suspended before it can be ran. Any pointers?
