### ISSUE TITLE
Detect data onlick notification [ Android ]

### ISSUE THREAD

**Issue by mathieu21** [arnesson/cordova-plugin-firebase#111]
So the question has already been asked but nothing cleared came out of it : 

Can we execute pass a parameter / data anything that we can detect when opening the app.

Simply I am sending a notification to my user and i would like to pass a parameter that i can detect when opening the app and execute a script according to the parameter.

Thanks for the help on this :)

**Comment by device68** [comment]
Yes that's easy using server-side scripts and Curl:

Example

```
$message['from'] = GCM_SENDER_ID; // not sure if this is needed
$message['to'] = $token; // the device token you are sending to
$message['priority'] = 'high';

$message['notification']['title'] ='Live Chat Message';
$message['notification']['body'] ='Hello, this is a demo chat message from someone';
$message['notification']['sound'] = 'default';
$message['notification']['icon'] ='notify_icon'; // the icon you want to use (Android only)
$message['notification']['color'] ='#E72B2B'; // the colour of the icon (Android only)

// Your name and value pairs go in the 'data' array.
// Your app can process these values using regular JS
// from within onNotificationOpen functions

$message['data']['app_user'] = 'a user name';
$message['data']['app_acc_id'] = 123456;
$message['data']['app_page'] = 'app_chat';

//etc

$send = json_encode($message);
```

// The above payload is sent to Googles Firebase server using Curl. See their docs for instructions.

Handling if the notification was tapped.

With iOS it's easy to handle this request as any notification that is 'tapped' sets the 'tap' variable of the payload to tap = 1 when the app is opened.  If it's not tapped it stays as tap = 0;

With Android it's a little more awkward. tap = 0 is set by default for any notification received by the app when it's in the foreground. However If the notification was tapped, it will set some additional variables in the payload which you can use to distinguish between the two. For example the 'collapse_key' is added for any tapped notification.
