### ISSUE TITLE
GoogleService failed to initialize

### ISSUE THREAD

**Issue by GabrielOtero** [arnesson/cordova-plugin-firebase#112]
I did every step as said and I got this error:

```"GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id."```

My google-service.json is located in the right place:

<img width="255" alt="screen shot 2016-12-04 at 12 38 35" src="https://cloud.githubusercontent.com/assets/2881903/20866875/a58232f8-ba1e-11e6-9cee-2b3cf4791a08.png">

The hook works:

<img width="283" alt="screen shot 2016-12-04 at 12 41 24" src="https://cloud.githubusercontent.com/assets/2881903/20866890/0fb68624-ba1f-11e6-9dcf-05898a90dfa1.png">

But I still got the error and cant user firebase plugin:

<img width="990" alt="screen shot 2016-12-04 at 12 40 34" src="https://cloud.githubusercontent.com/assets/2881903/20866891/204d55a8-ba1f-11e6-91c0-8aa086fbc1ff.png">

What am I doing wrong?

**Comment by robertarnesson** [comment]
it looks like you are using multiple plugins for firebase (cordova-plugin-firebase and cordova-plugin-firebase-hooks). You should only use this plugin
