### ISSUE TITLE
OnNotificationOpen callback does not work when the application is background

### ISSUE THREAD

**Issue by jnazima** [arnesson/cordova-plugin-firebase#113]
My callback function does not work when the app is background. When is foreground, it's ok.

Client-side
window.FirebasePlugin.onNotificationOpen(function(notification){
       alert(JSON.stringify(notification));
    }, function(error) {
      alert("Erro: "+error);
      // console.error(error);
    });

**Comment by fabianVeliz** [comment]
The same problem here

**Comment by saghul** [comment]
You need to attach the callback again on the resume application event.

**Comment by robertarnesson** [comment]
try with this pull req: https://github.com/arnesson/cordova-plugin-firebase/pull/123
