### ISSUE TITLE
is this abandoned?

### ISSUE THREAD

**Issue by Zrny** [arnesson/cordova-plugin-firebase#1135]
i dont see any updates reflectin fails of builds on cordova 9

**Comment by raco** [comment]
yes

**Comment by kevinswartz** [comment]
@dpa99c made a great fork of this that's actively maintained.  I've been using it in production for 3-4 months, and it's been working great so far.  https://github.com/dpa99c/cordova-plugin-firebasex

**Comment by Zrny** [comment]
i know, i am using exactly that one :)
i was just curious :)
