### ISSUE TITLE
verify if notifications are allowed

### ISSUE THREAD

**Issue by voidbrain** [arnesson/cordova-plugin-firebase#114]
iOS10
1) **window.FirebasePlugin.grantPermission()** the first time I open the app it asks me to allow notifications (correct) but how can i check if permissions are allowed in the phone settings?
How can i tell if user went to settings and disallowed notifications?

2) **window.FirebasePlugin.setBadgeNumber()** works only if app is in foreground, I never see the badge number while app is in background. How can i tell to increment the number when I receive notification in phone system?

3) **window.FirebasePlugin.onNotificationOpen()** if app is in background or in foreground, all is ok, I can pass data inside the notification and read it when i open the app, but it doesn't works if app is closed (notification works but no data is passed). I also tried to put the function in the document.addEventListener("resume") event listener but it doesn't work

**Comment by chanphillip** [comment]
Currently this plugin does not provide the interface to check if the user has allowed notification.
I hope this function will be available soon!

**Comment by robertarnesson** [comment]
it does now if you get this change: https://github.com/arnesson/cordova-plugin-firebase/pull/152

2): you can set a badge number from the notification payload. See the firebase docs on the server side api.

3): is this on android? should be fixed in https://github.com/arnesson/cordova-plugin-firebase/pull/153

**Comment by robertarnesson** [comment]
fixed in 0.1.20
