### ISSUE TITLE
iOS Push Notification Not working

### ISSUE THREAD

**Issue by rakeshaset** [arnesson/cordova-plugin-firebase#117]
Hi,

I performed steps as sugegsted in the pluin page. 

1: Ran Plugin command .
2: Added Google Plist file in project root folder .

When i install my IPA from tunes to my iPhone , i am not able to see my app under Apples Notification Tab.

One thing is i am able to receive Notification Token. But when i am trying to push notification to the generated token it's not going.

Am i missing anything? Please let me know.

I am using Apples Development Provision Profile. Not the production one yet.

Thanks in advance.

**Comment by mbkinnovo** [comment]
I had the same issue... I think it is related to that the Push rights are not requested before the app finished loading. In the firebase documentation it says: 

> for devices running iOS 10 and above, you must assign your delegate object to the UNUserNotificationCenter object to receive display notifications, and the FIRMessaging object to receive data messages, before your app finishes launching. For example, in an iOS app, you must assign it in the applicationWillFinishLaunching: or applicationDidFinishLaunching: method.

 Source: https://firebase.google.com/docs/cloud-messaging/ios/client

But I might be wrong!

**Comment by rakeshaset** [comment]
Thanks mbkinnovo let me check if this helps.

Moreover when i try adding below mentioned line it gives me Firebase module not found error.

@import Firebase;

Do we need to add these lines when we are running this plugin. My assumption is this is already taken care by this plugin.

Thanks
Rakesh

**Comment by rakeshaset** [comment]
Working fine after adding Swift code.

**Comment by mbkinnovo** [comment]
Can you elaborate on that?

**Comment by elewin** [comment]
Yes, please share your wisdom!

**Comment by FreezyExp** [comment]
what swift code where?

**Comment by rakeshaset** [comment]
Hi All,

Sorry I missed that we already had a method to grantPermission when using iOS . So i added my own swift code mentioned in Firebase website to grant permission to my app for push notification on user device.

After adding grantPermission method on my device ready everything is working as expected. I removed swift code which i added.

Thanks for such a nice plugin!!!:-)
