### ISSUE TITLE
Problem plugin with phonegap build

### ISSUE THREAD

**Issue by mvitalia** [arnesson/cordova-plugin-firebase#119]
Hi, i have created one private fork of this plugin. Inside the folders ios and android i changed the file, with my files GoogleService-Info.plist and google-services.json downloaded from Firebase.
I compiled the project with phonegap build. I used method window.FirebasePlugin.getToken and the app return null... Help me please...

**Comment by catakkio** [comment]
@mvitalia Have you found a solution ? I have the same problem :(
