### ISSUE TITLE
Multiple "duplicate symbol" error messages when building for iOS

### ISSUE THREAD

**Issue by Hissvard** [arnesson/cordova-plugin-firebase#120]
I'm trying to build my project for iOS devices. Things were working well before, but after adding the phonegap-plugin-push package I started getting this:
http://hastebin.com/dakizemona.md
Anyone know of a solution that doesn't require me recreating the phonegap project from scratch? It'd be the third time today.

**Comment by robertarnesson** [comment]
Don't use this plugin and phonegap-plugin-push, they do the same thing and will have colliding symbols.
