### ISSUE TITLE
Invalid google_app_id

### ISSUE THREAD

**Issue by luisbg1983** [arnesson/cordova-plugin-firebase#125]
Hello,

I did each step but i always had a same problem.

![captura de pantalla 2016-12-18 a las 17 32 54](https://cloud.githubusercontent.com/assets/9257749/21295222/4f332d46-c548-11e6-9810-1d3523581169.png)

I'm looking for about this error, but all people says that problem is google-service.json but i think that It's correct.

![captura de pantalla 2016-12-18 a las 17 33 32](https://cloud.githubusercontent.com/assets/9257749/21295225/593bd338-c548-11e6-837a-6dabe1c26ade.png)

Any idea?

**Comment by patricksebastien** [comment]
I have the same issue. I have the google-services.json & the GoogleService-Info.plist (it works for iOS).

**Comment by robertarnesson** [comment]
try with the latest release of the plugin. re-open if needed
