### ISSUE TITLE
Badge Set Not working for few android devices

### ISSUE THREAD

**Issue by siddharthnaik7** [arnesson/cordova-plugin-firebase#126]
I used cordova-plugin-firebase plugin to set the badge count for testing.
Actually, I am getting the badge count for few android devices but not all.
viz.: getting for few Samsung devices, but not for MI or Lenovo devices.
What is the solution for this issue?

**Comment by siddharthnaik7** [comment]
For an instance I am using:

ionic plugin add cordova-plugin-firebase as plugin.

This is the line that I am adding in my app.js to get the badge count on application icon.

window.FirebasePlugin.setBadgeNumber(value);

Specific Problem here is Badge Count is not reflected on all Android devices Except for Samsung Devices

What is the solution for this issue?

**Comment by mathiasmuller4sh** [comment]
Plugin use an external  lib for android badge device, not all 
Check compat with your device with this lib
https://github.com/leolin310148/ShortcutBadger

**Comment by robertarnesson** [comment]
@mathiasmuller4sh is correct, we use a 3rd party lib for this and it does not support all devices.

**Comment by rhernandez-domandtom** [comment]
What if the demo app from the third party is working.. but there is not badge with my app using this plugin ?

**Comment by eeschiavo** [comment]
Is there something new here? The demo app from ShortcutBadger is working but with this plugin doesn't seem to work
