### ISSUE TITLE
Information Needed: How to add more than 1 parameter to an event?

### ISSUE THREAD

**Issue by Venkat-TTapp** [arnesson/cordova-plugin-firebase#127]
Thanks for this wonderful plugin.

I would like to know, how to add more than 1 parameter to an event.

For instance:

Event “select_content” can have CONTENT_TYPE and ITEM_ID parameters

I could see "content_type" getting tracked by below code, but not sure how to get item_ID parameter associated with this particular event.

`window.FirebasePlugin.logEvent("select_content", {content_type: "abcd"});`

Reference Link:
Firebase Events: 
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html

Firebase Parameters:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param.html#ITEM_ID

Regards,
Venkat

**Comment by r7sy** [comment]
`window.FirebasePlugin.logEvent("select_content", {content_type: "abcd",item_id=2});`

**Comment by Venkat-TTapp** [comment]
Thanks for your time and information. Just 3 days back, I released my live app, will try this code for my next build.

**Comment by Venkat-TTapp** [comment]
I will close this for now as I have got the information what I needed.
