### ISSUE TITLE
Token is null on iOS store app

### ISSUE THREAD

**Issue by RadomirPerisic** [arnesson/cordova-plugin-firebase#128]
Hi,

I'm having problem on store version of my iOS app where token is always returned as null, however, when I use local build through Xcode I get a valid token (tested both debug and production build). In addition on iOS no notifications are received (group notifications).

I added `window.FirebasePlugin.grantPermission();` which promts users to allow notifications, also in Xcode I allowed notifications in app. I'm also checking for token after a timeout (if it returns null function is called again after some time but it's always null).

`google-services.json` and `GoogleService-Info.plist`   are also present and should be valid.

Everything works fine on android, both local and production version.

I'm out of ideas where to look for issue.

**Comment by sondreb** [comment]
Seeing same issues with devices, works perfectly when launching app in Simulator, but on connected devices it fails to return token. The dialog for permissions appears just fine, but token is always null. Tested on iPhone S6 with iOS 10 and iPad with iOS 9.
