### ISSUE TITLE
Event for when application launches from notfication.

### ISSUE THREAD

**Issue by theonemule** [arnesson/cordova-plugin-firebase#129]
I'm looking for an event that fires when the application is neither in the foreground or background and the application is opened from a notification that is received. The onNotificationOpen works great whenever the application is already open or is in the background.

Am I missing something?

**Comment by chanphillip** [comment]
I think I have the same issue.
I've tested it on Android. If the app is killed (not in background), clicking the notification launches the app but onNotificationOpen is not fired afterwards.

**Comment by javierreyesc1** [comment]
I think I have the same issue.

**Comment by florinmtsc** [comment]
This happens to me when application is in background too. Works great in foreground, but not when it's in background or closed.

**Comment by robertarnesson** [comment]
try to install the plugin from github master so that you have this change https://github.com/arnesson/cordova-plugin-firebase/pull/153

**Comment by jafaripur** [comment]
Same for me.

**Comment by Tertiush** [comment]
I've tried the 0.1.19 version and get the same result; the notification arrives but when I tap on it it just disappears and the app doesn't start. Anyone else also getting this?

**Comment by Tertiush** [comment]
So I got mine to work but simply commenting out the line below (click_action) from my server that sends the push notifications:

`
notification: {
                            title: site,
                            body: fcmBody,
                            'priority': 'high',
                            'sound': 'default',
                            /*"click_action": "FCM_PLUGIN_ACTIVITY",*/
                            'color': '#ff0000',
                        }
`

**Comment by SiempreProgramadorNovato** [comment]
Reinstalling the plugin from github solved the issued for me, after trying all the suggested solutions

cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --save

**Comment by drptbl** [comment]
@SiempreProgramadorNovato Removing cordova-plugin-firebase and reinstalling it to latest version from npm fixed this issue. Latest master version doesn't compile for me. Fixed anyway, thanks.

**Comment by SiempreProgramadorNovato** [comment]
@drptbl glad to hear that (y)

**Comment by wo-github** [comment]
This problem is still alive on iOS. The onNotificationOpen Event is just fired, if the app is in the foreground or background, but not if the app isn`t in the list of the open app, if you doubleclick on the homebutton.
How could I get the message data in this case?
