### ISSUE TITLE
notification arriving as if app was in background when in foreground

### ISSUE THREAD

**Issue by loama** [arnesson/cordova-plugin-firebase#130]
When I send a notification it does not seems to matter whether the app is open, in background or closed, it just arrives as if it was from an external app.

**Comment by tresdev** [comment]
It's kinda abnormal in a similar way for me too.
When the app is open,
nothing happens. 
When the app is in the background it works.

I want it to work just like it's in the background.(when the user clicks the notification on the push alarm list)

**Comment by device68** [comment]
I noticed this strange behaviour with an older phone running Android 4+

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
