### ISSUE TITLE
Android not asking for permission

### ISSUE THREAD

**Issue by lahdekorpi** [arnesson/cordova-plugin-firebase#131]
I've set up for getting a token and I do receive one just fine with getToken. I'm also subscribing to a topic.
However Android isn't asking for notification permission nor is the permissions shown in the permission list.

I've also set up a onNotificationOpen that never gets triggered when sending a notification.
Do I need to manually add something else?

(Running on an Ionic 2 app via `ionic run android --device`)

**Comment by device68** [comment]
From my understanding Android doesn't need to request permission to send notifications, it's set automatically. Unlike iOS where you must add the function FirebasePlugin.grantPermission() or it won't register the device.

**Comment by aakritiOpallios** [comment]
@device68 can we change any settings to request for a permission before receiving notifications in android?
For now it directly allows to receive notifications.
