### ISSUE TITLE
Is crash reporting in the scope of this plugin?

### ISSUE THREAD

**Issue by chanphillip** [arnesson/cordova-plugin-firebase#134]
Hi @robertarnesson 
I saw crash reporting mentioned in README. I would like to know if this will be in the scope and any plans to implement crash reporting features? If it's true it will be so handy!

**Comment by renanss** [comment]
I think it has crash report that is auto-reported in case the app crashes. To manually create a report via method I think we should use this one:
https://github.com/chemerisuk/cordova-plugin-firebase-crash

**Comment by robertarnesson** [comment]
Crash reporting comes with Firebase as default. If anyone want to create a PR with the manual crash methods please go ahead 👍
