### ISSUE TITLE
Difference version repo and npm

### ISSUE THREAD

**Issue by ntiseira** [arnesson/cordova-plugin-firebase#135]
Hi, 

I have a problem when i install cordova plugin by npm not load the lastest changes, in this merge https://github.com/arnesson/cordova-plugin-firebase/commit/e132d7c55e615f0ff68757e0463741cfbd1e8246

Then I view the plugin package version and it's the same version. Why is it?

**Comment by robertarnesson** [comment]
use 0.1.19
