### ISSUE TITLE
how to received attached images

### ISSUE THREAD

**Issue by tdigambar** [arnesson/cordova-plugin-firebase#136]
i have used this plugin and its working fine for android and ios.but,
how to get attached images ?, is this functionality available in this plugin?

**Comment by GuilhermeSanches** [comment]
+1

**Comment by John-Henrique** [comment]
FCM message can transfer a payload of up to 4KB to a client app... so, send files need some creativity of you. Maybe upload image to server and send a FCM message with ID of image...
