### ISSUE TITLE
INVALID_SENDER

### ISSUE THREAD

**Issue by quangtung02** [arnesson/cordova-plugin-firebase#138]
Hi all,
I met an issue when i use this plugin on Android. It alway get token = null and INVALID_SENDER.
I put google-services file in root folder but it is not working. But it does works normal with cordova-plugin-fcm. How can solve this issue?

This is my log:
FirebaseInstanceId: background sync failed: INVALID_SENDER, retry in 40s
FirebaseInstanceId: background sync failed: INVALID_SENDER, retry in 80s

Thanks.

**Comment by sajTempler** [comment]
+1

**Comment by hitpopdimestop** [comment]
Same with 0.0.19 version, only on Android

**Comment by TatsuUkraine** [comment]
+1

**Comment by Rakeshpatel87p** [comment]
+1

**Comment by ensargunesdogdu** [comment]
+1

**Comment by ensargunesdogdu** [comment]
Guys i think i found a workaround for this problem.

In the android build res/values/strings.xml. Get bold values from google-services.json and put in strings.xml file

<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">Pocket</string>
    <string name="launcher_name">@string/app_name</string>
    <string name="activity_name">@string/launcher_name</string>
    <string name="google_app_id">**client_info.mobilesdk_app_id**</string>
    <string name="google_api_key">**api_key.current_key**</string>
</resources>

**Comment by gersonmontenegro** [comment]
I solved that problem in a web angular app adding:

export const firebaseConfig = {
    apiKey: "XXXX",
    messagingSenderId: "XXXX"
};
firebase.initializeApp(firebaseConfig);

**Comment by adelph0** [comment]
@ensargunesdogdu 

this works for me

**Comment by garam1** [comment]
I am getting this error while build the application in Android Studio. Please help
