### ISSUE TITLE
How use this plugin in ionic 2?

### ISSUE THREAD

**Issue by lionalex** [arnesson/cordova-plugin-firebase#139]
I try to use 'window.FirebasePlugin....' but the object not exist in ionic 2. Home can use this plugin? Can you give me some example? I must import something in app.component.ts?

**Comment by OBout** [comment]
For Ionic I am using [this one](https://github.com/angular/angularfire2)

**Comment by chanphillip** [comment]
Angularfire2 includes only web sdk. It doesn't provide features like notification and mobile analytics.

On ionic 2, you should ensure it is installed and appears on config.xml
Then you need to add this line to avoid compilation error:

    declare var FirebasePlugin: any;

**Comment by lionalex** [comment]
@chanphillip thanks for yout reply, but if I try to include 

`declare var FirebasePlugin: any;`

in my **app.components.ts**, the system give me this error:

**ReferenceError: FirebasePlugin is not defined**

I write your suggestion after all "import" instruction, before **@component**

```
import { Component, ViewChild } from '@angular/core';
import .....

declare var FirebasePlugin: any;

@Component({
  templateUrl: 'app.html'
})

export class MyApp {
  constructor(
  ){
    this.platform.ready().then(() => {
      FirebasePlugin.grantPermission(); 
      FirebasePlugin.subscribe("appAndroid");
      FirebasePlugin.getInstanceId( function(token) { 
        //this.saveToken(token); 
      }, function(error) { 
        console.log(error); 
      });

      FirebasePlugin.onNotificationOpen( function(notification) {
        alert("Yeahh!"); 
        alert(JSON.stringify(notification));
      }, function(error) { 
        //alert("Error"); 
      });
    });
  }

}
```

Wher is my error?

**Comment by chanphillip** [comment]
@lionalex Are you running using `ionic serve`? This plugin doesn't work on browsers.
You need to test it on devices.

**Comment by lionalex** [comment]
Yes, because when I write this instruction, the app on device is blocked on the splashscreen. Then I try with the browser...

**Comment by lionalex** [comment]
Ok, I've test another time and with your suggest the plugin work. 
I've tried this script

```
 FirebasePlugin.onNotificationOpen( function(notification) {
        alert("Yeahh!"); 
        alert(JSON.stringify(notification));
      }, function(error) { 
        //alert("Error"); 
      });
```

but when I receive the notification on my device, it don't run this part of code. I click on the notification, the device open the APP, but don't open the alert...so I think there is some problem with this method.

**Comment by chanphillip** [comment]
On ionic, you need to call onNotificationOpen when the app resumes:

    this.platform.resume.subscribe(() => {
        FirebasePlugin.onNotificationOpen(...);
    });

**Comment by GuilhermeSanches** [comment]
Is it possible to open the application on a specific page when clicking on one when the application is initially closed ?

**Comment by sajTempler** [comment]
well there is official plugin now [here](http://ionicframework.com/docs/v2/native/firebase/)

and yes

`
Firebase.onNotificationOpen()
            .subscribe((res) => {
                if (res.tap) {
                    // since firebase sends always string as data you have to parse it
                    // let data = JSON.parse(res.data)
                    // if(data.type === 'page1') {
                    // this.navCtr.push(Page1);
                    // }
                    // this else if is for background mode
                    } else if (!res.tap) {
                    // this.navCtr.push(Page)
                    }
            }

`

you can add let's say 'type' to your push payload and  based on that navigate to choosen pages, when app is in foreground or in background.

**Comment by GuilhermeSanches** [comment]
And with dead application? Does it work too?

**Comment by JumBay** [comment]
Doesn't seem to work if the app is completely closed

**Comment by GuilhermeSanches** [comment]
I tested 3 plugins for firebase and it seems that none implements this handler with "dead" application  :(

**Comment by sajTempler** [comment]
@GuilhermeSanches  @JumBay 
my bad I checked and if the app is killed it doesn't open again from push.

I used [this](https://github.com/fechanique/cordova-plugin-fcm) one with Ionic 2 and was working as expected even when app was killed or in background. Checked on both android and iOS. But iOS has to use older version of that plugin (1.1.5 e.g.) and for Android it's fine with v 2.1.1

**Comment by GuilhermeSanches** [comment]
@sajTempler  Eu usei este plugin, e uma limitação dele é que não implementar bigstyle nas notificações. Elas exibem apenas uma linha :(

**Comment by vikramprabhu123** [comment]
I tried the plugin FirebasePlugin along with AngularFire2.
But in the function below:

FirebasePlugin.onNotificationOpen(function (notification) {
                console.log("Yeahh!");
                console.log(JSON.stringify(notification));
    //I am not seeing the message. I see only the flags sender data like message_id, tap: false....etc
            }, function (error) {
                console.log("Error");
            });

I am trying to figure what I am doing wrong.

**Comment by robertarnesson** [comment]
is this still an issue now that ionic have proper support for this plugin? https://ionicframework.com/docs/native/firebase/

**Comment by Sampath-Lokuge** [comment]
Hi @robertarnesson 

The problem here is we don't have a proper example of how to implement this. All your doc and Ionic doc have just method names.It is not enough.Can you please provide us a complete example how to do this? Thank you.

**Comment by morariu** [comment]
So, is this working in Ionic 2? Looking to implement Google Analytics; it was easy in Ionic 1 but confusing in Ionic 2. Thanks

**Comment by Sampath-Lokuge** [comment]
Hi @morariu 

Yes.It is working fine with the Ionic 3.I have implemented it.Where do you have a problem?

**Comment by morariu** [comment]
@Sampath-Lokuge thanks, I'm using Ionic 2. As the OP, I was also using the below method but that only works in Ionic 1.

`if (window.FirebasePlugin) window.FirebasePlugin.logEvent("page_view", {page: "login"});`

**Comment by Sampath-Lokuge** [comment]
Please see the below Gist @morariu .If you have any question please let me know.

[**Analytics with Firebase**](https://gist.github.com/Sampath-Lokuge/c532167c544dd15b2d0d390bbdff4b27)
