### ISSUE TITLE
Minimal Android version?

### ISSUE THREAD

**Issue by mhanke** [arnesson/cordova-plugin-firebase#141]
Hi,

I can't get your plugin working on android. The app crash on start. I don't know how to go on with the problem. I have placed the google-services.json in the app Folder and it is also in the platform/android folder. But it is not located in the built APK file. Is this wrong? I am working with android API level 21, is it a problem?

Please help me. Thank you very much.

Moritz

**Comment by kiralikbeyin** [comment]
KitKat didnt work, now using Api 24 and fine.

**Comment by FreezyExp** [comment]
On android logcat should give you more information on what is causing the crash.
Anything in there?

**Comment by joy2012bd** [comment]
Same problem. My app doesn't receive notification on my kitkat running tablet. Has your problem been resolved?
