### ISSUE TITLE
FirebaseApp is not initalized.

### ISSUE THREAD

**Issue by bullb** [arnesson/cordova-plugin-firebase#142]
After building a new release to submit to the store I am now getting the following error appear when I call 'getToken'

> Default FirebaseApp is not initialized in this process `processName` Make sure to call FirebaseApp.initializeApp(Contect) first. 

This is only happening on android the same build is working on IOS, also this error was not present on the last build I did last year.

**Comment by mvnerisantos** [comment]
Same problem here.

**Comment by Krisa** [comment]
This already happened to me too (not sure why). I could resolve the error by forcing a reinstallation (remove then add the plugin through the cordova cli).

**Comment by mvnerisantos** [comment]
Not worked. removed, add again and same error.

**Comment by bullb** [comment]
I actually got this error to go away. I started a fresh project to check if it was something with the plugin and was not getting an error.

I checked the difference between this and my project and realized I had the _google-services.json_ and _GoogleService-Info.plist_ in the root of the project once I removed these it all worked fine.

**Comment by hitpopdimestop** [comment]
The same with my app. It is in Ionic 2, working just fine on IOS, but on Android I get an error:

> `"Native: tried calling Firebase.onTokenRefresh, but the Firebase plugin is not installed."`

And plugin sure is installed. This is the line of code I have in my config.xml:
<plugin name="cordova-plugin-firebase" spec="~0.1.19" />

I'm using:

> Cordova CLI 6.5.0

Platforms:

> IOS 4.3.1

> Android 6.1.2

**Comment by amitanmol** [comment]
Hi,

I am facing same issue in android plugin:

Default FirebaseApp is not initialized in this process com.x.xyz. Make sure to call FirebaseApp.initializeApp(Context) first.

Please suggest.

Duplicate: https://github.com/arnesson/cordova-plugin-firebase/issues/206

Thanks

**Comment by jlsuarezs** [comment]
Yes, I am having the same issue. Any help?

**Comment by AyoGitNg** [comment]
I had this issue. I built the generated android project in the platform in android studio then I found the issue and solved this.

Follow this steps.

Inside the platforms folder, android/src/{package name}/MainActivity.java

Import the firebase library, 
- import com.google.firebase.FirebaseApp;

Inside the oncreate method, below super.oncreate(savedinstancestate),

Add FirebaseApp.initializeApp(this);

Last step, 

Inside the platforms folder, android/res/values/string.xml,

Add <string name="google_app_I'd"I had this issue. I built the generated android project in the platform in android studio then I found the issue and solved this.

Follow this steps.

Inside the platforms folder, android/src/{package name}/MainActivity.java

Import the firebase library, 
- import com.google.firebase.FirebaseApp;

Inside the oncreate method, below super.oncreate(savedinstancestate),

Add FirebaseApp.initializeApp(this);

Last step, 

Inside the platforms folder, android/res/values/string.xml,

Add 

<string name="google_app_id" templateMergeStrategy="preserve" translatable="false">{you can find this value in your Google services.json file client_info, mobile ask_app_id}</string>

**Comment by linuxs** [comment]
Thank you for your solution! It worked great!

**Comment by sharpyx-official** [comment]
Thank you! Very helped!

**Comment by informatico40** [comment]
Thank you for your solution!!!!

**Comment by bdirito** [comment]
A post-prepare cordova hook to implement ayngitng's solution.

https://gist.github.com/bdirito/74ba45ef314d2d9f9afb73f37ecf815a

**Comment by arevaloaraque** [comment]
Thank you so much @AyoGitNg. It worked well. I love you. :+1: Hahahaha

3 weeks ago with this error.

**Comment by sebrojas14** [comment]
Is not possible to release a version with this fix? @arnesson

**Comment by alemdg** [comment]
STILL HAPPENING, version 1.0.5

**Comment by ahayder** [comment]
+1

**Comment by korey1020** [comment]
AyoGitNg Thanks this worked for me
