### ISSUE TITLE
onNotificationOpen is not called on Android

### ISSUE THREAD

**Issue by davidgamarra** [arnesson/cordova-plugin-firebase#143]
I’m doing tests with this plugin and I 'm getting an unexpected result:
On Android when the app is absolutely closed and I tap on the notification, the app is opened but onNotificationOpen is not fired, but when the app is in foreground or in background this method is called correctly. I tested it on Android 4.4.4, 5.1, 6.0.1 and I got the same result.
Nevertheless on iOS it works correctly. When the app is closed and the notification is tapped, the app is opened and onNotificationOpen is called.
Any suggestion? Thanks

**Comment by chanphillip** [comment]
Same issue as #108

**Comment by davidgamarra** [comment]
issue #108 not solve this problem

**Comment by blackholegalaxy** [comment]
I face the same problem here, issue #108 doesn't fix anything. The function is never called: the app opens, but then nothing is done.

**Comment by etherny** [comment]
I found a turn around, not really elegant but it works : 
```
var intervalId = setInterval(function(){
    window.FirebasePlugin.onNotificationOpen(function(notification) {
      console.log(notification);
      clearInterval(intervalId);
    }, function(error) {
      console.error(error);
    });

  }, 1000);
```

Will try to bind onNotificationOpen and stop at first received notification.

Why i need to do this : 
When i start the application with this code just in onDeviceReady it's like the FMC service not yet connected to firebase server.

```
window.FirebasePlugin.onNotificationOpen(function(notification) {
      console.log(notification);
    }, function(error) {
      console.error(error);
    });
```

But if i evaluate this same code in the chrome console after app start, it works.
Except when the application is not started and i receive a notification, i touch the notification, the application start, but plugin look like not yet ready, and onNotificationOpen is not called.

I hope this debug session could help.

**Comment by etherny** [comment]
I use this plugin in a very slow device, perhaps an asynchronous issue ?

**Comment by chanphillip** [comment]
@etherny did you have problem even when the app is in background (launched, not completely killed)?
If so, you should call onNotificationOpen on both device ready and resume.

I thought your workaround was to fix the problem when the app is not even launched. I've tested it on Android and it did not work on my end.

**Comment by chanphillip** [comment]
@davidgamarra I just read your post again. Did you say on your end tapping the notification when the app is not launched did fire onNotificationOpen on iOS? It did not work on my end.

**Comment by davidgamarra** [comment]
document.addEventListener("deviceready", function() {
        window.FirebasePlugin.grantPermission();
        
        var saveToken = function(token) {
            var myToken = localStorage.getItem("onevent.firebase.token");
            if(myToken != token) {
                    localStorage.setItem("onevent.firebase.token", token);
                    console.log(token);
                }
            }
        }
        
        var errorToken = function(error) {
            console.error(error);
        }
        
        window.FirebasePlugin.getToken(saveToken, errorToken);

        window.FirebasePlugin.onTokenRefresh(saveToken, errorToken);

        window.FirebasePlugin.onNotificationOpen(function(notification) {
            console.log(notification);
            alert(notification.text);
        }, function(error) {
            console.error(error);
        });

    }, false);

This is my code, as you can see, its on "deviceready" so the expected behaviour is when I tap on the notification when te app is closed it must open the app and call onNotificationOpen but it dont work. On iOS yes. When te app is open onNotificationOpen works perfectly so I dont need "resume" event.
I emphasize that on Android I mean app closed when the app is completely killed. If the app is closed but on background it works as well.

**Comment by etherny** [comment]
@chanphillip hello, yes i tried to add the onNotificationOpen in ready and resume methods. I put traces in both methods to be sure to pass through, and i m certain to pass in the two methods but onNotificationOpen never called.
Same issue on background app and on not open app.

I looked at your code but all looks good, i forked your job, and investigate in few days.

**Comment by psaussure** [comment]
Same here: `onNotificationOpen` method is never triggered. I tried to place it on both resume and onDeviceReady without success.

**Comment by etherny** [comment]
#### I put traces in : 
FirebasePlugin : onNotificationOpen
FirebasePlugin: sendNotification
FirebasePluginMessagingService : onMessageReceived
OnNotificationOpenReceiver : onReceive

##### Case app in front
1. Send notification
2. log and all working
```
01-16 21:10:31.567 4722-6742/##project## D/ETHERNY: onMessageReceived com.google.firebase.messaging.RemoteMessage@5b8029a
01-16 21:10:31.567 4722-6742/##project## D/FirebasePlugin: From: 329027973252
01-16 21:10:31.568 4722-6742/##project## D/FirebasePlugin: Notification Message id: 0:1484619032357658%a9549c76a9549c76
01-16 21:10:31.568 4722-6742/##project## D/FirebasePlugin: Notification Message Title: null
01-16 21:10:31.568 4722-6742/##project## D/FirebasePlugin: Notification Message Body/Text: test
01-16 21:10:31.568 4722-6742/##project## D/ETHERNY: sendNotification Bundle[{tap=false}]
```

##### Case app in back
1. Send notification
2. Click on notification icon
3. App come back in front
4. Only this trace and not call of onNotificationOpen
5. log
```
01-16 21:09:49.178 4722-4722/##project## D/ETHERNY: sendNotification Bundle[mParcelledData.dataSize=308]
```

##### Case app closed
1. Send notification
2. Click on notification icon
3. App come back in front
4. No trace and not call of onNotificationOpen

---
##### I have this log for all notifications even if the application is in front and active
```
01-16 21:21:10.850 13745-16353/##project## D/FA: Logging event (FE): _nr, Bundle[{_o=fcm, _ndt=0, _nmn=test, _nmt=1484619671, _nmid=4324614190085375568}]
01-16 21:21:11.069 13745-16353/##project## V/FA: Using measurement service
01-16 21:21:11.069 13745-16353/##project## V/FA: Connecting to remote service
01-16 21:21:11.118 13745-13745/##project## W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
```

**Comment by etherny** [comment]
Use case : 
Send notification, tray icon, click on notification while application in background.
Application immediately opened after notification click.

```

01-16 21:46:16.560 2850-3839/##project## D/FA: Logging event (FE): _no, Bundle[{_o=fcm, _ndt=0, _nmn=test, _nmt=1484621164, _nmid=7882742816762035924}]
01-16 21:46:16.586 2850-2850/##project## D/ETHERNY: sendNotification Bundle[mParcelledData.dataSize=308]
01-16 21:46:16.608 2850-2850/##project## D/CordovaActivity: Started the activity.
01-16 21:46:16.617 2850-2850/##project## D/CordovaActivity: Resumed the activity.
01-16 21:46:16.639 2850-2850/##project## D/SystemWebChromeClient: file:///android_asset/www/js/firebase-message-cloud.js: Line 18 : [object Object]
01-16 21:46:16.639 2850-2850/##project## I/chromium: [INFO:CONSOLE(18)] "[object Object]", source: file:///android_asset/www/js/firebase-message-cloud.js (18)
01-16 21:46:16.739 2850-3839/##project## V/FA: Using measurement service
01-16 21:46:16.739 2850-3839/##project## V/FA: Connecting to remote service
01-16 21:46:16.746 2850-3839/##project## W/GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 9879480
01-16 21:46:16.746 2850-3839/##project## V/FA: Using measurement service
01-16 21:46:16.747 2850-3839/##project## V/FA: Connection attempt already in progress
01-16 21:46:16.747 2850-3839/##project## V/FA: Activity resumed, time: 142150
01-16 21:46:16.766 2850-2894/##project## E/EGL_emulation: tid 2894: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
01-16 21:46:16.766 2850-2894/##project## W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x79bcf48bcc40, error=EGL_BAD_MATCH
01-16 21:46:16.799 2850-2857/##project## W/art: Suspending all threads took: 20.837ms
01-16 21:46:16.869 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:16.898 2850-2861/##project## I/art: Background sticky concurrent mark sweep GC freed 1730(132KB) AllocSpace objects, 1(20KB) LOS objects, 0% free, 12MB/12MB, paused 63.221ms total 120.237ms
01-16 21:46:17.231 2850-2850/##project## W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
01-16 21:46:17.265 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:17.386 2850-2861/##project## I/art: Background partial concurrent mark sweep GC freed 882(72KB) AllocSpace objects, 1(20KB) LOS objects, 16% free, 19MB/23MB, paused 19.678ms total 161.802ms
01-16 21:46:18.255 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:18.416 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:18.557 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:18.699 2850-2850/##project## W/art: Attempt to remove non-JNI local reference, dumping thread
01-16 21:46:18.720 2850-2861/##project## I/art: Background sticky concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 26MB/26MB, paused 7.596ms total 22.828ms
01-16 21:47:16.782 2850-5047/##project## W/FA: Tasks have been queued for a long time

```

**Comment by etherny** [comment]
Use case : 
Application not started, send notification, receive notification in tray, click on it and application start.

https://gist.github.com/etherny/81eab0b991dca2cdfc345350c379abe8

**Comment by mathiasmuller4sh** [comment]
Hi there,
I'am facing the same issue, so i'am trying to understand what's going on in the code.
For the cold start usecase the doc says to use
