### ISSUE TITLE
iOS Notifications Opens Automatically

### ISSUE THREAD

**Issue by rakeshaset** [arnesson/cordova-plugin-firebase#150]
Hi All,

I am able to get notifications perfectly when app is in background. But in iOS when app is in foreground notifications sent on iOS opens automatically. This is working fine in iOS.

When app is minimzed or is killed i am able to get notifications in my notification container. But when app is opened notifications are getting opened automatically.

Please advice  if somebody had faced same issue before.

Thanks
Rakesh

**Comment by robertarnesson** [comment]
this is how the plugin works right now. If the app is in the foreground, you are responsible for displaying it in the ui or sending a local notification.
