### ISSUE TITLE
Device token not generated getting error in Android

### ISSUE THREAD

**Issue by darshitmaniar** [arnesson/cordova-plugin-firebase#151]
Hi, 
I have integrated this plugin in my app, iOS working in fine getting device token and working smooth. but in android not works properly. and getting an error while initializing app.
error message : "**Default FirebaseApp is not initialized in this process com.abc.appname. Make sure to call FirebaseApp.initializeApp(Context) first.**"
I am using:
Cordova CLI 6.4.0 
Cordova Android : 6.0.0
And Cordova iOS : 4.1.0
please help me out to solve this issue.

**Comment by uttamkukadiya** [comment]
Hii buddy,
I have same issue in Android,
Cordova CLI 6.3.1
Cordova Android : 5.2.2 

I had previously installed plugin version : 0.1.18 that worked fine for android.
Thank you,

**Comment by hitpopdimestop** [comment]
Hello!
Had issues with 0.1.19 - couldn't get firebase token on android. Switched to 0.1.18, now method `Firebase.onNotificationOpen()` isn't working at all. Too bad there's no changelog, does this method exist in 0.1.18?
Thanks!

**Comment by robertarnesson** [comment]
try with the latest release of the plugin. re-open if needed

**Comment by priyasuthar** [comment]
Now we are getting a same.

Let us know if any solution u have find.

Thanks in advance.

**Comment by darshitmaniar** [comment]
Now we are getting a same.

Let us know if any solution u have found.

Thanks in advance.

**Comment by priyasuthar** [comment]
We have tried with the latest released plugin, But we are getting same issue and we have created new bug -  151
