### ISSUE TITLE
Conflict with OneSignal plugin

### ISSUE THREAD

**Issue by pablo-gonzalez** [arnesson/cordova-plugin-firebase#159]
I am using OneSignal plugin to send notifications. I created a Firebase project in console and used Cloud networking keys.

I would like to use your plugin to use Analytics. So I have installed your plugin and copied the json file to the project root folder. Analytics is working fine.

However everytime I send a nofitication with OneSignal is catched by your plugin also.
I have tried to create a different project in Firebase to separate analytics and push notifications but the result is the same.

Because I am not using the Cloud messaging keys related to the project informed in json file to get analytics I do not know why push notifications are catched by your plugin. The second notification in the panel is created by your plugin:

![screenshot_2017-02-01-01-30-10](https://cloud.githubusercontent.com/assets/15030532/22568678/e42bfcbe-e97b-11e6-92f4-6cfdbe116b7f.png)

Anyway to disable the Push Notifications functionality of your plugin? I would like to use only Analytics part.

Thanks in advance,
Pablo

**Comment by robertarnesson** [comment]
there is no way to turn off the notifications part. You can make a fork and disable it yourself or use e.g. https://www.npmjs.com/package/cordova-plugin-firebase-analytics which has only analytics...

**Comment by pablo-gonzalez** [comment]
I am aware of the plugin you are quoting. In fact, I tried that plugin first because it was only analytics.
However it is not working fine with Android and has some issues. That's why I tried your plugin that works perfectly.
As far as I know this is the only Firebase Analytics plugin working for cordova/Ionic.

I am not sure if I have the knowledge to make a fork right now. I created my app using Ionic.
Perpaps I will try that option in the future.

Thanks.

**Comment by epetre** [comment]
It's funny how this issue was just closed like that.

**Comment by epetre** [comment]
I created a fork to use the rest of this plugin without the conflicting notification handling part in android. It doesn't seem to be causing other issues for me when using OneSignal.

**Comment by pablo-gonzalez** [comment]
Thank you very much. I will give it a try! 

Best regards,
Pablo

**Comment by rodrigoreal** [comment]
I'm also having this problem, any update on that?
