### ISSUE TITLE
copy key files via <source-file>

### ISSUE THREAD

**Issue by rolandjitsu** [arnesson/cordova-plugin-firebase#161]
I just started using this plugin for FCM, but I seem to have some issues with config files. The problem I am facing is that I'm using Ionic Cloud to package my apps, but they do not run custom hooks, thus the config files are never copied to the proper destination.

There is a similar plugin, [cordova-plugin-fcm](https://github.com/fechanique/cordova-plugin-fcm), which copies the files through the `<source-file>` tag.
```xml
<platform name="android">
    <source-file src="google-services.json" target-dir="./"/>
</platform>
<platform name="ios">
    <source-file src="GoogleService-Info.plist"/>
</platform>
```

Could this plugin do a similar thing instead of the hook?

**Comment by rolandjitsu** [comment]
I also just made a [PR](https://github.com/driftyco/ionic-package-hooks/pull/24) to make the hook you made available in Ionic Cloud, but I'm not sure how soon that will be merged.

**Comment by robertarnesson** [comment]
a quick fix is to fork the plugin privately and put the config files in there. the hook does more things than just copy the files in place. cordova-plugin-fcm is using the same hook that we do

**Comment by rolandjitsu** [comment]
@robertarnesson true, I just noticed that now. Well, I think the PR that I made with the script you guys have should provide a proper fix. But it might take some time until it gets merged, there are some other PRs waiting since two months ago.

**Comment by robertarnesson** [comment]
closing this for now
