### ISSUE TITLE
I seem to be getting notifications while the app is in the foreground

### ISSUE THREAD

**Issue by GunslingerBara** [arnesson/cordova-plugin-firebase#163]
This used to work correctly but recently, with seemingly no related code change, notifications started appearing while the app is in the foreground. Is there a way to debug why this is happening?

Edit: If it makes a difference, this only seems to be affecting Android.

**Comment by sam6258** [comment]
I'm getting two notifications when in background on Android and one when in foreground. Hoping some can find a fix.

**Comment by sam6258** [comment]
I've found a work around for my situation for the time being. This receives one notification in foreground and one in background like most apps do.

`var devicePlatform = device.platform;
        
        if (devicePlatform == "Android") {
                window.FirebasePlugin.onPause(function() {
                        window.FirebasePlugin.inBackground = false;
                });

                window.FirebasePlugin.onResume(function() {
                        window.FirebasePlugin.inBackground = true;
                });
        }`

This requires an additional plugin to identify device. `cordova-plugin-device`. Somewhere there is a duplicate notification being pushed out.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
