### ISSUE TITLE
hasPermission() missing

### ISSUE THREAD

**Issue by nlasso** [arnesson/cordova-plugin-firebase#165]
Hi, 

It seems that the ```window.FirebasePlugin.hasPermission()``` is missing. I've just reviewed the firebase.js file under platforms/ios/platform_www/plugins/cordova-plugin-firebase/www/firebase.js. All of the functions seems to be there but ```hasPermission()```. Any ideas?

PS: functions like ```grantPermission```, ```onNotificationOpen```, etc. are working.

**Comment by ilyakar** [comment]
The author forgot to change the plugin version when pushing the commits. Do a `cordova plugin add https://github.com/arnesson/cordova-plugin-firebase --save`. That should get you the changes which are on github.

**Comment by nlasso** [comment]
great, thnx @ilyakar!
