### ISSUE TITLE
Is it possible to allow notification when app is in foreground on iOS?

### ISSUE THREAD

**Issue by chanphillip** [arnesson/cordova-plugin-firebase#167]
I know apple suggests the behavior of notifications in foreground should be handled by the app silently, but I would like to achieve so because my notifications are reminder type and I want to prompt the user like such in background.
I was planning to use another local notification plugin to fire a notification when the app receives a push notification from firebase while it is in foreground. However, after testing out and reading some discussions over there, I realized that local notification plugin is implemented in the same way, which means no notifications can be seen in foreground.

I saw a similar plugin for react native includes a flag to allow notifications shown in foreground.
Wonder if that can be considered in this plugin as well.
FYI: https://github.com/evollu/react-native-fcm

Meanwhile, I was trying to modify the source code and make a hacky workaround but without success.
I am not so familiar with objective C so I'm looking for some help here.

**Comment by MattDHill** [comment]
When in the foreground, onNotificationOpen() silently returns the notification data. Just capture the data and present it with your own alert, toast, etc. Obviously, the notification title/message would have to be part of the data payload. On iOS, it can be found in the "apn" object. On Android, it doesn't seem to be there. As a solution, I decided to replicate the title and body of the notification (server-side) and included them in the data payload.
