### ISSUE TITLE
onNotificationOpen() is triggered by NFC tag detection

### ISSUE THREAD

**Issue by rolandjitsu** [arnesson/cordova-plugin-firebase#169]
I've just experienced some weird behaviour today while implementing a NFC feature. It seems that `onNotificationOpen()` is triggered when an NFC tag is detected.

So whenever I approach a tag I get the following from `onNotificationOpen()`:
```js
{
    android.nfc.extra.ID: "[B@2418aa78",
    android.nfc.extra.NDEF_MESSAGES: "[Landroid.os.Parcelable;@1f670fdb",
    android.nfc.extra.TAG: "TAG: Tech [android.nfc.tech.NfcA, android.nfc.tech.Ndef]"
}
```

Note that I use the [Ionic 2 Firebase](http://ionicframework.com/docs/v2/native/firebase) native plugin and for NFC I use [Ionic 2 NFC](http://ionicframework.com/docs/v2/native/nfc/) which is just a wrapper for [phonegap-nfc](https://github.com/chariotsolutions/phonegap-nfc).

I'm not sure if there is a conflict or if this is expected behaviour.

**Comment by soumak77** [comment]
Closing out-dated issue.  Please reopen if issue still exists with the latest version of the plugin.
