### ISSUE TITLE
QUESTION: way to hook into user response for grantPermission?

### ISSUE THREAD

**Issue by MattDHill** [arnesson/cordova-plugin-firebase#170]
I would like to know if a user chooses to allow or deny remote notifications, so that I may update their preferences accordingly. Is it possible to hook into the response from this prompt?

**Comment by chanphillip** [comment]
Hi @MattDHill 
I'm looking for this function as well. Did you have a solution yet?

**Comment by RubenWalraevens** [comment]
Any updates on this?
