### ISSUE TITLE
getToken() return empty

### ISSUE THREAD

**Issue by theunreal** [arnesson/cordova-plugin-firebase#171]
I'm using ionic 2 with this plugin, and the token appears to be empty on my Android:

```
this.platform.ready().then(() => {
       if (this.platform.is("cordova")) {
         Firebase.getToken()
         .then(token => console.log(`The token is ${token}`)) // save the token server-side and use it to push notifications to this device
         .catch(error => console.error('Error getting token', error));
       }
     });
```

shows an empty value in the console.

What's wrong?

**Comment by gregorgold** [comment]
Hi theunreal,

the snipped posted by you is copied from some example, right? Used this myself and didn't work, too. Just replace the console.log() part by some function or so to check wether a token is received or not.

Working example from my app:


```
//Place within platform.ready() as in your example 
Firebase.getToken().then(token =>this.storeToken(token)).catch(error => console.log(''));
 
//place as class function 
 storeToken(token){
 alert(token) // or whatever you would like to do. I do send it to a backend server for example.
 }
```
Should work then.

**Comment by theunreal** [comment]
Sorry, Forgot to put my google-service json file so it returned an empty token.

**Comment by Noble-Shiva** [comment]
@theunreal , I have the google-service.json as well, but still the user token is empty.
