### ISSUE TITLE
Crash reporting not working

### ISSUE THREAD

**Issue by themastersoda** [arnesson/cordova-plugin-firebase#174]
Looking at methods, there's no option to manually send error logs to firebase. And even though it should be automatic, this does not work. Everything is installed and connected to existing firebase account correctly, since i can see analytics data, but whenever i get an error, no data is being sent to firebase and it does not appear on my dashboard.

**Comment by robertarnesson** [comment]
that is because firebase does not provide methods to do that. The crash reporting is for native crashes, not javascript errors and the like.

**Comment by themastersoda** [comment]
Readme states that `this plugin brings push notifications, analytics, event tracking, crash reporting`. At the moment it clearly doesn't, as there is no way to log errors from javascript. If no implementation exists, the above statement is misleading to most people looking for solution.

Also, Firebase documentation states that there exists method to send error logs manually:
```
FirebaseCrash.report(new Exception("My non-fatal error"));
```
Exposing that as a method in plugin would be enough for people looking to implement it.

**Comment by robertarnesson** [comment]
.report does not exist for ios, so its not a complete solution. if you need to log javascript errors (these are not crashes), you can use event logging

**Comment by themastersoda** [comment]
Yes, that's what i'm doing currently, but event logs take time to show up in console. Even though report does not work on iOS, having it exposed and marked as working for android only would still be better than no option at all. Hopefully some time later Firebase will implement error logging for iOS as well, but at least Android users would be accomodated for.
