### ISSUE TITLE
Ios push not received

### ISSUE THREAD

**Issue by ai2010** [arnesson/cordova-plugin-firebase#178]
I managed to install correctly the plugin and to receive the token, however I can receive the push (I am sure the push is sent correctly):
{"multicast_id":6327218701336414815,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1487164253529268%3cca9ec63cca9ec6"}]}

Do you know what it can be?

**Comment by FreezyExp** [comment]
did you resolve the issue? if so please share how.
