### ISSUE TITLE
Merge all  message in single Notification

### ISSUE THREAD

**Issue by Nagaraj007** [arnesson/cordova-plugin-firebase#179]
Hi, Thanks for this plugin,it help a lot, its working great,My issue is, If i have multiple Notification its not get append to previous one,its comes up with new Notification every time.If the message is more then 15 its fill all my mobile Status Bar with Notification in my android,Is there any solution to show single notification in status bar and append all the message any suggestion would help me

**Comment by m6246** [comment]
Set the 'tag' property to an equal string within the notification payload for notifications to be replaced with the same tag. Refer to http://stackoverflow.com/questions/40816284/fcm-notification-messages-not-collapsing
