### ISSUE TITLE
Not recieving notifications both android or ios

### ISSUE THREAD

**Issue by tryadelion** [arnesson/cordova-plugin-firebase#180]
i just ifnished installed this plugin, was testing it and found i'm getting no notifications at all. they are neither shown nor catched by the events. the token is retrieved correctly and firebase reacts positively to sending him events.

my code: 

`Firebase.getToken()
        .then(token => console.log("The token is ${token}")) // save the token server-side and use it to push notifications to this device
        .catch(error => console.error("Error getting token", error));

      Firebase.onTokenRefresh()
        .subscribe((token: string) => console.log("Got a new token ${token}"));

      Firebase.logEvent("HI",{}).then(token => console.log("event sent")) // save the token server-side and use it to push notifications to this device
        .catch(error => console.error("Error sending event", error));
      Firebase.onNotificationOpen().subscribe(data => {
        console.log("YAAY" + data);
      }, error => {
        console.log("NOOO" + error);
      });`

I'm using ionic v2 + angular 2

**Comment by Nagaraj007** [comment]
Just try this link it might help you, its use to send FCM notification,If u got any notification from this link,Your client side working and you need check your backed service 
"http://pushtry.com/"

**Comment by tryadelion** [comment]
I'm not even using curl, i'm throwing them from the firebase console.

**Comment by Nagaraj007** [comment]
just try to use in your real device. Are you getting Token..?

**Comment by tryadelion** [comment]
yes, i'm only using real devices. no web/serve. both get token, both get a success on sending events, none gets notifications.

**Comment by Nagaraj007** [comment]
just save the token in DB,Copy that token and try it in above mention link!

**Comment by tryadelion** [comment]
"Firebase Push Notification successfully sent" ->  no notification on any device.

**Comment by Nagaraj007** [comment]
Check the that your app is foreground or background!

**Comment by tryadelion** [comment]
doesn't work, wathever the mode be. The notifications are not even showing in the notification tray. they're not being recieved by the devices.

**Comment by Nagaraj007** [comment]
uninstall the plugin and try it once!

**Comment by tryadelion** [comment]
Already tried, ended up testing cordova-plugin-fcm and it works, there must be some weird issue

**Comment by m6246** [comment]
You are not registering the callbacks in onNotificationOpen as per the docs:

window.FirebasePlugin.onNotificationOpen(function(notification) {
    console.log(notification);
}, function(error) {
    console.error(error);
});

**Comment by tryadelion** [comment]
I'm using ionicv2 with typescript, i can't use the callbacks as per the docs.
Firebase console is the main core of firebase, if it doesn't work there, how do i make sure notifications are working before making my own service?  http://pushtry.com/ didn't work either

**Comment by dmitryshepelev** [comment]
For me, a mistake was an invalid android app package name in Firebase project settings. I found a solution here: http://stackoverflow.com/a/39262282/3877938
Pay attention to the statement: 

> Add your Package Name, which is the id of your app: you can see it in your config.xml (something like id="com.ionicframework.someTest123").

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
