### ISSUE TITLE
No sound/vibration features?

### ISSUE THREAD

**Issue by theunreal** [arnesson/cordova-plugin-firebase#184]
Is it possible to control vibration and screen wake when receiving new notifications using this plugin?

**Comment by John-Henrique** [comment]
I try but can't play my own sound or vibration. I can play default sound of device sending in payload (FCM)
````'sound' => 'default',````

I can't choose my icon or my sound.

**Comment by robertarnesson** [comment]
you can control this in the fcm payload. e.g. {sound: true, vibrate: true}

**Comment by jablesauce** [comment]
I tried adding {vibrate:true} and even {vibrate: 1} to the notification data and I sent the push as below. It still did not work. Can you elaborate by what you meant by fcm payload please? Thank you!

```
{
	"to": "token",
	"priority": "high",
	"notification": {
		"title": "Test title",
		"body": "Test message",
		"sound": "notification",
                "vibrate": 1,
		"content_available": 1
	},
	"data": {
		"stuff": "Test stuff"
	}
}
```

**Comment by jarekskuder** [comment]
Same here, can you tell how to properly send info to have default sound or custom? And do you need to add sound if you send sound:default ?

**Comment by supinder-cf** [comment]
With this code only sound is played but not vibration.
`var payload = {
  notification: {
    title: "Notification title",
    body: "Notification body",
    sound: "default",
    click_action: "FCM_PLUGIN_ACTIVITY", 
    icon: "notification_icon",
    vibrate: "1",
    priority: "high"
  },
  data: {
    param1: "value1",
    param2: "value2"
  }
};`
