### ISSUE TITLE
.....\..\FirebasePlugin.java:349: error: cannot find symbol Visual Studio Cordova Project

### ISSUE THREAD

**Issue by serhatuysal** [arnesson/cordova-plugin-firebase#190]
Hi,
I am getting this error during compilation
![image](https://cloud.githubusercontent.com/assets/5434174/23263156/09c538a8-f9e6-11e6-928f-24dbc697c851.png)

**Comment by mgregier** [comment]
Same here. Did you find solution for this problem?

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
