### ISSUE TITLE
Different callbacks for when the app is foreground and background 

### ISSUE THREAD

**Issue by dcuesta1** [arnesson/cordova-plugin-firebase#191]
Is there a way to have different callback functions for when the app is opened and for when the app in the background. I have a popup as the foreground callback and it would be annoying if the first thing the user see when they open the app from a notification would be a popup there as well.

**Comment by MattDHill** [comment]
Check the "tap" attribute in the data params. If true, it means the notification was opened from the background. If false, it means they did not.

**Comment by dcuesta1** [comment]
Awesome, that is exactly what I was looking for. Thank you!

**Comment by emilianoglucero** [comment]
Hello, is this "tap" attribute still working ?
I didn't saw it in the docs and I need something to make differents callback functions if the app is foreground or background.
Thank you !
