### ISSUE TITLE
How to trigger an event when notification received (not tapped)

### ISSUE THREAD

**Issue by hamzahppa** [arnesson/cordova-plugin-firebase#192]
I would like to know how to trigger an event when notification received by device (not tapped) so this event will trigged when there's a notification received on background or foreground.

On the documentation, I only found onNotificationOpen which trigger an event when the notification tapped. Is there any function that I can use to listen everytime the device receive a notification. Thanks

**Comment by Krishna25Vrinsoft** [comment]
Did you get any solution?

**Comment by jrice3rt** [comment]
Same thing here any solution for background notifications?  I would like to trigger a download but it doesn't seem the delegate message on iOS at least is being hit before the message goes to the OS.

**Comment by sdiabi** [comment]
+1

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by hamzahppa** [comment]
thank you @robertarnesson

**Comment by fasthostinc** [comment]
where you able to get this to work?
