### ISSUE TITLE
Any ios example?

### ISSUE THREAD

**Issue by kiralikbeyin** [arnesson/cordova-plugin-firebase#194]
I dont have any APNs certificate so i cant upload it to fcm.

Is there any way to test APN with emulator or with a real device? I dont want to pay a developer fee to Apple now.

Android is working fine (also with token) 

Can anyone confirm ios is good with this lib?

**Comment by robertarnesson** [comment]
testing notifications when the app is in the foreground should work I think, because in this case the notifications are pushed through firebase and not APN. In all other cases you need the APN certs
