### ISSUE TITLE
Remote config getValue not woking

### ISSUE THREAD

**Issue by pablo-albaladejo** [arnesson/cordova-plugin-firebase#195]
I am able to get success status at fetch, and setting defaults, but the remote value allways returns null.

In the other hand, setDefaults always requiered the namespace, but the readme states:

// set defaults
window.FirebasePlugin.setDefaults(defaults);
// or, specify a namespace
window.FirebasePlugin.setDefaults(defaults, "namespace");

I have the plugin working for push/auth apis, so it is well configured.

**Comment by aaronneon2** [comment]
I am also facing the same issue. It seems that if I don't pass in namespace at both setDefaults and getValue, getValue will not work. Despite specifying namespace at both, getValue is still not fetching the newly published value from Firebase.

**Comment by samarthagarwal** [comment]
Yes, it does not work if you do not pass in the (optional) namespace, and it never gets the value from the remote config, always returns the default value.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
