### ISSUE TITLE
White screen after resuming from background

### ISSUE THREAD

**Issue by kabus202** [arnesson/cordova-plugin-firebase#196]
Hi,

I'm getting a white screen after returning from the background with ionic2. I'm using WKWebView. Is this a known behavior? 

Kind regards,
kab

**Comment by kabus202** [comment]
Still having this problem. When using wkwebview in combination with this plugin. 

global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0-rc.1

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.1
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.1
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.13

**Comment by jjercTK** [comment]
@kabus202 did you solved the problem?
