### ISSUE TITLE
Uncaught TypeError: undefined is not a function - ionic

### ISSUE THREAD

**Issue by lucav90** [arnesson/cordova-plugin-firebase#197]
hi,

i have installed your plugin on my ionic app.
I WANT TO USER FIREBASE ONLY FOR THE STATISTIC FUNCTIONS.

i have insert the google-services.json file on the www folder.

i have insert in my app.js

  window.FirebasePlugin.setScreenName("apphome");

but in my android studio console i have the error:

 Uncaught TypeError: undefined is not a function

How solve?

**Comment by robertarnesson** [comment]
fixed in 0.1.20
