### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by alexbuijs** [arnesson/cordova-plugin-firebase#20]
I haven't seen these specific errors mentioned in #9 or #11, so here's another build error.

During compilation (cordova build ios), I get these errors:
```
platforms/ios/testapp/Plugins/cordova-plugin-firebase/FirebasePlugin.m:76:15: error: property 'app' not found on object of type 'FirebasePlugin *'
        [self.app setApplicationIconBadgeNumber:number];
              ^
platforms/ios/testapp/Plugins/cordova-plugin-firebase/FirebasePlugin.m:78:15: error: no visible @interface for 'FirebasePlugin' declares the selector 'sendPluginResult:callbackId:'
        [self sendPluginResult:CDVCommandStatus_OK callbackId:command.callbackId];
         ~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
platforms/ios/testapp/Plugins/cordova-plugin-firebase/FirebasePlugin.m:84:28: error: property 'app' not found on object of type 'FirebasePlugin *'
        long badge = [self.app applicationIconBadgeNumber];
                           ^
platforms/ios/testapp/Plugins/cordova-plugin-firebase/FirebasePlugin.m:86:15: error: no visible @interface for 'FirebasePlugin' declares the selector
      'sendPluginResult:messageAsLong:callbackId:'
        [self sendPluginResult:CDVCommandStatus_OK messageAsLong:badge callbackId:command.callbackId];
         ~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```
It ends with:
```
The following build commands failed:
	CompileC build/testapp.build/Release-iphoneos/testapp.build/Objects-normal/armv7/FirebasePlugin.o testapp/Plugins/cordova-plugin-firebase/FirebasePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,platforms/ios/cordova/build-release.xcconfig,-project,testapp.xcodeproj,-target,testapp,-configuration,Release,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=platforms/ios/build/device,SHARED_PRECOMPS_DIR=platforms/ios/build/sharedpch
```
Any ideas?

**Comment by robertarnesson** [comment]
fixed in 0.1.9

**Comment by hnakhuva** [comment]
facing the same issue... what do you mean by "fixed in 0.1.9" I've installed it latest.. and still facing same error.. using xcode 8.2.. any idea?? @robertarnesson

**Comment by tiagoSAmaral** [comment]
I'm faceing this erro in iOS.

**Comment by sansan88** [comment]
I have the same error with plugin version <plugin name="cordova-plugin-firebase" spec="^0.1.21" />:

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.9.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed


The following build commands failed:
	Ld /Users/package/Library/Developer/Xcode/DerivedData/unihockey.club-heuklkchvpvpfvcakusggpelyaid/Build/Intermediates/ArchiveIntermediates/unihockey.club/IntermediateBuildFilesPath/unihockey.club.build/Release-iphoneos/unihockey.club.build/Objects-normal/arm64/unihockey.club normal arm64
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/package/workspace/apps-693f2e22-122/cordova/platforms/ios/cordova/build-release.xcconfig,-workspace,unihockey.club.xcworkspace,-scheme,unihockey.club,-configuration,Release,-destination,generic/platform=iOS,-archivePath,unihockey.club.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/package/workspace/apps-693f2e22-122/cordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/package/workspace/apps-693f2e22-122/cordova/platforms/ios/build/sharedpch
