### ISSUE TITLE
Multiple android apps not working with plugin

### ISSUE THREAD

**Issue by soumak77** [arnesson/cordova-plugin-firebase#204]
I just created a 2nd android app for my firebase project.  In doing so, firebase generates a new `google-services.json` file that now contains information about both of my android apps.  When running this plugin, I noticed that `after_prepare.js` only grabs the information for the 1st app in `google-services.json`.

```
// replace the default value
strings = strings.replace(new RegExp('<string name="google_app_id">([^<]+?)</string>', "i"), '<string name="google_app_id">' + json.client[0].client_info.mobilesdk_app_id + '</string>')

// replace the default value
strings = strings.replace(new RegExp('<string name="google_api_key">([^<]+?)</string>', "i"), '<string name="google_api_key">' + json.client[0].api_key[0].current_key + '</string>')
```

Notice the use of `json.client[0]` in the 2 lines of code above.  The 2nd app I added to firebase is listed as the 2nd client and therefore the after_prepare script should be using `json.client[1]` instead.

**I need support for specifying which client should be used by the plugin otherwise all analytics will be reported for the first app.**  As a workaround I suppose I can re-structure the `google-services.json` by hand, however, I would prefer to not have to edit the file every time a new app is added to firebase.

**Comment by robertarnesson** [comment]
I don't see how we can solve this in an easy way in the plugin itself. To solve the problem you can create 2 separate projects for your apps, or use your own hook to pick the right one

**Comment by emilianoglucero** [comment]
Same problem here :(
Does anyone have a solution to implement analytics with multiple apps ?
