### ISSUE TITLE
Get data From notification Opening the App and not the push

### ISSUE THREAD

**Issue by shepax** [arnesson/cordova-plugin-firebase#207]
Is there a way to get the data of the push without taping the notification?

I want to open the app and trigger an alert with the notification data.

#192 same here

**Comment by shepax** [comment]
#192  same

**Comment by shepax** [comment]
Sorry not the same,
**# Expected Behaviour**
On app open and notification not tape trigger onNotificationOpen() or a new method

**#Actual Behaviour**
On app open and notification not tape nothing happend, the message is lost.

**#Reproduce Scenario**

1. Send push to the cliente
2. Open the app
3. See if something triggers

**Comment by robertarnesson** [comment]
you could get the information from your own backend system that is sending the messages
