### ISSUE TITLE
Build fails on iOS

### ISSUE THREAD

**Issue by josinalvo** [arnesson/cordova-plugin-firebase#208]
Thanks for the plugin! It is working fine and helping us with android. However, with ios, our luck was not so great...

When trying to use firebase on iOS, I get an error when trying to 'ionic build ios'

    FirebasePlugin.m:7:1: error: use of '@import' when modules are disabled

My project was compiling just before adding firebase, and still works for android. The difference between the working version and the non working version was just a

    cordova plugin add cordova-plugin-firebase@0.1.19 --save

and the files GoogleService-Info.plist and google-services.json

From what I read online, this @import error seems to be a common error with ios builds, and the solution seems to be to include files in some other way

[build_with_firebase_and_plist_file.txt](https://github.com/arnesson/cordova-plugin-firebase/files/829131/build_with_firebase_and_plist_file.txt)
[second_build_with_firebase_plist_and_google_services_json.txt](https://github.com/arnesson/cordova-plugin-firebase/files/829133/second_build_with_firebase_plist_and_google_services_json.txt)

**Comment by josinalvo** [comment]
Solution: open the project (APP_MAIN_DIR/projects/ios) on xcode, turn on the setting 'enable modules (c and objective c)'. Then the build process works even when building on the CLI

**Comment by realnumber** [comment]
Thanks! Worked like a charm.
