### ISSUE TITLE
cordova browser support

### ISSUE THREAD

**Issue by mohamedsharaf** [arnesson/cordova-plugin-firebase#209]
as firebase supports chrome 49+ ,safari and firefox

what about adding cordova browser support
if this in future features list let me know or
if there is any help on where to start i can work on it and pull a request 

Regards

**Comment by adam-clarey** [comment]
+1 for this feature

**Comment by robertarnesson** [comment]
I'll take a pr :)

**Comment by mohamedsharaf** [comment]
thx for your work i checked version 1.25 i still cant see browser support will it be in next version or which?
