### ISSUE TITLE
Always returns error "plugin_not_installed"

### ISSUE THREAD

**Issue by projectxmatt** [arnesson/cordova-plugin-firebase#211]
Trying to use the plugin in a Ionic2 app and following the examples I could find however when I try to run getToken it always returns with an error of plugin_not_installed. 

<plugin name="cordova-plugin-firebase" spec="~0.1.19" /> is added in my config.xml and its in my plugins directory installed. As well as 

import { Geolocation, Firebase } from 'ionic-native';

At the top of my file. Have removed my ios and android builds and recreated them and still get the same error.

**Comment by N44PS** [comment]
Hello, which version of Ionic do you use ? Can you please provide some code sample ? config.xml ? `ionic info` ?

Thank you

**Comment by projectxmatt** [comment]
Sorry it was an issue on my part. Dumb issue on my part from late night coding. Wasn't waiting to platform was ready.
