### ISSUE TITLE
setScreenName is not a function

### ISSUE THREAD

**Issue by BenLorantfy** [arnesson/cordova-plugin-firebase#212]
Has setScreenName been removed from the api? If so, it should be removed from the docs and replaced with something else. I attached a screenshot of the error I'm getting along with a list of functions for the window.FirebasePlugin object.

<img width="786" alt="screen shot 2017-03-13 at 7 26 32 am" src="https://cloud.githubusercontent.com/assets/4398635/23852485/6a65e5c8-07be-11e7-9dca-bd5e485ece16.png">

**Comment by xan589** [comment]
+1

**Comment by oudzy** [comment]
I think the version of the plugin must be bumped to .20 or so to be able to fetch the latest commits but until then change the plugin spec in config.xml to this line to get the latest version
    <plugin name="cordova-plugin-firebase" spec="https://github.com/arnesson/cordova-plugin-firebase#ff9232350761ee3550bb9f6a4f4bcc1930f10e54" />

**Comment by danieleboria** [comment]
I also have the same issue.
Any suggestion?
Many thanks

**Comment by robertarnesson** [comment]
fixed in 0.1.20
