### ISSUE TITLE
Application not receiving notification when it is closed. 

### ISSUE THREAD

**Issue by AkramFaiz** [arnesson/cordova-plugin-firebase#213]
My application is not receiving notification when it is closed. 
I have surfed for solution, and found something like adding  "click_action":"FCM_PLUGIN_ACTIVITY"
I didnt understand it. Can you help me out in getting the notification when application is closed.

**Comment by Hannu6** [comment]
I got the same issue, no way to open the application and then handle notification payload as it's not getting into the app if the application was closed (not at the background).

There is a way around but it's bit more complicated and currently seems to require sending two push notifications; one to "open the app" and second one to handle the data from the notification.

Please check this thread: https://github.com/phonegap/phonegap-plugin-push/issues/1274
Especially the second comment as that workaround applied here as well.

I'm currently sending two push messages, one to just show the notification to the users without any other payload and second one with actual payload for the application to use after it's opened by tapping the first notification. The second push doesn't have any visible notification as that would then disable the payload handling.

**Comment by AkramFaiz** [comment]
Thanks for quick reply.

 Can you tell me how you are opening the app with the notification when the
application is closed? As we don't receive any notification when
application is closed.

I didnt get this part --
' There is a way around but it's bit more complicated and currently seems
to require sending two push notifications; one to "open the app" and second
one to handle the data from the notification. '

Thanks,
Akram Faiz.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
