### ISSUE TITLE
Counted single in-app-purchase twice

### ISSUE THREAD

**Issue by ilyakar** [arnesson/cordova-plugin-firebase#215]
A single purchase that was made by a single user has been reported to Firebase as two purchases by that user.

It happened on the Android platform in production.

![image](https://cloud.githubusercontent.com/assets/1760709/24008018/a536578c-0a70-11e7-9e6a-331c43afc162.png)

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
