### ISSUE TITLE
How to open the link from notification bar?

### ISSUE THREAD

**Issue by merbin2012** [arnesson/cordova-plugin-firebase#217]
Usually my app doesn't require any notification, I am using the push notification for  only open web links. When I send the notifation with online link like (http://www.htmlcodeplay.com), it should open in the default browser, without open my application. How can I do this?

**Comment by robertarnesson** [comment]
you have to use other plugins to open the link

**Comment by merbin2012** [comment]
ha ha ha, I have successfully opened the link from notification click using this plugin.
