### ISSUE TITLE
onNotificationOpen() on Firebase Dynamic Link

### ISSUE THREAD

**Issue by saiy2k** [arnesson/cordova-plugin-firebase#218]
When I click on a Firebase Dynamic Link, my app is opened and this plugin's `onNotificationOpen()` function is invoked and the object with Single key/value pair is passed via Function parameter:
`com.google.android.gms.appinvite.REFERRAL_BUNDLE: "Bundle[mParcelledData.dataSize=492]"`

Is there any way, I could get the Dynamic URL itself?

**Comment by soumak77** [comment]
Closing out-dated issue.  Please reopen if issue still exists with the latest version of the plugin.
