### ISSUE TITLE
[DISCUSSION] Report javascript exceptions with Firebase

### ISSUE THREAD

**Issue by robertarnesson** [arnesson/cordova-plugin-firebase#22]
There are several ways to do this:

**A) Using Firebase Crash Reporting.**
This option would involve implementing FIRCrashLog/FirebaseCrash.log to first log the javascript exception(s) to a crash report, then on android we can send the report by triggering a non-fatal error
```
FirebaseCrash.report(new Exception());
```
On IOS its more complicated because Firebase only handles fatal errors. We can implement our own report method that calls e.g. ```assert(false);``` to trigger a crash which will cause the report to be sent. But javascript errors are essentially non-fatal so I don't like the idea of having to crash the entire app to catch them.

Crash docs: https://firebase.google.com/docs/crash/

**B) Use logEvent to log exceptions.**
The problem here is that there seems to be a character limit to event names and params (32 characters). We could split the exception info over several params, a message is rarely > 32 characters. But I feel that this will clutter the analytics console plus it would be ideal to have no size restriction so that e.g. the full callstack could be attached if desired. 

logEvent would need a rewrite for this. Right now the event name and param names are hardcoded

Analytics docs: https://firebase.google.com/docs/analytics/

**C) Use a combination of e.g. logEvent and Storage.**
This option would involve implementing Firebase Storage and rewriting logEvent, the rest of the implementation is done in the client by the user.
An example implementation would be to upload the javascript exception as a text file to Firebase Storage and also log an event with e.g. name "exception" and url to the file as param. You could also generate a hash from the exception/message/callstack and save that as a param as well, this way crashes can be grouped in the analytics console

Opinions, ideas?

**Comment by TroyStopera** [comment]
Here's my thinking:

A) Works great for Android, but I agree that causing a fatal error for iOS is not something that would be OK. No need to crash an app for a JavaScript error.

B) I definitely think it would cause too much clutter in the console. It may be harder to make sense of crashes reported like this. 

C) This idea seems the most usable, but, some people may not want to use Storage for their crash files. I don't think I'd want to do so, but I'd be willing to if I had to. 

I feel like all three options are less than ideal. I'd say B is the least ideal in my eyes. I don't like A causing unneeded crashes, but I almost equally don't like C using storage and events to create a makeshift system. However, in the end I think C is the most versatile and users could adapt their implementation to fit their needs. 

Would it be feasible to offer both option A and C somehow? Maybe users could use option A for critical errors that couldn't really be recovered from, and other errors could use option C. Not saying it's a great idea (having two simultaneous  systems to monitor bugs would be irritating), just brainstorming.

**Comment by robertarnesson** [comment]
I sent a feature request and got a response back from Google. Basically a lot of people have requested this so hopefully we'll see non-fatal crash reporting on iOS soon, which would solve this issue
