### ISSUE TITLE
Notification tabbed

### ISSUE THREAD

**Issue by pdmshrestha** [arnesson/cordova-plugin-firebase#220]
Hi,

This great plugin. But I am not able to detect if the notification was tapped or not? "window.FirebasePlugin.onNotificationOpen" is fired whenever the notification is tapped but this function is also fired when notification is received in foreground.

**Comment by michael-unitn** [comment]
If notification was not tapped, the notification object will have a tapped parameter, which is set to false. Instead, if the notification was tapped, the parameter will not be available at all. So, you can check if notification was not tapped an proceed accordingly.
`if(notification.tap === false) {
//app was brought to the foreground without tapping the notification
}`
