### ISSUE TITLE
hasPermission never calls my callbacks

### ISSUE THREAD

**Issue by dwoodlock** [arnesson/cordova-plugin-firebase#223]
hasPermission doesn't seem to be working.  I call it (see below) but it never calls my callbacks. I have tried with push notifications turned on and off on the device.  I'm on iOS 10.2.  Any ideas?
`	window.FirebasePlugin.grantPermission();	

  console.log("calling hasPermission");
  window.FirebasePlugin.hasPermission(
    function(data){
      console.log("hasPermission", data.isEnabled);
      },
    function(err) {
      console.log("hasPermission error ", err)
    }
  );	`

**Comment by dcuesta1** [comment]
I believe the hasPermission method is available only on iOS.

**Comment by alejandro-lopez** [comment]
@dcuesta1, @dwoodlock is talking about iOS 10.2, I also have the same problem.

**Comment by robertarnesson** [comment]
try with the latest release 0.1.20
