### ISSUE TITLE
grouping push in background

### ISSUE THREAD

**Issue by ai2010** [arnesson/cordova-plugin-firebase#227]
Hello,

I'm using this plugin to notify of messages. If the user receives a lot of them, I would like to group them in 1 notification instead of adding many of them.

Do you know how can I do that?
Is there any push.off method implemented to remove the push outstanding?
Thanks

**Comment by nickmendes** [comment]
Hello, you can use **collapseKey** on your sent payload.

eg. 
{
`priority: 'high',
                            contentAvailable: 'true',
                            collapseKey: 'test',
                            notification: {
                              title: 'stuff',
                              body: 'stuff'     
                            }`
}

**Comment by moromer90** [comment]
It will work if you include in your notification 2 lines:
                                        collapse_key: 'your_app_unique_string',
                                        tag: 'your_app_unique_string'
So the full code would be:
var payload = {notification: {
                                        title: "Mensaje de "+message.name,
                                        body: message.text,
                                        sound: "default",
                                        collapse_key: 'charlero',
                                        tag: 'charlero'
                                    }
                                };
