### ISSUE TITLE
App crash with v0.1.20 when in foreground (+quick fix)

### ISSUE THREAD

**Issue by media0101** [arnesson/cordova-plugin-firebase#228]
Android 5.0.2
Cordova Android 6.1.2
Sending a notification from Firebase Console to device, app in foreground crashes. In code there aren't plugin script functions. If app is in background, no crash.

Debug error:
04-06 16:50:35.680 22035-24233/com.XXXX.app E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
                                                                   Process: com.XXXX.app, PID: 22035
                                                                   java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar:classes2.dex)
                                                                       at org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification(FirebasePluginMessagingService.java:105)
                                                                       at org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived(FirebasePluginMessagingService.java:71)
                                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source)
                                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
                                                                       at com.google.firebase.messaging.FirebaseMessagingService.zzm(Unknown Source)
                                                                       at com.google.firebase.iid.zzb$2.run(Unknown Source)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)

*************************************************************************
I solved the problem temporarily commenting lines 104 and 105 in the file \platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java :
/**
int accentID = getResources().getIdentifier("accent", "color", getPackageName());
notificationBuilder.setColor(getResources().getColor(accentID, null));
*/

In this way notifications work without problems (color and icon are defined in the message).

**Comment by s3ppo** [comment]
i have the same issue, it always crashes when in foreground.

**Comment by stormwin** [comment]
+1

**Comment by media0101** [comment]
I solved the problem temporarily commenting lines 104 and 105 in the file \platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java :
/**
int accentID = getResources().getIdentifier("accent", "color", getPackageName());
notificationBuilder.setColor(getResources().getColor(accentID, null));
*/

**Comment by s3ppo** [comment]
@media0101 thanks for your temp fix, but its just sometimes working. i will post the error later when im on my notebook :)

**Comment by s3ppo** [comment]
so after i commented the lines from your quick fix :)
i sometimes get this error:
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:112)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzl ()
com.google.firebase.messaging.FirebaseMessagingService.zzJ ()
com.google.firebase.messaging.FirebaseMessagingService.handleIntent ()
com.google.firebase.iid.zzb$1.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

**Comment by media0101** [comment]
@s3ppo which version of Android you use?

**Comment by s3ppo** [comment]
@media0101 its a LG G5 with Android version 7.0.0

**Comment by media0101** [comment]
@s3ppo I use lollipop and it works but I tried Nougat with emulator and occurs your error.
Try to comment the line 111 (same file:  \platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java):
/ ** (fix x os = Nougat error)
notification.contentView.setImageViewResource (iconID, notiID);
* /
It works for me on Nougat emulation.
Verify if the icon and the colors are correct; Keep in mind that mine is just a quick fix that could create problems with the notification icon customization.

**Comment by s3ppo** [comment]
@media0101 thank u i will try it in the evening. would be cool to get some feedback from official side if there will be a bugfix for this :)

**Comment by s3ppo** [comment]
@media0101 works like charm. but is this normal that i get the notification on the device i sent it from, when im subscribed to a topic?

**Comment by media0101** [comment]
@s3ppo Sorry, but I never used topics. In my app I use only the classic notifications sent to the devices by a remote server.

**Comment by Deluxo** [comment]
# regarding quick fix

This no longer enough. One must also add this (or something similar) to res/value/colors.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">#FFFFFF00</color>
    <color name="primary_dark">#FF220022</color>
    <color name="accent">#FF00FFFF</color>
</resources>
```

**Comment by foxxx** [comment]
I'm having the same issue, foreground or background -- doesn't matter. The fixes are also not working...

**Comment by Deluxo** [comment]
Indeed. The java code compiles, however many methots stay unfired.

**Comment by alx-andru** [comment]
Quickfix by @Deluxo worked, hope there is a proper fix soon.

**Comment by appsasync** [comment]
Hellos

I have placed the colors.xml file [projectRoot]/res/value/colors.xml and also in [projectRoot]/plugins/cordova-plugin-firebase/res/value/colors.xml

but app still crahes when in foreground
do i need to comment the FirebasePluginMessagingService.java 
or use the last FirebasePluginMessagingService.java with the commits from  GerardSoleCa

**Comment by sssrajshri** [comment]
You need to add the file on following locations "platforms\android\res\values"

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
