### ISSUE TITLE
Sample implementation?

### ISSUE THREAD

**Issue by chrisknu** [arnesson/cordova-plugin-firebase#230]
I'm working with a Meteor app that handles cordova bits a bit differently. Do you have a standard cordova example app with this working that could be added to the repo?

It'd be handy to see an example

**Comment by joseryzmal** [comment]
```
meteor add cordova:cordova-plugin-firebase@0.1.23
```

- Download `google-services.json` and `GoogleService-Info.plist` from Google Firebase Console, and place them following the directory below:

```
cordova-build-override
├── GoogleService-Info.plist
└── google-services.json
```

- Confirm it's logging in Xcode by following this https://firebase.google.com/docs/analytics/ios/events#view_events_in_the_xcode_debug_console

Tested using Meteor 1.5.1
