### ISSUE TITLE
getToken return empty string

### ISSUE THREAD

**Issue by jeansarlon** [arnesson/cordova-plugin-firebase#231]
i have this code:

```
constructor(
      public navCtrl: NavController,
      public navParams: NavParams,
      public firebase: Firebase,
      public platform: Platform
   ) {
      this.navCtrl = navCtrl;
      this.Http = http;
      this.filter = Filter;
      this.infinitePage = 0;
      this.getData();


      platform.ready().then(() => {
         if (platform.is("cordova")) {
            firebase.getToken().then(token =>this.storeToken(token)).catch(error => console.log('erro'));
         }
      });
   }

   storeToken(token){
      alert(token)
   }
```

## end google service files:
[project](http://imgur.com/a/Qg80p)
![alt tag](http://i.imgur.com/2ds78Cw.png)

## In device app
the alert is empty
![alt tag](http://i.imgur.com/pgzVSOZ.png)

I hope someone can help me. 
Thx

**Comment by GerardSoleCa** [comment]
I'm not sure about that, but, are you sure that you have google-services.json and GoogleService-Info.plist inside www directory?

It seems that they are just on the root dir...

**Comment by Nerdcode** [comment]
Same issue as @jeansarlon. Anyone please help 
donno what im missing.

@jeansarlon have u fixed this issue

**Comment by adadgio** [comment]
Another solution is here: https://github.com/arnesson/cordova-plugin-firebase/issues/558

To the author: A PR and a fix is **URGENT** now... ;-)
