### ISSUE TITLE
error: cannot find symbol  mFirebaseAnalytics.setCurrentScreen(cordova.getActivity(), name, null);

### ISSUE THREAD

**Issue by roshni-kamath** [arnesson/cordova-plugin-firebase#232]
error: cannot find symbol
                    mFirebaseAnalytics.setCurrentScreen(cordova.getActivity(), name, null);
                                      ^
  symbol:   method setCurrentScreen(Activity,String,<null>)
  location: variable mFirebaseAnalytics of type FirebaseAnalytics
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I am using the latest cordova-firebase-plugin and cordova version

**Comment by sleever** [comment]
Bump! I've got the same issue.

**Comment by roshni-kamath** [comment]
Solved the issue by updating the android sdk platform tools, Android support repository and Google repository
