### ISSUE TITLE
Notification Bar not opening app

### ISSUE THREAD

**Issue by pedrodagraca** [arnesson/cordova-plugin-firebase#233]
Android 5.X+ When the app is in the background and a message is received, I get a notification in the notification bar but when clicking the notification, the app does not open.

**Comment by martykan** [comment]
Same issue here

**Comment by pedrodagraca** [comment]
yes I did, and then changed to this one. why do you ask?

**Comment by Almya** [comment]
Because I had the same issue. If you use http on your server to send your notifications don't forget to remove the `click_action` from your message object.

**Comment by pedrodagraca** [comment]
ah brilliant. let me give it a try and will revert.

**Comment by pedrodagraca** [comment]
And first prize goes to Almya!! Thank you so much. The issue is resolved!

**Comment by Almya** [comment]
@pedrodagraca you're welcome ;)

**Comment by mbn18** [comment]
Yep, the server side had:

        $n = new Notification($title, $body);
        return $n->setClickAction("FCM_PLUGIN_ACTIVITY")->setIcon('fcm_push_icon')-
>setSound('default');

I changed it to:

        return $n->setIcon('fcm_push_icon')->setSound('default');

And now it works as expected

**Comment by brickolicious** [comment]
But what if you have the app in production.
if you remove the click_action old version wont open the app on notification tap, how would we go about defining a click action in cordova?

**Comment by JaviChaques** [comment]
Same problem here
