### ISSUE TITLE
Sound not correctly sent ios

### ISSUE THREAD

**Issue by dtruel** [arnesson/cordova-plugin-firebase#234]
Hello, thank you for making this plugin!  I have an issue though.

Update - I realized that nothing is working via APNS for iOS now.  This may be the root cause.

Strange issue - when I send this

```php

Array
(
    [registration_ids] => Array
        (
            [0] => ID_REDACTED
        )

    [priority] => high
    [notification] => Array
        (
            [title] => 
            [body] => stuff
            [sound] => sounds/test.m4a
        )

)
```
it comes in as 
```
{
  body = stuff;
  e = 1;
  sound = default;
  sound2 = "sounds/test";
  title = titletest
}
```

What is sound2 for?  I couldn't find that anywhere in the docs for this or firebase

**Comment by robertarnesson** [comment]
this is not related to the plugin itself, we don't handle sending messages and the response is just passed on from the firebase sdk. I think stackoverflow or the firebase repo is a better place for this question
