### ISSUE TITLE
Build failed: cannot find symbol notificationManagerCompat & setCurrentScreen

### ISSUE THREAD

**Issue by sleever** [arnesson/cordova-plugin-firebase#235]
Hello everybody,

I have recently upgraded to the latest version of cordova, ionic and angular and when I emulate/build my app it throws the following error:

```
BUILD FAILED


Total time: 2.681 secs

Error: cmd: Command failed with exit code 1 Error output:
D:\projects\apps\portemewallet\Portemewallet\platforms\android\src\org\apache\cordova\firebase\FirebasePlugin.java:270: error: cannot find symbol
                    boolean areNotificationsEnabled = notificationManagerCompat.areNotificationsEnabled();
                                                                               ^
  symbol:   method areNotificationsEnabled()
  location: variable notificationManagerCompat of type NotificationManagerCompat
D:\projects\apps\portemewallet\Portemewallet\platforms\android\src\org\apache\cordova\firebase\FirebasePlugin.java:370: error: cannot find symbol
                    mFirebaseAnalytics.setCurrentScreen(cordova.getActivity(), name, null);
                                      ^
  symbol:   method setCurrentScreen(Activity,String,<null>)
  location: variable mFirebaseAnalytics of type FirebaseAnalytics
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

The firebase plugin is also updated to the latest version (0.1.20).

Does anyone have a solution for this issue?

(I do find it interesting that Analytics is now available in the plugin, though).

Thanks in advance.

Best regards,
Stefan

**Comment by sleever** [comment]
Going to perform this test: Solved the issue by updating the android sdk platform tools, Android support repository and Google repository.

If it's succesful I will close this issue.

**Comment by sleever** [comment]
Just to confirm: installing a new version of the SDK or Android API fixes the errors.

**Comment by t2wu** [comment]
Does this mean the plugin only works with Android 7?

**Comment by floydus** [comment]
I'm lost, I have a few AVDs in android studio and I still have the same exact build error.
Here are my SDK tools settings.
![screen shot 2017-09-02 at 4 31 29 am](https://user-images.githubusercontent.com/19679654/29994186-ac9f635e-8f97-11e7-91b2-785183073335.png)
And my virtual devices...
![screen shot 2017-09-02 at 4 37 15 am](https://user-images.githubusercontent.com/19679654/29994221-7762bf8c-8f98-11e7-8d7d-4964e8e0af44.png)
Let me know if you require more information to help. thanks.
