### ISSUE TITLE
Firebase notification causing app crash

### ISSUE THREAD

**Issue by vvsraju04** [arnesson/cordova-plugin-firebase#237]
Tried sending firebase notification using token , app got crash with following error:

> D/FirebasePlugin( 3621): From: 1068471080
> D/FirebasePlugin( 3621): Notification Message id: 0:1491926652330332131e1237da0e12
> D/FirebasePlugin( 3621): Notification Message Title: null
> D/FirebasePlugin( 3621): Notification Message Body/Text: My mobile notification message
> E/UncaughtException( 3621):
> E/UncaughtException( 3621): java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
> E/UncaughtException( 3621):     at org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification(FirebasePluginMessagingService.java:105)
> E/UncaughtException( 3621):     at org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived(FirebasePluginMessagingService.java:71)
> E/UncaughtException( 3621):     at com.google.firebase.messaging.FirebaseMessagingService.zzl(Unknown Source)
> E/UncaughtException( 3621):     at com.google.firebase.messaging.FirebaseMessagingService.zzJ(Unknown Source)
> E/UncaughtException( 3621):     at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
> E/UncaughtException( 3621):     at com.google.firebase.iid.zzb$1.run(Unknown Source)
> E/UncaughtException( 3621):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/UncaughtException( 3621):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/UncaughtException( 3621):     at java.lang.Thread.run(Thread.java:818)
> E/AndroidRuntime( 3621): FATAL EXCEPTION: pool-5-thread-1
> E/AndroidRuntime( 3621): Process: com.company.entity, PID: 3621
> E/AndroidRuntime( 3621): java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
> E/AndroidRuntime( 3621):        at org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification(FirebasePluginMessagingService.java:105)
> E/AndroidRuntime( 3621):        at org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived(FirebasePluginMessagingService.java:71)
> E/AndroidRuntime( 3621):        at com.google.firebase.messaging.FirebaseMessagingService.zzl(Unknown Source)
> E/AndroidRuntime( 3621):        at com.google.firebase.messaging.FirebaseMessagingService.zzJ(Unknown Source)
> E/AndroidRuntime( 3621):        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
> E/AndroidRuntime( 3621):        at com.google.firebase.iid.zzb$1.run(Unknown Source)
> E/AndroidRuntime( 3621):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/AndroidRuntime( 3621):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/AndroidRuntime( 3621):        at java.lang.Thread.run(Thread.java:818)
> W/ActivityManager( 1693):   Force finishing activity com.company.entity/.MainActivity

Any help would be appreciated. 
Thanks

**Comment by media0101** [comment]
View my quick fix here:
https://github.com/arnesson/cordova-plugin-firebase/issues/228

**Comment by dloijenga** [comment]
This is due to the assumption that the color.xml exists in the cordova-plugin-firebase/res/values folder, while it is not, either place one there, or omit the lines as described by media0101
