### ISSUE TITLE
Icon in notification is always a white square

### ISSUE THREAD

**Issue by Nunatani** [arnesson/cordova-plugin-firebase#239]
I'm trying to change the notification icon when the user swipe down the notification menu.
In the status bar, everything is OK.

As said in the readme, I have a notification_icon.png file in <projectroot>/res/native/android/res/<drawable-DPI> and my app icons are OK (I have the correct icon on my launcher)

My XML files are, as asked in the readme :
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <!-- inherit from the holo theme -->
    <style name="AppTheme" parent="android:Theme.Light">
        <item name="android:windowDisablePreview">true</item>
    </style>
    <drawable name="notification_big">@mipmap/ic_launcher</drawable>
    <drawable name="notification_icon">@drawable/notification_icon</drawable>
</resources>
```
and
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <!-- inherit from the holo theme -->
    <style name="AppTheme" parent="android:Theme.Light">
        <item name="android:windowDisablePreview">true</item>
    </style>
    <drawable name="notification_big">@drawable/notification_icon</drawable>
    <drawable name="notification_icon">@drawable/notification_icon</drawable>
</resources>
```

What do I have to change to have the correct icon ?

**Comment by Nunatani** [comment]
OK, found it

It was a color problem

**Comment by arielgelbard** [comment]
@Nunatani can you expand on that issue please?

**Comment by Nunatani** [comment]
The color of my picto was white, so, when a push was in my notification center, I could only see a white square. This white square was the superposition of the white background, and my white icon.
Once I've tried with an other png, I saw that it was just a background color relative problem.
So, I just changed the color of the picto
