### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by t2wu** [arnesson/cordova-plugin-firebase#241]
I have the following error, any help appreciated. I'm testing it on Android 6.

Error: /Users/t2wu/Documents/Work/John/DEMO_APP/BCAppII/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/t2wu/Documents/Work/John/DEMO_APP/BCAppII/platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:270: error: cannot find symbol
                    boolean areNotificationsEnabled = notificationManagerCompat.areNotificationsEnabled();
                                                                               ^
  symbol:   method areNotificationsEnabled()
  location: variable notificationManagerCompat of type NotificationManagerCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by t2wu** [comment]
I tried by setting minimum sdk version to 24 and the error remains. BTW does this mean this will only work with Android 7?

**Comment by marcusforsberg** [comment]
I have a similar error:

`cannot find symbol mFirebaseAnalytics.setCurrentScreen(cordova.getActivity(), name, null);`

Has anyone had any luck getting it to build?

**Comment by zgluis** [comment]
I removed version 0.1.2, installed 0.1.19 and now works, we must check what changed between these versions

**Comment by t2wu** [comment]
I tried it with 0.1.19 and it does build! However, on iOS hasPermission is not defined.

**Comment by t2wu** [comment]
Removing Android platform and reinstalling it solves this issue.

**Comment by t2wu** [comment]
`cordova clean android` may solve it as well.

**Comment by 2016508006** [comment]
> I removed version 0.1.2, installed 0.1.19 and now works, we must check what changed between these versions

i dont understand dude. which you removed and installed . can you pls tell me clearly
