### ISSUE TITLE
IOS notifications not received when permission is granted afterward

### ISSUE THREAD

**Issue by Almya** [arnesson/cordova-plugin-firebase#242]
Hi there, I made some test on my app on IOS.

If I grant the permission when the prompt shows, I receive the notifications. Everything works fine.

If I decline the permission when the promp shows, I don't receive the notifications. Everything works fine too.
But if I go to my settings and grant the notifications permission to my app afterward, I still don't receive any notification.

**Comment by spivotron** [comment]
+1

**Comment by eros2187** [comment]
Hello can i know what procedure you followed to make notifications work?
Do you send them messages with the firebase console?
If you use some script, you can post a code sample because I can not get any notification even if I can get the token thanks

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
