### ISSUE TITLE
When app is in foreground, how to push the notification to notification bar.

### ISSUE THREAD

**Issue by harshvardhan12** [arnesson/cordova-plugin-firebase#243]
When app is in use and notification comes, is there any way to send that notification to notification bar of the device. Is there any way to notify the user

**Comment by loama** [comment]
In the onNotificationOpen method you should call what happens when user receives notification, for example "alert(notification.data)"

This way you can notify the user while using the app.

**Comment by StasKalishenko** [comment]
It works for me (for iOS 10 only):

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    ...
    **completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);**
}

And if anybody wants to handle clicks on notification in foreground, change application:didReceiveRemoteNotification:fetchCompletionHandler method setting YES for 'tap':

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
    fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    ...
    **[mutableUserInfo setValue:@(YES) forKey:@"tap"];**
    ...
}

**Comment by rolinger** [comment]
@Ioama @StasKalishenko  @harshvardhan12 - did any of you ever get notifications working on Android when app is open and in foreground?  I got it working on iOS but not on Android.

If app is closed or open in the background - I got it working on both Android & iOS.  But if open and in foreground I only have it working on iOS - not on Android. 

In fact, on Android, when a message arrives while app is open in foreground nothing happens - I can't even get a console.log to fire in the success callback (like Ioama's example above) - but works just fine in iOS.

I am on Android 6x...wondering if that has anything to do with it?  Oh, and I am literally just using native Javascript - as defined in the plugin specs.

Here is my code:
```
  window.FirebasePlugin.onNotificationOpen(function(payload) {
    alert(payload.data) ;  // open/foreground - this should fire when but does not
    console.log("here we are") ;
    // the below all works just fine if app is closed or open/background.
    // if there is a payload it will be in payload object
    if (payload.action == 1) { // email verification confirmation
      setDB("user_emailVerify",payload.user_emailVerify) ;
    } else if (payload.action == 2) {
      alert(payload.dataTitle+ "\n" +payload.dataMsg) ;
    }
  }, function(error) {
      console.error(error);
  }) ;
```

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by tshepo-choshi** [comment]
cordova - how to show firebase notification when the app is in foreground? 
Is the a method I can use to trigger notifications while application is open,
It works perfect when the application is closed.

**Comment by jogat** [comment]
on AppDelegate+FCMPlugin.m
use **UNNotificationPresentationOptionAlert**
 // Change this to your preferred presentation option
    completionHandler(UNNotificationPresentationOptionAlert);
