### ISSUE TITLE
Does not work on iOS 10, works on iOS 9

### ISSUE THREAD

**Issue by dtruel** [arnesson/cordova-plugin-firebase#244]
Hello,

I've built an app with this plugin with XCode 7 and tested on iOS 9.  It works perfectly.  I get notifications in foreground, and push notifications in backround or when app is closed no complaints.

Now when the app is tried on 2 iOS 10 devices, there is not even any popup requesting permission to show push notifications!  Push notifications don't work at all.  Here is my code:

```javascript
    if(window.FirebasePlugin){
        window.FirebasePlugin.grantPermission();
        FirebasePlugin.onTokenRefresh(function(token) {
            processToken(token);
        });
        window.FirebasePlugin.onNotificationOpen(function(notification) {
            // if(data.wasTapped){
            // //Notification was received on device tray and tapped by the user.
            // alert( JSON.stringify(data) );
            // }else{
            //Notification was received in foreground. Maybe the user needs to be notified.
                onNotification(notification);
            // }
        })
    }
```

Here is more debug info:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 7.3.1 Build version 7D1014

cordova-background-geolocation 2.4.0 "BackgroundGeolocation"
cordova-plugin-background-fetch 4.0.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-dialogs 1.3.2 "Notification"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-firebase 0.1.20 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-keyboard 1.1.4 "Keyboard"
cordova-plugin-media 3.0.0 "Media"
cordova-plugin-whitelist 1.3.2 "Whitelist"

**Comment by loama** [comment]
double check that you are using the same app on iOS 9 and iOS 10, I am currently using this plugin and testing on both iOS 9 and 10 and it works perfectly.

**Comment by swbradshaw** [comment]
I'm using this plugin on iOS 10. No problems here, either.

**Comment by vegetablesalad** [comment]
@dtruel check out my post https://github.com/arnesson/cordova-plugin-firebase/issues/247
perhaps you have the same issue

**Comment by hungkun** [comment]
I have the same issue when I build project with Xcode 7. And I review source code obj-C of plugin, I founded logic get permission on ios will check with your SDK build project. And then I build with Xcode 8, SDK 10.2, my app working normally on ios.

Thus, please build your project with latest Xcode for resolving this issue.

Hope this help.

**Comment by robertarnesson** [comment]
you need to build with xcode 8, otherwise you are missing the ios 10 sdk and nothing will work..

**Comment by dtruel** [comment]
Ok, I will update XCode. Thanks for the help!
