### ISSUE TITLE
Android notification does not trigger "window.FirebasePlugin.onNotificationOpen" function when app is open

### ISSUE THREAD

**Issue by loama** [arnesson/cordova-plugin-firebase#245]
Hi, notifications are working perfectly on iOS and on Android when app is in foreground.

But with app open or completely closed on Android, notifications just don´t arrive.

**Comment by jpfsilva** [comment]
same for me but I'm on ionic 2, I guess you are coding in ionic 1

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
