### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by silasmatheus** [arnesson/cordova-plugin-firebase#248]
Config Remote not working for me. The data not update.

I'm using this methods:

window.FirebasePlugin.fetch()
window.FirebasePlugin.activateFetched()
window.FirebasePlugin.getValue()

Is there any completed example?

**Comment by remisture** [comment]
+1

**Comment by samarthagarwal** [comment]
Not working. Always returns the default value.

**Comment by Bodeclas** [comment]
(<any>window).FirebasePlugin.fetch(600, result => {
           // activate the fetched remote config
           console.log(JSON.stringify(result)); //Always "OK"
           (<any>window).FirebasePlugin.activateFetched(
             // Android seems to return error always, so we want to cath both
             result => { 
               console.log(JSON.stringify(result)); //either true or false
              (<any>window).FirebasePlugin.getValue("value", result => {  
              console.log(result)  
               }, reason => {
              console.warn(`Error  ${reason}`);
              });
             }, reason => { 
               console.warn(reason); 
             }
           )
         });

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
