### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by KhomkribSingh** [arnesson/cordova-plugin-firebase#25]
**After I add this plugin to my Cordova project, I got an error Message:**

MDAVSCLI : error : Uh oh!
Executing "before_plugin_install"  hook for "cordova-plugin-firebase" on android.
Install start for "cordova-plugin-firebase" on android.
Beginning processing of action stack for android project...
"(ProjectPath)\platforms\android\google-services.json" already exists!
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**My Environment:**

- cordova-plugin-firebase Version 0.1.9 
- Visual Studio 2015 Apache Cordova Update 7
- Cordova CLI Version 5.4.1
- Cordova Android Version 4.1.1

**Comment by robertarnesson** [comment]
what other plugins are you using?

**Comment by KhomkribSingh** [comment]
My Plugins:

- com.lampa.startapp 0.1.4 "startApp"
- com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin" (with android-support-v13.jar)
- com.telerik.plugins.healthkit 0.4.2 "HealthKit"
- cordova-plugin-camera 2.2.1-dev "Camera"
- cordova-plugin-compat 1.0.0 "Compat"
- cordova-plugin-customurlscheme 4.1.3 "Custom URL scheme"
- cordova-plugin-device 1.1.2 "Device"
- cordova-plugin-dialogs 1.2.0 "Notification"
- cordova-plugin-file 4.1.1 "File"
- cordova-plugin-file-transfer 1.5.1 "File Transfer"
- cordova-plugin-firebase 0.1.9 "Google Firebase Plugin"
- cordova-plugin-geolocation 2.1.0 "Geolocation"
- cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
- cordova-plugin-media 2.2.0 "Media"
- cordova-plugin-splashscreen 4.0.0 "Splashscreen"
- cordova-plugin-themeablebrowser 0.2.15 "ThemeableBrowser"
- cordova-plugin-whitelist 1.2.1 "Whitelist"
- cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
- ionic-plugin-keyboard 2.2.0 "Keyboard"
- phonegap-facebook-plugin 0.12.0 "Facebook Connect" (with android-support-v13.jar)

**Comment by robertarnesson** [comment]
this plugin replaces PushPlugin so don't use both

**Comment by KhomkribSingh** [comment]
I use this PushPlugin in both cordova iOS and Android platforms but I need to add firebase analytic to my app. I should remove pushPlugin and use push function from this firebase plugin instead. Is it right?

**Comment by KhomkribSingh** [comment]
After I remove pushPlugin I got the same error message:

Installing plugin "cordova-plugin-firebase" following successful platform add of android
Found variables for "cordova-plugin-firebase". Processing as cli_variables.
Installing "cordova-plugin-firebase" for android
Running command: cmd "/s /c <ProjectPath>\platforms\android\cordova\version.bat""
Command finished with error code 0: cmd /s /c <ProjectPath>\platforms\android\cordova\version.bat"
Executing "before_plugin_install"  hook for "cordova-plugin-firebase" on android.
Install start for "cordova-plugin-firebase" on android.
Beginning processing of action stack for android project...
MDAVSCLI : warning : Error during processing of action! Attempting to revert...
MDAVSCLI : warning : Failed to install 'cordova-plugin-firebase':Error Uh oh!
<ProjectPath>\platforms\android\google-services.json" already exists!
at Object.module.exports.common.copyNewFile (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:67:19)
at module.exports.source-file.install (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:78:20)
at C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:654:27
at Object.ActionStack.process (C:\Users\Khomkrib\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\src\ActionStack.js:56:25)
at PlatformApiPoly.addPlugin (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:259:20)
at handleInstall (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:603:6)
at C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:382:28
at _fulfilled (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\q\q.js:787:54)
at self.promiseDispatch.done (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\q\q.js:816:30)
at Promise.promise.promiseDispatch (C:\Users\<MyUser>\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.4.1\node_modules\cordova\node_modules\q\q.js:749:13)
MDAVSCLI : error : Uh oh!
 "<ProjectPath>\platforms\android\google-services.json" already exists!
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by robertarnesson** [comment]
have you tried to make a clean build?

**Comment by KhomkribSingh** [comment]
Yes, I made a clean build and remove project platforms before.

**Comment by robertarnesson** [comment]
then one of the other plugins you use also write the google-services.json file, or you are writing it yourself. There can only be one file. We could change the hook to just throw a warning but It won't fix the problem

**Comment by madebydavid** [comment]
This happened to me when I had a `GoogleService-Info.plist` file present in the root, but had not previously added the ios platform. I would assume the inverse would also cause the issue - having a `google-services.json` file but no android platform added.

**Comment by julienroubieu** [comment]
This still happens whenever you remote and add a platform, with the plugin previously installed.
I'm guessing that both the hook and and the dummy files from plugin.xml are trying to be copied to the same location.

In my case, since my build process always recreates the platform, I removed `<source-file src="src/android/google-services.json" target-dir="." />` and `<resource-file src="src/ios/GoogleService-Info.plist" target="Resources/GoogleService-Info.plist" />` from `plugin.xml`. The hook still copy both files from the root folder of my project.

**Comment by alokps6295** [comment]
in your config.xml first install cordova-plugin-firebase then push plugin then this problem would be resolved. But make sure to first remove both plugins from plugins folder after removing platform
