### ISSUE TITLE
iOS app_remove event is not tracking

### ISSUE THREAD

**Issue by arthurbaghdasar** [arnesson/cordova-plugin-firebase#251]
Hi all.

I've started using this plugin to integrate with Firebase. And I can say everything works perfect on Android. However on iOS i see only first_open and session_start events in console.

can anyone help me with this?

**Comment by arthurbaghdasar** [comment]
app_remove event is only tracked for Android devices. my fault

**Comment by lexuanquynh** [comment]
can we use another type for tracking this event in ios?
