### ISSUE TITLE
Firebase push notification not working in iOS 10

### ISSUE THREAD

**Issue by Siva-93** [arnesson/cordova-plugin-firebase#252]
Hi,

I'm using cordova-plugin-firebase to send push notifications across multiple platforms(Android and iOS). For Android is working fine. But for iOS it is not working as expected. The push notification is completely not working in the iOS 10.

Plugins used:
  cordova platform - 6.4.0
  cordova-plugin-firebase - 0.1.20

Procedure to repeat : 
  I did this configuration for Android and iOS
    - Created project in firebase.
    - Added Android and iOS app into that and generated configuration files (google-service.json for android and Google-Serivce-Info.plist for iOS).
    - And I added these configuration files in the project root folder.
    - For iOS I have added push notification entitlement to my provisioning profile.

Code used:
  This is the code I have used for push notification
  ```
window.FirebasePlugin.grantPermission();
  window.FirebasePlugin.onTokenRefresh(function(token) {
      console.log(token);
  }, function(error) {
    console.error(error);
  });
  window.FirebasePlugin.hasPermission(function(data){
    console.log(data.isEnabled);
  });
```

It is working good on the Android platform. I have tested in android version > 4.4. But I'm not getting the expected output in iOS 10. Is that I'm missing a configuration for iOS? Please help me to get out from this !!!

Thanks in advance.

**Comment by rakeshaset** [comment]
Hello

I don't know how to get this working using this plugin code, but i faced same issue and solved it by adding below mentioned code from Firebase website to my appdelegate class.

https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m#L60-L83


...................................
if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_9_x_Max) {
      UIUserNotificationType allNotificationTypes =
      (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
      UIUserNotificationSettings *settings =
      [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
      [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
    } else {
      // iOS 10 or later
      #if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
      // For iOS 10 display notification (sent via APNS)
      [UNUserNotificationCenter currentNotificationCenter].delegate = self;
      UNAuthorizationOptions authOptions =
          UNAuthorizationOptionAlert
          | UNAuthorizationOptionSound
          | UNAuthorizationOptionBadge;
      [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {
          }];

      // For iOS 10 data message (sent via FCM)
      [FIRMessaging messaging].remoteMessageDelegate = self;
      #endif
    }
.....................................................

Check the link above to get exact piece of code.

Thanks
Rakesh

**Comment by robertarnesson** [comment]
you also need to set up the APNS certificates. see https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by faustoct** [comment]
@robertarnesson I'm using APNs auth key , it stopped working!

**Comment by faustoct** [comment]
@robertarnesson, I'm using apn auth key, it stopped working on iOS! any idea?
