### ISSUE TITLE
App Crashes when in foreground v.1.20

### ISSUE THREAD

**Issue by sfstar** [arnesson/cordova-plugin-firebase#254]
You might find this error in the firebase console if the app crashes while receiving a notification in the foreground.
This issue comes around when you use the plugin without specifying the onNotification handler
In other words you might not have set this function:
"window.FirebasePlugin.onNotificationOpen(function(notification) {
      console.log(notification);
    }, function(error) {
      console.error(error);
    });"

This will result in the app crashing (while in foreground during receiving) with the only error being logged in the firebase console being:

"Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RemoteViews.setImageViewResource(int, int)' on a null object reference
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:112)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzl ()
com.google.firebase.messaging.FirebaseMessagingService.zzJ ()
com.google.firebase.messaging.FirebaseMessagingService.handleIntent ()
com.google.firebase.iid.zzb$1.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)"

**Comment by leyenda** [comment]
My app is crashing because of this in the time the app is passing from background to foreground, as I wait for cordova device to be ready to setup the handler.

**Comment by jeansantana** [comment]
Check you project for the files colors.xml on resources/values, if you have not this file, create one and put some colors.

**Comment by tegarkurniawan** [comment]
Same issue, I have created colors.xml but still have the same error but if in add
Window.FirebasePlugin.onNotificationOpen (function (notification) {
     Console.log (notification);
}, Function (error) {
     Console.error (error);
});
No error but not show notification

**Comment by jeansantana** [comment]
@tegarkurniawan have you put the google-services.json file in project root folder?

**Comment by tegarkurniawan** [comment]
Yes I've added google-services.json in the root folder, but if the background mode I get notifications but i do not get the title or label, i get only message

**Comment by tegarkurniawan** [comment]
I know the problem when I just send the application message is not stoped, but if I send the message and the application label will stoped, how the solution?

**Comment by tegarkurniawan** [comment]
I know the solution, I change the code
String title;
        String text;
        String id;
        if (remoteMessage.getNotification() != null) {
            title = remoteMessage.getNotification().getTitle();
            text = remoteMessage.getNotification().getBody();
            id = remoteMessage.getMessageId();
        } else {
            title = remoteMessage.getData().get("title");
            text = remoteMessage.getData().get("text");
            id = remoteMessage.getData().get("id");
        }
be 
if (remoteMessage.getData().size() > 0) {
            try {
                JSONObject json = new JSONObject(remoteMessage.getData().toString());
                JSONObject data = json.getJSONObject("data");

            //parsing json data
                String title = data.getString("title");
                String id = data.getString("id");
                String message = data.getString("message");
            } catch (Exception e) {
                Log.e(TAG, "Exception: " + e.getMessage());
            }
        }
application not stoped and notification appear, but title there is no

**Comment by t2wu** [comment]
@jeansantana Adding color.xml works for me, thanks.

**Comment by CasperKruger** [comment]
Adding color.xml worked for me too
