### ISSUE TITLE
android.os.Build.VERSION_CODES.MARSHMALLOW

### ISSUE THREAD

**Issue by alcristog** [arnesson/cordova-plugin-firebase#255]
Hello!

I was experiencing an error when compiling Cordova with Visual Studio 2017. It seemed that for the sentence android.os.Build.VERSION_CODES.MARSHMALLOW the attribute MARSHMALLOW was not found... However, I replaced it to android.os.Build.VERSION_CODES.M (in FirebasePluginMessagingService.java) and it compiles and works properly.

Is this a bug? Or perhaps I am using a too new Android SDK?

Thanks!

**Comment by patrickr** [comment]
I also experienced this issue and it is a bug M is the correct version code for marshmallow ( Nougat is N, next version is O) and it is fixed in my fork #253 commit 4eaeca9

**Comment by patrickr** [comment]
https://github.com/arnesson/cordova-plugin-firebase/commit/4eaeca90c11cda60f07299ff4bcab32140f41c2a is merged #253 this issue can probably be closed
