### ISSUE TITLE
custom notification_icon not showing 

### ISSUE THREAD

**Issue by roshni-kamath** [arnesson/cordova-plugin-firebase#257]
I had set the icons in the drawable folders. I also set styles in values and values-v21 folder. But still the notification icon in status bar is the blank white icon

**Comment by alx-andru** [comment]
same here if I install the app through Google Play store. If installed through `ionic run android` the icon works.

**Comment by josh-m-sharpe** [comment]
Think I figured this out.  I added a 'icon' attr to my notification payload: icon: 'notification_icon' -- then it picked up the 'notification_icon.png' that was in all of my drawable folders.

**Comment by shamank** [comment]
I'm getting crazy with this. I tried EVERYTHING and I can't get it work. These are all the generated drawable directories in my app:

![drawable](https://cloud.githubusercontent.com/assets/819192/26534669/e229181c-43fc-11e7-8b6c-46a4cd946e53.png)

Which one of them should contain notification_icon.png? Do I need to generate different icon sizes? Any help would be really appreciate. Thank you.

**Comment by shamank** [comment]
My solution https://github.com/arnesson/cordova-plugin-firebase/issues/53#issuecomment-304573222

**Comment by rolinger** [comment]
I use Ionic as well, I got my icons to work cleanly without any extra XML...see my write up:  [icon tutorial](https://github.com/arnesson/cordova-plugin-firebase/issues/335)
