### ISSUE TITLE
Unable to parse topic

### ISSUE THREAD

**Issue by jeddai** [arnesson/cordova-plugin-firebase#26]
So I am getting an `Unable to parse topic: "/topic/<my-topic>"` error in Xcode and I found the issue. It's only happening on iOS, and In the FirebasePlugin.m the subscribe and unsubscribe functions have this line:
```NSString* topic = [NSString stringWithFormat:@"/topic/%@", [command.arguments objectAtIndex:0]];```,
when I think the string it sends through actually needs to be 
```NSString* topic = [NSString stringWithFormat:@"/topics/%@", [command.arguments objectAtIndex:0]];```.

I am basing that off of [this documentation](https://firebase.google.com/docs/notifications/ios/console-topics#receive_topic_messages_on_an_ios_client_app). I might be wrong but I changed it to have `topics` instead of `topic` in my workspace and everything seems to be working fine now.

**Comment by robertarnesson** [comment]
you are right, thx for catching that. fixed in 9a41403

**Comment by jeddai** [comment]
Awesome! Also thanks for making this plugin - it's seriously helpful.
