### ISSUE TITLE
What is the lowest version of Android on which this plugin runs?

### ISSUE THREAD

**Issue by t2wu** [arnesson/cordova-plugin-firebase#260]
I want to ask what version of Android this has to run on?
I ran into 

> Fatal exception: java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage

isDeviceProtecedStorage seems to be available only on Nougat. Is this the lowest version it will run?

**Comment by nobuhiroharada** [comment]
+1

**Comment by remisture** [comment]
+1

**Comment by t2wu** [comment]
@nobuhiroharada  @remisture I removed the Android platform completely, and install it again. It all works fines afterward.
