### ISSUE TITLE
Push notifications won't work in Testflight

### ISSUE THREAD

**Issue by alx-andru** [arnesson/cordova-plugin-firebase#261]
Hi,

I'm having some issues figuring out why push notifications are not working if the app is installed via Testflight. I do have both dev and prod certificates registered in firebase. Is there an additional flag which has to be set before the build?

Any hints how I could debug or narrow down the issue are welcome!

**Comment by placha433** [comment]
Hi,

Try to call the method window.FirebasePlugin.grantPermission() before calling other methods like getToken, onTokenRefresh and onNotificationOpen.

**Comment by asrytis** [comment]
Hey @alx-andru , I'm experiencing the exact same issue. Did you ever manage to solve it?
