### ISSUE TITLE
setScreenName not working?

### ISSUE THREAD

**Issue by s3ppo** [arnesson/cordova-plugin-firebase#263]
anybody tried the setScreenName Method?:
setScreenName("Home")

i tried it but can nothing see about in analytics :(

**Comment by alx-andru** [comment]
I think it's fixed in commit ba5a5aaf9c7b2294bf1940253c8deadbd8598672 which should be included in next release. I had he same issue and looked into it a few days ago.

**Comment by s3ppo** [comment]
thanks for your answer, but the title says that its for iOS... do you think it also works for android?

**Comment by alx-andru** [comment]
according to the source it should be set. I'm mostly using iOS

**Comment by shepax** [comment]
Same problem here with android, there is no record of the screen at firebase, 

haven't try it on iOS

**Comment by coreyroth** [comment]
I can confirm it definitely doesn't work in iOS right now.  Someone in another thread mentioned you could install the plugin based off of that commit listed above and it fixes it but I haven't confirmed myself.

**Comment by s3ppo** [comment]
is there anybody care about this repo???

**Comment by robertarnesson** [comment]
happy now? :)

**Comment by s3ppo** [comment]
WHOHOOOO ;)

**Comment by s3ppo** [comment]
@robertarnesson still not working :((
