### ISSUE TITLE
Firebase Analytics not working for Android

### ISSUE THREAD

**Issue by sleever** [arnesson/cordova-plugin-firebase#264]
Hello everybody,

I have currently setup an integration of Firebase within my app which is working fine. It is receiving notifications for Android and iOS and it is reporting data to Firebase Analytics on iOS.

I have also setup a pageview to be registered.

However, I am not receiving any data on the Android app. Could somebody determine whether there is something obvious missing in a starter implementation?

Thanks in advance.

Best regards,
Stefan
`this.firebase.onTokenRefresh()
		  .subscribe((token: string) => console.log('Got a new token '+token));
		  
		this.firebase.onNotificationOpen()
			.subscribe((notification: string) => {
				console.log("hello");
				console.log(notification);
			})
			
		this.firebase.subscribe("testing")
			.then(() => console.log('subscribed')) // save the token server-side and use it to push notifications to this device
			.catch(error => console.error('not subscribed', error));
			
		this.firebase.logEvent("page_view", {page: "initiator"})
			.then(() => console.log('measured pageview')) // save the token server-side and use it to push notifications to this device
			.catch(error => console.error('not measured pageview', error));`

**Comment by johncblandii** [comment]
Try calling `this.firebase.grantPermission()`.

**Comment by sleever** [comment]
Hello John,

Thanks for the advice! Although grantPermission isn't relevant for analytics it did give me an extra insight in integrating notifications in a correct way for iOS.

Does anybody know how to get Firebase Analytics working on Android?

Best regards,

**Comment by s3ppo** [comment]
@sleever hmm strange for me its working, i can see countries and other things, only thing thats not working is the setScreen Method.

**Comment by sleever** [comment]
@s3ppo Could you show me a snapshot of your configuration?

**Comment by s3ppo** [comment]
@sleever which config do you mean?

**Comment by sleever** [comment]
@s3ppo specifically for the setup to measure data in Firebase Analytics for Android. I would like to see whether I am missing something in the initialization.

**Comment by s3ppo** [comment]
you mean the app.module.ts ?

**Comment by sleever** [comment]
@s3ppo Yes and a copy of how you measure a screenview to see whether I am actually calling enough or too little functions to get it working.

**Comment by maitham1** [comment]
any chance you could share this?

**Comment by sleever** [comment]
Bump.

Can anyone share information on how to get Firebase Analytics working for Android?

Thanks in advance.

**Comment by sleever** [comment]
Alright, today I've checked my configuration (google-services.json) which seemed quite incorrect. The configuration that was implemented in this file consisted of two configurations in one and the API key was wrong.

I fixed the issue by re-downloading the google-services.json from the Firebase console which fixed my problem.

This issue is solved.

**Comment by BluebambooSRL** [comment]
Hi @sleever I just downloaded this plugin (version 1.0.0) . Firebase Analytics works well on iOS, but not in Android. It seems that even with the google-services.json file at the root level it does not generate the "values.xml" file in the path /platforms/android/build/generated/res/google-services/debug/values.xml 

I have a few app in this firebase project. The google-services.json looks like:

{
  "project_info": {
    "project_number": "xxxxx",
    "firebase_url": "https://xxx-xxx.firebaseio.com",
    "project_id": "xxx-xxx",
    "storage_bucket": "fgdev-xxx.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:xxxx:android:xxxxx",
        "android_client_info": {
          "package_name": "xxx.xxxx.xxx"
        }
      },
      "oauth_client": [
        {
          "client_id": "xxxxx.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "xxxx"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    },
    {
      "client_info": {
        "mobilesdk_app_id": "xxxx",
        "android_client_info": {
          "package_name": "xxxx"
        }
      }....
  ],
  "configuration_version": "1"
}

Could you help me to understand what I am doing wrong?
Thanks in advance
Federico
