### ISSUE TITLE
Delete Token from Firebase

### ISSUE THREAD

**Issue by jpfsilva** [arnesson/cordova-plugin-firebase#272]
Hello,

Is it possible to delete a token from firebase with this plugin?
I contacted firebase support and they told me that I can delete it using deleteToken() for Android when the user signs out and deleteTokenWithAuthorizedEntity for iOS.

At the moment, I'm using this plugin, but is it possible to do it?
Or if I add manually to the method execute() on FirebasePlugin.java will it work?

Thank you in advance

**Comment by robertarnesson** [comment]
those methods are not implemented in the plugin. I'll take a PR :)

**Comment by robertarnesson** [comment]
this is on its way, see https://github.com/arnesson/cordova-plugin-firebase/pull/289
