### ISSUE TITLE
Ionic: can't log error

### ISSUE THREAD

**Issue by MitchBrands** [arnesson/cordova-plugin-firebase#273]
Hi there,
When I use the .logError(message) function, my app fails. 
It says: 
'Native: tried calling Firebase.logError, but the Firebase plugin is not installed.'
''Install the Firebase plugin: 'ionic plugin add cordova-plugin-firebase'"
"plugin_not_installed"
However: the plugin is installed, because getting a token and receive push messages are working fine.
Anyone know why this isn't working?

**Comment by robbannn** [comment]
Found a solution?

**Comment by tgezginis** [comment]
+1

**Comment by MitchBrands** [comment]
Nope =[
Just using the LogEvent for now, but that's not really effective.

**Comment by robertarnesson** [comment]
logError is android only, other than that I cant see why it would not work. pass this on to the ionic community?

**Comment by SoldierCorp** [comment]
+1

**Comment by ron-gonzalez** [comment]
After Platform.ready()
I'm trying to do this :+1: 

 
    this.firebase.getToken()
    .then(token => this.showAlert('Token :' + token)) // save the token server-side and use it to push notifications to this device
    .catch(error => this.showAlert('Error getting token' + error));

But always get error "plugin_noit_installed" 
HOw can I solve this problem ?
Thank you a lot,
Roni

**Comment by hookdump** [comment]
Having the same issue. Heads up I'm an extreme newbie with all this, so more than reporting an issue, I'm trying to find information about what I could be doing wrong.

**Comment by ron-gonzalez** [comment]
Hi hookdump !
Could you be more specific ?

Best regards!

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
