### ISSUE TITLE
Error ios run - NSInvalidArgumentException

### ISSUE THREAD

**Issue by lucav90** [arnesson/cordova-plugin-firebase#274]
hI,

When i run the app i  have this error on console and the app doesn't work.

NSInvalidArgumentException', reason: '+[NSData gtm_dataByGzippingData:error:]: unrecognized selector sent to class 0x1035f3338'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000103339b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102c93141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001033a9074 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001032c0840 ___forwarding___ + 1024
	4   CoreFoundation                      0x00000001032c03b8 _CF_forwarding_prep_0 + 120
	5   App                             0x0000000100bc0f82 -[FIRNetwork postURL:payload:queue:usingBackgroundSession:completionHandler:] + 331
	6   App                             0x0000000100bb6c4a -[FIRClearcutLogger sendNextPendingRequestWithCompletionHandler:] + 570
	7   App                             0x0000000100bb66f0 -[FIRClearcutLogger sendLogsWithCompletionHandler:] + 447
	8   libdispatch.dylib                   0x0000000106a3c4a6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x0000000106a6505c _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x0000000106a4394f _dispatch_queue_serial_drain + 221
	11  libdispatch.dylib                   0x0000000106a44669 _dispatch_queue_invoke + 1084
	12  libdispatch.dylib                   0x0000000106a44b32 _dispatch_queue_override_invoke + 654
	13  libdispatch.dylib                   0x0000000106a46ec4 _dispatch_root_queue_drain + 634
	14  libdispatch.dylib                   0x0000000106a46bef _dispatch_worker_thread3 + 123
	15  libsystem_pthread.dylib             0x0000000106dfc616 _pthread_wqthread + 1299
	16  libsystem_pthread.dylib             0x0000000106dfc0f1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

What is the solution?

**Comment by lucav90** [comment]
hi,

no solution?

**Comment by ginkgomzd** [comment]
This error is caused by the firebase config file being missing (GoogleService-Info.plist for ios and google-services.json for android).
