### ISSUE TITLE
APP Crash iOS Invalid configuration

### ISSUE THREAD

**Issue by btx78000** [arnesson/cordova-plugin-firebase#275]
Hi, i have an issue after APP Launch in iOS Cordova application + Firebase Plugin

It's perfectly working on Android and already worked on iOS in previous version of app ( no changes in plugins and minor changes in html code )
I have theses files in root project folder  downloaded from firebase console : 
- google-services.json
- GoogleService-Info.plist

( Name of my application in logs are renamed as : "MY APP NAME" )
 If someone have an idea or already have this issue, tell me, i'm lost, already waste lot of time on this bug and no changes :/

[Firebase/Core][I-COR000001] Configuring the default app.
2017-05-12 17:41:30.484 MY APP NAME[5764] <Error> [Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2017-05-12 17:41:30.499 MY APP NAME[5764:710972] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'
*** First throw call stack:
(
	0   CoreFoundation                      0x016dbded __exceptionPreprocess + 189
	1   libobjc.A.dylib                     0x010a6d6f objc_exception_throw + 49
	2   CoreFoundation                      0x017467d8 +[NSException raise:format:] + 104
	3   MY APP NAME                   0x00134fa0 +[FIRApp addAppToAppDictionary:] + 438
	4   MY APP NAME                  0x00134463 +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 330
	5   MY APP NAME                   0x00134144 +[FIRApp configure] + 334
	6   MY APP NAME                   0x000aa38a -[AppDelegate(FirebasePlugin) application:swizzledDidFinishLaunchingWithOptions:] + 154
	7   UIKit                               0x024a847f -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 299
	8   UIKit                               0x024a9fce -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4702
	9   UIKit                               0x024b0d07 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1828
	10  UIKit                               0x024d1d5e __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3147 + 50
	11  UIKit                               0x024adace -[UIApplication workspaceDidEndTransaction:] + 160
	12  FrontBoardServices                  0x08a95590 __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2 + 59
	13  FrontBoardServices                  0x08a950b9 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 46
	14  FrontBoardServices                  0x08abd635 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 23
	15  FrontBoardServices                  0x08abd499 -[FBSSerialQueue _performNext] + 168
	16  FrontBoardServices                  0x08abd86e -[FBSSerialQueue _performNextFromRunLoopSource] + 52
	17  FrontBoardServices                  0x08abccb5 FBSSerialQueueRunLoopSourceHandler + 29
	18  CoreFoundation                      0x01680a5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	19  CoreFoundation                      0x016661c4 __CFRunLoopDoSources0 + 500
	20  CoreFoundation                      0x0166569c __CFRunLoopRun + 1084
	21  CoreFoundation                      0x01664fd4 CFRunLoopRunSpecific + 372
	22  CoreFoundation                      0x01664e4b CFRunLoopRunInMode + 123
	23  UIKit                               0x024ac1e6 -[UIApplication _run] + 488
	24  UIKit                               0x024b2cb9 UIApplicationMain + 148
	25  MY APP NAME                   0x000a91b9 main + 89
	26  libdyld.dylib                       0x04046779 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Thanks in advance

**Comment by antoine92190** [comment]
I just had the same issue, I guess after upgrading cordova to version 7.0.1
Did you recently upgraded cordova?

I solved it by falling back to cordova 6.5.0 and reverting my package.json.
I noticed the new version of cordova adds some new code inside of package.json.

**Comment by kkangsla** [comment]
Hey, antoine92190.
I had a headache for the same problem for a long time.
You Good job!!!!!!!! Thank you!!

**Comment by btx78000** [comment]
Hey, i found the bug, Cordova & The firebase plugin don't do all the work for u at build, you need to add the content of your GoogleService-info.plist ( in root project folder ) in platforms/ios/Ressources/Ressources/GoogleService-info.plist ( this file is empty after cordova prepare & cordova platform add ios , but need to be set correctly).

I hope this tricks can help u, this is my solution for the moment

**Comment by sleever** [comment]
@btx78000 You're a true life shaver! I was able to reproduce the problem you're describing, copied the *.plist file to the platforms/ios/appname/Resources/Resources folder and the project was able to build and start fine :)!

**Comment by aagasi** [comment]
Hey @sleever, sorry to bother, but can you take a look at my issue https://github.com/arnesson/cordova-plugin-firebase/issues/277 and give me some feedback. Thanks

**Comment by robertarnesson** [comment]
should be fixed now in master

**Comment by evdjramos** [comment]
@btx78000 It worked for me! Thank you!
