### ISSUE TITLE
getToken returns empty/undefined

### ISSUE THREAD

**Issue by aagasi** [arnesson/cordova-plugin-firebase#277]
Hi, 

I'm using this code to get tokens, but so far no luck. 

`document.addEventListener("deviceready", onDeviceReady, false);`
`function onDeviceReady() {
    window.FirebasePlugin.getToken( function( token ) {
        console.log('TOKEN: ');
        console.log(token);
    }, function( error ) {
        console.error( error );
    });
}`

I did placed the **GoogleService-Info.plist** and **google-services.json** in the root directory of the project.

Currently i'm testing this on chrome browser within laptop. But also tested building the app for Android and testing it on a physical device. Still getting **empty/undefined**.

Any help would be appreciated, regards.

**Comment by leyenda** [comment]
What version of Cordova and SDK tools are you using? 
This happened to me with the latest(26.0.2) SDK tools, getToken return null, and onTokenRefresh was never called.

I've downgraded to tools_r25.2.5-linux.zip and it worked again.

**Comment by aagasi** [comment]
Hi, I'm using **PhoneGap 6.5.0**. No SDK tools installed. I'm going to try to downgrade PhoneGap unless you can give me another hint. 

Thanks

**Comment by aagasi** [comment]
So i tested within the Android Studio simulator and works. I was able to receive a push notification. Now i need to figure out why is not working on physical devices.

**Comment by aagasi** [comment]
This is the code i'm using to get the token and to pop an alert when notification arrives. The thing is that in Physical device the token is always empty.

`document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    window.FirebasePlugin.getToken( function( token ) {
        alert( token );
    }, function( error ) {
        console.error( error );
    });

    window.FirebasePlugin.onNotificationOpen( function( notification ) {
        alert( "Hi, this a test!" );
    }, function( error ) {
        console.error( error );
    });
}`


Seems like something in the Firebase plugin is not configured correctly or i miss something in the implementation.

I replaced the placeholder files inside **src/android** and **src/ios** in the plugin directory and also hardcoded the API Key and App Id in **plugin.xml** as recommended by https://www.npmjs.com/package/cordova-plugin-firebase

What could be ?

**Comment by CasperKruger** [comment]
Found that it did the same with my app Using Visual Studio 2015. The issue I found to cause the Plugin to crash is the colors.xml resource being missing from the build. It should be under platforms>android>res>values

I created the file and copied in.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">#FFFFFF00</color>
    <color name="primary_dark">#FF220022</color>
    <color name="accent">#FF00FFFF</color>
</resources>
The app now displays the
``` Notification...

Hope this helps...

**Comment by aagasi** [comment]
Hey @CasperKruger, i reviewed that files and exists in my build. The content of my **colors.xml** under **platform/android/res/values** directory is:

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="common_google_signin_btn_text_dark_default">@android:color/white</color>
    <color name="common_google_signin_btn_text_dark_disabled">#1f000000</color>
    <color name="common_google_signin_btn_text_dark_focused">@android:color/black</color>
    <color name="common_google_signin_btn_text_dark_pressed">@android:color/white</color>
    <color name="common_google_signin_btn_text_light_default">#90000000</color>
    <color name="common_google_signin_btn_text_light_disabled">#1f000000</color>
    <color name="common_google_signin_btn_text_light_focused">#90000000</color>
    <color name="common_google_signin_btn_text_light_pressed">#de000000</color>
    <color name="contents_text">#ff000000</color>
    <color name="encode_view">#ffffffff</color>
    <color name="possible_result_points">#c0ffbd21</color>
    <color name="result_minor_text">#ffc0c0c0</color>
    <color name="result_points">#c099cc00</color>
    <color name="result_text">#ffffffff</color>
    <color name="result_view">#b0000000</color>
    <color name="status_text">#ffffffff</color>
    <color name="transparent">#00000000</color>
    <color name="viewfinder_laser">#ffcc0000</color>
    <color name="viewfinder_mask">#60000000</color>
</resources>` 

I wonder if my implementation is correct. I implemented the **getToken** and **onNotificationOpen** method in the **index.js**. Do you think i should do it in any other place?

Thanks

**Comment by aagasi** [comment]
@CasperKruger i also tried adding **primary** **primary_dark**  and **accent** and testing on physical device is still crashing. 

Any clue? Thanks

**Comment by Sampath-Lokuge** [comment]
See this too: [**Firebase native plugin with push notifications is not working**](https://stackoverflow.com/questions/44224052/firebase-native-plugin-with-push-notifications-is-not-working)

**Comment by maleavle** [comment]
agassi how do you slution your problem??

**Comment by fanfare** [comment]
I was having this exact issue, it was returning undefined because in Safari the 'show messages logged to console' button wasn't clicked. **At the top of Web Inspector look for a little text bubble probably with a number next to it.** Click that, and then you might be able to see the plugin returning the token id. I'm not used to Mac so I completely overlooked this.

**Comment by adadgio** [comment]
Another solution is here: https://github.com/arnesson/cordova-plugin-firebase/issues/558

To the author: A PR and a fix is **URGENT** now... ;-)
