### ISSUE TITLE
Android crash Push-notification in foreground

### ISSUE THREAD

**Issue by pinox12** [arnesson/cordova-plugin-firebase#278]
Hi,

When the app is in foreground and recive a push-notification the application crash, whereas the app is in background works perfectly.

I did placed the GoogleService-Info.plist and google-services.json in the root directory of the project.

Any help would be appreciated, regards.

**Comment by aagasi** [comment]
Hey, 

Can you take a look at my issue  https://github.com/arnesson/cordova-plugin-firebase/issues/277, and maybe when i get at the same point as you are i can give you feedback about your issue.

Thanks!

**Comment by CasperKruger** [comment]
Found that it did the same with my app Using Visual Studio 2015. The issue I found to cause the Plugin to crash is the creation of the colors.xml resource being missing from the build. It should be under platforms>android>res>values

I created the file and copied in.

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">#FFFFFF00</color>
    <color name="primary_dark">#FF220022</color>
    <color name="accent">#FF00FFFF</color>
</resources>

The app now displays the Notification...

**Comment by menghao93** [comment]
you have phonegap and ionic native firebase plugin both installed?

**Comment by jpfsilva** [comment]
You have to implement the method onNotificationOpen.
For exemple, try this:
`this.firebase.onNotificationOpen()
.subscribe((notification) => {
  let alert = this.alertCtrl.create({
    title: 'New Notification.',
    subTitle: "There is a new Notification",
    buttons:['OK']
  });
  alert.present();
});`

**Comment by aagasi** [comment]
Hey @jpfsilva, do you mind taking a look at mine? #277. Thanks

**Comment by jpfsilva** [comment]
@aagasi I'm not really expert but I can tell you some things...
Since you are using it for android, build the app yourself instead on phonegap, I got lots of problems with phonegap... build using ionic, I got a problem there but it was solved by downloading the tools and add it to C:\Users\[Your Username]\AppData\Local\Android\sdk\tools
Also, if you are using ionic 1 instead ionic 2, I also got lots of problems with that and had to migrate my App to ionic 2 to solve them.

**Comment by aagasi** [comment]
Yep, i'm struggling a lot. Maybe coding in native language could be the solution. So far no plugin worked correctly for the push notifications.

**Comment by pinox12** [comment]
I added the missing color lines on platforms>android>res>values>style.xml

`<color name="primary">#FFFFFF00</color>`<br>`
<color name="primary_dark">#FF220022</color>`<br>`
<color name="accent">#FF00FFFF</color>`

 and it works perfectly, thank you very much.
