### ISSUE TITLE
Not receiving any notifications

### ISSUE THREAD

**Issue by Hudhud** [arnesson/cordova-plugin-firebase#280]
Hello,

I have installed your plugin (`cordova plugin add cordova-plugin-firebase@0.1.20 --save`) and placed my Firebase configuration files in the root folder. However, when I try testing it, it doesn't work. I am testing it with Firebase's own Notifications feature in the console.

**Comment by adairborba** [comment]
getToken = success
onTokenRefresh = success
onNotificationOpen = no work

cordova-plugin-firebase@0.1.20
