### ISSUE TITLE
Error: method getColor in class Resources cannot be applied to given types

### ISSUE THREAD

**Issue by ernestohegi** [arnesson/cordova-plugin-firebase#283]
platforms/android/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:105: error: method getColor in class Resources cannot be applied to given types;

                notificationBuilder.setColor(getResources().getColor(accentID, null));

                                                           ^
  required: int
  found: int,<null>
  reason: actual and formal argument lists differ in length

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
