### ISSUE TITLE
InvalidApnsCredential ios 10?

### ISSUE THREAD

**Issue by eros2187** [arnesson/cordova-plugin-firebase#284]
The issue I posted does not concern the certificate because the certificate is trusted because it is still valid.
The problem concerns the plugin because as seen from my example I tested with ios 10 when I call the getTheToken () function WITHOUT RECOGNIZING THE FUNCTION THAT I HAD TO DISPLAY NOTES window.FirebasePlugin.grantPermission (); I do not receive any error on the certificate, in fact getting feedback on the server:
{"Multicast_id" 7649446427278374045, "success": 1, "failure": 0, "canonical_ids": 0, "results": [{"message_ID": "0: 1494347311775201% 812d9b5d812d9b5d"}]}
But I do not see any notification on the device even if I'm successful!!

If I ask permissions using the function
window.FirebasePlugin.grantPermission ();
  When I try to send the message from the server I get:

`{" Multicast_id "6314053970229096456," success ": 0," failure ": 1," canonical_ids ": 0," results ": [{" error ":" InvalidApnsCredential "}]}

I would like to understand why this happens? I used a ipad with version 10.3.
Someone tested on ios 10 confirm me that it works? thank you

**Comment by jpfsilva** [comment]
That happen to me a few weeks ago...
The problem is indeed the certificate. You got a first successfull message because you were registered to firebase, but after the first push, APNS refused the certificate and firebase refuse your certificate after that.
Check the certificates, if you are trying to sign them using a windows system, I wish you good luck, I tried every way I could using a windows system for 2 weeks and I couldn't do it, I changed plugin and everything until I get a mac and after generate the certificates throught the mac it worked like a charm...

**Comment by eros2187** [comment]
So did you plug this plugin with ios 10 and confirm that pushes work?
Meanwhile the certificates I have created them with a mac .. I do not understand why it does not work
I wanted to confirm somebody before doing a test drive.

**Comment by jpfsilva** [comment]
Yes, and I tested on a iPad and in a iPhone since iPad doesn't have vibration.
Make sure you don't mix the production certificate with the sandbox one...
I followed this guide: https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by eros2187** [comment]
Thanks feel you can send me a test project if possible maybe we put it here so that everyone can see it? You can contact me at my cloud2187@gmail.com email.

**Comment by jpfsilva** [comment]
Well, I don't have any test project to share, when I did this, it was to a company where I work and I'm not allowed to share the code...
Just be sure about the certificates and remember to download the GoogleService-Info and put it in your root folder and one of the things that I forgot to tell you is to compile the code using the Xcode. build the project with cordova and then open it with Xcode.

**Comment by t2wu** [comment]
@jpfsilva How do you switch between Production and Sandbox? On Firebase Console I've configured for both. But how do we switch between it while using the plugin?

**Comment by jpfsilva** [comment]
Do ionic build ios --release and then publish it with Xcode...
There is a guide: http://ionicframework.com/docs/v1/guide/publishing.html

**Comment by t2wu** [comment]
@jpfsilva  

I'm not using ionic but it works with the following:

`cordova build ios --release`

Never knew there was `--release`. Thank you so much it works like a charm!
