### ISSUE TITLE
Problem with method setUserId

### ISSUE THREAD

**Issue by rodrifmed** [arnesson/cordova-plugin-firebase#286]
I have this problem when a setUserId first time.

Android error log:

> Error: Uncaught (in promise): JSON error
>     at c (polyfills.js:3)
>     at polyfills.js:3
>     at Object.callbackFromNative (cordova.js:295)
>     at processMessage (cordova.js:1119)
>     at processMessages (cordova.js:1142)
>     at t.invoke (polyfills.js:3)
>     at Object.onInvoke (main.js:4405)
>     at t.invoke (polyfills.js:3)
>     at r.run (polyfills.js:3)
>     at polyfills.js:3

iPhone error log:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x15fca660'
> *** First throw call stack:
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb)

In android the error occur, but the application still working, but in IOS the app crach.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
