### ISSUE TITLE
Android - problem with custom notification icon + notification icon color on light status bar

### ISSUE THREAD

**Issue by Nico924** [arnesson/cordova-plugin-firebase#290]
1. I tried to use what is in the last readme file to set a custom icon for my notifications.
However while i wrote the two following lines in the values/styles.xml (+ values-v21), it keeps setting the default app application icon if I send a random notification using the firebase console (https://console.firebase.google.com).
`<drawable name="notification_big">@drawable/notif_icon</drawable>`
`<drawable name="notification_icon">@drawable/notif_icon</drawable>`

However, if I tell firebase the icon I want through a custom parameter (I tell him to use notif_icon in my case), then it works, the custom icon is displayed. 
(same consideration for for the accent color. It works through firebase but not using the colors.xml file in values)

To summarize what I have:
cordova-android 6.2.3
cordova-plugin-firebase 0.1.21
Android version 7.0

In the res/ folder 
- notif_icon.png in the drawable/ folder (not in the suffix folders, I also tried to copy it in every dpi folders, nothing changed)
- in values/colors.xml (red to test)
`<?xml version="1.0" encoding="utf-8"?>`
`<resources>`
`      <color name="accent">#8B0000</color>`
`</resources>`
- in values/styles.xml
`<?xml version="1.0" encoding="utf-8" ?>`
`<resources>`
`    <!-- inherit from the holo theme -->`
`    <style name="AppTheme" parent="android:Theme.Light">`
`        <item name="android:windowDisablePreview">true</item>`
`    </style>`
`    <drawable name="notification_big">@drawable/notif_icon</drawable>`
`    <drawable name="notification_icon">@drawable/notif_icon</drawable>`
`</resources>`

In AndroidManifest
`<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" />`

2. I also read that in order to have a notification icon that becomes grey if the status bar is light. You have to add in the values-v23/styles.xml file the following line
`<item name="android:windowLightStatusBar">true</item>`
(from here https://stackoverflow.com/questions/35119021/invert-icon-color-of-status-bar)

So I also created a values-v23/styles.xml file like this
`<?xml version="1.0" encoding="utf-8" ?>`
`<resources>`
`    <!-- inherit from the material theme -->`
`    <style name="AppTheme" parent="android:Theme.Material">`
`        <item name="android:windowDisablePreview">true</item>`
`        <item name="android:windowLightStatusBar">true</item>`
`    </style>`
`    <drawable name="notification_big">@drawable/notif_icon</drawable>`
`    <drawable name="notification_icon">@drawable/notif_icon</drawable>`
`</resources>`
`
Once again, it does nothing. If someone could explain me what I'm doing wrong, it would be very great !

Thank you in advance

**Comment by shamank** [comment]
I can't make it work at all. I tried copying a "notification_icon.png" to every drawable directory but it didn't work. In Firebase console how did you get it to work? I've just added a custom data field like this:

key: notification
value: {"icon":"notification_icon","color":"#000000"}

But didn't work. I'm targeting to API 23 and this is my directory structure in the APK:

![drawable](https://cloud.githubusercontent.com/assets/819192/26535651/e4d887ec-4405-11e7-80a2-c7752458cfb4.png)

Just to know, what drawable directories did you use to put the notification_icon.png in there? And how did you set all the required sizes? I'm getting crazy with this :(

**Comment by shamank** [comment]
My solution.

I'm using **Ionic v2** and **cordova-plugin-firebase@0.1.21**:
Ionic: 2.2.2
cordova: 6.5.0
npm: 4.6.1

1. Install the custom-config plugin:
`$ ionic plugin add cordova-custom-config --fetch --save`

2. Download https://github.com/driftyco/ionic-package-hooks/blob/master/android_custom_resources.js and https://github.com/driftyco/ionic-package-hooks/blob/master/android_custom_values.js into a new directory called "package-hooks" (or whatever you want) in your project root.
`package-hooks/android_custom_resources.js`
`package-hooks/android_custom_values.js`

3. Create the following directories and files in your project root (not inside platforms):
`resources/android/custom/notification_icon.png`
`resources/android/values/styles.xml`

`notification_icon.png` is your Android >= API 21 notification icon. Mine is 144x144px and it looks great.

`styles.xml` contains:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="red">#FF8614</color>
</resources>
```
4. Edit config.xml. **Important**: Make sure you add that namespace in the widget tag.

```xml
    <widget ... xmlns:android="http://schemas.android.com/apk/res/android">
        <platform name="android">
            <hook src="package-hooks/android_custom_resources.js" type="after_prepare"/>
            <hook src="package-hooks/android_custom_values.js" type="after_prepare"/>
            <hook src="package-hooks/android_fixes.js" type="after_prepare"/>
            <config-file parent="./application" target="AndroidManifest.xml">
                <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon"/>
                <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/red"/>
            </config-file>
        </platform>
    <widget>
```

**Comment by shamank** [comment]
My solution https://github.com/arnesson/cordova-plugin-firebase/issues/53#issuecomment-304573222

**Comment by Nico924** [comment]
@shamank thank you, it solved my first problem :) 
However have you a solution for the second point, the one about the notification icon color that does not become grey on light notification bar (for exemple the app messages or google agenda) ?

**Comment by shamank** [comment]
@Nico924 Sorry man, I've not been around these days.
> However have you a solution for the second point, the one about the notification icon color that does not become grey on light notification bar (for exemple the app messages or google agenda) ?
Sadly not :( BTW and just for further use, did you find a solution to this?

**Comment by tgensol** [comment]
@Nico924 How did you solve your first issue ? thanks

**Comment by Nico924** [comment]
@shamank unfortunately no :/ However, It appears that you can use colorful icons (at least it worked on my Samsung when I had Android 6 and now with Android 7 as well) so the idea is to use a color that works both on dark and white background haha but I know it does not follow the Android guidelines but who cares ? :p 
@tgensol  There is two way of doing that, the easiest is to use send the name of the resource you want to use in your drawable folder along with your notification sent from your backend thanks to the firebase api (more info [here](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support)). 
The second one is to add custom configuration lines in your Manifest using either the custom-config plugin or by writing in the manifest directly these two lines
`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_message_notification" />`
`<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />`
This will update the **default** notification icon and color of your app (but it will still be overridden if you use the first solution) 
More info about the default notification icon and color [here](https://firebase.google.com/docs/cloud-messaging/android/client)

**Comment by soumak77** [comment]
closing as resolved
