### ISSUE TITLE
(Property ‘FirebasePlugin’ does not exist on type ‘Window’) 

### ISSUE THREAD

**Issue by 10ur10der** [arnesson/cordova-plugin-firebase#291]
I watched the steps exactly but I get an error.

**app.component.ts**

      import { Component } from '@angular/core';
      import { Platform } from 'ionic-angular';
      import { StatusBar } from '@ionic-native/status-bar';
      import { SplashScreen } from '@ionic-native/splash-screen';

      import { HomePage } from '../pages/home/home';

     @Component({
      templateUrl: 'app.html'
     })

     export class MyApp {
        rootPage:any = HomePage;
  

       constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
         platform.ready().then(() => {
     
          statusBar.styleDefault();
          splashScreen.hide();

      

           window.FirebasePlugin.getToken(function(token) {
          // save this server-side and use it to push notifications to this device
             console.log(token);
            }, function(error) {
           console.error(error);
         });

           Window.FirebasePlugin.onNotificationOpen(function(notification) {
             console.log(notification);
          }, function(error) {
          console.error(error);
         });
       
          });
 
          }
       }

`

**Comment by robertarnesson** [comment]
do not use capital W

**Comment by gersonmontenegro** [comment]
even without the capital, the error persist

**Comment by kierandesmond** [comment]
Same here, was this solved?

**Comment by gersonmontenegro** [comment]
I solved using another plugin : cordova-plugin-fcm

**Comment by rwoody** [comment]
Caused by using TypeScript with out the proper types. You can get around this by doing:

```typescript
const plugin = (<any>window).FirebasePlugin;
// or
const plugin = (window as any).FirebasePlugin;
```

**Comment by OBout** [comment]
> I solved using another plugin : cordova-plugin-fcm

FCM breaks on Android 7.1.1 for Ionic. @rwoody solution works.

**Comment by tabarakMohammed** [comment]
> Caused by using TypeScript with out the proper types. You can get around this by doing:
> 
> ```ts
> const plugin = (<any>window).FirebasePlugin;
> // or
> const plugin = (window as any).FirebasePlugin;
> ```

thank Mr.
