### ISSUE TITLE
android:windowLightStatusBar true for grey notification icon does not work 

### ISSUE THREAD

**Issue by Nico924** [arnesson/cordova-plugin-firebase#294]
Hello guys,

Following this link (https://stackoverflow.com/questions/33316668/how-to-change-the-status-bar-notification-icons-color-tint-in-android-marshmal/33316669#33316669) I added the recommended line in the values-v23/styles.xml file of my android application, but it does not affect the (custom) notification icon color I added (it stays white). Does anyone have a recommendation ?

**Comment by rolinger** [comment]
I think the intended path is \platforms\android\res\values\styles.xml.   However, color nor icon style worked for me.  Only way I could get it work was to pass color/icon from the message - and depending on phone type you would get different results:
```

  $fcmMsg = array(
    'body' => $msgBody,
    'title' => $msgTitle,
    'sound' => "default",
    'color' => "#cccccc",
    'icon' => "whipsterIcon.png"
  );
```

On Samsung, above color was the background color behind my actual app icon.
On LG K20, above color was the color of the icon - one solid color, but it was the outline of my app icon.

I am still searching for a better universal solution.

**Comment by soumak77** [comment]
closing for cleanup
