### ISSUE TITLE
iOS grantPermission

### ISSUE THREAD

**Issue by ChristosGeorgiou** [arnesson/cordova-plugin-firebase#297]
The following issue may have some relation with the #242 

- On the application start I request permission with `grantPermission()`
- The native popup pops and I select _deny_. My app save that preference to the db and at the ios setting the correct option is displayed _(notifications off)_
- After that, I navigate to the application preferences page, where I toggle on the notification setting. This check current permission with `hasPermission()` and try `grantPermission()`. This time though not popup appears, and in addition, the promise returns `null`

I believe that the problem may be because iOS is not allowing a second grantPermission request, although I can not verify this due to not knowing objective-c to dig through the solution.

**Comment by robertarnesson** [comment]
This is correct, ios does not allow a second prompt

**Comment by ChristosGeorgiou** [comment]
Thanks for your immediate response.
I will work around it as I should.

**Comment by francois-n-dream** [comment]
Hi, is there a way to wait for the result of the notification prompt?

Since the callback gets called while the prompt is still open.
```
grantPermission(function() {
 // gets executed immediately
 // Also hasPermission will return false, since the user hasn't decided yet
}
```

Basically I need to know what the user pressed so I can continue.
