### ISSUE TITLE
Validate if the aplication is open/active

### ISSUE THREAD

**Issue by alcarcel** [arnesson/cordova-plugin-firebase#299]
I have an app in Android developed with corodova, and I have the firebase plugin running.

When i send a notification to the device I want than that notification open the app in a specific location, I just do it, but when the app is open and I send any notification, the app just jump to the location specified.

I want to know if exist some function or else who show me if the app is open, then do not execute nothing, just show the notification message in the status bar, also if I click on it, run as is expected.

Tnks.

**Comment by robertarnesson** [comment]
there is the tap true/false property. other than that its up to you to detect that in other ways
