### ISSUE TITLE
Log every page visit

### ISSUE THREAD

**Issue by devthree** [arnesson/cordova-plugin-firebase#30]
I'm using framework7 (single page application) for android, and trying to analyze user behavior on my apps. I want to know at which page users mostly stop using my apps by counting page visit. I'm trying put this code from example : 
`window.FirebasePlugin.logEvent("page_view", {page: "dashboard"});` 
everytime I call a page (change page parameter with my custom page name), but I still can't see the result at my firebase console. Is it possible to do this?

**Comment by robertarnesson** [comment]
the events end up under Events -> select_content -> [your event name]

This will change in the next release to simply Events -> [your event name]
