### ISSUE TITLE
#import "AppDelegate.h" File is not found error in Xcode (IOS)

### ISSUE THREAD

**Issue by roneyvia** [arnesson/cordova-plugin-firebase#301]
When I build Xcode project for iOS. I got this issue "#import "AppDelegate.h" File is not found "
Please help. I'm new in Xcode

**Comment by mbn18** [comment]
@roneyvia , have you found a solution?

**Comment by nadavb** [comment]
Same problem here

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by KUSH9148** [comment]
This issue is still there in latest version, please look into it.
