### ISSUE TITLE
Conflict with phonegap-plugin-push (google-services.json already exists)

### ISSUE THREAD

**Issue by morariu** [arnesson/cordova-plugin-firebase#303]
It seems that both your plugin and phonegap-plugin-push are copying google-services.json hence the issue on build. Is there a way to bypass this? Thanks

**Comment by amokrunner** [comment]
I had the same issue. I forked it and removed those source-file lines from plugin.xml for my use

**Comment by morariu** [comment]
Do you mean these:

```
<config-file parent="/resources" target="res/values/strings.xml">
        <string name="google_app_id">@string/google_app_id</string>
</config-file>
```

**Comment by amokrunner** [comment]
These:
<source-file src="src/android/google-services.json" target-dir="." />
<resource-file src="src/ios/GoogleService-Info.plist"
target="Resources/GoogleService-Info.plist" />

**Comment by morariu** [comment]
@amokrunner for me removing the config file worked fine.

**Comment by robertarnesson** [comment]
both plugins implement push notifications via firebase, so I would not recommend using both together, use either one.

**Comment by wo-github** [comment]
I get the error, after try to build my project in Xcode to emulator. Appple Mach-O Linker(id) Error. It`s not possible to build a app. But I don`t want to use use the push in firebase.

**Comment by wolfg1969** [comment]
@wo-github need to re-add ios platform to get rid of the files (pod related) left by phonegap-plugin-push.

**Comment by wo-github** [comment]
No that doesn`t work, the error still exist after remove and add the platform.

**Comment by wolfg1969** [comment]
@wo-github  Do you see this issue in Xcode?

![image](https://user-images.githubusercontent.com/1585718/27481967-fd0da9ea-5851-11e7-92fe-b8f52b1c1e70.png)

The missing lib causes 'Appple Mach-O Linker(id) Error' .

My project is a Ionic v1 (with latest ionic cli) project.  I add phonegap-plugin-push and cordova-plugin-firebase both then get the error.  What I do to solve the build error is:

1. remove the phonegap-plugin-push 
```$ ionic cordova plugin rm phonegap-plugin-push```

2. re-add ios platform
``` $ ionic cordova platform rm ios && ionic cordova platform add ios```

If phonegap-plugin-push still exists in your plugin directory, I guess re-adding platform won't work.
