### ISSUE TITLE
Analytics is disabled in android

### ISSUE THREAD

**Issue by mazt-dev** [arnesson/cordova-plugin-firebase#305]
Hi
I have added the plugin to my IOS app and the analytics works fine, but when I run the android version all I can see in the logs are "Event not sent since app measurement is disabled".

If I add mFirebaseAnalytics.setAnalyticsCollectionEnabled(true); close to the mFirebaseAnalytics instantiation the android app will start sending analytics data, but according to [documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setAnalyticsCollectionEnabled(boolean)) the analytics should be enabled by default.

It's also possible to make the plugin work by adding
`<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />` to the AndroidManifest.xml ([link](https://firebase.google.com/docs/reference/android/com/google/android/gms/measurement/AppMeasurementService))

But it feels like I'm missing something here since I don't want to add any of these options in my app. Is something missing in the plugin?

Version used:
Cordova: 6.5.0
Android platform: 6.1.2
cordova-plugin-firebase: 0.1.21

**Comment by robertarnesson** [comment]
its now fixed in master
