### ISSUE TITLE
iOS is not handling data notifications

### ISSUE THREAD

**Issue by alexislg2** [arnesson/cordova-plugin-firebase#308]
Hello, as you know, FCM has 2 types of notifications:

- Notification messages, sometimes thought of as "display messages."
- Data messages, which are handled by the client app.

It seems that this plugin only handles Notification messages. therefore if I send only data, notification is not treated by this plugin

**Comment by jaybowman** [comment]
I've been unable to get notifcations on IOS with this plugin. I'm sending both Notification json and data json from my service. Everything works great with android. I have all the pieces in place for ios, but it still is not working.

**Comment by ben-8409** [comment]
The same happens for me. Notifications work on Android and iOS, but Data messages do not work on iOS.

**Comment by soumak77** [comment]
closing for cleanup
