### ISSUE TITLE
When you receive notification with, the application opens, the app automatically closes

### ISSUE THREAD

**Issue by lepokoloko** [arnesson/cordova-plugin-firebase#312]
When you receive notification with, the application opens, the app automatically closes version 0.1.21

**Comment by GabrielOtero** [comment]
I have the same problem...


Checking firebase logs I have:

Exception android.content.res.Resources$NotFoundException: Resource ID #0x0
android.content.res.Resources.getValue (Resources.java:1351)
android.content.res.Resources.getColor (Resources.java:963)
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:105)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzo ()
com.google.firebase.messaging.FirebaseMessagingService.zzn ()
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)

**Comment by Netpllay** [comment]
i back to version 0.1.20, and not have problem

**Comment by delbertf** [comment]
Creating the colors.xml as described in the README.md solved this problem for me. Plugin version 0.1.21 and Android API 25.

**Comment by Netpllay** [comment]
Hi, this solution solved. Thanks

**Comment by mohamedsharaf** [comment]
@lepokoloko please close the issue as there is a solution as @delbertf

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by soumak77** [comment]
closing for cleanup
