### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by yossibeck** [arnesson/cordova-plugin-firebase#317]
I have an issue with values not being set in strings.xml (android)
from what I see this is the order of things:
cordova platforms add android 
-- gets me a correct strings.xml

cordova build android 
-- the content read from strings.xml is empty 
line #63
        var strings = fs.readFileSync("platforms/android/res/values/strings.xml").toString();

adding right after that line shows me that the file is empty
console.log("got:" + strings); 

if I change the plugin.xml from
	<hook src="scripts/after_prepare.js" type="after_prepare" />
to
	<hook src="scripts/after_prepare.js" type="before_build" />

I get duplicates entries in strings.xml
  <string name="google_api_key">@string/google_api_key</string>
  <string name="google_api_key">---my actual key from google-services.json -- </string>

and then build fails with 
C:\dev\phonegap\platforms\android\res\values\strings.xml: Error: Found item String/google_api_key more than one time

I guess cordova cleans the strings.xml file on each build, run the "before prepare" which does nothing, then overrides the file with the plugin.xml

I solved it myself - changing the "after_prepare" to run before build and adding the entries in the same js if they're missing, but ... I wont get any updates this way :(

if I am missing something, I'd love to know what it is
thanks a lot

**Comment by robertarnesson** [comment]
should be fixed in master now
