### ISSUE TITLE
Firebase API Not Working

### ISSUE THREAD

**Issue by JohnScottMcNerney** [arnesson/cordova-plugin-firebase#318]
I can only get device notifications via the Google Firebase console, and not through the server http API.

APP: cordova (6.4.0) default app, not changed, with plugin cordova-plugin-firebase (0.1.21) added.

Steps to reproduce

1. Download APP to device (android phone)
2. Start APP (seems like this is required to register this app with the phone)
3. Close APP
4. Send message from server through FCM http API
     { notification:
          { title: 'Notification Test',
         body: 'Notification Test Body Text' },
          to: '/topics/all',
        priority: 'high' }
5. Device does not receive/show a notification was received.

Is there a bug in the server script?

No. If I replace cordova-plugin-firebase with cordova-plugin-fcm, then the device (and APP) receive notifications through the API just fine.

Why not just use cordova-plugin-fcm then?

cordova-plugin-fcm is not well maintained, and I would like to use the Analytics in cordova-plugin-firebase

**Comment by JohnScottMcNerney** [comment]
cordova-plugin-fcm gets messages from FCM server HTTP API
cordova-plugin-firebase does NOT get messages from FCM server HTTP API
cordova-plugin-firebase does gets messages from Firebase Console Messaging system.

FCM API server script has not changed in 6 months.

**Comment by rolinger** [comment]
Agreed, cordova-plugin-firebase is not well maintained at all.  Its why i left it for this one.  However, my messages arrive just fine if my app is closed or in background, but nothing happens if app is opened in foreground.  Trying to resolve that one now.

**Comment by JohnScottMcNerney** [comment]
@rolinger isn't that the way it's supposed to work? If the APP is closed, the device gets the notification, but if the APP is open then the APP gets the notice. It's then up to you to support the incoming notice within the APP.

I remember reading somewhere that if there is no "data" object in the sent notice, and the APP is open, the APP does not get the notice because there is no data to give to it. I could simply be wrong on this though..... or maybe it's just on some specific devices....

**Comment by rolinger** [comment]
correct.  Its supposed to work that way...but its not.  If app is closed or in background everything works fine.  But if app is open in the foreground and a message arrives it never triggers the onNotificationOpen - thus any 'data' that is passed via the message can't be processed.  Unless I am doing something wrong...but I don't think so, because a simple console.log(notification) in the onNotificationOpen function isn't even firing.  Then I close the app...send the same message again, it the notice appears, click the notice...all the data/console.log message is processed.

**Comment by rolinger** [comment]
And from the server side I am sending the notification as such:

```
  $fcmMsg = array(
    'body' => $msgBody,
    'title' => $msgTitle,
    'sound' => "default",
    'color' => "#203E78",
    'icon' => "notification_icon.png"
  );

  // 'to' => $singleID ;
  // 'registration_ids' => $registrationIDs ;  expects an array of ids
  // 'priority' => 'high' ; // options are normal and high, if not set, defaults to high.
  $fcmFields = array(
    'to' => $singleID,
    'priority' => 'high',
    'notification' => $fcmMsg
  );
  if ($dataObj) {
    $fcmFields['data'] = $dataObj ;
  }
  $ch = curl_init();
  curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
  curl_setopt( $ch,CURLOPT_POST, true );
  curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
  curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
  curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
  curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fcmFields ) );
  $result = curl_exec($ch );
  curl_close( $ch );
  return json_decode($result) ;

```

**Comment by apptum** [comment]
@rolinger 
For me ``onNotificationOpen`` fires when app is in foreground while sending messages via notification composer or via cloud functions through admin sdk and gives me a 
`` Object {tap: false, body: "testText"} ``.
Make sure to call ``onNotificationOpen`` after onTokenRefresh is successfully set up.

**Comment by robertarnesson** [comment]
you are saying it works through the firebase console? if that is the case then your server code is the problem. can you post the server code?

**Comment by JohnScottMcNerney** [comment]
@robertarnesson thank you.

The code is a NODEJS script, shown below with a few edits for privacy. Please note that I do not think that this is the problem. If I switch to a different push notification plugin, cordova-plugin-fcm, then both my server script and the console can send notifications. If I simply switch back to cordova-plugin-firebase then only the console can send.

One difference that I noticed between cordova-plugin-firebase and cordova-plugin-fcm is how the Google libraries are used. The cordova-plugin-fcm has the Google libraries built into their plugin, so If you use another plugin that uses those same libraries (like a Google Maps plugin) you will get a error like "library function already exists". This cordova-plugin-firebase plugin seems to rely on Google libraries that are installed on the machine that is building the app. 

        #!/usr/bin/env nodejs
        var unirest = require('unirest');

       var key = "MyValidKeyString"; // insert yours here

        var done = function(e,d){ setTimeout(function(){ if (e) { console.error(e); process.exit(1); } else { console.log(JSON.stringify(d,null,2)); process.exit(0); } },500); };

        console.log("fcm");
        fcmTest(done);
        console.log("fcm.... queued");

        function fcmTest(done){
        console.log("fcmTest");
        var data = {
          "notification":{
            "title":"Notification Test",
            "body":"Notification Test Body Text"
          },
          "data":{ "param1":"value1", "param2":"value2" },
          "to":"/topics/all"
        };

        unirest.post("https://fcm.googleapis.com/fcm/send").headers({'Content-Type': 'application/json','Authorization':'key='+key}).send(data).end(function(r){
          console.log(data);
          if (r.status != 200) return done(" HTTP status:" + r.status);
          var rtn = r.body;
          return done(null,rtn);
        });

        };

**Comment by JohnScottMcNerney** [comment]
@robertarnesson 

Thank you. Good catch. In my zeal to remove comments from my script in my last post, I accidentally deleted priority:high. It actually reads:

        "data":{ "param1":"value1", "param2":"value2" },
        "to":"/topics/all",
        "priority":"high"

If this plugin does not automatically subscribe to any topics, then the console should not work either since I would not be subscribed to anything, right? Or, does the console somehow operate differently with regards to topics?

I have tried sending it to a valid token. I have tried sending it to a restricted_package_name. I have tried with data and without data. Nothing yet has this working for me....

**Comment by robertarnesson** [comment]
@JohnScottMcNerney what response from the server do you get? if you send to individual tokens you cannot use "to" as far as I know, you should use registration_ids: [list_of_tokens]

**Comment by JohnScottMcNerney** [comment]
@robertarnesson 

The response is a simple

      {
        "message_id": 8171985385404735000
      }

I tried individual tokens just to try to check things out. I do not plan to ever do this in the released APP.

Next week I will try different things with the "topic" and try doing a subscription from the device.

Thank you for all the help so far !  :)

**Comment by JohnScottMcNerney** [comment]
Had an issue with my Facebook plugin, and I had to do a

    android update sdk --no-ui --filter extra-android-m2repository,extra-google-m2repository

Now, my problem with this module is gone. I have no idea why. I have not touched my code.

**Comment by JohnScottMcNerney** [comment]
Made sure to subscribe with

    window.FirebasePlugin.subscribe("all");

and use Topic:all on Firebase console, and "to:'/topics/all'" in API and it works.

**Comment by rolinger** [comment]
@JohnScottMcNerney - can you elaborate on the window.FirebasePlugin.subscribe("all") within the app and how your server api  is sending to "all" ?  I think this might me my issue that I can't receive notifications while the app is open and in foreground.

**Comment by JohnScottMcNerney** [comment]
@rolinger  In the APP, when I'm setting up the FirebasePlugin I do:

    window.FirebasePlugin.onNotificationOpen(openCallback,setupFailureCallback);
    window.FirebasePlugin.subscribe("all");

I don't do any server saving of tokens, or try to notify just one device, so I don't set up window.FirebasePlugin.onTokenRefresh.

On the server, my data is (see the '/topics/all'):

    { notification: { title: 'Welcome to My APP.', body: 'Yeah! NFL starts soon' },
      data: { param1: 'value1', param2: 'value2' },
      to: '/topics/all',
      priority: 'high' }

I also test on Firebase Console, changing the Target to "Topic" and writing "all" in for the topic.

After may installs, uninstalls, open/close, etc. I finally had to reboot my phone to get the messages working again. You may want to try on a different device completely.
