### ISSUE TITLE
Blank screen after build

### ISSUE THREAD

**Issue by underscorenico** [arnesson/cordova-plugin-firebase#323]
I'm using the plugin for Google Analytics features only.
Our project uses ionic 2 and its written in typescript.
After building the Android app with NO ERRORS, and having the **google-services.json** on the root of the project (same level as config.xml or platforms/), when I launch the app on a device, it gets stuck on a blank screen.
It is very difficult to debug (and I 100% certain that the app builds correctly when I remove the plugin). 
Have anybody had this issue (and maybe solved it)?

**Comment by robertarnesson** [comment]
this happens when google-services.json is invalid or missing. how do you build the project? phonegap build is known to cause problems
