### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by jarekskuder** [arnesson/cordova-plugin-firebase#326]
When i add this plugin and build the project i get this error:

Error: /home/jarek/Projects/UniparkApp/uniparkparkingapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I understand that i have cordova-google-play-services plugin and it is using com.google.android.gms package and that's the thing that doesn't allow to build, but i can find the solution to this. Deleting the cordova-google-play-services plugin is not an answer because i need it for my other plugins, so if someone has the answer to this i would appreciate for help.

**Comment by robertarnesson** [comment]
for now you can fork this plugin and remove the com.google.android.gms dependency. this way you will only use the same library once
