### ISSUE TITLE
plugin create an extra Resources folder inside Resources with an empty google-info.plist

### ISSUE THREAD

**Issue by henrychavez** [arnesson/cordova-plugin-firebase#327]
the plugin create an extra Resources folder inside Resources with an empty google-info.plist

the problem is that the project is linking the Google-info.plist inside /platforms/ios/<project>/Resources/Resources/Google-Info.plist that is empty.

and the before_prepare hook is copying the correct file in the follow directory /platforms/ios/<project>/Resources/Google-Info.plist which is the correct config file.

cordova-ios: 4.4.0;
cordova: 7.0.1
ionic 1

**Comment by henrychavez** [comment]
I changed my cordova-ios version from 4.4.0 to 4.3.0 an the problem is solved but I'm still worried because I want to use the latest version of cordova-ios

**Comment by wolfg1969** [comment]
Is it caused by this fix of cordova-ios? https://issues.apache.org/jira/browse/CB-12009
