### ISSUE TITLE
Add permissions to plugin.xml

### ISSUE THREAD

**Issue by mymanga** [arnesson/cordova-plugin-firebase#33]
Permissions missing......

<uses-permission android:name="android.permission.INTERNET"/>
      <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
      <uses-permission android:name="android.permission.WAKE_LOCK"/>
      <uses-permission android:name="android.permission.VIBRATE"/>
      <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
      <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>
      <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature"/>

**Comment by robertarnesson** [comment]
what permissions?

**Comment by mymanga** [comment]
sorry, my bad...botched installation. Reinstalled and push messaging permissions showed up on android  manifest
