### ISSUE TITLE
Getting blank from firebase in response

### ISSUE THREAD

**Issue by bhaveshvyas007** [arnesson/cordova-plugin-firebase#330]
I have installed this plugin in ionic 1 and following are the versions of ionic and cordova,
**ionic** - 3.3.0
**cordova** - 7.0.1
**angular** - 1.0
**node** - v6.9.4
**npm** - 3.10.10
**gulp CLI** - 1.3.0

Following is code which I have implemented in my application - 

        if($window.FirebasePlugin){
          $window.FirebasePlugin.getValue("dev_name", function(response) {
              console.log(response);
              alert("Success:", response);
          }, function(error) {
              console.error(error);
              alert("Firebase Error:", error);
          });
          window.FirebasePlugin.subscribe("testing");
          window.FirebasePlugin.logEvent("page_view", {page: "initiator"});
          window.FirebasePlugin.grantPermission();
          window.FirebasePlugin.logEvent("cordova", {content_type: "page_view", item_id: "cordova"});
          window.FirebasePlugin.setBadgeNumber(100);
          window.FirebasePlugin.getToken(function(token) {
          // save this server-side and use it to push notifications to this device
          console.log("Firebase ===>"+token);
          }, function(error) {
          console.error("Firebase ===> failed"+error);
          });
        }

I am facing the issue of not getting anything in response, created the dev_name in firebase, in code it comes to success but nothings comes in response. 

Please help me out in this.
Thanks in advance

**Comment by robertarnesson** [comment]
ios or android?

**Comment by prasadgupte** [comment]
Android

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
