### ISSUE TITLE
getToken vs onTokenRefresh

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#332]
Can some one post a good example of using the two functions getToken and onTokenRefresh?

When do you actually use onTokenRefresh?  Couldn't you just initialize a getToken every time the app started and compare it to a stored token?  If different, then use the new one? 

Or is there some fundamental difference in how the two are evaluating tokens?

**Comment by robertarnesson** [comment]
getToken will simply return the current token, or null if the token is not yet available. onTokenRefresh on the other hand will be called every time the token changes, including the first time (i.e. when its changing from null), so there is indeed a fundamental difference. onTokenRefresh is safer in that sense. if you call getToken when your app is starting, it could be null (could be waiting to recieve one, or maybe the user has no internet connection, etc)
