### ISSUE TITLE
Feature Request - Getting notification while app is open

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#333]
the window.FirebasePlugin.onNotificationOpen doesn't get called at all if the app is already open.  Specifically data passed back in the payload is not triggering (even without a notice appearing in the forground).  Works great if app is closed or in the background, but if in the foreground, that function never fires.  

As well, is there a method or option that will allow the clean drop down notification icon and message to appear in the phone status bar at the top while the app is open or in the foreground?

> The documentation does say:
> App is in foreground:
> User receives the notification data in the JavaScript callback without any notification on the device itself (this is the normal behaviour of push notifications, it is up to you, the developer, to notify the user)

But I would like to take advantage of the very clean notification method/system that is already in place - don't want to recreate something that already looks good and works.

I am working on adding these, not working yet.  Maybe could use some help here - I am not a java guy:

In `\project\plugins\cordova-plugin-firebase\src\android\FirebasePlugin.java`, add to the end of the first boolean condition:
```

else if (action.equals("onNotification")) {
            this.onNotification(callbackContext);
            return true;
        }
```

And then add a new function:
```
    private void onNotification(final CallbackContext callbackContext) {
        FirebasePlugin.notificationCallbackContext = callbackContext;
        if (FirebasePlugin.notificationStack != null) {
            for (Bundle bundle : FirebasePlugin.notificationStack) {
                FirebasePlugin.onMessageReceived(bundle);  //<- in FirebasePluginMessagingService.java
            }
            FirebasePlugin.notificationStack.clear();
        }
    }
```

And then in the `\project\platforms\android\platform_www\plugins\cordova-plugin-firebase\www\firebase.js` file, add:
```
exports.onNotificationOpen = function(success, error) {
    exec(success, error, "FirebasePlugin", "onNotificationOpen", []);
};

```

I think this should be close...

**Comment by jorgemejia** [comment]
Same suggestion I think this function should be available for both events.

**Comment by rolinger** [comment]
I think the java files that are in the base plugin have what is needed to allow app foreground notifications to happen..  In the FirebasePluginMessagingService.java file there is a function called `onMessageReceived` - I am trying to see if I can fork this and use this to receive messages while the app is open in the foreground.  So far no luck yet.

**Comment by rolinger** [comment]
I am working on adding these, not working yet.  Maybe could use some help here - I am not a java guy:

In `\project\plugins\cordova-plugin-firebase\src\android\FirebasePlugin.java`, add to the end of the first boolean condition:
```

else if (action.equals("onNotification")) {
            this.onNotification(callbackContext);
            return true;
        }
```

And then add a new function:
```
    private void onNotification(final CallbackContext callbackContext) {
        FirebasePlugin.notificationCallbackContext = callbackContext;
        if (FirebasePlugin.notificationStack != null) {
            for (Bundle bundle : FirebasePlugin.notificationStack) {
                FirebasePlugin.**onMessageReceived**(bundle);  //<- in FirebasePluginMessagingService.java
            }
            FirebasePlugin.notificationStack.clear();
        }
    }
```

And then in the `\project\platforms\android\platform_www\plugins\cordova-plugin-firebase\www\firebase.js` file, add:
```
exports.onNotificationOpen = function(success, error) {
    exec(success, error, "FirebasePlugin", "onNotificationOpen", []);
};

```

Its close...

**Comment by sharjeel619** [comment]
Can you guys please tell me if there is already an event like OnMessageReceived even if the app is in the background or any similar event?

**Comment by rolinger** [comment]
@sharjeel619  - yes...its clearly listed in the documentation, its `onNotificationOpen` - however it only works when is closed or in the background.  When the app is open and in the foreground, the documentation says its supposed to only process a data payload in a received message - but I (and it seems a few others) haven't been able to get that part to work.

**Comment by sharjeel619** [comment]
@rolinger Isn't there a difference. because I want to set a badge number on top of My app icon when a notification is received not when it is opened. Anyways thank you for replying.

**Comment by sharjeel619** [comment]
@rolinger Also I don't receive a notification when the app is not running in the background or in the foreground. Only when the app is running in the background. Should it be like this?

**Comment by rolinger** [comment]
@sharjeel619 - I don't follow your first question at all.  For your second question, an app has three states:

1.  Running in foreground - notifications arrive, nothing happens.  Supposedly if message has payload it will be processed.  But I have not gotten that to work yet.
2.  Running in background - notifications arrive, notification icon appears in status bar.  If message is clicked, app will come to foreground and if a payload exists it can be processed
3.  Not running, - notifications arrive, notification icon appears in status bar. If message is clicked, app will open into the foreground and if a payload exists it can be processed.

**Comment by sharjeel619** [comment]
In the First Question. I was asking that isn't there a difference between events. First even being that the notification arrives and you see a notification bar. And the second event being that the notification bar is clicked. So I was asking what event does the function onNotificationOpen correspond to?

**Comment by sharjeel619** [comment]
In my second question I was stating that I do not receive any notification when my app is not running at all. But you stated in point 3 that it does. Please Confirm

**Comment by rolinger** [comment]
@sharjeel619 - thanks for clarifying.

1. Google Firebase supports multiple types of events.  This plugin supports a few of them.  Yes, if the app is in background or closed this plugin allows you to see the notification in the status bar.  If the message is clicked on, that is a second event that is handled by onNotificationOpen.

2. You must be doing something wrong then.  When my app is closed it does receive messages and when the message is clicked my app opens up

**Comment by apptum** [comment]
@rolinger haven't tested this, but after a quick look, this line could be of interest for you:

FirebasePluginMessagingService.java, line 70:
```
boolean showNotification = (FirebasePlugin.inBackground() || !FirebasePlugin.hasNotificationsCallback()) && (!TextUtils.isEmpty(text) || !TextUtils.isEmpty(title));
```

**Comment by apptum** [comment]
got interested and tried something. :)
https://github.com/arnesson/cordova-plugin-firebase/pull/313
Beware: not tested exhaustively (not an java guy either)

**Comment by rolinger** [comment]
@apptum - did you make any progress with your fork?  I still haven't gotten "app open - process payload" to work....however, using `onNotificationOpen` I was able to do "app background/closed - notification clicked - payload processed".  I pretty much have everything working the way I want except for when the app is already open.

**Comment by apptum** [comment]
@rolinger sorry, but I'm not actively developing on this

**Comment by dronzer92** [comment]
I have made this functionality for Android, at line number 71 in `FirebasePluginMessagingService.java` send last parameter always `true` like this
`sendNotification(id, title, text, remoteMessage.getData(), true);`
and in `sendNotification` function at line 123 at the end in if condition copy this code
```
    if (!FirebasePlugin.inBackground()) {
        bundle.putBoolean("tap", false);
        bundle.putString("title", title);
        bundle.putString("body", messageBody);
        FirebasePlugin.sendNotification(bundle);
    }
```

but i need this functionality for ios too, please help i someone find the solution

**Comment by Hanzofm** [comment]
Finally, I managed to solve the problem. In my case the problem was due to a incompatibility with cordova-plugin-local-notifications

This plugin captures the event of ondidreceived of ios and disables the normal flow

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by soumak77** [comment]
closing as resolved
