### ISSUE TITLE
Remote Config

### ISSUE THREAD

**Issue by rockrgrrl** [arnesson/cordova-plugin-firebase#334]
I'm using the plugin in an ionic project and I can't seem to get fetch() or activateFetched() to work. I've added parameters my project's firebase console. I've tried: 
window.FirebasePlugin.fetch(0);
window.FirebasePlugin.activateFetched(function(activated) {
        console.log('ACTIVATED.....', activated);
    }, function(error) {
        console.error('ERROR', error);
    });

This is what I get in my logs:
ERROR... – null

Any suggestions on how I can successfully retrieve the config parameter values?

**Comment by prasadgupte** [comment]
We're also having an issue with RemoteConfig

**Comment by remisture** [comment]
+1

**Comment by samarthagarwal** [comment]
Trying the following code, but always get a blank string as the value.
`this.firebase.fetch(0).then((fetched) => {
        alert(JSON.stringify(fetched));

        this.firebase.activateFetched().then((activated) => {
          alert(JSON.stringify(activated));

          this.firebase.getValue("store_url").then((value) => {
            alert((value))
          }).catch((error) => {
            alert(JSON.stringify(error));
          })

        })

      })`

**Comment by Bodeclas** [comment]
(<any>window).FirebasePlugin.fetch(600, result => {
           // activate the fetched remote config
           console.log(JSON.stringify(result)); //Always "OK"
           (<any>window).FirebasePlugin.activateFetched(
             // Android seems to return error always, so we want to cath both
             result => { 
               console.log(JSON.stringify(result)); //either true or false
              (<any>window).FirebasePlugin.getValue("value", result => {  
              console.log(result)  
               }, reason => {
              console.warn(`Error  ${reason}`);
              });
             }, reason => { 
               console.warn(reason); 
             }
           )
         });

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
