### ISSUE TITLE
getToken always returning null for android devices

### ISSUE THREAD

**Issue by camilacanhete** [arnesson/cordova-plugin-firebase#336]

**Comment by uchida-nunet** [comment]
+1. I have same issue.  getToken() returns always null and onTokenRefresh() never fire.

**Comment by uchida-nunet** [comment]
In my case, I had built my app with 'Hydration' on Adobe Phonegap Build.
Now, I can get token value after I turn off this option.

**Comment by robertarnesson** [comment]
More info is needed in order to help out, re-open if the problem persists
