### ISSUE TITLE
getValue is not working

### ISSUE THREAD

**Issue by remisture** [arnesson/cordova-plugin-firebase#339]
I can't get `getValue` to work. It seems to always be null. Has anyone got a working example?

```
$ionicPlatform.ready(function () {
   if (window.FirebasePlugin) {
      window.FirebasePlugin.getValue("xxx", function (value) {
         console.log(value);
      }, function (error) {
         console.error(error);
      });
   }
});
```

> Cordova CLI: 7.0.1
> Gulp version:  CLI version 1.2.1
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.3.2
> Ionic CLI Version: 2.1.1
> Ionic App Lib Version: 2.1.1
> ios-deploy version: 1.9.1 
> ios-sim version: 5.0.6 
> OS: Mac OS X Sierra
> Node Version: v4.4.0
> Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by narf** [comment]
For me getValue promise never returns anything, there is no rerject nor resolve called.

```
console.log("firebase getValue");
firebase.getValue("delayBeforeSleep").then((...args) => {
    console.log("ok", args)
}).catch((...args) => {
    console.log("error", args)
});
 console.log("after firebase getValue");
```
Displays
```
firebase getValue
after firebase getValue
```
And nothing else.

> Ionic 3.5.0
> "@ionic-native/firebase": "4.0.0"
> "cordova-plugin-firebase": "0.1.22",

**Comment by Bodeclas** [comment]
(<any>window).FirebasePlugin.fetch(600, result => {
           // activate the fetched remote config
           console.log(JSON.stringify(result)); //Always "OK"
           (<any>window).FirebasePlugin.activateFetched(
             // Android seems to return error always, so we want to cath both
             result => { 
               console.log(JSON.stringify(result)); //either true or false
              (<any>window).FirebasePlugin.getValue("value", result => {  
              console.log(result)  
               }, reason => {
              console.warn(`Error  ${reason}`);
              });
             }, reason => { 
               console.warn(reason); 
             }
           )
         });

**Comment by rockrgrrl** [comment]
Thanks @Bodeclas. I saw what you did, and I got it to work. I was trying to use the ionic wrapper initially, but there seems to be an issue with that. Once I used the plugin straight up, it worked as expected.

**Comment by Bodeclas** [comment]
@rockrgrrl Great!

**Comment by remisture** [comment]
Thanks, @Bodeclas. I still can't get it working. Any ideas?

```
window.FirebasePlugin.fetch(600, new function () {
   console.log("*** fetch");
   window.FirebasePlugin.activateFetched(function (activated) {
      console.log("*** activateFetched: " + activated);
      window.FirebasePlugin.getValue('xxx', function (value) {
         console.log("*** getValue: " + value);
      }, function (error) {
         console.log("*** getValue error: " + error);
      });
   }, function (error) {
      console.log("*** activateFetched error: " + error);
   });
});
```

> 2017-08-02 14:33:41.637302 My App[442:109789] *** fetch
> 2017-08-02 14:33:41.646855 My App[442:109789] *** activateFetched error: null
> 2017-08-02 14:33:41.654042 My App[442:109789] Error in Success callbackId: FirebasePlugin594619209 : TypeError: callback.success.apply is not a function. (In 'callback.success.apply(null, args)', 'callback.success.apply' is undefined)

**Comment by remisture** [comment]
What is wrong with the success callback? This works:

```
      window.FirebasePlugin.fetch(600, new function () {
        console.log("*** fetch");
        window.FirebasePlugin.activateFetched(function (activated) {
          console.log("*** activateFetched: " + activated);
          window.FirebasePlugin.getValue('feedback_email', function (value) {
            console.log("*** getValue: " + value);
          }, function (error) {
            console.log("*** getValue error: " + error);
          });
        }, function (error) {
          console.log("*** activateFetched error: " + error);
          window.FirebasePlugin.getValue('feedback_email', function (value) {
            console.log("*** getValue: " + value);
          }, function (error) {
            console.log("*** getValue error: " + error);
          });
        });
      });
```

**Comment by jairemix** [comment]
@remisture 

You might have already figured this out, but if you do too many requests an hour with the same device, the Firebase SDK goes into 'throttling mode':

https://firebase.googleblog.com/2017/01/firebase-remote-config-loading.html

This registers as an error in the plugin, hence why the error callback is called.

**Comment by Thomasbehan** [comment]
In order for the getValue function to work properly you are required to set a default value see firebase loading strategies => https://firebase.googleblog.com/2017/01/firebase-remote-config-loading.html

**Comment by meetshahblogs** [comment]
@Bodeclas 

Where do I import FirebasePlugin from?
I am getting " Cannot read property 'fetch' of undefined" when I copied your code.

Currently only import have is,
import { Firebase } from '@ionic-native/firebase';

but this doesn't seems to resolve FirebasePlugin object!

**Comment by Bodeclas** [comment]
@meetshahblogs Hi! 

```typescript
import { Injectable } from '@angular/core';
import { Platform }   from 'ionic-angular';
import { Firebase }   from '@ionic-native/firebase';

@Injectable()
export class Provider {

...

  constructor(
  readonly platform: Platform,
  readonly firebase: Firebase) {
    platform.ready().then(() => {
      if (platform.is('cordova')){
        if (platform.is('ios')) {
          this.firebase.grantPermission()
            .then((success) => {
              if (success) {
                console.log(`Success grant permission on iOS value`);
                this.doGetDeviceToken();
              }
            });
        } else {
          this.doGetDeviceToken();
        }

        firebase.onNotificationOpen()
        .subscribe(res => {
          if (res.tap) {
            //background mode
            console.log(`notification on background`);
            console.log(res);
          } else if (!res.tap) {
            //foreground mode
            console.log(`foreground`);
            console.log(res);
            this.presentToast(res);
          }
        })

          if ((<any>window).FirebasePlugin !== undefined) {
          // Fetch Firebase remote config
          (<any>window).FirebasePlugin.fetch(60000, result => {
            // activate the fetched remote config
            console.log(JSON.stringify(result)); //Always "OK"
            (<any>window).FirebasePlugin.activateFetched(
              // Android seems to return error always, so we want to cath both
              result => {
                console.log(JSON.stringify(result)); //either true or false
                this.getValue("paginationApi");
              }, error => {
                console.warn(error);
              }
            )
          });

          this.firebase.getInfo().then(res =>{
            console.log(`get info success ${JSON.stringify(res)}`);
          }).catch(err => console.warn(`get info error ${err}`));
        }
      }
    }).catch(reason => console.warn(reason));
  }

  private getValue(value:string) {
    console.log("launch get value function");
    (<any>window).FirebasePlugin.getValue(value, result => {
      console.log(value);
      if (result) {
        console.log(`remote config value: ${result}`);
        console.log('result from firebase', result);
      }
    }, reason => {
      console.warn(`Error! ${reason}`);
    });
  }

  doGetDeviceToken() {
    this.firebase.getToken()
      .then(token => console.log(`The token is ${token}`))
      .catch(error => console.log(`Error getting token${error}`));
    this.firebase.onTokenRefresh()
      .subscribe((token: string) => console.log(`Got a new token ${token}`));
  }
}
```
