### ISSUE TITLE
IOS notification on status bar not working

### ISSUE THREAD

**Issue by brunosoaresds** [arnesson/cordova-plugin-firebase#340]
Hi,

I'm using ionic with cordova 7. I have installed APN certificates, adjusted the GoogleServices-Info.plist in the xcode project and enabled capabilities (Push notification and Remote notifications in Background capabilities). I have published my app in the testflight and when i send the notification to ios devices the firebase says that is successfully sent, however the notification in the IOS status bar is not created or showed even if my app is in background ou not opened.

However, if my app is in foreground and running, when i send the notification, it can be received in the OnNotification method. What i'm doing wrong? Can anyone help-me?

**Comment by rolinger** [comment]
You sound like you are having the opposite issue of everyone else.  The Docs say its only supposed to register a notification is the app is closed or in the background - which is how mine is working on Android.  however I can't get notifications to work with my app on iOS...in fact I can't even figure out how to enable the permissions for my iOS app.  when I see iPhone -> Settings -> MyApp, "NOTIFICATIONS" is not listed in the entitlements/access permissions.  

I have done the same as you, APN Certs, added the GoogleServices-Info.plist to the root of my project and in Xcode enabled Push Notifications....and Background Modes -> Remote Notifications.  But when I look in my iPhone App permissions settings NOTIFICATIONS is not listed.

**Comment by brunosoaresds** [comment]
@rolinger, i have the same problem than you. My app have no notification permission in the settings. I tried but i cant make It Works. However, when the app os in the foreground the firebase notification data, comes into onNotification function. I think maybe you can receive It in the foreground mode too. 

Im thinking if anyone here have successfully made notification in the status bar works in IOS using this plugin...

**Comment by jaybowman** [comment]
I'm trying to get notification to work in IOS also. So far I've had no luck, not even if the app is in the foreground. I have everything set up. Brunosoaresds when you created your app id on developer.apple.com did you enable push notification? When my app installs it shows up on my device settings and it has notifcations enabled.  
I'm using cordova-ios 4.3.1, cordova-cli 6.3.1, xcode 8.3.3, build for ios 10.3, 
I have an issue i can't figure out. if i build for 9.3 and install on an ipad the app will freeze on startup, but i done see any errors. 
I had to edit the AppDelegate.m file and add firebase.h, and [FIRApp configure];
Does anyone have notifications completely working in IOS?

**Comment by brunosoaresds** [comment]
@jaybowman i have enabled this options. But im thinking that the problem is because im using 9.3 SDK. Searching this repository, i found pull requests to fix this bugs. However, i don't want to upgrade my Macbook to Sierra, so for now, i can't test it with 10++ SDK.

**Comment by zgluis** [comment]
Are you executing   [Grant Permissions?](https://github.com/arnesson/cordova-plugin-firebase#grantpermission-ios-only), without it you wont see Notifications in the permission's list. @rolinger @brunosoaresds

**Comment by brunosoaresds** [comment]
yes @zgluis , but its doesn't works in my app compiled with 9.3 SDK. The popup don't appear.

**Comment by rolinger** [comment]
I got my iOS notifications to work.  It was a grant permissions issue.  I am working on cleaning it up though because when it the grant permissions is executed at app install/launch, the app doesn't wait for user response, it fully loads the app while the permission request is still on the screen.  That poses a problem for me because parts of my app need to determine if the permission is set before the app loads.  Maybe you all can assist on how to pause the app while waiting for user action on the permission.

Here is my code:
```
  function iosPush() {
    var q = $q.defer() ;
    if (/(iPad|iPhone|iPod)/i.test(navigator.userAgent)) {
      window.FirebasePlugin.grantPermission(function(status) {
        q.resolve(status) ;
      }) ;
    } else {
      q.resolve("Android") ;
    }
    return q.promise ;
  }
    // calling iosPush() should pause the app install waiting for user action on the permission, but
   // but it doesn't pause, the app continues and other permissions do pop up waiting for user action.
   // I think this is because the window.FirebasePlugin.grantPermission isn't a true "success/error" callback function.
    iosPush().then(function(status) {   
      return getLocationAuth()
    }).then(function(status) {
      errMgmt("ctrl/init",30.2,'GPS Auth was '+status) ;
      if (/(android)/i.test(navigator.userAgent) ) {
        return getReadPhoneAuth() ;  // process Android Permission
      } else {
        return "GRANTED" ;  // if iOS, pass 'granted' which is used to bypass certain sections in next promise chain.
      }
    }).then(function(status){ ...... }) ;
```
