### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#341]
Just installed the plugin for my apple project and got this error during the build process:

AppProject/Plugins/cordova-plugin-firebase/FirebaseMessaging.framework/FirebaseMessaging(GtalkCore.pbobjc_ad79188db2f7ee25404fa2685578f27f.o)
ld: 42 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/AppProject.app/AppProject normal x86_64
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/test/dev/AppProject_0.1.90/platforms/ios/cordova/build-debug.xcconfig,-workspace,AppProject.xcworkspace,-scheme,AppProject,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Users/test/dev/AppProject_0.1.90/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/test/dev/AppProject_0.1.90/platforms/ios/build/sharedpch

Please advise.  thanks.

Your system information:

> Cordova CLI: 7.0.1
> Ionic Framework Version: 1.0.0
> Ionic CLI Version: 1.7.16
> Ionic App Lib Version: 0.7.3
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v8.0.0
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by rolinger** [comment]
Correct...disregard and close.

Turns out I had two conflicting "PUSH" plugins installed.  `phone gap-plugin-push` was also installed with `cordova-plugin-firebase`.  I removed both...did a clean build...readded `cordoba-plugin-firebase` and it compiled without the above error.

**Comment by cyrilbras** [comment]
I have similar problem but phone gap-plugin-push isn't installed

It causes many duplicate symbols when i fresh install the cordova-plugin-firebase, 
I have 3 warnings of  " directory not found for option " for respectively GoogleToolboxForMac - Protobuf -nanopb

example
`1>  duplicate symbol _GPBEmptyNSData in:
1>      /Users/user/.taco_home/remote-builds/taco-remote/builds/89035/cordovaApp/platforms/ios/build/device/libProtobuf.a(GPBUtilities.o)
1>      MyProject/Plugins/cordova-plugin-firebase/Protobuf.framework/Protobuf(GPBUtilities_87a96be5a9c7edc361c6e0b1a3300ded.o)`

I have tried remove -ObjC in  target->MyProjetc-> build settings -> all -> other linker flags
, after this change compilation works but app crashes immediately on launch

Any help would be welcome!
