### ISSUE TITLE
getToken no return value

### ISSUE THREAD

**Issue by 201110670** [arnesson/cordova-plugin-firebase#343]
update for version 0.1.22 is not getting token from device.. Please help to fix.﻿

**Comment by dobbinx3** [comment]
Hey there, give more information please. Like the platform you are using, node version, etc. 

You get any error? Or nothing appear?

**Comment by 201110670** [comment]
Problem solved!

forgot to set the below code.
window.FirebasePlugin.onTokenRefresh(function(token) {
    // save this server-side and use it to push notifications to this device
    console.log(token);
}, function(error) {
    console.error(error);
});

need to set this on first time use.

**Comment by maleavle** [comment]
man ehre you put tis function??  im using is code too but i get:   Uncaught TypeError: Cannot read property 'getToken' of undefined  please help

**Comment by 201110670** [comment]
you need to initialize the function on the start of the program.

**Comment by maleavle** [comment]
thanks it works, but the first time what the app runs token is empty. i must update the index file and the it generate the token, do yohad this issue too?

**Comment by 201110670** [comment]
if the code is set and completely initialized,the application must connected to the internet to get and refresh the token.

yes, I had those issue before.
