### ISSUE TITLE
Stack the Notification in Ios and Android

### ISSUE THREAD

**Issue by Nagaraj007** [arnesson/cordova-plugin-firebase#345]
Hi thanks for this plugin this works great,But my issue is How i can stack the notification multiple notification into one,Now for each post i am getting each different Notification,How i can stack it kindly suggest

**Comment by brunosoaresds** [comment]
Hi,

On Android you van set the parameter "tag" insiste your notification according the firebase API. However i think this is not possible on IOS.

**Comment by Nagaraj007** [comment]
thanks its working

**Comment by Nagaraj007** [comment]
how i can change the background color of Notification,I am getting gray color background with my custom logo,Is it possible to change the color..?

**Comment by brunosoaresds** [comment]
Yes, its possible, but again, only for Android. You van check all notification parameters att firebase docs https://firebase.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload

**Comment by Nagaraj007** [comment]
Thanks for your time,Its working i have changed background color.

**Comment by NBAMj** [comment]
Adding the attribute `tag` doesn't stack notifications, it just replaces the old notification with the new one.
Have you figured how to stack notifications rather than replacing them?
