### ISSUE TITLE
How to enable push notification within iOS app?

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#346]
Hi all...I have this plugin and push notifications all working on Android but not having luck with iOS.  I can't even get NOTIFICATIONS to show up in my apps Access Permissions within the iPhone Settings.

In my cordova app I add the plugin.  In firebase console I have linked the iOS app with all the appropriate APNS IDs and generated the GoogleService-info.plist file and added that to the root of my project.  In Xcode I have enabled the push notification entitlement and can see its set to "configurable" on my developer.apple.com Account IDs for my app.  So it all looks right.

However when I compile my app and load it onto an actual iPhone in the Settings the app shows that access to NOTIFICATIONS isn't even an option...I can see it listed as an option in other apps.  so I am not turning mine on correctly but can't tell if its something I am doing from my cordova code, or my Xcode project or....???

Any help would be appreciated.

**Comment by joelmarquez90** [comment]
Ok so you first have to grant permissions only on iOS, the code would be something like this:

```javascript
  getDeviceToken() {
    if (this.platform.is('ios')) {
      this.firebase.grantPermission()
        .then((success) => {
          if (success) {
            this.doGetDeviceToken();
          }
        });
    } else {
      this.doGetDeviceToken();
    }
  }

  doGetDeviceToken() {
    this.firebase.getToken()
      .then((token) => this.setToken(token))
      .catch((error) => this.handleError(error));
    this.firebase.onTokenRefresh()
      .subscribe((token) => this.setToken(token));
  }
```

Where `setToken` is a function that updates the current device token of the user on the Firebase Database.

Hope it helps!

**Comment by rolinger** [comment]
@joelmarquez90 - thanks.  I now have 'notifications' enabled on the app via the iOS permissions.  Quite honestly, I completely missed that in the documentation.  That being said, I then used the token key that was generated and tested it directly in firebase console and sent a test message - and it never arrived.

I had really hoped this was the last piece of the puzzle but I still can't get push messages to arrive at my phone:

Xcode 8.2.1
   - App Capabilities:
      Push Notifications enabled
      Background Modes - Remote Notifications enabled (is this even necessary)
Firebase Console:
   - iOS app added, using APNs Auth Tokens (.p8) exported from Developer.apple.com ACCOUNTs
   - imported GoogleService-Info.plist to root of project
Cordova:
   - Successfully getting iOS grantPermissions to enable NOTIFICATIONS in app access features

In console I can see the following firebase messages:
Firebase Analytics enabled
2017-07-09 11:44:07.555 appName[2214] <Notice> [Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
2017-07-09 11:44:07.866418-0400 appName[2214:1566818] Connected to FCM.
2017-07-09 11:44:07.875018-0400 appName[2214:1566818] InstanceID token: ecQmuaDFbUU:APA91bEXiEekgm9Z3bUBuKPHzVEVwZSlSJgVmzGGv4Q3zZ6UwJDkWQN9Jtt8j40ylG6qoj49SML............vR1z2vy3gu51hL7DnntBxoDSzk

What else am I missing?  What should my bundle AppID permissions look like on Developer.Apple.com console?  Should I see "Push Notifications :   Development=configurable, Distribution=configurable".  ???? Trying to get this to work I also attempted to create a .p12 certificate....but never uploaded that to Firebase Console App....but right now my "Distribution=Enabled" when I created the .p12 - does that matter?  

This is not easy stuff - someone needs to a SOLID tutorial on this.  Its quite confusing.

**Comment by rolinger** [comment]
@joelmarquez90 - never mind on that last one.  ITS WORKING!!!!!  Holy crap, what a pain in the ass that was.

I was sending messages from FB Console with no badge or sound on...so they were arriving silently in the background and I wasn't seeing them.  

Soon...now on both Android and iOS, push notifications arrive ONLY if app is in background or if app is closed.  How can this plugin be used to get notifications to arrive/show up if app is foreground?  I still want the notifications to alert the user the notification has arrived when they are actively using the app.

**Comment by remisture** [comment]
I think you have to manually handle the use case where the app is in foreground.

**Comment by rafaelsilvestre** [comment]
@rolinger how you fix it? i have added the grant permission into my app and it works in the simulator, but in the testflight installation the app don't ask for notification permission and because of that the app settings don't show NOTIFICATION.

**Comment by rolinger** [comment]
@remisture - When the app is open and in the foreground I am not receiving any notification that a message has arrived.  As well, the onNotificationOpen doesn't seem to process any data payload to trigger the app to do something.  So I can't even do my own internal notification alert.  Have you gotten that to work?

Ideally I want to be able to receive normal push notifications (on the status bar) even when app is open in the foreground...but just being able to process data payloads would help.

@rafaelsilvestre - you have to enable the "Push Notification" on your app "Capabilities" within Xcode.  It was a simple on liner in the JS though: `window.FirebasePlugin.grantPermission();` - there didn't seem to be a proper success/error callback though - because I can't get the permission process to halt until the user says OK or NO...the rest of my app continues to initialize even while the permission alert stays on top of the screen.

**Comment by rolinger** [comment]
I got this resolved.  Closing it out.

**Comment by gregor-srdic** [comment]
@rolinger  how did you solve it? I am experiencing the same problem :S

**Comment by rolinger** [comment]
I went through several iterations to get it working and I don't recall all the steps.  what specifically is not working for you?  I can take a look at my code and get back to you.

**Comment by gregor-srdic** [comment]
Thanks for the answer, I got the notification on iOS when app was in the background, but onNotificationOpen callback was never fired if app was in foreground or when I tapped on the notification.
I added this `window.FirebasePlugin.grantPermission()` call, removed and readded plugin and cordova-ios platform and now it is working.

**Comment by rolinger** [comment]
ok cool....yeah, I recall having to drop cordova-ios and/or firebase and readd them...and then it started working.
