### ISSUE TITLE
token only works if internet connection is ON the first time the app is opened on iOS

### ISSUE THREAD

**Issue by nyluje** [arnesson/cordova-plugin-firebase#347]
I use the getToken() function to get the reg id when my app starts.

_Situation A:_ If the **internet connection is ON the first time** I open the app, I get a token from getToken() that I save on the server DB. And **everything works fine afterwards, Push Notifications arrive on my device**.

_Situation B:_ If the **internet connection is OFF the first time** I open the app, the getToken() sends a 'null' (which totally makes sense). Later on, I turn the internet connection to ON again. I refresh the app, it plays the getToken() function and this time the app receive a token value, which is sent to the server DB and I can see in my DB that this value has been uploaded in the tuple where it should be (so it does look alike _Situation A_). 

**BUT if I use FCM to send Push Notification, it does not work in that case.**

I have also tried to use the tokens in the Firebase single device send test message, and it showed the same pattern: a token from _Situation A_ was good to receive test Push Notif whereas a token from _Situation B_  was not correct to receive test Push Notif.

I did the same test on Android and token received in _Situation B_ works to send push notifications.

Version:
cordova-plugin-firebase version: 0.1.21
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.3.3 Build version 8E3004b

Device: iPhone 7+, ios 10.3.2

**Comment by robertarnesson** [comment]
if this is a problem it would be a problem with firebase itself and not the plugin. closing this for now
