### ISSUE TITLE
window.FirebasePlugin.grantPermission() issue

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#348]
On iOS I am able to get the grantPermission to work, but there doesn't seem to be a proper success/error callback associated with it.  When I do:

window.FirebasePlugin.grantPermission(function(success) {
     console.log(success) ;
}, function(error) {
     console.log(error) ;
});

my console spits out: null regardless if I permit or deny the permission.

As well, I am looking for a method with grantPermission that will halt app while the user Permits or Denies the permission request....currently the grantPermission pops up a window but my app continues to initialize in the background...but I need to capture that Permit/Deny before allowing the app to continue to initialize.  Other init features are based on the user's selection.

**Comment by SuryaThrideep** [comment]
i am also not getting any prompt for agreeing push notification

**Comment by dobbinx3** [comment]
Hi @rolinger 

The grantPermission method don't have this info. Maybe what you should do to get this info is, inside your `grantPermission` callback you use the `hasPermission` method and check if is true or false.

`
   window.FirebasePlugin.hasPermission(function(data) {
      console.log(data.isEnabled);
   });
`

---

Now to "Block" your appplication, in your app init you should send your user to a waiting view (so your app functionality won't apper for him), create a method and add a return to it, this return will be called when your `grantPermission` is answered and ou know if  he enable or not the plugin.

Inside this callback you put some code to change the view and etc.

**Remember** that after your user answer the `grantPermission` method, it won't pop up again automatically. So you need to add a logic that won't let your user stuck in this waiting view when he enters your app the second time for example.

**Comment by rolinger** [comment]
I follow the gist of what you have suggested but have not been able to get it to work correctly.  Any chance you could write a working example?  I have tried multiple times.

**Comment by robertarnesson** [comment]
pull https://github.com/arnesson/cordova-plugin-firebase/pull/306 is now included in the lastest release. this should help you
