### ISSUE TITLE
IOS application will not start , freeze on splash screen.

### ISSUE THREAD

**Issue by jaybowman** [arnesson/cordova-plugin-firebase#352]
This plugin is working fine with android. but the application freezes on starup. xcode debug log:
error [firebase/Core][I-COR000003] The devault firebase app has not yet been configured,..
Unable to connect to FCM...
I have APN's configured in firebase console 
Do I need to install Firebase SDK on my Mac?
see attached logs image.
running cordova 6.5, cordova,ios 4.2.0, node 6.11.0, My app is an Ionic 1.x.
Please help. I've been struggling with this for a couple of days.
![firebase error](https://user-images.githubusercontent.com/4990535/28213808-ad4a3e8a-6875-11e7-95f4-b85a2d2b89f4.PNG)

**Comment by jaybowman** [comment]
I added the import "firebase.h" and [FIMApp configure] to the appDelagate.m class. now my start up is clean. But the app still freezes after the finish load of index.html.
i have a debug log message "Disconnected from FCM"
then i ran the app again from xcode in debug and this time i got the "unable to connect to FCM".
the application froze after the loading of index.htm. I also have a codova-plugin-google-analytics installed could this cause a conflict.

**Comment by noveweb** [comment]
+1

**Comment by zgluis** [comment]
Did you tried removing codova-plugin-google-analytics?

**Comment by bunday** [comment]
i suggest you do the following

Open Firebase
Add iOS to your App
Enter your App Name
Enter your BundleID (com.something.something)
Download your GoogleService-Info.plist
Paste it inside your platform/ios/AppName/Resources folder
Copy the content also and paste in your platform/ios/AppName/Resources/Resources
Re Build your App.
It should work perfectly,

Drop a message if anything happens
cheers

**Comment by jaybowman** [comment]
Thanks for the suggestion. I've created a barebones app to try to get it work. Still working on it. I've switched over to using cordova-plugin-fcm. I have this one working in my main application. But would like to use the firebase one for analytics also. I think I have some plugin conflicts because the app never gets past the initialization. I found that the cordova-plugin-fcm only works for IOS > 10. What ios and cordova-ios versions is this plugin compatible with. 

I did remove the codova-plugin-google-analytics this was definitely causing a conflict.

**Comment by jaybowman** [comment]
I have the plugin working in my stripped down test app. I'm troubleshooting by adding plugins in to see if any that i use in my main application will cause the test app to hang on startup.

**Comment by jaybowman** [comment]
had a conflict between this plugin and geolocation, upgraded my cordova-plugin-geolocation and the app is starting, notifcations are working.

**Comment by Isaacn123** [comment]
Thanx a lot Olayinka Zadat O.....it was successful help a whole month of struggling with the Crush...

**Comment by devotebest** [comment]
@jaybowman  I got exactly same problem today.
what is your version of cordova-plugin-firebase and cordova-plugin-geolication?

Thanks

**Comment by jaybowman** [comment]
Currently I'm running cordova 8.1.2 on pc and 9.0 on mac. I found that cordova android@7.1.4 works best. I tried the latest cordova android but had problems I think related to the firebase plugin. IOS ver 4.5.5.
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
