### ISSUE TITLE
iOS IDFA advertisingIdentifier and cordova-plugin-firebase: What are the purposes of IDFA in FirebaseAnalytics ?

### ISSUE THREAD

**Issue by nyluje** [arnesson/cordova-plugin-firebase#353]
(also submitted on [SO](https://stackoverflow.com/questions/45118759/ios-idfa-advertisingidentifier-and-cordova-plugin-firebase-what-does-it-use-if))

I am in the process of submitting an iOS App and reached the question about: "Advertising Identifier" (IDFA).

I ve looked around on SO and found [here][1] that I could run this command: `fgrep -R advertisingIdentifier . ` in my iOS project folder to find out if  `advertisingIdentifier` was in it.

It happens that I use the [cordova-plugin-firebase][2]. **But I have not set in my program any functionality to use the IDFA.** I understand the use of the [cordova-plugin-firebase][2] could imply that my app use it despite it was not meant to.

Command `fgrep -R advertisingIdentifier . ` shows:

    Binary file ./[my ionic project name]/Plugins/cordova-plugin-firebase/FirebaseAnalytics.framework/FirebaseAnalytics matches
    Binary file ./build/device/[my ionic project name].app/[my ionic project name] matches
    Binary file ./build/device/[my ionic project name].app.dSYM/Contents/Resources/DWARF/[my ionic project name] matches
    Binary file ./build/emulator/[my ionic project name].app/[my ionic project name] matches
    Binary file ./build/emulator/[my ionic project name].app.dSYM/Contents/Resources/DWARF/[my ionic project name] matches

So I reach the conclusion that it has advertisingIdentifier  in [`.../cordova-plugin-firebase/FirebaseAnalytics.framework/FirebaseAnalytics`][3]. 

Now on iTune Connect, I check YES to the question:
 > Does this app use the Advertising Identifier (IDFA)?

But then I have to qualify by YES or  NO what the "Advertising Identifier" do among those options:

 - > Serve advertisements within the app
 - > Attribute this app installation to a previously served advertisement
 - > Attribute an action taken within this app to a previously served
   advertisement

Does anyone know exactly, what is advertisingIdentifier purpose in [`.../cordova-plugin-firebase/FirebaseAnalytics.framework/FirebaseAnalytics`][3]?

  [1]: https://stackoverflow.com/questions/23124663/does-this-app-use-the-advertising-identifier-idfa-admob-6-8-0
  [2]: https://github.com/arnesson/cordova-plugin-firebase
  [3]: https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/Firebase/Analytics/FirebaseAnalytics.framework/FirebaseAnalytics

**Comment by apptum** [comment]
does this help you? https://support.google.com/firebase/answer/6318039?hl=en

> By default, the Firebase SDK collects identifiers for mobile devices (for example, Android Advertising ID and Advertising Identifier for iOS) and utilize technologies similar to cookies.

> On iOS, the SDK collects the Advertising Identifier if it is available. For IDFA to be available, a developer has to link in the following libraries:

> libAdIdAccess.a
>AdSupport.framework
>If the Advertising Identifier is unavailable, the SDK collects the Vendor Identifier. If the Advertising Identifier becomes available after the Vendor Identifier was reported, the SDK stops collecting the Vendor Identifier.

**Comment by nyluje** [comment]
Thanks apptum, it gives me a better understanding.

**Comment by davejlong** [comment]
@apptum I'm building my app with Ionic, but I was wondering if there was a way in `config.xml` ti link `libAdIdAccess.a` and `AdSupport.framework` to my app? Otherwise, if the Firebase plugin is supposed to do it for me, is there a way to verify that IDFA is in use on iOS?

**Comment by apptum** [comment]
@davejlong sorry, can't help with ionic and have no further knowledge of IDFA or its inner workings..

**Comment by robertarnesson** [comment]
I think its safe to say no. we dont pull in AdSupport.framework. but even if that was the case my understanding is that you can still say no unless you actually use the IDFA
