### ISSUE TITLE
logEvent not recording event to Firebase console

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#354]
I am using the following function to record events and page-views throughout my app.  However I am not seeing any of these events being triggered or recorded.  In fact, when I look at the 'network' tab of Chrome Inspector I don't even http calls to Firebase.  I would imagine I would see the outbound calls no?

```
function fireBase(action,loc,contentType,eventType) {
  // fireBase(1,"") ;
  // fireBase(2,"","","") ;
  var fire = window.FirebasePlugin ;
  if (action == 1) {
    fire.setScreenName(loc);
    console.log("Firebase 1: "+loc)
  } else if (action == 2) {
    fire.logEvent("select_content", {content_type: contentType, item_id: loc});
    console.log("Firebase 2: "+contentType+ ", " +loc) ;
  }
}
```

I do have push notifications working, therefore I think all of my FB console and app is set up correctly.  Are there specific FB console configs or things I must add to FB Console to specifically add the event I want to record?

**Comment by dobbinx3** [comment]
Hi there, everything should  be working. Firebase do not log anything in network or console (don't know if there is an option to enable that, if it possible).

But do the actions that call this logEvent and after one day it will appear in your firebase console.

And as I can see you are passing some data to firebase. It is not automatic tracked this information (especially when you create the tags [which is not the case]), but if you want to see the graphs of the object that you send with the log. Go to Analytics > Events, whe the tag appear there in the right part of the row you will see 3 dots menu, click there and select the edit parameters option, select the parameters you want to see in the console, trigger the action again and wait for one more day. 

Don't know it there is an easy way to track it, if there is please enlighten me.

**Comment by rolinger** [comment]
@dobbinx3 - I am performing the actions that are triggering the logEvents.  I see the events in my Developer Console - so I know the function is firing.  You say by default that Firebase plugin won't report events to Network or Console; but how else can I see if my app is working correctly - especially if those custom tags aren't even appearing in Analytics -> Events section.

In `Analytics -> Events` I don't any of the custom tags I am logging from the app.  I don't see any of the page names or any of the specific `select_content` tags I am trying to log.  Thus I am not able to add them to any charts or graphs.   Must I configure something in Firebase Console or within the Events section just to get my tags to be accepted or to appear in that section?

**Comment by rolinger** [comment]
Well....its working.  I guess it was all along...just took me forever to actually find where the data was being logged.  Under `Events`...i had to select `screen_view` or `select_content` and then change the `content` or `user engagement` report to reflect the custom names or fields.

A bit of a kludge if you ask me.  Those events should show up as list higher up...you have to drill down like 4 levels before you actually find our custom data.

**Comment by dobbinx3** [comment]
@rolinger Nice it works for you. And I completely agree with you. Since we are passing the data, we want it to show in the graphs. 

Hope the firebase team come up with this functionality in the future.

Cya
