### ISSUE TITLE
AdWords attribution with iOS app store

### ISSUE THREAD

**Issue by sengoontoh** [arnesson/cordova-plugin-firebase#357]
Has anyone been able to get conversion events in iOS recorded by Firebase Analytics attributed back to AdWords? It works fine on Android but on iOS, I'm not seeing the conversions reported back to AdWords.

I even installed the AdFramework in Xcode and informed iTunesConnect that I'm using IDFA for ad attribution.

Any help would be greatly appreciated

**Comment by pkudel4** [comment]
hi guys, anyone on the above? Im also working on adding the Firebbase into my Apache Cordova 6 app just to get AdWords iOS conversions working. Any feedback would be great

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
