### ISSUE TITLE
Notification comes perfectly but does not pop out when i am on home screen 

### ISSUE THREAD

**Issue by KishanIos007** [arnesson/cordova-plugin-firebase#358]
i want pop out just like below image but unfortunately only notification appears.

![qh43y34](https://user-images.githubusercontent.com/18045135/28457102-7a1bf834-6e22-11e7-9951-e218cea139a2.jpg)

**Comment by MontblackArg** [comment]
emm. try with this:

grantPermission (iOS only)

Grant permission to recieve push notifications (will trigger prompt):

window.FirebasePlugin.grantPermission();

**Comment by KishanIos007** [comment]
i already does that. Notification comes perfectly but what i want is in android notification doesn't pops out like other apps notification @MontblackArg

**Comment by hoonblizz** [comment]
Same thing is happening here. 
I can see that notification had been arrived from the log but not in notification bar.

**Comment by zgluis** [comment]
I had the same issue, I was forgetting to add the APNs certification Key in the firebase console. Check this: [https://firebase.google.com/docs/cloud-messaging/ios/certs](url)

![image](https://user-images.githubusercontent.com/16930032/28750015-0e4ab9e0-74aa-11e7-95df-985311dd8b36.png)
> FirebaseConsole/Overview/iOS-Settings/CloudMessaging

**Comment by pruthwirajkadam** [comment]
I have same problem in android.All code work fine.when i send notification using php (from my server) then notification not display on noticebar but using firebase console when i send notification then its pop up.

**Comment by maleavle** [comment]
pruthwirajkadam im  using php (from my server) i can recive de notification on my device, the title and body are showing correctly, but icant do vibrate or sound my phone, this is my code:
 $msg = array
          (
		'body' 	=> 'body prueba',
		'title'	=> 'title de prueba',
		'vibrate' => true,
		'sound' => true
          );
is your php code similar, its works for you??

**Comment by AsimNet** [comment]
guys how to send a notification with custom sound to both ios & android ?
they have different extensions.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by lben** [comment]
Hi, I am facing this exact same issue on android using cordova-plugin-firebase@0.1.25. How can I make the push pop up like the other notifications? Thank you
