### ISSUE TITLE
icon not displayed when drop down the slide on android , and can't change the icon

### ISSUE THREAD

**Issue by joesleiman** [arnesson/cordova-plugin-firebase#359]
I'm using cordova-plugin-firebase and trying to change the icon because it looks white square inside a dark circle.
when the notification comes, the icon looks good,  it's the default icon of the app but when I drop down the slide from top header bar of Android the icon looks white square inside a dark circle.
I'm trying this: 
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <!-- inherit from the holo theme -->
    <style name="AppTheme" parent="android:Theme.Light">
        <item name="android:windowDisablePreview">true</item>
    </style>
    <drawable name="notification_big">@mipmap/icon</drawable>
    <drawable name="notification_icon">@mipmap/icon</drawable>
</resources>
```
without understanding what it does , but not working
i;m using ionic3.3

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
