### ISSUE TITLE
how to catch notifications in ios ?

### ISSUE THREAD

**Issue by santhoshscs** [arnesson/cordova-plugin-firebase#36]
The wiki shows onNotificationOpen (Android only) 
does this means there is no provision to catch notifications in ios ?

**Comment by robertarnesson** [comment]
the ios side needs implementation. I'll take a pr if you want to have a go

**Comment by robertarnesson** [comment]
made a first pass on this.

you can install the plugin from github master to test it.

```
<plugin name="cordova-plugin-firebase" spec="https://github.com/arnesson/cordova-plugin-firebase" />
```

**Comment by benny1308** [comment]
Hi Robert,
I just tried the onNotificationOpen-Method on my iPad, unfortunately it doesn't seem to work. I removed the plugin, installed it via plugin tag in config.xml (see above). Added the following after getInstanceId:
`window.FirebasePlugin.onNotificationOpen(function(success){console.log(success);},function(error){console.log(error);}`
If I have the app active (foreground), nothing happends during push, if the app is in background, i get the standard ios notification, tap on it, app opens, but the onNotificationOpen is never called :-(. 
I really like your plugin, but I can only use it with this functionallity. How can I help you? 
The other firebase plugin cordova-plugin-fcm  implements the onNotification-Method very well, maybe you could have a look at its implementation :-).
Thanks for your work @robertarnesson!
Ben

**Comment by robertarnesson** [comment]
@benny1308 thx for the feedback. there are additional work in 8316e05c040665f6badf213b1220b324b54ad82f, I have not been able to test it fully myself though. Feel free to have a go again if you have time to do it

**Comment by benny1308** [comment]
Hey @robertarnesson, I tested it again, but without success, same behaviour like last time. The onNotificationOpen Method is not called. No matter if the app is active or in background. But I'm sure, you're close :-) keep trying, I'll test it for you.
Ben

**Comment by robertarnesson** [comment]
there was indeed some more work needed, but I got it working on my device now

**Comment by c4software** [comment]
@robertarnesson With the current git version, if i didn't register an notification callback handler the app crash here : 

```
[self.notificationBuffer addObject:userInfo];
```

**Comment by benny1308** [comment]
Hey, work's great for me. Haven't testet the issue @c4software reports, because I always have to register the callback.
Thanks!

**Comment by robertarnesson** [comment]
@c4software should be fixed now!

**Comment by benny1308** [comment]
@robertarnesson now it seems that the android callback onNotificationOpen is not working anymore, could please someone verify? Should i open a new issue?
The callback is never called, no matter if the app is active (foreground) or in background. I receive the notification, but e.g. on tap, the app opens, but onNotificationOpen isn't called :-(.
Ben

**Comment by robertarnesson** [comment]
@benny1308 thats odd, that code has not changed. does it work if you use latest release from npm instead of git master?

**Comment by robertarnesson** [comment]
closing this as onNotificationOpen for ios was integrated in 0.1.11. If there are issues open a new ticket
