### ISSUE TITLE
Analytics doesn't work

### ISSUE THREAD

**Issue by mushketer888** [arnesson/cordova-plugin-firebase#362]
All works fine. For example push notifications works.
But any Analytics stuff doesn't. For example: setScreenName doesn't work and analytics doesn't appear after few days at all!

I must add my app to Google Analytics? Firebase Analytics can't function in stand alone mode without Google Analytics?
Thanks

**Comment by jaybowman** [comment]
I'm able to capture analytics in android app, still testing for IOS
Are you able to get push notification to ios device? I haven't been successful with this but push does work for android.
I have all my GA commented out. just using firebase analytics.

**Comment by mushketer888** [comment]
I use only Android. I can only receive push notifications.

**Comment by ivanov84** [comment]
Also I cannot get notifications on ios. Also tried to send from dashboard with token that I got with this plugin - still failed:
https://console.firebase.google.com/project/xxx-project/notification

But android gets notifications.

**Comment by dobbinx3** [comment]
@mushketer888 i've never used the `setScreenName` method, but try to use the `logEvent` method just to see if the event appear in firebase analytics.

@ivanov84 did you update your credentials (.p12 file or .p8 file) to the firebase console?

**Comment by ivanov84** [comment]
@dobbinx3 Yes, I uploaded .p8 credentials. I think that Google forces people to switch to a raw product... And unfortunately I can not create a new UA for a new application.

**Comment by ivanov84** [comment]
Solved! 😁
I granted permissions via cordova-plugin-local-notifications
and when I changed granting permissions on this.firebase.grantPermission(); - started to work! 😏

**Comment by dobbinx3** [comment]
@ivanov84 nice to hear that. Cya

**Comment by kedai** [comment]
> I granted permissions via cordova-plugin-local-notifications
and when I changed granting permissions on this.firebase.grantPermission()

Could you elaborate? grantPermission() is only for ios, aren't you developing android?

i've this running for a month on android and still nothing on firebase console :(

**Comment by mushketer888** [comment]
@kedai Same situation!

**Comment by robertarnesson** [comment]
if you use logEvent together with the free version of firebase you can only log these standard events: https://support.google.com/firebase/answer/6317498?hl=en&ref_topic=6317484

to log custom events you have to enable billing and enable bigquery, then you can see all your events in bigquery

**Comment by kedai** [comment]
@robertarnesson
i only use select_content. and i do enable billing. 
alas still no log :(

**Comment by mushketer888** [comment]
@robertarnesson 
I dont use any events at all. I dont see any analytics: users per month, day etc. In Firebase Web Console

**Comment by stephdgenius** [comment]
I Download my GoogleService-Info.plist on Firebase and paste it inside on platform/ios/AppName/Resources folder and then in the second folder with the same name (Resources). Then I rebuilt the app.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
