### ISSUE TITLE
What is the minimum ios build version required?

### ISSUE THREAD

**Issue by jaybowman** [arnesson/cordova-plugin-firebase#363]
Plugin works good for android. But i'm trying to build ios also. What is the minimun hardware ios version required? I have my deployment target set to 9.3 and when i install on a 9.3.5 ipad the app stalls before the home page with no errors. (see attached log). when i install on 10.3 device the app works fine, almost, notification still don't work. but i hope the analytics do.
![villages app log](https://user-images.githubusercontent.com/4990535/28638412-cd363fae-7212-11e7-9953-a0bee86b2af9.PNG)

**Comment by premtemp** [comment]
Hello,
Were you able to get the plugin to work ? I am having the same issue..Nothing is getting recorded in firebase debug screen,, I am just  trying to see the default analytics data
 The android version works but not iOS

**Comment by jaybowman** [comment]
Yes, During my testing i found that i needed to use cordova-ios vesion 4.2. and i removed other plugins one at a time to see if any where causing conflicts. Its been over 6 months, I'm having a time remembering what exactly fixed it.  Update other plugins one at a time and test. I'm thinking cordova-plugin-geolocation was causing a conflict. But definitely when i tried to use the most current cordova ios version it did not work. So i stuck with 4.2 . Hope this helps.
