### ISSUE TITLE
FirebasePlugin.unregister() is not working

### ISSUE THREAD

**Issue by merbin2012** [arnesson/cordova-plugin-firebase#367]
**window.FirebasePlugin.unregister();** this is not working, this will display the "function not found error". I want to unsubscribe from all subscribed topic. Please help me

**Comment by ioliynichenko** [comment]
+ I have "SERVICE_NOT_AVAILABLE" on fail callback

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue

**Comment by neil-pan-s** [comment]
I have "SERVICE_NOT_AVAILABLE" on fail callback, too!
