### ISSUE TITLE
Remote Config - getValue() not working on android

### ISSUE THREAD

**Issue by rockrgrrl** [arnesson/cordova-plugin-firebase#368]
this.firebase.getValue('CONTACT_DATA', '')
  .then((data) =>  {
      console.log('CONTACT_DATA.....', data);
  });

I am having an issue with the above code when running on android. I have my CONTACT_DATA set in the firebase console. I am running fetch() and activateFetched() as well. When I run on iOS, the above data (the remote config value that I set in the firebase console) is logged out as expected. However on android, no data is logged out. The string 'CONTACT_DATA' from above is logged out, but no remote config value.

**Comment by bytekode** [comment]
It's working for me. Try like this
window.FirebasePlugin.fetch(600, new function () {
        window.FirebasePlugin.activateFetched(function (activated) {
            window.FirebasePlugin.getValue(YOUR_KEY, function (value) {
                alert("FirebasePlugin.getValue " + value);
            }, function (error) {
                console.log("FirebasePlugin.getValue error " + error);
            });
        }, function (error) {
            console.error(error);
        });
});

**Comment by rockrgrrl** [comment]
Yeah, I got it to work as well. I was trying to use the ionic wrapper initially, but there seems to be an issue with that. Once I used the plugin straight up, it worked as expected. Thanks.

**Comment by bok04** [comment]
Has anyone got this to work on iOS? I tried that code but always receive null.

**Comment by remisture** [comment]
@bytekode Why `new function () {}` vs. `function() {}`?

**Comment by samarthagarwal** [comment]
@rockrgrrl, can you please share you code that worked in Ionic?

**Comment by bytekode** [comment]
@remisture LOL! It's because I write JAVA code a lot. UPDATED!

**Comment by rockrgrrl** [comment]
@samarthagarwal Sure. Here it is:
`window['FirebasePlugin'].fetch(3600, (result) => {
      window['FirebasePlugin'].activateFetched((activated) => {
        // do something here
      }, (error) => {
        const message = 'There was an error getting the contacts.';
        const toast = this.toastCtrl.create({
          message: message,
          duration: 3000,
          cssClass: 'toast-danger',
        });
        toast.present();
      });

    }, (error) => {
      const message = 'There was an error getting the contacts.';
      const toast = this.toastCtrl.create({
        message: message,
        duration: 3000,
        cssClass: 'toast-danger',
      });
      toast.present();
    });`

**Comment by Bearbite** [comment]
Same bug here. Thank you rockrgrrl for the solution its working for me.

**Comment by Thomasbehan** [comment]
In order for the getValue function to work properly you are required to set a default value see firebase loading strategies => https://firebase.googleblog.com/2017/01/firebase-remote-config-loading.html

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by nivemaham** [comment]
@Thomasbehan I tried setting default values using the `setDefaults` API. Still does not work. So I think there is an issue with the firebase-native implementation. 
```
    this.firebase.setDefaults( {
      projectId: 'DefaultProject'
    }).then( () => {
      alert("Default set")
      this.firebase.fetch(60).then(() => {
          this.firebase.activateFetched().then((value) => {
            alert('Activated' + value)
            this.firebase.getValue('projectId').then((proj) => {
              alert('proj' + proj)
            })
              .catch((err) => {
                alert('getvalue err' + err)
              })
          })
            .catch((error2) => {
              alert('activation error' + JSON.stringify(error2));
            });
        }
      );
      });
```
I get success for setDefaults and nothing afterwards. On the other hand, following this and other issues, it is possible to fetch the remote config without the native plugin implementation as mentioned by @rockrgrrl
