### ISSUE TITLE
Error at launch - invalid plist

### ISSUE THREAD

**Issue by Hurinj** [arnesson/cordova-plugin-firebase#37]
Hello,

I downloaded the plist in my firebase project and put it in my root folder.
When I launch my app I get : 

` Terminating app due to uncaught exception 'com.firebase.core', reason: '[FIRApp configure] could not find a valid GoogleServices-Info.plist in your project. Please download one from https://console.firebase.google.com/.'`

Why could it be invalid ?

**Comment by robertarnesson** [comment]
did you run cordova prepare after putting GoogleServices-Info.plist into the project?

**Comment by Hurinj** [comment]
I tried, it still doesn't work

**Comment by Hurinj** [comment]
The message is now : HelloCordova[2207:612538] Could not locate configuration file: 'GoogleService-Info.plist'.

**Comment by robertarnesson** [comment]
are you using phonegap build?
