### ISSUE TITLE
Cannot read property 'onTokenRefresh' of undefined

### ISSUE THREAD

**Issue by dcuesta1** [arnesson/cordova-plugin-firebase#372]
I have used the plugin before, now that I am trying to use it in a new and fresh project i get this error. I am probably missing something very basic I just can't recall.

Tried adding: 
`<plugin name="cordova-plugin-firebase" spec="0.1.22" />`

to the config.xml file. before adding a platform and building/serving

also, tried installing using the cordova cli, it always seems to install properly but when i go on the console for chrome "window" doesnt show "FirebasePlugin" which tells me its definetly missing.
O yea, I also added the google-services.json file from firebase in the root folder.

Thanks!

**Comment by robertarnesson** [comment]
it wont be available until after deviceready has been fired. see http://cordova.apache.org/docs/en/7.x/cordova/events/events.html#page-toc-source

if you have other js errors or you try to run an ios/android build in the browser (instead of a browser build) it may never fire
