### ISSUE TITLE
Android Uninstall / Install issue

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#374]
Just uninstalled the 0.1.21 and installed 0.1.23.

During the install of 01.23 got the following error:

BUILD SUCCESSFUL

Total time: 29.709 secs
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebase': CordovaError: Uh oh!
"C:\Users\rpo\dev\myApp\platforms\android\res\values\colors.xml" already exists!

Looks like the uninstall process doesn't remove the 'colors.xml' file...or the new install doesn't account for one that may already exist.  I removed mine then copied it back after the install/compile was complete.

**Comment by robertarnesson** [comment]
There is not much we can do to fix this, unless cordova introduces some kind of optional or replace tags that we can use inside plugin.xml.

The platforms folder is a build artifact folder and should really be cleaned (removed) between builds anyway. there is also the cordova clean command which I think does something similar

**Comment by bhavinwebdesk** [comment]
Hello @robertarnesson ,

I am facing same problem when installing plugin first time.
can you change colors.xml to cv_plugin_colors.xml or something?
Till cordova can fix this.

Thanks,
Bhavin
