### ISSUE TITLE
Does this plugin have a full client-side capabilities for push notification ?

### ISSUE THREAD

**Issue by faustoct** [arnesson/cordova-plugin-firebase#380]
@robertarnesson  Looking for alternative to https://github.com/phonegap/phonegap-plugin-push since it both plugins conflict. Does it work like plugin phonegap-plugin-push im terms of features ?

**Comment by faustoct** [comment]
It covers ?
- Sending Upstream
- Device Group Messaging
- Topic Messaging
- Receive Messages
- Receive Messages

**Comment by robertarnesson** [comment]
It supports all of those except upstream messaging

**Comment by faustoct** [comment]
@robertarnesson does any idea when to support upstream messaging?
