### ISSUE TITLE
How to use collapse_key ?

### ISSUE THREAD

**Issue by faustoct** [arnesson/cordova-plugin-firebase#385]
@robertarnesson any suggest of how to use collapse_key parameter on ios and android ?

Everytime I send a push notification the app has a new entry which is very annoying. How can I keep it as single one, updating the existent notification ?

Thanks in advance !

**Comment by zgluis** [comment]
There is a limit of 4 collapse_keys for app, so, I prefer to use the "tag" param, please read the [docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref)

**Comment by faustoct** [comment]
beautiful, I'm gonna try it. Any progress update here.

**Comment by faustoct** [comment]
@zgluis It's creating new a notification using tag
here is push code 
`options = { data:{title: 'myApp', text: 'notif', tag: "1"}, tag: "1" }`
`response = fcm.send_notification([ids_here],options)`

**Comment by zgluis** [comment]
Here is how I do it: 

> { 
  "data": {//params taken by the OS
    "title": "SomeTitle",
    "info" : "Content"
  },
  "notification" : {//params taken by the app
      "tag" : "myTag",
      "title" : "SomeTitle",
      "body" : "SomeContent",
      "color" : "#1f295d",          
      "sound": "default",
      "icon" : "notification_icon"
    },
  "to": "f8oq0...-o5",
  "priority" : "normal"
}

**Comment by faustoct** [comment]
@zgluis r u using any ruby lib? I'm using https://github.com/spacialdb/fcm
I'll have a look thank you

**Comment by faustoct** [comment]
hum, just got it working fine. here my test code hope someone having the same problem, thanks @zgluis 

````
fcm.send(ids,{
        data: {
        title: "SomeTitle",
        info: "Content"
        },
        notification: {
        tag: "myTag",
        title: "SomeTitle",
        body: "SomeContent",
        color: "#1f295d",
        sound: "default",
        icon: "notification_icon"
        },
        "priority": "normal"
        })
````

**Comment by faustoct** [comment]
@zgluis quickly suggestion of how to break the message in multiline text ?

**Comment by zgluis** [comment]
@faustoct I cannot test it right now but I think you can use "\n" to create a line break

**Comment by faustoct** [comment]
@zgluis  the first thing I tried. I'll take a look and just update here .

**Comment by zgluis** [comment]
Yep, I checked an old code and I create some line breaks with "\n".

**Comment by faustoct** [comment]
Seems \n solve it in some circumstances the same \n puts the messages beside ignoring it. thnx

**Comment by faustoct** [comment]
@zgluis sounds stupid but it was collapsed !
