### ISSUE TITLE
Can't Subscribe to a topic

### ISSUE THREAD

**Issue by adminanto** [arnesson/cordova-plugin-firebase#386]
Hi, Everyone.

I've tried to implement this plugin. It has been able to get the registration ID. 
But unfortunately it can't subscribe to a topic. 

Event hardcoded this function right after register token is doesn't work:
 `FirebaseMessaging.getInstance().subscribeToTopic("news");`

Maybe you guys have any idea about this.  
Any help would be really appricated. 
I just can't figure it out why.

**Comment by JohnScottMcNerney** [comment]
To verify your topic is active, on the Firebase Console website:

1. select your APP
2. Go to Notifications Page (under GROW on left)
3. Select "NEW MESSAGE" button
4. Change Target to "Topic"
5. Type in "n" in "Enter a Topic" to see all registered topics that start with the letter "n" in your APP.

**Comment by adminanto** [comment]
Ohh, okay. 
You gave me an idea. 
There is a one day delay before a topic can be targeted as target message and of couse one delay also before a new topic creation. 

Thanks
