### ISSUE TITLE
Appodeal plugin VS Cordova Firebase Plugin PROBLEM

### ISSUE THREAD

**Issue by Netpllay** [arnesson/cordova-plugin-firebase#387]
I have a problem on use the plugin appodeal. My error is:

Note: C:\xxxxxx\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java uses or overrides a deprecat
ed API.
Note: Recompile with -Xlint:deprecation for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithJarMergingForDebug FAILED

BUILD FAILED

Total time: 1 mins 26.085 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/z
zcq.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\xxxxxxxx\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java uses or overrides a deprecat
ed API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/z
zcq.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by FaynePerera** [comment]
Same here.

**Comment by robertarnesson** [comment]
remove the google/android/gms in either this plugin or the other
