### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by KunalPradhan415** [arnesson/cordova-plugin-firebase#389]
I have been trying to use the plugin with an ionic1 project. I followed the steps that were given at
http://ionicframework.com/docs/native/firebase/         and when I try to launch the iOS app it will not pass the splash screen. The Xcode errors are
**The default Firebase app has not yet been configured. Add [FIRApp configure] to your application**  and **the GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid.**
As far as I am aware we do not need to manually add [FIRApp configure to the project], and adding it in AppDelegate has not helped either. As for the second error the GoogleService_Info form has all the right information and is in the main app directory as specified. 
Has anyone else has an issue with running the plugin on iOS?

**Comment by soumak77** [comment]
this is fixed by re-merging https://github.com/arnesson/cordova-plugin-firebase/pull/328

**Comment by petru224** [comment]
+1, doesn't work anymore

**Comment by PixsideGames** [comment]
doesn't work anymore again

**Comment by briantobo** [comment]
+1 same problem here

**Comment by bunday** [comment]
i suggest you do the following 

Open Firebase 
Add iOS to your App
Enter your App Name
Enter your BundleID (com.something.something)
Download your GoogleService-Info.plist
Paste it inside your platform/ios/AppName/Resources folder
Copy the content also and paste in your platform/ios/AppName/Resources/Resources
Re Build your App. 
It should work perfectly, 

Drop a message if anything happens
cheers

**Comment by soumak77** [comment]
An easier fix is to just downgrade to version `0.1.22`
