### ISSUE TITLE
Xcode Rejects Section of Code for iOS 10

### ISSUE THREAD

**Issue by bunday** [arnesson/cordova-plugin-firebase#395]
In FirebasePlugin.m

the section for iOS 10

UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert|UNAuthorizationOptionSound|UNAuthorizationOptionBadge;
	[[UNUserNotificationCenter currentNotificationCenter]
		requestAuthorizationWithOptions:authOptions
	 				  completionHandler:^(BOOL granted, NSError * _Nullable error) {
			
			if ( ![NSThread isMainThread] ) {
				dispatch_sync(dispatch_get_main_queue(), ^{
					[[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
					[[FIRMessaging messaging] setRemoteMessageDelegate:self];
					[[UIApplication sharedApplication] registerForRemoteNotifications];
					
					CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus: granted ? CDVCommandStatus_OK : CDVCommandStatus_ERROR];
					[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
				});
			}
			else {
				[[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
				[[FIRMessaging messaging] setRemoteMessageDelegate:self];
				[[UIApplication sharedApplication] registerForRemoteNotifications];
				CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
				[self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
			}
	  }
	];
	
has the following error:

Use of undeclared identifier 'UNAuthorizationOptions'
No known class method for selector 'currentNotificationCenter'
No known instance method for selector 'requestAuthorizationWithOptions:completionHandler:'
Use of undeclared identifier 'authOptions'

**Comment by robertarnesson** [comment]
are you using xcode 8?

**Comment by bunday** [comment]
i'm using Xcode: Xcode 7.3.1 Build version 7D1014

**Comment by robertarnesson** [comment]
you need xcode 8 ;)
