### ISSUE TITLE
didn't get push notification

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [arnesson/cordova-plugin-firebase#396]
When I try to get token It's throwing me error in error function.
Default FirebaseApp is not initialized in this process. Make sure to call FirebaseApp.initializeApp(Context) first.

My code:
function getdeviceToken(){
            window.FirebasePlugin.getToken(function (token) {
                // save this server-side and use it to push notifications to this device
                console.log(token);
                if(!token){
                    getdeviceToken();
                }
                localStorage.setItem('device_id', token);                
            }, function (error) {
               console.log(error);
            });
        }

**Comment by Krishna25Vrinsoft** [comment]
can anyone please help me?

**Comment by soumak77** [comment]
iOS is broken in version 0.1.23 (https://github.com/arnesson/cordova-plugin-firebase/issues/389).  Revert to using version 0.1.22 until it is resolved.

**Comment by robertarnesson** [comment]
fixed in 0.1.25
