### ISSUE TITLE
My application does not start

### ISSUE THREAD

**Issue by stephdgenius** [arnesson/cordova-plugin-firebase#399]
Hello, I try to compile my ionic application for iOS but every time I receive this error :
`[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
Aug 20 14:49:21 stephdgeniusMBP Zero Code[11607]: [Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
Aug 20 14:49:21 stephdgeniusMBP Zero Code[11607]: *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.`

This also prevents the application from getting started. What can I do to solve this problem ?

**Comment by stephdgenius** [comment]
I Download my GoogleService-Info.plist on Firebase and paste it inside on platform/ios/AppName/Resources folder and then in the second folder with the same name (Resources). Then I rebuilt the app.

**Comment by plul** [comment]
Did that fix the issue for you?

**Comment by nikmartin** [comment]
I'm also getting this, and placing the plist file in the Resources folder does NOT solve the issue for me. It works properly on Android

**Comment by robertarnesson** [comment]
what version of cordova are you using?

**Comment by igorbt** [comment]
I'm also having this issue with cordova 7.0.1. It seems that after `cordova build ios` it just copy an empty GoogleService-Info.plist. It worked for me to manually copy afterwards this file to the `platforms/ios/<appname>/Resources/` and `platforms/ios/<appname>/Resources/Resources`.

**Comment by robertarnesson** [comment]
try again now with latest changes from master

**Comment by inidona** [comment]
Hi, downgrade your cordova-plugin-firebase to 0.1.22, in latest 0.1.23 was a bug in copying GoogleService-Info.plist

**Comment by esmiralha** [comment]
It fixes the issue for me. Can you make a release to NPM?

**Comment by PrithiviRajG** [comment]
@robertarnesson how to get the latest changes from the master?

**Comment by ourarash** [comment]
I have the same issue. I copied GoogleService-Info.plist to both `platforms/ios/<appname>/Resources/` and `platforms/ios/<appname>/Resources/Resources`.  I also installed the plugin by this command:

`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --save`

**Comment by lionking917** [comment]
Hi, Robert.
When using your plugin, the android works fine.
But while running on ios real device, I got this error.

"<Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8."

I have googled about this but I can't find exact solution yet.

Can you guide me more about this issue?

**Comment by jkhask** [comment]
I'm having same issue as lionking97. It prevents my app from getting past the splash screen for iOS

**Comment by soumak77** [comment]
What version of the plugin are you using?  And did you follow the [setup](https://github.com/arnesson/cordova-plugin-firebase#setup) to add the firebase config files?

**Comment by jkhask** [comment]
I have tried using the latest 1.0.4 and also the older 0.1.25. My plist file is correct and in the right spots. This was working before but now it isn't. I checked the APN certificates and everything. I have added sentry error logging to my app, but I don't think that would have caused this.

**Comment by jkhask** [comment]
Actually my bad. It was sentry, but I still did see the error from this issue in the console. Regardless, it is working.

**Comment by vc-hitesh** [comment]
I am also facing similar issue like this. But in my case if i'm installing cordova-plugin-firebase-invites 
firebase auth is not working returning below error.
2018-05-26 15:23:45.333437+0530 The Xavier's Connect[5753:2255300] 4.13.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2018-05-26 15:23:45.344879+0530 The Xavier's Connect[5753:2254784] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:

Any suggestion to resolve this issue?

**Comment by traxtrox** [comment]
I was able to solve the problem adding the plugin [https://github.com/arnesson/cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) and downloading the GoogleService-Info.plist as it is indicated
