### ISSUE TITLE
subscribe to topics

### ISSUE THREAD

**Issue by BugsBunnyBR** [arnesson/cordova-plugin-firebase#4]
Hi, would it be possible to use this plugin to subscribe/unsubscribe to FCM topics?
Thanks

**Comment by robertarnesson** [comment]
Right now you can do it server side - https://developers.google.com/instance-id/reference/server

Its very easy to implement in the client too, I just havent got to it yet. see https://firebase.google.com/docs/cloud-messaging/topic-messaging#subscribe-to-a-topic-with-ios

**Comment by BugsBunnyBR** [comment]
Thanks, but I know nothing about iOS development, so I will keep an eye at this project.
Keep the good work! :-D
