### ISSUE TITLE
SIGABRT on iOS

### ISSUE THREAD

**Issue by thomas-alrek** [arnesson/cordova-plugin-firebase#401]
This plugin was working fine for me, until 2db18e6e0f377b2f9b1be1e37240bdc58cc33411

Now iOS builds crashes immediately on splash screen with a SIGABRT

**Comment by robertarnesson** [comment]
try again with latest

**Comment by jhcruz** [comment]
Hi!!
I have the same problem :/, it only works when i copy manually the Google file to
platforms/ios/" + name + "/Resources/Resources/GoogleService-Info.plist..

**Comment by vzts** [comment]
Same issue here with
`"cordova-plugin-firebase": "^0.1.25"`

Any updates?

**Comment by vzts** [comment]
For me, it was a mistake with the firebase settings.
It was accidentally removed when arranging the project.
Consult the Installation section of README.
Properly adding the required configuration files & `prepare` fixed the problem.
