### ISSUE TITLE
Expose API to disable analytics when Test Lab Pre-Launch Report

### ISSUE THREAD

**Issue by guyman** [arnesson/cordova-plugin-firebase#402]
Firebase itself allows to disable analytics when the app runs in a pre-launch report. 
This is the code:

```
mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);

    String testLabSetting =
            Settings.System.getString(getContentResolver(), "firebase.test.lab");
    if ("true".equals(testLabSetting)) {
        //You are running in Test Lab

        mFirebaseAnalytics.setAnalyticsCollectionEnabled(false);  //Disable Analytics Collection
    }
```

The plugin doesn't expose this capability so pre-launch reports of the Google Play Store contaminate the analytics data.

**Comment by robertarnesson** [comment]
I can integrate this if you create a PR with the changes

**Comment by Pl4yeR** [comment]
This addition would be interesting too for disabling analytics for privacy minded users (ie, option in settings).

I may try to expose it.

**Comment by msimkunas** [comment]
I've forked the plugin and exposed the `setAnalyticsCollectionEnabled` method to the API: https://github.com/msimkunas/cordova-plugin-firebase/commit/95220fdcaf9003a6c01e58816c31be441cded715

Please note that the above changes have **not** been tested. I'm neither a Java nor an Objective-C developer and have added the additional code using  the `setUserId` method and the [Firebase docs](https://firebase.google.com/support/guides/disable-analytics) as a reference.

**Comment by robertarnesson** [comment]
@msimkunas you can create a PR with this change for integration

**Comment by briantq** [comment]
@soumak77 I believe this is already implemented with the setAnalyticsCollectionEnabled API that is in the documentation.

**Comment by soumak77** [comment]
We should add an option to disable analytics via a variable so that users can enable/disable it based on their environment. This request is captured via https://github.com/arnesson/cordova-plugin-firebase/issues/843

**Comment by briantq** [comment]
@soumak77 If that is captured in a different issue and the APIs that were requested in this issue are already present can we close this guy?

**Comment by carlos-mg89** [comment]
Is this valid for Firebase Test Lab reports and / or for Google Play Store Pre-Launch Reports?

Thanks in advance!
