### ISSUE TITLE
No recive notification on killed app

### ISSUE THREAD

**Issue by davidgalarza** [arnesson/cordova-plugin-firebase#408]
Iam able to ecive notification when the app is in foregroun but if i kill the app from the task manager i dont recive any notification.

`{ "notification": {
        "title": title,
        "body": message,
        "sound":"default",
        "show_in_foreground": true
      },
        "wasTapped":false,
        "to" : deviceId,
        "priority":"high", 
        "restricted_package_name":"shops.blipclub.com"
      }
    )`

**Comment by henrychavez** [comment]
I have the same problem in android. I didn't test it on iOS. 

The version of the plugin is cordova-firebase-plugin@0.1.21

**Comment by davidgalarza** [comment]
Apparently it just does not work on my phone (Huawei P8), I tested it on other android and it worked perfectly.

**Comment by epoplavskis** [comment]
I have the same problem on ios (tested on iphone 6 and 7) but on my android it works fine.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
