### ISSUE TITLE
Notification receive in but just hide in status bar.

### ISSUE THREAD

**Issue by kirajhpang** [arnesson/cordova-plugin-firebase#409]
Hi guys, thanks for contributing this great library, it is easy and nice to use. But I do have some question to ask.

Now my situation is I do try set priority setting to high/max/1 in android

1. When Apps in background,
    1. receive notification, no flip out in the screen, it just hide in status bar, but got sound. 
    2. user tap
    3. trigger `onNotificationOpen()`, show `receive in background`
When 
2. Apps in foreground, receive notification
    1. nothing from notification, no flip out, no in the status bar, but trigger `onNotificationOpen()`  show`receive in foreground`

My question is, is that a right way to deal with android notification? Because it seem like scenario 1 should be show in **flip/expanded notification** no matter in any place of android right? While I do appreciate the call back is wrong but when there is no flip out, user doesn't know there is urgent right?

Then come the scenario 2, apps also still need show flip even when user is using the apps right? so that user know there is urgent to do some action. If there is only a call back being trigger, what should I do next? 

I no very familiar with android notification setting/UX, anyone has suggestion?

**Comment by lionalex** [comment]
I've the same problem, have anyone some fix?

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
