### ISSUE TITLE
error: cannot find symbol areNotificationsEnabled

### ISSUE THREAD

**Issue by floydus** [arnesson/cordova-plugin-firebase#416]
Output from cordova run android
![screen shot 2017-09-02 at 6 01 33 am](https://user-images.githubusercontent.com/19679654/29994721-3a566696-8fa4-11e7-8840-ca4d3bc28901.png)

Must be related to some SDK versioning issue, but my sdk is up to date I believe.
Here are my current SDK versions.
![screen shot 2017-09-02 at 4 31 29 am](https://user-images.githubusercontent.com/19679654/29994705-e4fdfa06-8fa3-11e7-908d-086489560021.png)
I'm stuck since to long, first I installed cordova-plugin-fcm, wasn't working, switch to firebase plugin and still having issues.

**Comment by robertarnesson** [comment]
probably the android sdk (and not the tools). try to update to >5.0. closing this for now
