### ISSUE TITLE
Incompatibility with local notifications (iOS)

### ISSUE THREAD

**Issue by ThomasKientz** [arnesson/cordova-plugin-firebase#419]
Looks like there is an incompatibility with the plugin [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications)

Firebase plugin causes local notifications to cease triggering on iOS : https://github.com/katzer/cordova-plugin-local-notifications/issues/1373

It's may be due to the version of the firebase iOS SDK used by the plugin (used : 3.6 (september 2016), last : 4.1.1 (august 2017)). https://github.com/katzer/cordova-plugin-local-notifications/issues/1373#issuecomment-327192495

Any plan to update the sdk ?

**Comment by jorgemejia** [comment]
I have the same problem :( any solution for this ?

**Comment by GunslingerBara** [comment]
I am also experiencing this problem. Has anyone fixed this?

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
