### ISSUE TITLE
Receiving notifications on iOS 9 but not iOS 10

### ISSUE THREAD

**Issue by bellsaladin** [arnesson/cordova-plugin-firebase#420]
Hello,
I'm facing a problem with notifications, i'm a not a able to receive notifications only on iOS 10. 
XCode returns the following error when i run the app on iOS 10 device :

`<Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization.`

Did anyone solve this issue ?
Thanks.

**Comment by sebastian312** [comment]
I receive the same error on iOS 10( 10.3.3) . in iOS 9 and Android devices everything works fine. There's also no difference when using the plugin version 0.1.22, 0.1.23 or 0.1.24

**Comment by mathieu21** [comment]
I experience the same and still cannot find a solution to it.

**Comment by jskidd3** [comment]
Any luck finding a solution to this?

**Comment by kirajhpang** [comment]
I also facing similar issue with this. OS version 9.3 can receive, but 10.3 no receive and capture this in error log

```
2017-09-11 15:47:15.920352+0800 xxx[4891:1857825] [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
2017-09-11 15:47:15.921 xxx[4891] <Warning> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
2017-09-11 15:48:14.309268+0800 xxx[4891:1857603] Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}
```

**Comment by jjosef** [comment]
Any possibility upgrading to SDK 4.1.1 will help? Anyone tried this? If not I will give it a go.

**Comment by bellsaladin** [comment]
This issue might be caused by xCode i was using xCode 7. Now i use xCode 8 and my application can receive notifications on iOS 10+.
Please confirm it if this solves your problem.

**Comment by sebastian312** [comment]
I use xCode 8.3.3 and still can't receive notifications on iOS 10.*

**Comment by bellsaladin** [comment]
I use version 0.1.22 cordova-plugin-firebase. Check if you use 0.1.24 it's known to be not compatible with iOS 10 yet.

**Comment by kirajhpang** [comment]
@jjosef you mean which SDK? ionic-iOS? 

@bellsaladin I was use xCode 8 and no notification receive, I was suspect is because the connection from FCM to ASP take time to configure. But at the end, I was turn down this plugin and go for paid service, work well for me now so all platform.

**Comment by bellsaladin** [comment]
@kirajhpang jjosef suggested to change the Firebase SDK to 4.1.1. All i did for notifications to work on iOS 10 was switching back to cordova-plugin-firebase v0.1.22 and using xCode v8 instead of v7.

**Comment by wo-github** [comment]
@bellsaladin I have the same problem. On iOS 9 it works and I receive the message in window.FirebasePlugin.onNotificationOpen() function. On iOS 10 this function isn`t called and nothing happens.
Xcode Version is 8.3.3
plugin verison is now 0.1.22

**Comment by bellsaladin** [comment]
@wo-github i only tried notification while app is closed or in background so window.FirebasePlugin.onNotificationOpen() is not being used in this case. Didn't try foreground notifications yet.

**Comment by wo-github** [comment]
I make a update of cordova to 7.0 and update ios to 4.4
I receive now the data, if the app is open in the window.FirebasePlugin.onNotificationOpen() function.
The next problem is, I receive nothing, if the app is in background. Does someone has an idea what could be the problem?

**Comment by wo-github** [comment]
I analyze the behavior with Xcode. If I open the app the console shows:
Connected to FCM.
InstanceID token: ##########

And if I close the app to background, the console shows:
Disconnected from FCM

Could this be the problem? How could the app receive messages in backgroundmode?

**Comment by damianobarbati** [comment]
Cannot get this working on iOS 11
```
2017-10-05 22:42:45.262307+0200 adminify[3570:2011054] THREAD WARNING: ['FirebasePlugin'] took '15.776855' ms. Plugin should use a background thread.
2017-10-05 22:42:45.890781+0200 adminify[3570:2011054] InstanceID token: fNmcCeHa6hs:APA91bE28bXAzhLDXXhOnHX__e9gBzJKDTGWxkGoJ-pWjrh60Q_EyQM2XidwmzP575WfZgKWhM93QySt3R375qusHXfJCV5tC5xxtJTmbEDm8Gf1GoDiX8zHHzSrbZXpKlh3NDVoyqNn
2017-10-05 22:42:45.891773+0200 adminify[3570:2011054] Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}
2017-10-05 22:43:06.953268+0200 adminify[3570:2011054] THREAD WARNING: ['FirebasePlugin'] took '12.334961' ms. Plugin should use a background thread.
2017-10-05 22:43:22.510277+0200 adminify[3570:2011536] TIC Read Status [9:0x0]: 1:57
2017-10-05 22:43:22.510339+0200 adminify[3570:2011536] TIC Read Status [9:0x0]: 1:57
2017-10-05 22:43:23.296173+0200 adminify[3570:2011054] Disconnected from FCM
```

**Comment by gioramies** [comment]
@wo-github 
I'm having the same issue.
Console logs "Disconnected from FCM" when app goes to background.
Please help.

**Comment by ourarash** [comment]
Any luck with solving this issue? I also get this message and notifications don't work: 

> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by suresh-selvaraj** [comment]
Is this issue solved?

**Comment by bellsaladin** [comment]
@suresh-selvaraj @ourarash @gioramies @wo-github @sebastian312 @jjosef @jskidd3 @kirajhpang 
I had the same problem and to solve i did the following :
- was using _xcode 7_ updated it to _xcode 8_
- Downgraded cordova-plugin-firebase to _v0.1.22_ (which is the version i use actually)
- I checked the git commit with which i fixed this issue and i found these changes in the **plist** file set to true both  NSAllowsArbitraryLoads & NSExceptionAllowsInsecureHTTPLoads params

These changes are required to fix a known issue with iOS related to Apple's ATS (App Transport Security). Check the links below for more details. I hope this helps. 

**Sources :** 
https://developers.google.com/admob/ios/app-transport-security (Admob iOS10 problem & ATS)
https://www.techrepublic.com/article/how-to-migrate-to-https-using-app-transport-security-when-developing-ios-apps/

**Comment by gioramies** [comment]
Thank you @bellsaladin 

I only tested my problem on iOS 9. It was that the notification didn't arrive when the app was in background. To fix it I followed the Google FCM documentation: https://firebase.google.com/docs/cloud-messaging/ios/certs and now it works (only tested on iOS9)

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
