### ISSUE TITLE
Registed, Subscribed, but no Push on iOS.

### ISSUE THREAD

**Issue by christianwico** [arnesson/cordova-plugin-firebase#421]
*Using version 0.1.22*

I'm using this plugin in my Android and iOS app. On Android, it works absolutely fine. On iOS, the app definitely registers to Firebase and subscribes to the topics I need.

However, iOS just doesn't receive any notifications. It can successfully register tokens *(as per the debug console)* but it can't receive any notifications. Anyone?

**Comment by jskidd3** [comment]
Exactly the same problem. Have you had any luck resolving it?

**Comment by kirajhpang** [comment]
same issue, here is my detail

I using 
`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase`
register APN in firebase console, enable notification and remote push notification From Xcode, GoogleService-inf.plist also in platform/ios, everything seem working, but my onNotificationOpen doesn't work like my android. 

Nothing receive for my iOS

**Comment by christianwico** [comment]
@jskidd3 absolutely no luck yet. I'm seeing a lot of these topics all over Google. They all have no resolutions...

**Comment by christianwico** [comment]
Ok. I think I found a solution. It makes some sense, but it's also kinda silly...

First, **uninstall** the `cordova-plugin-firebase`:
```bash
ionic cordova plugin remove cordova-plugin-firebase
```

Next, **remove** the *iOS* platform:
```bash
ionic cordova platform remove ios
```

After that, re-install `cordova-plugin-firebase`, but for extra assurance, install only version `0.1.22`:
```bash
ionic cordova plugin add cordova-plugin-firebase@0.1.22 --save --save-exact
```

Then, grab a copy of your project's `GoogleService-Info.plist` from the *Firebase Console*. Once you have it, copy it to each of these two locations:
```text
your_project_root/platforms/ios/your_project_name/Resources/GoogleService-Info.plist
your_project_root/platforms/ios/your_project_name/Resources/Resources/GoogleService-Info.plist
```

Finally, open `your_project_root/platforms/ios/your_project_name.xcodeproj`. Once **XCode** is loaded up, go to the **Capabilities** section and enable `Push Notifications`. Once complete, *run your app*.

Should be fixed.

**NOTE: Add `sudo` when necessary.**

*(If it works and someone can explain, please do.)* Closing...

**Comment by kirajhpang** [comment]
I just drop from this package and use paid service solution, their work pretty well for receive and setup those configuration.

**Comment by wilfredonoyola** [comment]
Hi @christianwico , Could this work with the latest version (cordova-plugin-firebase@0.1.25)?
I will try it.
Thanks,

**Comment by christianwico** [comment]
@wilfredonoyola yes. It should. I just upgraded to to v0.1.25 about a month ago. Works like a charm.
