### ISSUE TITLE
getToken(function(token)... returns undefined

### ISSUE THREAD

**Issue by BeRMaNyA** [arnesson/cordova-plugin-firebase#422]
Hi, I'm having lot of issues trying to make this plugin works in android. 

I created an app in Google Firebase, I downloaded the google-services.json and I placed it into the root folder, I installed the plugin, I ran the app (in the simulator) and then when I run this command:

```
window.FirebasePlugin.getToken(function(token) {
  alert(token);
}, function(error){
  alert('Error!!!');
});
```
I just got a blank alert. 

What am I doing wrong?

**Comment by BulliteShot** [comment]
Your emulator needs some extra setup to support push notifications. Try installing on your phone and see if it works.

**Comment by kirajhpang** [comment]
if your token is blank, try reinstall your plugin with GitHub url 
`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase`

**Comment by neogero** [comment]
I found the same problem with this plugin under ionic2 and with the @kirajhpang solution works correctly, thanks!!!

**Comment by Makaveli17** [comment]
I have the same problem on android (not ios) . plugin version : 0.1.24. The google-services.json is well in platforms/android folder.  I've already try to reinstall plugin with GitHub url but without success :(

**Comment by kirajhpang** [comment]
@Makaveli17 do you receive token recently but suddenly blank?

**Comment by Makaveli17** [comment]
I received with the FCM-plugin  but i changed to firebase-plugin because i had a conflict between FCM plugin and goople-plus plugin. 
At start I had a problem with the google-services.json to 0 octet in  platform/android  so I copied directely the right file in, but no more success. (sorry for my english and thanks you for the help)

**Comment by c0bra** [comment]
Thank you, @kirajhpang!

**Comment by camtera** [comment]
@kirajhpang very helpful, thanks a lot.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by omeriko** [comment]
Hi guys, i've installed 0.1.25 yesterday, did exactly what the documentation says, and when i run the getToken: in the success handler, the token equals an empty string.
Android: Oreo (8.0), Xiaomi Mi A1 
cordvoa version: 8

**Comment by soumak77** [comment]
@omeriko version 0.1.25 is broken and we are still waiting for a new release (https://github.com/arnesson/cordova-plugin-firebase/issues/625)

**Comment by omeriko** [comment]
Ok,
Meanwhile which version is recommend to the community for use?
BTW, there is  a fix in one of the issue trackers: copying the app_id, and app_key from google-services.json to strings.xml, it works for me. It's a good idea to mention it in the installation documentation of version 0.1.25, at least until the new version comes out.

**Comment by Harha** [comment]
I'm getting this only with an android emulator using the 1.0.4 version of the plugin.

On real hardware the token is returned just fine.
