### ISSUE TITLE
iOS problem. setScreenName:screenClass: must be called after a view controller has appeared

### ISSUE THREAD

**Issue by MartynovMax** [arnesson/cordova-plugin-firebase#425]
Hi. I receive the following error in logs (in XCode) when the app calls method `window.FirebasePlugin.setScreenName('ScreenName')`:

```
<Warning> [Firebase/Analytics][I-ACS031003] setScreenName:screenClass: must be called after a view controller has appeared
```

It happens not every time. 
I have wrapped calling setScreenName to `setTimeout` function and now the problem appears not so often, but it's still here.

**INFO**
Ionic 1.7.16
Cordova 7.0.1
Tested on iPhone 5 iOS 10.3
Used most fresh commit of the plugin (`6afd92e48aa2a81d10a1d9e3732162b78f4ed724`)

Thanks

**Comment by NoorinHasan** [comment]
Where do you call setScreenName? It is supposed to be called in viewDidAppear. Having said that, I call it in viewDidAppear and still facing this issue, though putting it in viewDidAppear has fixed it for others.

**Comment by robertarnesson** [comment]
closing this for now. re-open if still a problem with the latest version of the plugin

**Comment by brianshepanek** [comment]
I'm having this same issue, using v1.0.2 of the plugin. Any other tips to get this to work?

**Comment by terminaltor** [comment]
Still getting this error using the latest commit :-/

**Comment by newuser44** [comment]
We still see this for our Ionic app.   We tried using different Ionic life cycles but nothing seems to work.  Do people not use this plugin to track pages/screen names?

**Comment by superarts** [comment]
Any reason why it's designed like this? To me, it makes sense that FirebaseAnalytics holds this information and read it in the swizzerling function.
