### ISSUE TITLE
Can't send notifications on iOS 10.3.3

### ISSUE THREAD

**Issue by vrabota** [arnesson/cordova-plugin-firebase#428]
Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}

In Xcode debugger, I see my push notification, but can't see it on iOS :(

Can someone help me?

**Comment by jjosef** [comment]
I think that plugin.xml may be missing this configuration, so be sure to turn them on manually in XCode:

```
    <config-file target="*-Info.plist" parent="UIBackgroundModes">
      <array>
        <string>remote-notification</string>
      </array>
    </config-file>
```

**Comment by robertarnesson** [comment]
closing this for now. re-open if still a problem with the latest version of the plugin
