### ISSUE TITLE
Cordova PlugIn Firebase for Hybrid Apps

### ISSUE THREAD

**Issue by analytics-jiten** [arnesson/cordova-plugin-firebase#429]
Hi Team,

First of all great work done.

I was trying to use Cordova Firebase Plugin for my hybrid application. This application based on ionic - cordova framework. So here is the list of questions/issues we are facing:

1. Is this plug-in is also work for Hybrid Applications ? Can we implement firebase analytics in hybrid application ?
2. If yes, then we are facing app kill/stopped issue while using this plug-in. 
3. We have installed this plug-in in our project.
4. We have added the google-services.json file in the app plugin folder as well as on root folder.
5. We have done the required changes in build.gradle as well

But the moment we run the project and launch the app then the same is getting closed/crashed.

Please help.

**Comment by JorgeTorres-BM** [comment]
Cordova version?
OS-device?

**Comment by analytics-jiten** [comment]
Hey Jorge,

Following are the complete details:
1) SDK version 
Android 26

2) Technology versions 
   node  4.2.1
   ionic 2.0.0
   cordova 5.3.3 
3) OS - Device
      Android
      Moto - E Mobile

**Comment by JorgeTorres-BM** [comment]
Please open the android platform-project and find the gradle.build from android, paste the content of defaultConfig {...}

**Comment by analytics-jiten** [comment]
Thanks Jorge,

I found the defaultConfig code in  build.gradle file under root folder which is "/my-project/platform/android/src/". 

Here is the content of default config -
defaultConfig {
        versionCode cdvVersionCode ?: Integer.parseInt("" + privateHelpers.extractIntFromManifest("versionCode") + "0")
        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
    }

Please go through the defaultConfig and help. Thanks in Advance

**Comment by JorgeTorres-BM** [comment]
this is my defaultConfig
defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        **applicationId privateHelpers.extractStringFromManifest("package")**

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }
    }
the app it's crashing because you need this var **applicationId**, you could try to run the app from android studio and inspect the log cat, during boot time you would see that its asking for applicationId

why its missing?: you need to update to cordova 7.0.1, I was having the same issue but on 6.5.0.
why the applicationId its needed?: its the id you use on firebase config.
could I edit the build.gradle?: no, its a file wich is automaticaly generated.
after the cordova update whats next?: delete the platform andorid and add it again !important.
you dont have android studio?: you only need log cat to inspect the missing var

**Comment by analytics-jiten** [comment]
Thanks Jorge for your help and support,

Quick questions:

1. Our application is built on java script using ionic + cordova so it won't be possible to run the same on Android Studio unless we change the platforms of the build or create a new build. Is there anything you would like to suggest for that ?

2. As you suggested that we need to update the cordova platform in our systems with latest of 7.0.1. So its more of a compatibility issue. Similarly, do we need to update any other systems like SDK Versions, Android SDK or ionic or node js platform ?

3. What if we don't have android studio ? Can we still get the log cat  ?
