### ISSUE TITLE
If directory for both ios and android is present then the hook part for android doesnt work

### ISSUE THREAD

**Issue by kingofest** [arnesson/cordova-plugin-firebase#430]
Hi,
I found a bug in the code. When the directories for both the **ios** and **android** are present in ionic cordova project then due to this code:

```
// Copy key files to their platform specific folders
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
} else if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}
```
the copy key part for android does not works as expected hence please change it to either
```
// Copy key files to their platform specific folders
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
} if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}
```

or check for which platform the command is for and then accordingly check the directory. 

**Please update the code so that no one in the future faces the same problem.**

**Comment by sebrojas14** [comment]
Is done, current code is:
`// Copy key files to their platform specific folders
  if (platforms.indexOf('ios') !== -1 && directoryExists(IOS_DIR)) {
    console.log('Preparing Firebase on iOS');
    copyKey(PLATFORM.IOS);
  }
  if (platforms.indexOf('android') !== -1 && directoryExists(ANDROID_DIR)) {
    console.log('Preparing Firebase on Android');
    copyKey(PLATFORM.ANDROID, updateStringsXml)
  }`

**Comment by marcoramires** [comment]
Nice! Thanks.

**Comment by marcoramires** [comment]
Installing 'cordova plugin add cordova-plugin-firebase@0.1.24 --save'

It looks like the bug has been re-introduced. However, the master branch seems to have it fixed.

Would you be able to update the Readme file (installation)please? Or if we always have to use the plugin using the master branch url.

// Copy key files to their platform specific folders
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
} else if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}

Cheers,
Marco
