### ISSUE TITLE
PhoneGap build

### ISSUE THREAD

**Issue by ahar** [arnesson/cordova-plugin-firebase#433]
Hi guys, 

Has somebody resolved and successfully build application using phonegap build? I placed my fork of this plugin to npmjs.com , but android build is failing with logs: 
Fetching plugin "****-firebase@~0.1.27" via npm
Installing "****-firebase" at "0.1.27" for android
Subproject Path: CordovaLib

**Comment by robertarnesson** [comment]
see the README
