### ISSUE TITLE
Notification get twice using FCM

### ISSUE THREAD

**Issue by santoshpati** [arnesson/cordova-plugin-firebase#439]

**Comment by jcyh0120** [comment]
I am facing this issue, too. Here's my phone screenshot. 
[screenshot](https://imgur.com/a/V9AB9)

**Comment by Ziv-Barber** [comment]
It's using the same token as other push notification plugins.
Use only one of them.
For example: I had this issue when I used this plugin's push notification and the https://github.com/phonegap/phonegap-plugin-push plugin. Both had the same token.
