### ISSUE TITLE
getInstanceId return null

### ISSUE THREAD

**Issue by harksin** [arnesson/cordova-plugin-firebase#44]
hello, 

I have used, this plugin : https://github.com/fechanique/cordova-plugin-fcm, and it works correctly.
But your plugin provides support for a more important part of Firebase system.
So I Try to migrate to your solution.

However, I cannot get the Firebase Token, function return "null", and I can't see any  error in DDMS.

Do you see where  can be the problem ?

**Comment by harksin** [comment]
OK , when there is no connection or when sender id is invalid, plugin return null.
I think the plugin should throw an error in this case.

do you agree ?

**Comment by robertarnesson** [comment]
the firebase sdk does not throw an error so I don't agree that the plugin should change the behavior and do that on its own.
