### ISSUE TITLE
iOS 11

### ISSUE THREAD

**Issue by ironbone** [arnesson/cordova-plugin-firebase#440]
Was this plugin tested on ios11? Somebody was able to get notifications there?

**Comment by brunosoaresds** [comment]
I have tested with IOS 11 (builded with xcode9) and it works! however, the first app open crashes after the user grant notification access. The permission was set and after that the app opens and works normally.

**Comment by Jeremlicious** [comment]
We get notification on iOS 9 & iOS 10 but not on iOS 11.
Swizzling is enabled (no setting), we get a FCM token. Seems that Firebase does not know the APNs token
I found issues that could be releated on iOS Firebase SDK.
https://github.com/firebase/firebase-ios-sdk/issues/254
https://github.com/firebase/firebase-ios-sdk/issues/314

We tried to copy the iOS SDK v4.4.0 instead of v4.0.0 inside this plugin but it does not work straight away
https://github.com/Loisirsencheres/cordova-plugin-firebase/commit/6c118fa8ac9900f69a948a5d97473b123bc7ceb9

Has anyone got Firebase notification on iOS 11 ?

**Comment by brunosoaresds** [comment]
@ironbone 
Yes, also when app is closed. All works fine, the only issue is in the first app open.

@Jeremlicious, you tried to use cordova IOS platform 4.5.1 and xcode 9?

**Comment by ironbone** [comment]
I just did some tests. The newest xcode, newest iOS, newest cordova, newest ionic.
When application is closed (not in background but not working at all) and I send a Data (only) Message I never obtain it when I open the application. Is I see it arives on the phone nut there is never called the function onNotificationOpen()
If the application is in foreground or backgroud it works ok.

**Comment by Jeremlicious** [comment]
We ended up by using phonegap-plugin-push + cordova-plugin-fcm it works.

**Comment by Cicciokr** [comment]
Hi, i use ios 11, and cordova-plugin-firebase version 0.1.25 with cordova-plugin-ionic 2.0.4.
In my case the iphone ask me to accept grant permission for push notification, i accept it. And the when i re open the app, it was blocked with no error message.. someone had the same problem?

**Comment by kyleamadio** [comment]
@Cicciokr Yes I have a similar issue - I get a token fine however nothing else happens

**Comment by Cicciokr** [comment]
Hi, maybe this can help you http://francescopantisano.it/complete-guide-ionic-3-firebase-cordova-plugin-firebase/  it's important the last point, to install the ios certs for send notification: https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by soumak77** [comment]
closing as resolved

**Comment by AFMiziara** [comment]
I was having this issue too, but it was only happening with iOS. On Android it was fine. I realised that I wasn't getting the token when connected with an iOS device even with the APN certs already configured. I just add this to make it work:
`window.FirebasePlugin.grantPermission();`
It seens that by default any iOS app is set to deny push notifications, so you have to grant permission it when the app initializes.

**Comment by campagna91** [comment]
@Cicciokr try to debug with device console, maybe there are some details logged.
i encountered a similar problem on my ios 11 relates to a GoogleService.plist problem but no one log in dev console of Safari (now called 'Safari Technologies Preview' wtf)

Hope it can helps
