### ISSUE TITLE
window.FirebasePlugin.getVerificationID errors

### ISSUE THREAD

**Issue by MrShakes** [arnesson/cordova-plugin-firebase#441]
- Firstly, NPM does not have this method so I had to install directly from this git using `cordova plugin add <git repo> --save --nofetch --noregistry`
- Secondly, upon using the `window.FirebasePlugin.getVerificationID` function, I got the error: `Invalid code`

System:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    Cordova Platforms : android 6.1.0 ios 4.5.1
    Ionic Framework   : ionic1 1.3.2

System:

    ios-sim : 5.0.8 
    Node    : v6.10.2
    npm     : 3.10.10 
    OS      : macOS Sierra
    Xcode   : Xcode 8.3.3 Build version 8E3004b

**Comment by emilianoglucero** [comment]
I have a similar Issue with window.FirebasePlugin.getVerificationID
It gives me a "Invalid Action" error message. But only on Android in iOS works well.

Any idea with this kind of problem?

**Comment by MrShakes** [comment]
None, will have to look at the code to understand it, a quicker way would be to determine the platform you're on and use `verifyPhoneNumber` for Android.

**Comment by nikmartin** [comment]
So, I searched the code and getVerificationID is only implemented in the iOS plugin. for some reason this plugin isn't being maintained very well. The Readme is incorrect.

**Comment by soumak77** [comment]
should be fixed by version 1.0.2
