### ISSUE TITLE
'Invalid Action' on window.FirebasePlugin.getVerificationID 

### ISSUE THREAD

**Issue by emilianoglucero** [arnesson/cordova-plugin-firebase#443]
Hello.
I have a Cordova proyect and I'm facing an issue with the window.FirebasePlugin.getVerificationID
It gives me an 'Invalid Action' message. This happens only on Android, in iOS works well.

I' been working with the https://github.com/jestcastro/cordova-plugin-firebase plugin with great results in the 0.1.22 version. But with the last update I get this error. And now with this plugin is the same.

Any suggestion? Thank you very much!

**Comment by derTuca** [comment]
For now, I think the best option would be to check whether you're running on Android or iOS and to use verifyPhoneNumber instead if you're running on Android.
