### ISSUE TITLE
TokenRefresh stalls app on iOs

### ISSUE THREAD

**Issue by d-fnc** [arnesson/cordova-plugin-firebase#445]
Hey everyone!

So i'm facing an issue here on iOs. Once the app is in the background for a few minutes, and it's opened up, the token need to be refreshed or something, and when that request doesn't go through properly, the app is unusable for like 30 seconds.
How can i avoid that? Is there a way for me to move the whole refreshing process into the background? As of now it completely blocks the further execution of the app.

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
