### ISSUE TITLE
UI API called from background thread Group, xcode 9 ios 

### ISSUE THREAD

**Issue by epetre** [arnesson/cordova-plugin-firebase#448]
<img width="444" alt="xcode error" src="https://user-images.githubusercontent.com/1010282/31456855-fd8f9cce-ae88-11e7-8730-ca61c9b11d81.png">

It seems to be related to ios 11.
[This issue](https://github.com/firebase/firebase-ios-sdk/issues/69) says it's fixed in Firebase SDK 4.2.0 and this plugin seems to be at 4.0.0.

Does this mean that this plugin doesn't support iOS 11 yet?

**Comment by robertarnesson** [comment]
sdk is now at 4.5.0

**Comment by askilondz** [comment]
With the latest version of this plugin `0.1.25` (assuming that has sdk 4.5)  I'm still getting this same UI thread warning. It causes my screen to go white until I touch the screen.
