### ISSUE TITLE
Phone Number auth with window.FirebasePlugin.verifyPhoneNumber

### ISSUE THREAD

**Issue by Abdelazziz** [arnesson/cordova-plugin-firebase#450]
I would like to implement phone authentication with ionic and gordova firebase plugin, so i did these steps, but not succeful sent on android device :
1 - configure my firebase project : 
Enable phone authentication, download google-services.json and place it root directory, generate SH1 key. (i followed all steps).
2 - configure firebase plugin :
i install firebase plugin https://github.com/arnesson/cordova-plugin-firebase, i install angularfire2 with firebase : npm install firebase angularfire2 --save.
3 - And my code is here : 
import { Component } from '@angular/core';
import { NavController, AlertController } from 'ionic-angular';

import { Firebase } from '@ionic-native/firebase';
import firebase from 'firebase';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, public aletCtl: AlertController,
    public firebase: Firebase) { }

  public eer: string = 'error';
  public phone : number ;

  public getSMS() {
    let number = '+213' + this.phone;
    (<any>window).FirebasePlugin.verifyPhoneNumber(number, 60, function (credential) {
      console.log(credential);
      prompt user to enter code
      var code = this.getcodeuser();

      var verificationId = credential.verificationId;

      var signInCredential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);
      firebase.auth().signInWithCredential(signInCredential);
    }, function (error) {
      this.eer = error;
      console.error(error);
    });

  }

}
-----------------
----------------- app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

import { Firebase } from '@ionic-native/firebase';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Firebase,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

Please any help

**Comment by brunosoaresds** [comment]
Have you the console log?

**Comment by Abdelazziz** [comment]
Thanks Bruno, i resolved the problem

**Comment by kkrishnan90** [comment]
@Abdelazziz  It would be better if you post how you resolved it. Might definitely be helpful for others too.. And also your code on the ```import``` statements aren't completed. It would be also better if you post your complete code since there are many firebase plugins lying around for cordova. Awaiting your response on the same.

**Comment by Abdelazziz** [comment]
Hi @kkrishnan90 
this is how i resolved the probleme :
1- You must work with this plugin for firebase beacause this plugin have the implementation for phone auth : 
ionic cordova plugin add https://github.com/jestcastro/cordova-plugin-firebase --save.
2- See the code in this link : 
https://forum.ionicframework.com/t/phone-authentication-firebase-in-ionic-with-cordova-plugin-firebase/102058/7
Hope that will satisfay you.

**Comment by danbeo95** [comment]
@Abdelazziz  i try work follow you,but the app was exit when i call (window).FirebasePlugin.verifyPhoneNumber.Please help me.i use ionic framework

**Comment by Abdelazziz** [comment]
Hi @danbeo95 
First when you said the app was exit, so you are running not in browser, your are in device, in that case the plugin will work only in real device that is mentionned in plugin doc, if not the case try to work with try catch and get your error and post it here, hope that will help you.

**Comment by kkrishnan90** [comment]
@Abdelazziz  Thanks mate ! Got this fixed and I've released a `gist` as well.. Here's the link below 
which might help someone...
[](https://gist.github.com/kkrishnan90/f9b61c52850571fa3700fc043b06f53c)

**Comment by danbeo95** [comment]
@Abdelazziz  i dont't understand your answer.I run in device

**Comment by danbeo95** [comment]
@kkrishnan90  thanks for reply.i try follow you.but when i call 
signIn(phoneNumber: number) { //Step 2 - Pass the mobile number for verification
    this.api.presentLoader('Sending OTP to your mobile number');
    let number =this.phoneNumber;
    (<any>window).FirebasePlugin.verifyPhoneNumber(number, 60, (credential) =>{
    console.log(credential);
    this.api.dismissLoader();
    var verificationId = credential.verificationId;
    this.navCtrl.push('OtpPage',{verificationid: verificationId}); //This is STEP 3 - passing verification ID to OTP Page
    }, (error) =>{
      //this.eer = error;
      this.api.dismissLoader();
      this.api.presentToast('Failed to send OTP. Try again');
      console.error(error);
    });
  }
}
the app still was exited.Please help me!

**Comment by Abdelazziz** [comment]
Hi first thanks very well @kkrishnan90  for this work and your time on this post https://gist.github.com/kkrishnan90/f9b61c52850571fa3700fc043b06f53c, and for @danbeo95 please post your config.xml that can be found on  root project and your app.module.ts to see if you have all things correct.

**Comment by danbeo95** [comment]
here is my congfig.xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.ionic" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyApp</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-whitelist" spec="1.3.1" />
    <plugin name="cordova-plugin-device" spec="1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.11" />
    <engine name="android" spec="~6.3.0" />
    <plugin name="cordova-plugin-firebase" spec="https://github.com/jestcastro/cordova-plugin-firebase" />
</widget>

App.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
 any is incorrect??

**Comment by danbeo95** [comment]
I am going to need to fix this bug.you can provided your sky to support via sky.Thanks so much

**Comment by kkrishnan90** [comment]
I'm at an Indian Time here.. At my office. Ping your Skype ID and I shall support you tonight Indian Time after getting back to my home.

**Comment by danbeo95** [comment]
Hey.thanks a lot.this is my skype +841687072421

**Comment by kkrishnan90** [comment]
@danbeo95 .. could you pls specify the Skype ID ? Cuz this is your Skype number. I won't be able to call to your number. Better we have a Skype and I can help you out today to fix your issue

**Comment by danbeo95** [comment]
Ok.my id skype.beodan95@gmail.com.. Hope you support me soon.

**Comment by kkrishnan90** [comment]
@danbeo95 Sure I will.if it's urgent. Post your code and error msg on GitHub.create a repo or gist and post them. I'll try to support you to fix this one. Ok??

**Comment by danbeo95** [comment]
Ok.have you add my skype? It will esaier support to me

**Comment by kkrishnan90** [comment]
I'm at work now. Will do it tonight. Sorry.

**Comment by danbeo95** [comment]
https://gist.github.com/danbeo95/ede894f319be0f85cff42e2f12a59a22 here is my login.ts .When i call logIn() my app was exited!Please help me fix it
i use cordova-plugin-firebase https://github.com/jestcastro/cordova-plugin-firebase

**Comment by kkrishnan90** [comment]
@danbeo95 check my imports and yours. Install firebase native plugin for ionic. Did you check installing firebase native ionic plugin  ?some imorts seem to be not installed in your app. 
Also import firebase from 'firebase'. If possible I'll share my `package.json` tonight. That should solve your problem. Apart from this your code seems to be fine.

**Comment by danbeo95** [comment]
here is my package.json
{
  "name": "test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.1.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-firebase": "^0.1.21",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-whitelist": "1.3.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.0",
    "typescript": "2.4.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-firebase": {}
    },
    "platforms": [
      "android"
    ]
  can you support me for skype?

**Comment by danbeo95** [comment]
please support me.i have deadline tomorrow

**Comment by venkateshimmidi** [comment]
Followed all the steps. But showing error at auth in the folowing code, i have installed the firebase plugin and firebase angular2 as suggested with imports as well. but it is not taking auth , please help me out. i tried all the ways but nothing seems worked out, i stucked here from 2days

private verifyCode(code): void {
    console.log(code);

    let credential = firebase.auth.PhoneAuthProvider.credential(this.verificationId, code);

    firebase.auth().signInWithCredential(credential).then((res) => {
      console.log('SCC', res);
      this.doLogin()
    })
  }

**Comment by venkateshimmidi** [comment]
plugins installed:
 ionic cordova plugin add https://github.com/jestcastro/cordova-plugin-firebase.git
npm install firebase angularfire2 --save
imports:
import {Firebase} from "@ionic-native/firebase";

**Comment by akshgods** [comment]
@Abdelazziz  what is 
prompt user to enter code
var code = this.getcodeuser();

how to use it  this.getcodeuser() ?

**Comment by soumak77** [comment]
should be fixed by version 1.0.2
