### ISSUE TITLE
Retrieved a null token

### ISSUE THREAD

**Issue by ElRochito** [arnesson/cordova-plugin-firebase#451]
When I call getToken method, I retrieve a null token, I don't understand why. I've got any error log  ...
    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    Cordova Platforms : ios 4.4.0
    Ionic Framework   : ionic1 1.3.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.0
    ios-sim           : 5.0.8
    Node              : v8.0.0
    npm               : 5.0.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : legacy`

**Comment by julio6114** [comment]
I've got this problem on iOS 10.2.1 (iPhone 5C) but on iOS 10.3.3 (iPhone 6) it still works.

**Comment by aetchegoyen** [comment]
Same here, any news with these?
None of the solutions in other issues work.
I'm using latest versions of cordova and this plugin

**Comment by kelkmere** [comment]
For some reason, when I use cordova add plugin cordova-plugin-firebase,
the version 0.1.24 I get doesn't have the [latest changes](https://github.com/arnesson/cordova-plugin-firebase/issues/430) to /scripts/after_prepare.js

I fixed this by manually download the zip file from GitHub and place it in my node_modules directory.

**Comment by blackfan23** [comment]
@kelkmere 👍 
Same problem (on android), solved it exactly as you described. Thank you!

**Comment by kaynz** [comment]
@robertarnesson are you going to publish a new releasae anytime soon?

**Comment by dcxn** [comment]
Indeed, cordova add plugin cordova-plugin-firebase downloads an outdated version, which has a bug in the after_prepare hook, so the firebase config files are not copied over to the platforms correctly. Use cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --save or download the zip file and place it in plugins directory. Thank you @kelkmere

**Comment by ctopheryoung** [comment]
I experienced the same thing. Would be good to get a new release soon with the correct/latest `/scripts/after_prepare.js`. My solution was to peg to version `0.1.23` and have not had any problems since.
