### ISSUE TITLE
Error callback for fetch() function never called

### ISSUE THREAD

**Issue by jairemix** [arnesson/cordova-plugin-firebase#453]
When the FirebasePlugin.fetch() is called, the error callback is never executed, even in case of a plugin error.

```javascript
window.FirebasePlugin.fetch(600, (result) => {
  // Success callback
}, (error) => {
  // The error callback will never run
});
```

More specifically on iOS, the plugin does not have an else statement to handle firebase errors. Hence in case of an error, the plugin is left hanging forever.

```Objective-C
  if (status == FIRRemoteConfigFetchStatusSuccess) {
    CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
  } else {
    // We should handle the error here
  }
```

On Android, the plugin does not handle the error properly. The onCompleteListener is always called instead of the onFailureListener.

```Java
private void fetch(final CallbackContext callbackContext, final Task<Void> task) {
        cordova.getThreadPool().execute(new Runnable() {
            public void run() {
                try {
                    task.addOnCompleteListener(new OnCompleteListener<Void>() {
                        // This should be an onSuccessListener
                        @Override
                        public void onComplete(Task<Void> task) {
                            callbackContext.success();
                        }
                    }).addOnFailureListener(new OnFailureListener() {
                        // This is never called because of the onCompleteListener
                        @Override
                        public void onFailure(Exception e) {
                            callbackContext.error(e.getMessage());
                        }
                    });
                } catch (Exception e) {
                    callbackContext.error(e.getMessage());
                }
            }
        });
    }
```

Therefore, if the firebase SDK throttles the fetch call and throws an error, the app will not be able to run if it depends on the async call to finish executing.

**Comment by robertarnesson** [comment]
now merged..

**Comment by agrosner** [comment]
this doesnt appear merged. https://github.com/arnesson/cordova-plugin-firebase/blob/6d25a396deac74e0208e2619e2cf3380e9a947f4/src/ios/FirebasePlugin.m#L328

**Comment by agrosner** [comment]
This is especially problematic that it does not call back and so the JS is just left hanging indefinitely awaiting the callback when we get throttled. If you set a cache timeout to 10 seconds, highly likely you'll get throttled, which causes our app to freeze and expect the data to be there.
