### ISSUE TITLE
Any way to get APNS token too?

### ISSUE THREAD

**Issue by chrissterling** [arnesson/cordova-plugin-firebase#455]
We have a requirement to use APNS for some special messages that won't go through FCM.  Anyone know if there is a way to get the APNS token as well as the FCM device id so we can store both?

**Comment by chrissterling** [comment]
I've had to quick hack for now due to time pressures.  For anyone else looking for this, I've handled the didRegisterForRemoteNotificationsWithDeviceToken callback in AppDelegate+FirebasePlugin.m and fire that APNS token back from the plugin when it arrives.

**Comment by poernahi** [comment]
If anyone else needs this functionality, I have a fork at https://github.com/poernahi/cordova-plugin-firebase/tree/twilio-integration that implements `getAPNSToken`

**Comment by WoollyMittens** [comment]
Thanks @poernahi , that's just what I needed.
