### ISSUE TITLE
Problem IOS build Phone Gap Build

### ISSUE THREAD

**Issue by Netpllay** [arnesson/cordova-plugin-firebase#460]
I created the application, I added the certificates, in the firebase, I'm compiling with the phonegap build, it is generating the .ipa file normally, but when I install it on the iphone and open the application, it automatically closes, does anyone have any idea what this problem might be? I believe the GoogleService-Info.plist file is not being compiled together, but I copied that file to the project root and to the www folder.

**Comment by robertarnesson** [comment]
phonegap build is not supported.. check the README. you need to make a private fork of this repo and include the plist in the plugin source. The problem is that phonegap build does not support hooks, so the config files are never copied in to place
