### ISSUE TITLE
Cannot set correct google_app_id when using multiple App on Firebase

### ISSUE THREAD

**Issue by donuzium** [arnesson/cordova-plugin-firebase#465]
Cannot set correct setting if there were multiple application settings in google-service.json.

I'm using *2 Apps*, has different bundle ID, in same Firebase project.
From web page, download button, we can get google-service.json that contains both application's setting.

When install this plugin the setting will be the first one even if second bundle ID is set on Config.xml.

So I solved this problem with adding "google_app_id" directly into `/platforms/android/res/values/strings.xml`.

```xml
<string name="google_app_id">1:1111111111111111:android:xxxxxxxxxxxxxxxx</string>
```

I appreciate for all contributors of this plugin. 
Thank you.

**Comment by soumak77** [comment]
closing in favor of https://github.com/arnesson/cordova-plugin-firebase/issues/791 since it has more recent activity
