### ISSUE TITLE
Unable to build on iOS

### ISSUE THREAD

**Issue by AlessandroBagnoli** [arnesson/cordova-plugin-firebase#466]
When I try to build my ionic app for ios, this is the result. Is this because I don't have an APN certificate on FCM? Is it possible to use this plugin on iOS without a paid Apple Developer Account?

Everything is fine and works like a charm on Android

`Check dependencies
Code Signing Error: Automatic signing is unable to resolve an issue with the "Repair City" target's entitlements. Automatic signing can't add the aps-environment entitlement to your provisioning profile. Switch to manual signing and resolve the issue by downloading a matching provisioning profile from the developer website. Atlernatively, to continue using automatic signing, remove this entitlement from your entitlements file and its associated functionality from your code.
Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: com.infinitycode.repaircity" doesn't include the aps-environment entitlement.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
 
** ARCHIVE FAILED **
 
 
The following build commands failed:
        Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/luca/WebstormProjects/Repair City/platforms/ios/cordova/build-debug.xcconfig,-workspace,Repair City.xcworkspace,-scheme,Repair City,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Repair City.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/luca/WebstormProjects/Repair City/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/luca/WebstormProjects/Repair City/platforms/ios/build/sharedpch
 
[ERROR] An error occurred while running cordova build ios (exit code 1).`

**Comment by Ansorre** [comment]
Same problem here! Anyone knows what to do⁇

**Comment by robertarnesson** [comment]
the answer is right there, Code Signing Error. not related to this plugin

**Comment by markterrill** [comment]
i'd been building android fine, started on the alpha release for ios. got it to build and load, then it complained that cordova-plugin-firebase wasn't there. so installed, then xcode wouldn't build, complaining about aps-environment.
