### ISSUE TITLE
[iOS] Not receiving push notifications sent from Firebase Console

### ISSUE THREAD

**Issue by DigitalPumpkin** [arnesson/cordova-plugin-firebase#467]
Hello,

I'm not receiving any notifications sent from the Firebase Console. As far as I can see, the notifications are going out from Firebase but they're just not reaching my device. I'm not getting any indication that the notification made it to my device or any kind of error that something broke along the way (maybe I'm just not taking the necessary actions to show/log it).

The message statuses say **Completed** and clicking on the messages afterwards shows that it has been sent to 1 device.

Here's what I have currently. If I'm not mistaken this is all that is needed for a notification to come through (outside of having your device generate a token and also having permission)?

```javascript
window.FirebasePlugin.onNotificationOpen(function(notification) {
     console.log('Notification received',notification);
     alert('Notification: ' + notification);
}, function(error) {
    console.error(error);
});
```

Some info: 

- PhoneGap 7.0.0
- Latest version of the plugin
- Certificate is uploaded to the app in Firebase
- The generated GoogleServices-Info.plist and provisioning profile is included in my Xcode project
- App ID and APNs set up
- Device is generating a token and the app has permission to send push notifications (on the device and the Push Notifications/Remote Notification capabilities enabled in Xcode)

Any help is greatly appreciated!

Thanks!

**Comment by marcoramires** [comment]
Same issue here...
Cordova 7.0
<engine name="ios" spec="~4.5.2" /> 
APNs Key
AppID: Push Notifications Enabled
Provisional Profile: Push Notifications Enabled
XCode 9.1 Capabilities: Push Notifications ON

**Comment by antondb** [comment]
We are also having the same issue. We have tested with the p8 certificate APN key and p12 traditional certificate version.

We correctly receive the token from the app, but do not receive any notifications from Firebase when sending to that token or to all IOS devices. The plugin is working with our android build. We have also noticed (as above) that after some time Firebase will list that the notification as sent to a device.

Cordova 7.1.0
Iphone 6s
cordova-plugin-firebase 0.1.24

So far we have been unable to debug this to resolve.

**Comment by antondb** [comment]
Hello,

We have just set this "FirebaseAppDelegateProxyEnabled" to yes in our -info.plist file. This has resolved the issue for us.

**Comment by awabbi** [comment]
Thanks @antondb . That was exactly the solution.

**Comment by faustoct** [comment]
@antondb it did not work for me. any other try? just can't send push notifications to any iOS. @robertarnesson any idea, suggestion?

**Comment by markterrill** [comment]
Hi, I've set 'FirebaseAppDelegateProxyEnabled' to "yes" in the -info.plist file within /platforms/ios/[appname]/resources/[appname]-info.plist

No joy yet.

**Comment by michaelreiser** [comment]
Adding the plist key isn't working for me either

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin

**Comment by narenderreddych** [comment]
Adding the plist key isn't working for me either

Please suggest

**Comment by fcrozetta** [comment]
not working for me either.
Is this a bug on Cordova?

Regards

**Comment by sholatunji** [comment]
@fcrozetta try this

`window.FirebasePlugin.grantPermission();` work for me just now with the same problem

**Comment by Golem765** [comment]
@sholatunji Thanks, worked for me, it seems that we must ask for permission if we unregister and try to register again, even if that permission is technically already granted

**Comment by sholatunji** [comment]
Yes @Golem765 I noticed the same as well, i used it like this 

`				window.FirebasePlugin.hasPermission(function(data){
					if(!data.isEnabled){
						window.FirebasePlugin.grantPermission();
					}
				});`
