### ISSUE TITLE
TypeError: Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by swapie** [arnesson/cordova-plugin-firebase#469]
I am using ionic native firebase plugin. But i'm unable to access any of its method (e.g fetch)

Code snippet : 
(<any>window).firebase.fetch(600, result => {
           // activate the fetched remote config
           console.log(JSON.stringify(result)); 
           (<any>window).firebase.activateFetched(
             // Android seems to return error always, so we want to cath both
             result => { 
               console.log(JSON.stringify(result)); 
              (<any>window).firebase.getValue("test", result => {  
              console.log(result)  
               }, reason => {
              console.warn(`Error  ${reason}`);
              });
             }, reason => { 
               console.warn(reason); 
             }
           )
         });

**Comment by Thomasbehan** [comment]
In order for the getValue function to work properly you are required to set a default value see firebase loading strategies => https://firebase.googleblog.com/2017/01/firebase-remote-config-loading.html
