### ISSUE TITLE
Import AppDelegate of Swift

### ISSUE THREAD

**Issue by Derrick666** [arnesson/cordova-plugin-firebase#47]
Hi there,

I have been trying to use this plugin in my Cordova project where all classes are written in Swift. Hence I hit an issue in the FirebasePlugin.h and FirebasePlugin.m because they are trying to import Objective-C version of appDelegate.h. There are some suggestions out there for this issue e.g. http://stackoverflow.com/questions/33781505/cant-find-swift-appdelegate-inside-objective-c,
http://stackoverflow.com/questions/24062618/swift-to-objective-c-header-not-created-in-xcode-6 but found no luck, I was wondering if you have any ideas or workaround for it ?

Thanks in advance

**Comment by robertarnesson** [comment]
what is the actual build error?

**Comment by Derrick666** [comment]
It complained appDelegate.h not found. Because it has appDelegate.swift not appDelegate.h.

**Comment by robertarnesson** [comment]
as far as I can tell it looks like a bridging header is needed: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

should be pretty easy to try
