### ISSUE TITLE
Ionic2 token returning NULL

### ISSUE THREAD

**Issue by jdileep14** [arnesson/cordova-plugin-firebase#473]
Firrbase token always giving NULL 
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node  : v6.11.5
    npm   : 4.6.1 
    OS    : macOS Sierra
    Xcode : Xcode 8.3.3 Build version 8E3004b

**Comment by fobaz** [comment]
same here. was working fine a week ago

**Comment by dcxn** [comment]
Maybe related to #451 ?
