### ISSUE TITLE
Cocoon.io build error

### ISSUE THREAD

**Issue by gametrick** [arnesson/cordova-plugin-firebase#474]
Could you please help to solve this build error from Cocoon.io service?

-----------------

COMPILER ERROR: 

/workspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeArmv7ReleaseResources'.
> /workspace/platforms/android/res/values/strings.xml: Error: Found item String/google_app_id more than one time

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CORDOVA LOG: 

[36m[2017-11-09 08:23:12.483] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore platforms
[36m[2017-11-09 08:23:12.496] [DEBUG] AndroidBuilder - [39m[prepare] adding engine android@6.2.3
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
[36m[2017-11-09 08:23:26.096] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore plugins
[36m[2017-11-09 08:23:26.100] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cocoon-plugin-share@*
[36m[2017-11-09 08:23:26.164] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.defaultres.android@1.0.1
[36m[2017-11-09 08:23:26.223] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usericon.android@1.0.1
[36m[2017-11-09 08:23:26.278] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usersplash.android@1.0.2
[36m[2017-11-09 08:23:26.340] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.android@2.2.1
[36m[2017-11-09 08:23:26.393] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.ios@1.1.0
[36m[2017-11-09 08:23:26.447] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-admobpro@2.29.24
[36m[2017-11-09 08:23:26.483] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-firebase@*
[36m[2017-11-09 08:23:26.521] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-inappbrowser@*
[36m[2017-11-09 08:23:26.572] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-whitelist@*
[36m[2017-11-09 08:23:28.209] [DEBUG] AndroidBuilder - [39m[build]
[36m[2017-11-09 08:23:28.209] [DEBUG] AndroidBuilder - [39m[build] create certs folder
[36m[2017-11-09 08:23:28.210] [DEBUG] AndroidBuilder - [39m[build] keystore
[36m[2017-11-09 08:23:28.481] [DEBUG] AndroidBuilder - [39m[build] create release build.json
[36m[2017-11-09 08:23:28.482] [DEBUG] AndroidBuilder - [39m[build] call cordova
ANDROID_HOME=/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
Starting a Gradle Daemon, 19 stopped Daemons could not be reused, use --status for details
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_7vbjwsxik89y81tm0muz3422v.run(/workspace/platforms/android/build.gradle:140)
org.xwalk:xwalk_core_library:22+
Not writing assets/xwalk-command-line since file already exists.
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preArmv7ReleaseBuild UP-TO-DATE
:checkArmv7ReleaseManifest
:preArmv7DebugBuild UP-TO-DATE
:preX86DebugBuild UP-TO-DATE
:preX86ReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2420Library
:prepareComAndroidSupportSupportCoreUi2420Library
:prepareComAndroidSupportSupportCoreUtils2420Library
:prepareComAndroidSupportSupportFragment2420Library
:prepareComAndroidSupportSupportMediaCompat2420Library
:prepareComAndroidSupportSupportV42420Library
:prepareComGoogleAndroidGmsPlayServicesAds1104Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1104Library
:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:prepareComGoogleAndroidGmsPlayServicesClearcut1104Library
:prepareComGoogleAndroidGmsPlayServicesGass1104Library
:prepareComGoogleAndroidGmsPlayServicesSafetynet1104Library
:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:prepareComGoogleFirebaseFirebaseAnalytics1104Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1104Library
:prepareComGoogleFirebaseFirebaseCommon1104Library
:prepareComGoogleFirebaseFirebaseConfig1104Library
:prepareComGoogleFirebaseFirebaseCore1104Library
:prepareComGoogleFirebaseFirebaseCrash1104Library
:prepareComGoogleFirebaseFirebaseIid1104Library
:prepareComGoogleFirebaseFirebaseMessaging1104Library
:prepareMeLeolinShortcutBadger114Library
:prepareOrgApacheCordovaCordovaLib623ReleaseLibrary
:prepareOrgXwalkXwalk_core_library22525614Library
:prepareWebviewplusReleaseLibrary
:prepareArmv7ReleaseDependencies
:compileArmv7ReleaseAidl
:compileArmv7ReleaseRenderscript
:generateArmv7ReleaseBuildConfig
:generateArmv7ReleaseResValues
:generateArmv7ReleaseResources
:mergeArmv7ReleaseResources
/workspace/platforms/android/res/values/strings.xml: Error: Found item String/google_app_id more than one time
:mergeArmv7ReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeArmv7ReleaseResources'.
> /workspace/platforms/android/res/values/strings.xml: Error: Found item String/google_app_id more than one time

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.869 secs

**Comment by robertarnesson** [comment]
it looks like you have more than one plugin changing workspace/platforms/android/res/values/strings.xml
