### ISSUE TITLE
invalid googel app-id 

### ISSUE THREAD

**Issue by RameshkrishnanV** [arnesson/cordova-plugin-firebase#477]
Hi, plugin is not copying app id to the platform folder.
the google-service.json file is empty inside platforms folder

**Comment by gametrick** [comment]
Same problem here. Tried everything but no solution on Android.

**Comment by premtemp1** [comment]
I am having the same issue. Did you find a solution?

**Comment by RameshkrishnanV** [comment]
Try updating android platform version to 6.3. it will solve this issue.

On 13-Jan-2018 20:28, "premtemp1" <notifications@github.com> wrote:

I am having the same issue. Did you find a solution?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arnesson/cordova-plugin-firebase/issues/477#issuecomment-357441300>,
or mute the thread

**Comment by premtemp1** [comment]
Thanks for your help...

I tried to upgrade to 6.3 but I am getting lots of error..


*Command failed with exit code 1 Error output:*

*Note: Some input files use or override a deprecated API.*

*Note: Recompile with -Xlint:deprecation for details.*

*Note: Some input files use or override a deprecated API.*

*Note: Recompile with -Xlint:deprecation for details.*

*Note: Some input files use or override a deprecated API.*

*Note: Recompile with -Xlint:deprecation for details.*

*Note:
/Users/Prem/Documents/testing/MobileV2/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java
uses unchecked or unsafe operations.*

*Note: Recompile with -Xlint:unchecked for details.*

*Note: there were 7 duplicate class definitions.*

*
(http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass
<http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass>)*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced class android.app.NotificationChannel*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced method 'android.app.Notification$Builder
setChannelId(java.lang.String)' in library class
android.app.Notification$Builder*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced class android.app.NotificationChannel*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced class android.app.NotificationChannel*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced class android.app.NotificationChannel*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced method 'void
createNotificationChannel(android.app.NotificationChannel)' in library
class android.app.NotificationManager*

*Warning: com.google.android.gms.common.GoogleApiAvailability: can't find
referenced method 'android.app.NotificationChannel
getNotificationChannel(java.lang.String)' in library class
android.app.NotificationManager*

*Warning: com.google.android.gms.gcm.zza: can't find referenced class
android.app.NotificationChannel*

*Warning: com.google.android.gms.gcm.zza: can't find referenced method
'android.app.Notification$Builder setChannelId(java.lang.String)' in
library class android.app.Notification$Builder*

*Warning: com.google.android.gms.gcm.zza: can't find referenced class
android.app.NotificationChannel*

*Warning: com.google.android.gms.gcm.zza: can't find referenced method
'void createNotificationChannel(android.app.NotificationChannel)' in
library class android.app.NotificationManager*

*Warning: com.google.android.gms.gcm.zza: can't find referenced method
'android.app.NotificationChannel getNotificationChannel(java.lang.String)'
in library class android.app.NotificationManager*

*Warning: com.google.android.gms.internal.zzbhd: can't find referenced
method 'boolean isInstantApp()' in library class
android.content.pm.PackageManager*

*Warning: com.google.android.gms.internal.zzbhe: can't find referenced
method 'boolean isInstantApp(java.lang.String)' in library class
android.content.pm.PackageManager*

*Warning: com.google.android.gms.internal.zzcui: can't find referenced
method 'boolean isDeviceProtectedStorage()' in library class
android.content.Context*

*Warning: com.google.android.gms.internal.zzcui: can't find referenced
method 'boolean isUserUnlocked()' in library class android.os.UserManager*

*Warning: there were 6 unresolved references to classes or interfaces.*

*         You may need to add missing library jars or update their
versions.*

*         If your code works fine without the missing classes, you can
suppress*

*         the warnings with '-dontwarn' options.*

*
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass
<http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass>)*

*Warning: there were 10 unresolved references to library class members.*

*         You probably need to update the library versions.*

*
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember
<http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember>)*


*FAILURE: Build failed with an exception.*


** What went wrong:*

*Execution failed for task
':transformClassesAndResourcesWithProguardForRelease'.*

*> Job failed, see logs for details*


** Try:*

*Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.*
