### ISSUE TITLE
Change android notification icon

### ISSUE THREAD

**Issue by Hanzofm** [arnesson/cordova-plugin-firebase#479]
HI,

I'm trying to change the default notification icon on android (7.0). On ionic 3.9.2 project

**On the ionic root project** I have created the folders tree:

IonicROOT/res/native/android/res/drawable-hdpi.........
I**nside each folder is notification_icon.png**

Also  I have created

IonicROOT/res/native/android/res/values
IonicROOT/res/native/android/res/values-21

with the files styles.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <!-- inherit from the holo theme -->
  <style name="AppTheme" parent="android:Theme.Light">
    <item name="android:windowDisablePreview">true</item>
  </style>
  <drawable name="notification_big">@mipmap/icon</drawable>
  <drawable name="notification_icon">@mipmap/icon</drawable>
</resources>
```

styles v21

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <!-- inherit from the material theme -->
  <style name="AppTheme" parent="android:Theme.Material">
    <item name="android:windowDisablePreview">true</item>
  </style>
  <drawable name="notification_big">@mipmap/icon</drawable>
  <drawable name="notification_icon">@drawable/notification_icon</drawable>
</resources>
```

But when I've received a notification it has the default  white square

What I'm doing wrong?

**Comment by nikmartin** [comment]
I'm seeing this too on Android API 26 and > .

**Comment by Yuripetusko** [comment]
No matter what I try my icon is just white square.

My icon is in PNG24 with alpha transparency, appropriate sizes in different `platform/android/res/drawable-XXX/` folders.

- I tried route with adding `<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />` to Manifest file,

- I tried route with adding `values/styles.xml` and `values-v21/styles.xml` with notification_icon specified there

- I tried sending `icon` prop in FCM payload

- I even tried replacing `mipmap-XXX/icon.png` with transparent png icon

nothing works :( still just seeing white square in status and pull-down notifications

**Comment by robertarnesson** [comment]
closing this for now. re-open if still a problem with the latest version of the plugin

**Comment by nprail** [comment]
I seem to be having this issue as well with version 0.1.25 of the plugin.

**Comment by Hanzofm** [comment]
I have founded a workaround with `cordova-custom-config` plugin adding this snippet to config.xml on android platform

```
<custom-config-file parent="./application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </custom-config-file>
```

**Comment by Ahmadre** [comment]
@ Hanzofm:

I tried your solution, but i get:
`Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details`

are you sure @drawable/icon is the correct path for an ionic/android project?
