### ISSUE TITLE
Phone authentication the app exit when no internet connection in device.

### ISSUE THREAD

**Issue by Abdelazziz** [arnesson/cordova-plugin-firebase#480]
Hi every one, hope you are okay
So this is my probem i have implement phone authentication with firebase plugin exactly with this plugin https://github.com/jestcastro/cordova-plugin-firebase, i sent and receive code to confirmation succefuly,but when no internet connexion in device the code in app should show error to user but in my case the app exit, and i don't know why, please any helps. This is my code :
   try {
        let phone = '+213' + this.phoneNumber;
        window.FirebasePlugin.verifyPhoneNumber(phone, 30, credential => {
          this.verificationId = credential.verificationId;
        }, error => {
          this.error = error;
          this.showAlert('error');
          return;
        });
      } catch (e) {
        this.error = e;
        this.showAlert('problem in auth not send');
      }

**Comment by Abdelazziz** [comment]
Hi, Any update in this topic

**Comment by Hirbod** [comment]
Same issue here. Trying to call on android without internet access will crash the app.

**Comment by soumak77** [comment]
Closing in favor of https://github.com/arnesson/cordova-plugin-firebase/issues/503.  @Hirbod mentions to check the internet connectivity before sending the request.  PRs are welcome to integrate that functionality into this plugin.
