### ISSUE TITLE
cordova-plugin-firebase doesn't work on iOS

### ISSUE THREAD

**Issue by salvatoreferrigno** [arnesson/cordova-plugin-firebase#483]
Hello  I'm using cordova-plugin-firebase , for android platform it works, but for iOS it doesn't. I followed all the steps of the following guide(https://medium.com/@felipeevangelistapucinelli/how-to-add-push-notifications-in-your-cordova-application-using-firebase-69fac067e821) in order to configure my app, but i've still problems. I tried to build my app using Xcode both in debug and release mode, but my app doesn't receive notifications. 

Thank you in advance.

**Comment by faustoct** [comment]
save problem here. the plugin stopped working.

````
curl -X POST --header "Authorization: key=<yyy>" \
                --Header "Content-Type: application/json" \
                https://fcm.googleapis.com/fcm/send \
                -d "{\"to\":\"<xxx>\",\"notification\":{\"body\":\"Yellow\"},\"priority\":10}"
````
{"multicast_id":...,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:..."}]}

but notifications doesn't ping the device. Any idea? Suggestion to try? etc? pls

**Comment by faustoct** [comment]
@salvatoreferrigno did you fix it? if yes, how?

**Comment by faustoct** [comment]
What might be? It was working just stopped after some updates (plugin,
cordova, xcode).  It is in production. OMG!

Any ideia to figure out what's going?

Em 28/11/2017 16:57, "Salvatore Ferrigno" <notifications@github.com>
escreveu:

**Comment by salvatoreferrigno** [comment]
It never worked for me, i tried to downgrade to the previous version of the plugin (18, 17, ..) but nothing. i don't know what might be the problem. how do you get it to work? which version of the plugin ?

**Comment by faustoct** [comment]
@salvatoreferrigno I don't remember the version exactly, I'll look the history. After updates it stopped. I guess it's a plugin or xcode podfile issue.

The documentation says to add `pod 'Firebase/Messaging'` before as just `pod Firebase`. But podfile fails under `pod install`when added `Firebase/Messaging`, I left only `Firebase/Core`.

The log says `FCM connected`. Not sure what's going on here.

**Comment by faustoct** [comment]
@robertarnesson Does the plugin send ios push notifications for you ?

**Comment by faustoct** [comment]
@salvatoreferrigno this is my list try. Add `Firebase/Messaging` to podfile. Try to make it work
````
platform :ios, '7.0'
target 'XXX' do
    pod 'Fabric'
    pod 'Appsee'
    pod 'Crashlytics', '~> 3.9'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end
````

returns 

````
Analyzing dependencies
Downloading dependencies
Using Appsee (2.3.6)
Using Crashlytics (3.9.3)
Using Fabric (1.7.2)
Installing Firebase 4.6.0 (was 4.6.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseCore (4.0.11)
Using FirebaseInstanceID (2.0.6)
Installing FirebaseMessaging (2.0.6)
Installing GoogleToolboxForMac 2.1.3 (was 2.1.3)
Installing Protobuf (3.5.0)
````

**Comment by faustoct** [comment]
@salvatoreferrigno @robertarnesson  make it working again. I'm gonna share step by step what I did. Would be nice have a troubleshooting to help others in the future.

**Comment by faustoct** [comment]
Searching around I saw many suggestions to fix it but none of them really help me. It's what I did (when almost losing faith):

- Close Xcode
- Remove derivded data: rm -rf /Users/fausto/Library/Developer/Xcode/DerivedData
- Clean pods (be in the right folder) : sudo gem install cocoapods-deintegrate cocoapods-clean ; pod deintegrate ; pod clean ;
- In Xcode > Build Settings >> Enable bitcode = TRUE
- In Xcode in your -Info.list add/set FirebaseAppDelegateProxyEnabled = TRUE
- In Podfile add the lines: pod 'Firebase/Core' and pod 'Firebase/Messaging'
- In Xcode in General remove libPods.a
- cordova build ios
- Open Xcode try to run in your iphone

@salvatoreferrigno you can try, I can help you if you need any help. We can improve this troubleshooting

**Comment by premtemp1** [comment]
Have a similar issue.. I am just trying to install the SDK and see some analytic in the firebase console.. However, noting is showing up for iOS.. I do see default events for Android..

Do I have to install cocoapods and create a podfile?. The plugin did not say it..

Thanks for your help

**Comment by furkankatman** [comment]
Any updates?I am facing the same error ?

**Comment by soumak77** [comment]
closing as resolved
