### ISSUE TITLE
library conflict

### ISSUE THREAD

**Issue by zeroonea** [arnesson/cordova-plugin-firebase#489]
I use this version of ads

`compile "com.google.android.gms:play-services-ads:8.1.0"
`
it is conflict with your plugin 

`com.google.android.gms:play-services-analytics-impl-license:11.6.0
`
I want to change to version of play-services-analytics-impl-license to 8.1.0 but I don't know where to change it in your plugin.

I tried add this line in my build.gradle but no help, still version 11.6.0

`compile "com.google.android.gms:play-services-analytics-impl-license:8.1.0"`

**Comment by christocracy** [comment]
The solution is for the author of this plugin to use the new mechanism available in Cordova `7.1.0` (`android-6.3.0`) which now allows plugin developers to expose `<variable />`s in the `config.xml`, allowing plugin developers to do this:

```xml
<platform name="android">
  <preference name="GOOGLE_API_VERSION" default="11.0.1" />  
  <framework src="com.google.gms:google-services:$GOOGLE_API_VERSION" />
  <framework src="com.google.android.gms:play-services-tagmanager:$GOOGLE_API_VERSION" />
  <framework src="com.google.firebase:firebase-core:$GOOGLE_API_VERSION" />
  <framework src="com.google.firebase:firebase-messaging:$GOOGLE_API_VERSION" />
  <framework src="com.google.firebase:firebase-crash:$GOOGLE_API_VERSION" />
  <framework src="com.google.firebase:firebase-config:$GOOGLE_API_VERSION" />
  .
  .
  .
</platform>
```

Then in your application's `config.xml`, you will have a `<variable name="GOOGLE_API_VERSION />` exposed developers to configure.

```xml
<plugin name="cordova-plugin-firebase">
  <variable name="GOOGLE_API_VERSION" value="11.0.1" />
</plugin>
```

This is a very easy change to implement.  See [this commit](https://github.com/phonegap/phonegap-plugin-push/commit/468f6001c24a0e4889f64ad384f86585ff22ba9b) as `phonegap-plugin-push`, who were the first to implement this mechanism (they actually instigated it with Cordova).

**Note:** This mechanism **requires** `cordova @7.1.0`.

**Comment by robertarnesson** [comment]
I will take a PR if anyone feels like implementing this

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by Emersonifdl** [comment]
I have a problem like this [link]( https://github.com/arnesson/cordova-plugin-firebase/pull/662#issue-184792260).
The solution was to add these lines:
`allprojects {
    repositories {
         //start here
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '11.8.0'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '11.8.0'
                }
            }
        }
        //end`
 to the file build.gradle.

how could add this setting by config.xml ?
can anybody help me?
