### ISSUE TITLE
getInstanceId is undefined

### ISSUE THREAD

**Issue by LordAmarth** [arnesson/cordova-plugin-firebase#49]
Hello
I have copied google-services.json to root folder and installed the plugin

Phone constantly tells me that window.FirebasePlugin.getInstanceId is undefined
I'm of course running it at deviceready event.

Thanks

**Comment by robertarnesson** [comment]
sounds specific to your setup. is firebase.js loaded/included in your build?

**Comment by LordAmarth** [comment]
Weird
I was using other plugin and tried this again. After reinstall it works :D
