### ISSUE TITLE
iOS push notifications

### ISSUE THREAD

**Issue by jdileep14** [arnesson/cordova-plugin-firebase#493]
Hi i am using ionic2 firebase plugin .when i sending notifications from firebase i am receiving notification  in android but i amn't receiving notification in ios .I created another ios app with same package name in same app of google firebase.Do i need  any extra steps for ios.
this is my ionic configuration 
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.0
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Environment Variables:

    ANDROID_HOME : /Users/DileepKumar/Library/Android/sdk

Misc:

    backend : pro

this is code for getting token

this.firebase.getToken()
    .then(token =>{
      console.log(token);
    } ) 
    .catch(error => console.log('Error getting token'+error));

this is code for getting notification

    this.firebase.onNotificationOpen().subscribe(data=>{
      console.log(data);
    },
    (error=>{
      console.log(error);
    })
 )

Thanks in advance

**Comment by tporora** [comment]
Not getting notifications on iOS either. Notifications working fine in Chrome on the desktop.
May be related to iOS11.
There's an older similar issue:
[https://github.com/arnesson/cordova-plugin-firebase/issues/467](url)

**Comment by markterrill** [comment]
Hi, same issue here, been trying all day with deleting the ios platform, reinstalling plugins, all kinds of things.

**Comment by tporora** [comment]
Notifications from the firebase console are received on iOS, but not those produced by our application. We're using what firebase describes as the "legacy app server protocols". 
[https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_using_the_legacy_app_server_protocols]()
Haven't tried the "v1 HTTP" protocol yet

**Comment by tporora** [comment]
Notifications from the firebase console are received on iOS, but not those produced by our application. We're using what firebase describes as the "legacy app server protocols". 
[https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_using_the_legacy_app_server_protocols]()
Haven't tried the "v1 HTTP" protocol yet

**Comment by Limoli** [comment]
I get the same problem. It seems that **onNotificationOpen** is not triggered.

**Comment by markterrill** [comment]
Hi,
For iOS I can provide working samples of the FCM httpv1 API and the payload to the cloud functions admin messenger.

httpv1 API
Need to know:
- Payload https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
- OAUTH setup:  https://firebase.google.com/docs/cloud-messaging/auth-server#authorize_http_v1_send_requests . 
Personally i created a local nodejs file with:
```
var google = require('googleapis');

var SCOPES="https://www.googleapis.com/auth/firebase.messaging"

function getAccessToken() {
        return new Promise(function(resolve, reject) {
                var key = require('./serviceAccountKey.json');
                var jwtClient = new google.auth.JWT(
                        key.client_email,
                        null,
                        key.private_key,
                        SCOPES,
                        null
                );
                jwtClient.authorize(function(err, tokens) {
                        if (err) {
                                reject(err);
                                return;
                        }
                        resolve(tokens.access_token);
                });
        });
}

getAccessToken()
        .then(res => {

                console.log(res);

        });
``` and then run it via node file.js.

- URL etc . https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send

my httpv1 payload (tested on iOS):
```
{
   "validateOnly":false,
   "message":{
      "data":{
         "data1":"value31",
         "sound": "sonar.caf"
      },
      "notification":{
                  "title":"Hello6",
                  "body":"Please confirm your availability"
                  
      },
      "android":{
         "data":{
            "data1":"value1",
            "title":"Hello",
            "body":"Please confirm your availability"
         },
         "restricted_package_name":"io.xxx.app.controller",
         "priority":"high"
      },
      "name":"Planning validation",
      "apns":{
         "payload":{
            "aps":{
               
               "sound": "clock.caf"
            }
         }
      },
      "token":"du2I_135wHc:APA91bEg0lqTi7cqBrRUBRUwxKvaGhCkhiM1SZMxvJDUGBClN6egsBnwGbQT2XeYovkpkKX6kcnydNzRKj3Z_bubb7OpxXGsyCeeLoW9noXLUDVRlcQZUGbjTj-q0mJ3_X6YTtlPcKdI"
   }
}
```
(note, httpv1 api is recommended by google as the most feature rich and up to date, and i wanted to test sending different sound payloads to different platforms. I'll send a PR for my cordova-plugin-firebase for custom sounds)


**Cloud Functions Admin messenger**
for GCM:
```
{ data: { body: 'Pit is too HOT', message: 'Pit is too HOT', sound: 'sonar', notId: '2347', title: 'Too Hot Pit is 918.54F' } }
```
for iOS
```
{ notification: { body: 'Pit is too HOT', message: 'Pit is too HOT', sound: 'sonar.caf', title: 'Too Hot Pit is 918.54F' } }
```
Note on cordova-plugin-firebase an alert will not trigger unless you have a data packet, and iOS if in background its processed by apns/ios logic and appears not to touch the plugin and so seems to reject it unless you're just using the notification schema.

**Comment by christianwico** [comment]
Same issue here. What version of `cordova-plugin-firebase` are you guys using? I'm currently using `0.1.24`, but it seems there is already version `0.1.25`.

**Comment by markterrill** [comment]
@christianwico  its about the payload you send. i've got it working perfectly (with custom sound) on both ios and android.

**Comment by christianwico** [comment]
@markterrill indeed. I'm very sure that my payload is correct. It used to work before I decided to update my Cordova Plugins. After going from `0.1.22` to `0.1.24`, everything just didn't work.

I've updated to `0.1.25` and everything's good now. My app's working and receiving Push Notifications again.

**Comment by markterrill** [comment]
@christianwico nice! I'll try that. Hopefully it doesn't stuff everything up like 0.1.24 did and I had to change payloads etc to fire different messages to the different platforms to get it to work!

...updating cordova plugins has been a nightmare, had a ready to ship app 2 weeks ago then updated to cordova 7 etc and it broke multiple plugins. I'm still struggling with local notifications because firebase FCM and local notifications fight over the notification delegate role
