### ISSUE TITLE
Custom notification sound does not play when phone sleeps

### ISSUE THREAD

**Issue by jablesauce** [arnesson/cordova-plugin-firebase#494]
I am playing a custom notification sound when a Firebase notification of a particular kind is received. Basically, the path is specified in the payload and the .mp3 file is in the _resources/raw/_ path of the Android platform folder as specified in the documentation.

The issue is that the custom notification sound always plays except for when I leave the phone to sleep **while the application is in the foreground**. In this case, it will play the default notification sound from the phone itself. If the phone is manually locked while the app is in the foreground, the custom notification sound plays fine. It only happens when I leave the phone to sleep on its own. Most importantly, the issue only happens on some phones (generally older models), for example; the **Samsung Galaxy J1 Mini**. The Android version on this phone is **5.1.1**. 

I do not have any issues in the code or in the payload because this is happening only for when the phone sleeps **and** on certain phone models. I have not found any online sources that address this problem so I am hoping someone here has come across this before.

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
