### ISSUE TITLE
Include title and body when received in background

### ISSUE THREAD

**Issue by Screeze** [arnesson/cordova-plugin-firebase#496]
It seems the title and body information is missing when the notification is received in background and user tapped the notification. Is it possible to also include it in this case? Would be nice if you want to let the user choose something, you could reuse the same message and don't have to add another message as actual data to the notification.

(Workaround: Add 2 custom data fields to the notification in firebase, one called title, one called body and copy the values from title and message fields in there also)

**Comment by morteza-araby** [comment]
Hi, Can you please provide a sample for your Workaround? How should notification looks like?
Thanks

**Comment by morteza-araby** [comment]
OK, I looked at java code, it looks like if you are not sending a notification and only a custom data, body will be ignored and instead you should have 'text' property so, with data object as
const notification = {
            "message": { 
                  "token": pushToken,           
                  "data": {
                    "title": title,
                    "body": msg,
                    "text": msg,
                    "payload": payload,
                  },
                },                
              };
}

I receive body message as well.

**Comment by soumak77** [comment]
Closing as resolved
