### ISSUE TITLE
[iOS] onNotificationOpen doesn`t work, if App is in Background

### ISSUE THREAD

**Issue by wo-github** [arnesson/cordova-plugin-firebase#498]
On iOS the onNotificationOpen Event isn`t called, if the app is closed.
The code:

```
initRemotenotification() {
        let that = this;
        this.firebase.grantPermission();
        this.firebase.getToken().then(token => {
                this.appVersion.getVersionNumber().then(version => {
                    this.authService.getUserInfo().then(user => {
                        this.pushProvider.registerPush(token, this.device.platform, this.device.uuid, version, user);
                    });
                });
            },
            function (err) {
                
            }
        );

        this.firebase.onTokenRefresh().subscribe(token => {
                this.appVersion.getVersionNumber().then(version => {
                    this.authService.getUserInfo().then(user => {
                        this.pushProvider.registerPush(token, this.device.platform, this.device.uuid, version, user);
                    });
                });
            },
            function (err) {
               
            }
        );

        this.firebase.onNotificationOpen().subscribe(notification => {
                this.processAdditionalData(notification);
            }, error => {
               
            }
        );
    }
```

On Android the onNotificationOpen Event fires, if you clicked on the message in the notification bar. On iOS only the app will be open and the homescreen will be shown. The initRemotenotification) function is called, but the onNotificationOpen Event isn`t fired. This work only if the app is in the list of open apps, if you double click on the home button. If the app isn`t in this list, the event will not be fire.
How could I get the message data in iOS, if the app isn`t in the list of open apps?

Plugin Version: 0.1.24
ionic Version: 3.9.2

**Comment by Hanzofm** [comment]
Same problem.

**Comment by amon-ra** [comment]
Same problem on android. With latest ionic

**Comment by jpalvarez** [comment]
Same problem on iOS

**Comment by jpalvarez** [comment]
I just tried the app on a tablet with iOS 9 and everything works fine. Then onNotificationOpen is not called in the coldstart app on iOS 10 and iOS 11.

**Comment by tudordumitriu** [comment]
Same problem here
Plugin version 0.1.25
cordova 6.4.0
cordova-ios: 4.4.0

**Comment by Hanzofm** [comment]
Finally, I managed to solve the problem. In my case the problem was due to a incompatibility with `cordova-plugin-local-notifications`

This plugin captures the event of ondidreceived of ios and disables the normal flow

**Comment by soumak77** [comment]
closing as resolved

**Comment by shikelong** [comment]
@Hanzofm 
How to fix the incompatibility with cordova-plugin-local-notifications ?
local-notification (version: 0.9.0-beta2)
cordovan-firebase-plugin (version: 0.1.25)

Thank you.

**Comment by shivamethical** [comment]
Hi i am getting this issue and i have not local notification plugin !
