### ISSUE TITLE
Invalid GOOGLE_APP_ID closes the app

### ISSUE THREAD

**Issue by maury91** [arnesson/cordova-plugin-firebase#50]
On XCode I'm able to see the following error:

> The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to '(null)'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
> *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.'

Will be useful to catch it so the app doesn't close, and show an alert window, without XCode is really difficult to find this error.

**Comment by robertarnesson** [comment]
Clarified this in the readme, but there is not much more that can be done about it. Firebase SDK requires, and its clearly stated in the installation instructions, that you must have a valid config file in your project.

**Comment by Hasanajouz** [comment]
@maury91  Did you solve this problem?
I am sure that i am using the right "GoogleService-Info.plist" and it is teling me the same error.
Can you please tell me how you solved it?

Thanks.

**Comment by maury91** [comment]
Hi @Hasanajouz in my case the GoogleService-Info.plist was corrupted by Cordova when copying, I solve it by copying it directly to the resource folder after adding the platform.

**Comment by Hasanajouz** [comment]
@maury91 thanks very much this was my problem

**Comment by samiroquai** [comment]
@maury91 Same here. Your solution solved my problem. Thank you.

**Comment by austinemayer** [comment]
Has anyone figured out why Cordova is corrupting this file when copying?

**Comment by fvukovic** [comment]
Can somebody explain what to do step by step or what am i doing wrong..I'm downloaded the GoogleService-Info.plist and i copy it to he root directory of Ionic and the error is the same. Then i put the GoogleService-Info.plist in the root directory of ios platform and the error is the same again. Help please...what i'm i doing wrong?

**Comment by kabus202** [comment]
@fvukovic copy the GoogleService-Info.plist to `platforms/ios/YourProjectname/Resources/Resources`

**Comment by snstarosciak** [comment]
So in my `config.xml`, I replace this: `<plugin name="cordova-plugin-fcm" spec="^2.1.2" />` with:

`<plugin name="https://github.com/lp1bp/cordova-plugin-fcm" spec="^2.1.2" />`?

Do I need to remove the Android platform and add it again?

**Comment by Sroose** [comment]
The solution of @kabus202 works for me, strange enough most of the time but not always. During some builds, still I get an empty GoogleService-Info.plist in the final Resources folder on the Mac. (empty as in an empty plist <dict> object)

**Comment by pvdyck** [comment]
Looks like a path problem => repeating the /Resources/Resources

**Comment by VicBecerra** [comment]
> Hola, @Hasanajouz, en mi caso, Cordova corrompió GoogleService-Info.plist al copiar, lo soluciono copiándolo directamente en la carpeta de recursos después de agregar la plataforma.

De dando sacaron el GoogleService-info.plist?????  lo tengo en la carpeta de ios en recursos pero de donde lo sacan?

**Comment by jmdjr** [comment]
> @fvukovic copy the GoogleService-Info.plist to `platforms/ios/YourProjectname/Resources/Resources`

this path... I am using unity and Xcode to build this, and I don't see a path that starts with platforms/ios/projectname... would I just add a Resources/Resources folder to the root of my Unity-iPhone project?
