### ISSUE TITLE
Push notification problem iOS 11

### ISSUE THREAD

**Issue by fr4ngus** [arnesson/cordova-plugin-firebase#500]
Hi, I'm using Firebase Plugin with iOS 11 SDK and I have the following message problem when I try to send a push notification:
<Warning> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
Maybe is due to my version of SDK (11)
Thank your for your help.

**Comment by Deluxo** [comment]
Experiencing the same issue.

**Comment by alaborderie** [comment]
Hi, getting the same error with `"cordova-plugin-firebase": "^0.1.25"`.
Using iOS11 too, can not try with an older iOS device for now...

**Comment by christocracy** [comment]
[`#grantPermission`](https://github.com/arnesson/cordova-plugin-firebase#grantpermission-ios-only)

**Comment by ccorcos** [comment]
Same issue!

**Comment by christocracy** [comment]
I experienced this until I executed the `grantPermission()` method to allow the user to accept receiving notifications.

**Comment by ccorcos** [comment]
I reverted to v22 and it worked.

**Comment by christocracy** [comment]
Did you execute grantPermission()?

I’m on a pull request which dramatically refractors the entire dependency mgmt system of this plugin, gets rids of the hook script, and uses Cocoapods to install iOS Firebase dependencies.  You don’t want to be crawling back to hide in an old version.

This plugin is in serious need of a makeover.

**Comment by alaborderie** [comment]
I am using `grantPermission()` and the permission is successfully granted in the logs ! The `onNotificationOpen()` is just never called for some reason and I get this log:
`[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`

**Comment by christocracy** [comment]
@alaborderie come try [my fork](https://github.com/transistorsoft/cordova-plugin-firebase/tree/cordova-7.1.0) (Cordova `7.1.0` is required)

```
$ cordova plugin add https://github.com/transistorsoft/cordova-plugin-firebase#cordova-7.1.0
```

If you don't have Cocoapods set up on your system, follow the [Installation](https://github.com/transistorsoft/cordova-plugin-firebase/tree/cordova-7.1.0#installation) steps.

Come chat me at http://www.transistorsoft.com if you have issues.

**Comment by smoral** [comment]
Im experiencing the same issue. When I started using grantPermission the type of push notification "Notification message" started to work but "Data Message" still fires the implemented message of didReceiveMessage (differencies between this 2 types: https://firebase.google.com/docs/cloud-messaging/concept-options).

**Comment by ourarash** [comment]
I'm having the same issue. `grantPermission` does not open the dialog box to get user permission for push notifications. 

Also I wasn't able to use @christocracy branch. It gives me a linker error.

**Comment by christocracy** [comment]
If you’re having problems with my fork, read the README closely.  You need to open your Project.xcworkspace file — not YourProject.xcodeproj.

If you’re having issues with my fork, post an issue at my fork.

My fork dramatically changes the way ios dependencies are loaded (for the better), however it involves some Cocoapod setup.  See the README for iOS setup instructions / issues.

**Comment by christocracy** [comment]
[iOS issues](https://github.com/transistorsoft/cordova-plugin-firebase/tree/cordova-7.1.0)

**Comment by Cicciokr** [comment]
Hi, i use ios 11, and cordova-plugin-firebase version 0.1.25 with cordova-plugin-ionic 2.0.4.
In my case the iphone ask me to accept grant permission for push notification, i accept it. And the when i re open the app, it was blocked with no error message.. someone had the same problem?

**Comment by soumak77** [comment]
@christocracy could you create a PR with your cocoapods integration from your fork?  This will help fix https://github.com/arnesson/cordova-plugin-firebase/issues/672

**Comment by soumak77** [comment]
closing as resolved
