### ISSUE TITLE
Bulid failed with error message

### ISSUE THREAD

**Issue by joy2012bd** [arnesson/cordova-plugin-firebase#502]
Hello sir, I am getting this type of error when run command 'cordova run android'.

- cordova version 7.1.0
- Node version 8.9.1
- Phonegap version 6.4.3

I have one plugin installed 'cordova-plugin-whitelist' with firebase plugin. Please help to solve this problem. Thanks in advance.

:processDebugResourcesinvalid resource directory name: C:\Users\joy2012bd\Deskto
p\Apps\firebaseapp\platforms\android\build\intermediates\res\merged\debug/values
-b+sr+Latn
 FAILED

BUILD FAILED

Total time: 4.135 secs
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
invalid resource directory name: C:\Users\joy2012bd\Desktop\Apps\firebaseapp\pla
tforms\android\build\intermediates\res\merged\debug/values-b+sr+Latn

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
Picked up _JAVA_OPTIONS: -Xmx512M

**Comment by tordnilsen** [comment]
Got the same error. New Ionic project. Only thing added is this plugin.

**Comment by joy2012bd** [comment]
How did you slove it? I removed & added the plugin again. But same problem.

**Comment by tordnilsen** [comment]
@joy2012bd I uninstalled Android Studio, removed all references in environment variables (path etc). Installed newest version of AS, installed packaged and dev-tools. Checked paths, installed newest version of gradle. Took me two days, but now it's up and running

**Comment by soumak77** [comment]
closing as resolved
