### ISSUE TITLE
How do we know if onNotificationOpen comes from a user action or not?

### ISSUE THREAD

**Issue by ccorcos** [arnesson/cordova-plugin-firebase#504]
If the user clicks a notifiation, I want to do something. But if the application is already open, I want to handle the situation differently. How can we know?

**Comment by pmenager** [comment]
The notification object (the one you get via onNotificationOpen) has a tap property.
If tap = false => the notification has been processed without a user action (the app was open).
If tap = true => the user has tapped the notification (the app was in the background).

**Comment by jeangravier** [comment]
Actually I have an issue with that, the tap property is set to true, even if I did not touch the notification itself when application was in background.
I wanted to do some stuff only when user touches the notification, but if I leave the notification un touched, and run the application after it automatically dismissed, the application goes through "onNotificationOpen" callbak and has tap = true

**Comment by HVNT** [comment]
I have the same problem as @jeangravier. I do not think this issue is closed.
