### ISSUE TITLE
FCM with only data not receives messages

### ISSUE THREAD

**Issue by jotae1e** [arnesson/cordova-plugin-firebase#505]
If you send a message with only data in the payload, without notification to be shown, Ionic doesn't receive the message.

CODE -> Node.js
`
var payload = {
            data: {
                campo1: 'valor1'
            }
        };

        admin.messaging().sendToDevice(
            "**token**",
            payload)
            .then(function (response) {
                // See the MessagingTopicResponse reference documentation for the
                // contents of response.
                console.log("Successfully sent message:", response);
            })
            .catch(function (error) {
                console.log("Error sending message:", error);
            });
`

CODE -> In Ionic:

`
this.firebase.onNotificationOpen().subscribe(
      data => {
        if (data.wasTapped) {
          console.info("Received in background")
          console.info("1: " + JSON.stringify(data))
        } else {
          console.info("Received in foreground");
          console.info("2: " + JSON.stringify(data));
        };
      });
`

**Comment by smoral** [comment]
Something similar i guess: #500

**Comment by jotae1e** [comment]
Something similar i guess: #500
