### ISSUE TITLE
`getToken()` intermittently doesn't return device token on Android - help debugging this

### ISSUE THREAD

**Issue by gianpaj** [arnesson/cordova-plugin-firebase#506]
Hi,

I have an Ionic app in production and I get some random errors from users in our error tracking service (Sentry).

The code is like this:
```
this.firebase.getToken()
  .then(token => {
    console.log(`The token is ${token}`);
    this.mixpanelPeople.setPushId(token);
```

`token` appears to be undefined (i'm not 100% sure).
Mixpanel's `setPushId(...)` function is the one that error's out:
```
Error: Uncaught (in promise): invalid pushId: 
```

I tried disabling notifications on an Android 8.1, but I can't manage to reproduce this.
On an Android 5.1 phone, it just works as you have to accept all the permissions when you install the app (before 6.0).

Any suggestions on what else I can try?

The error occurred on Android 5.1, 6.0.1 and 7.0.

Maybe related to issue?: https://github.com/arnesson/cordova-plugin-firebase/issues/277

Some info:
```
$ yarn list --pattern cordova-plugin-firebase
└─ cordova-plugin-firebase@0.1.24

$ ionic info

cli packages: (/Users/gianfranco/.config/yarn/global/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v6.11.3
    npm               : 5.6.0
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/gianfranco/Library/Android/sdk

Misc:

    backend : legacy
```

**Comment by robertarnesson** [comment]
the token can be null / undefined. I suggest checking if it is before trying to send it to mixpanel

**Comment by PunitNamdeo** [comment]
Hi @robertarnesson  ,

I have done as it is which you have suggested in git plugin but still token is undefined.
I am calling plugin on device ready only.

Can you please help ?
