### ISSUE TITLE
Problems with iOS 11.2

### ISSUE THREAD

**Issue by juancafe4** [arnesson/cordova-plugin-firebase#508]
Hi,
I can get notifications everything works; however, the problem is in the subscriber onNotificationOpen is only called once after that it calls onNotificationOpen again. If you install again the app onNotificationOpen will be called but only once.

Where should I call on notification open ?

Thanks

**Comment by simoncena** [comment]
Same problem

**Comment by jotae1e** [comment]
I think that you must create a service (provider)

**Comment by Hanzofm** [comment]
Can someone explain how would be the best way to implement this?

onNotificationOpen should be open when an user clicks on notification in this cases on both ios, and android:

cold start(app closed)
app in background (minimised)
app is in foreground

Is this correct?

thanks

**Comment by robertarnesson** [comment]
the callback will be triggered when the user clicks on a notification, or when a notification arrives while the app is in the foreground.
