### ISSUE TITLE
Crashes Ionic 3 App

### ISSUE THREAD

**Issue by divanvb** [arnesson/cordova-plugin-firebase#509]
Hi

I've installed the plugin as stated in the Ionic Docs, trying to use the function verifyPhoneNumber() but as soon as it's called, it crashes my entire app without any error messages.

Any help would be appreciated.

**Comment by divanvb** [comment]
Still having this issue.

**Comment by soumak77** [comment]
@divanvb please try again with version 1.0

**Comment by soumak77** [comment]
should be fixed by version 1.0.2
