### ISSUE TITLE
Can't download dependencies

### ISSUE THREAD

**Issue by LordAmarth** [arnesson/cordova-plugin-firebase#51]
Hello
I tried to reinstall plugin and run app then this happened:
![image](https://cloud.githubusercontent.com/assets/4609432/18433413/afaf9126-78e7-11e6-85e2-b5188a6ccbbc.png)

Are dependencies really missing on server or I am doing something wrong ?
Thanks

**Comment by c4software** [comment]
Hi,

You have to add the « Google Repository » in the Android SDK Manager.

![capture d ecran 2016-09-12 a 13 20 51](https://cloud.githubusercontent.com/assets/988914/18434152/c8253dd8-78eb-11e6-90fe-4b0a000b6d93.png)

**Comment by LordAmarth** [comment]
It's installed but few hours ago it suddenly crashed after reinstall (around 10:30 AM UTC+01:00)

![image](https://cloud.githubusercontent.com/assets/4609432/18434189/f66970b0-78eb-11e6-881b-6dcc89385023.png)
