### ISSUE TITLE
Updated GoogleServices-Info.plist isn't working right...

### ISSUE THREAD

**Issue by ccorcos** [arnesson/cordova-plugin-firebase#510]
I changed `GoogleServices-Info.plist` to point to a new project and updated the app through the App Store. The firebase tokens appear to register properly, but the notifications aren't going through. When I delete the app entirely and reinstall it, I get a new token and notifications are going through. 

I suspect that firebase is somehow stuck on the old configuration when I update the app. Any ideas?

**Comment by austinemayer** [comment]
I am experiencing a similar issue. I created a ```GoogleServices-Info.plist``` for a new project and it works when installed locally through xcode, but when I create an IPA file and install it over the air the notifications are not going through.

**Comment by ccorcos** [comment]
I just verified this...

I exported my applications to .ipa files and used `ipa-deploy` to put them on my phone. When I install version 0.2.0 (with old firebase tokens), run the application, and then install 0.2.2 with the new keys, the notifications don't go through. The app state is kept around because I don't need to re-login. However if I delete the app entirely and install 0.2.2, everything works.

**Comment by ccorcos** [comment]
Ah. I've tracked down this error:

```
Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}
```

**Comment by ccorcos** [comment]
@robertarnesson I'm having trouble with this again. Luckily its only on our beta app so I can tell people to uninstall and reinstall, but its scary that I don't know how to fix this if it were to happen in production.

**Comment by charlie-rushton** [comment]
@ccorcos did you eventually figure this out? My app was receiving push notifications no problems and then suddenly this error occurs. I see the notifications in Xcode debugger but they don't come through to the device.

**Comment by ccorcos** [comment]
Sadly, push notifications are a complete nightmare which horrible debugging tools.
