### ISSUE TITLE
Erro on publish app to AppStore

### ISSUE THREAD

**Issue by pawanvivekananda** [arnesson/cordova-plugin-firebase#513]
iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseAnalytics.framework/FirebaseAnalytics' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseInstanceID.framework/FirebaseInstanceID' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/GoogleIPhoneUtilities.framework/GoogleIPhoneUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/GoogleInterchangeUtilities.framework/GoogleInterchangeUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseMessaging.framework/FirebaseMessaging' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/FirebaseCore.framework/FirebaseCore' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/GoogleUtilities.framework/GoogleUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

iTunes Store Operation Failed
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'The Sample App.app/www/plugins/cordova-plugin-fcm/src/ios/firebase/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

**Comment by premtemp1** [comment]
Were you able to resolve this issue?

**Comment by robertarnesson** [comment]
seems like your are including things in your bundle that shouldnt be there. also cordova-plugin-fcm is not this plugin
