### ISSUE TITLE
[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by javasol1** [arnesson/cordova-plugin-firebase#514]
I am able to run notification just fine in Android using same project, but on on IOS, when i send the notification through FCM, this is the message i see in log.

[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

This is just a helloworld application nothing fancy here. Just to make sure that nothing else is causing this issue

**Comment by sarawutl** [comment]
same +1

**Comment by vinicius-ov** [comment]
Same here. Target iOS 11 real device. Using latest version of the plugin. onNotificationOpen() won't trigger but getToken() and grantPermission() are working and I get the same message: 
[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by prashant37** [comment]
+1 :(

**Comment by michaelreiser** [comment]
Check the Capabilities tab in Xcode before you build the app.  Even though my App ID had notifications enabled, this was turned off in Xcode after my last Xcode update.  I had to turn it on there, then remove and re-add the iOS cordova platform in my app.  After that, it started working.

**Comment by vinicius-ov** [comment]
+1 @michaelreiser solved the issue by turning on Push Notifications on Capabilities Tab and configuring Firebase with APN key.

**Comment by gregor-srdic** [comment]
I had this problem because i didn't call `grantPermission` method ...

**Comment by RAJUSIVASANKAR** [comment]
i found the problem, which is I forgot this line

Messaging.messaging().delegate = self
in this method:

func application(_ application: UIApplication,
               didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {}

Then take 
public func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage){
    print(remoteMessage.appData)
}
