### ISSUE TITLE
Error with AdMob Free Plugin

### ISSUE THREAD

**Issue by danielpalen** [arnesson/cordova-plugin-firebase#515]
When installing this plugin in combination with AdMob Free 'ionic cordova build android' the process throws the following error.

```
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzau.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.655 secs

Error: /Users/Daniel/Code/baseball/baseball_app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzau.class
```

This error is clearly introduced by the combination of the two plugins. I checked this in a fresh ionic project where I only installed these two plugins and got the same error.

I did find this issue which seems to have a similar problem (https://github.com/arnesson/cordova-plugin-firebase/issues/387). Removing the following two lines from plugin.xml in this repo did not solve the error though.
```
<framework src="com.google.gms:google-services:+" />
<framework src="com.google.android.gms:play-services-tagmanager:+" />
```

**Comment by Calsy** [comment]
Receiving same issue as above.

**Comment by bulbul-ismail** [comment]
+1

**Comment by bulbul-ismail** [comment]
downgrading version of AdMob plugin resolved my issue
remove old admob plugin then 
`
cordova plugin add cordova-plugin-admob-free@0.12.1`

**Comment by soumak77** [comment]
Try installing https://github.com/dpa99c/cordova-android-support-gradle-release or https://github.com/dpa99c/cordova-android-play-services-gradle-release to fix the gradle build

**Comment by write2sandip** [comment]
use https://www.npmjs.com/package/cordova-plugin-firebase-extended-notification  plugin
