### ISSUE TITLE
App disconnected from fcm

### ISSUE THREAD

**Issue by etakh** [arnesson/cordova-plugin-firebase#517]
Hi,

I am using Xcode 8 and developed my iOS app for iOS9 and iOS10. The notification is successfully received in the app. But when I am clearing the app from background, the Xcode console shows "App disconnected from fcm" and app crashes after that. How can I fix this issue?

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
