### ISSUE TITLE
Not working when using with customizing and using Phonegap Build

### ISSUE THREAD

**Issue by smv-kepler** [arnesson/cordova-plugin-firebase#519]
Hello,
in the README you suggest that when using PGB one should fork this repo, customize it with the data from Firebase and use this in Phonegap Build.
I have done this (see https://github.com/smv-kepler/smv-kepler-app-firebase) but Firebase still does not work:
I am using the following code to initialize the plugin:
```
if (typeof window.FirebasePlugin !== "undefined") {
      window.FirebasePlugin.subscribe("all");
      alert("Plugin found (1)");
      window.FirebasePlugin.logEvent("select_content", {content_type: "page_view", item_id: "home"});

      window.FirebasePlugin.getToken(function(token) {
         alert(token);
      }, function(error) {
         alert(error);
      });
} else {
    alert("Plugin NOT found (2)");
}
```
and I am getting the alert "Plugin found (1)" but it doesn't show any token (empty/null), I don't receive notifications and the event that should be logged doesn't show up in the Firebase Console.
It seems like it is not properly getting my custom "google-services.json" but I don't understand why or what I should do differently.

**Comment by smv-kepler** [comment]
SOLVED: The problem was that I used my _project_ id in plugin.xml instead of my _app_ id.

**Comment by thienanle** [comment]
@smv-kepler were you able to successfully get PhoneGap Build to build with this plugin? If so, what did you have to do to get it working?

There's a question about it here https://github.com/arnesson/cordova-plugin-firebase/issues/907 I'm wondering if you could shed some light on?
