### ISSUE TITLE
Android on build :: variable conflict with phonegap-plugin-push :: duplicate string google_app_id after merge resources

### ISSUE THREAD

**Issue by davixz** [arnesson/cordova-plugin-firebase#52]
Hello guys!

Thanks for the plugin!

I have this problem because phonegap-plugin-push and this plugins both use google_app_id variable input. This result in a conflict when i try to build android version of my app.
The google_app_id in the push plugin is used for the GCM and here is used for Firebase.
Would be possible/viable to change the name of the variable like fb_google_app_id
There is also the thing that google is not deprecating GCM in favor of FCM, i dont know if the App Ids will be the same, in that case would not need to change the variable id.

Ill still use GCM for a while so if you have no plan to update the variable name i guess the only option i have is to fork the project and do a find/replace

Thanks again!

**Comment by robertarnesson** [comment]
This plugin replaces phonegap-plugin-push, they are not compatible with eachother. 

The variable can not be changed since its required by Firebase. The easy solution would be to use only this plugin, but if you really need to keep GCM you can fork and remove the variable. You will run into issues though (duplicate dependencies, etc)

**Comment by Alkasih** [comment]
> .The easy solution would be to use only this plugin

What do you mean by this? 

I need to use both Firebase and ionic-push-notification which must use phonegap-plugin-push.

I am using Firebase only for database usage, and Ionic push notifications has been set up for whole API (which impossible to move user authentication to firebase)
