### ISSUE TITLE
Android - icon is just white square

### ISSUE THREAD

**Issue by Yuripetusko** [arnesson/cordova-plugin-firebase#520]
No matter what I try my icon is just white square.

My icon is in PNG24 with alpha transparency, named `notification_icon` it's in appropriate sizes in different `platform/android/res/drawable-XXX/` folders.

- I tried route with adding `<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />` to Manifest file,

- I tried route with adding `values/styles.xml` and `values-v21/styles.xml` with notification_icon specified there

- I tried sending icon prop in FCM payload

- I even tried replacing `mipmap-XXX/icon.png` with transparent png icon

nothing works :( still just seeing white square in status and pull-down notifications

**Comment by write2sv** [comment]
I am in the same boat here. Have been trying to get this working since about 2 days. Tried all the above mentioned routes except the last one. Going crazy. Any help to resolve this will be very much appreciated.

**Comment by Yuripetusko** [comment]
What else I also tried that didn't work:

- Creating `-v11` folders for newer androids i.e. `drawable-xxxhdpi-v11`
- Using PNG provided by firebase sample app https://github.com/firebase/quickstart-android/tree/master/messaging/app/src/main/res

**Comment by Yuripetusko** [comment]
I did some debugging using `adb logcat` and I can see this when notification is received

`01-04 01:30:10.483 12737 13536 E FirebaseMessaging: Icon with id: 2130903040 uses an invalid gradient. Using fallback icon.`

**Comment by Yuripetusko** [comment]
Here is my icon in res folder, and all other sizes are there also

![screenshot 2018-01-04 02 08 54](https://user-images.githubusercontent.com/666169/34547606-4543d280-f0f4-11e7-8cba-52e505d48fbc.png)

**Comment by Yuripetusko** [comment]
I finally switched to `phonegap-plugin-push` and icon is showing there

**Comment by amritk** [comment]
I found the payload you send actually messes up the icon. What were you sending server side?

**Comment by Yuripetusko** [comment]
@amritk I tried 2 APIs

- First one:
https://firebase.google.com/docs/cloud-messaging/admin/send-messages

```
await firebaseMessaging.sendToDeviceGroup(notificationKey, {
      notification: { "title": "Testing", "body": "Hello World", "icon": "notification_icon" },
});
```

- Second one:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send

```
const messagePayload = {
      validate_only: false,
      message: { "notification": { "title": "Testing", "body": "Hello" }, "android": {"notification": { "title": "Testing", "body": "Hello", "icon": "notification_icon"}}, "topic": "testing"},
};

const response = await fetch(
      'https://fcm.googleapis.com/v1/projects/bridebook-test/messages:send',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify(messagePayload),
      },
);
```

Bot are sending notification fine but with no icon again (white square instead) and logcat warning about not being able to find icon with a name `notification_icon`

**Comment by amritk** [comment]
@Yuripetusko yea thats the same setup I have, I just recently switched from the phonegap-push-plugin and found that my icon worked with that plugin but not with this one. I had to switch my payload from data to a combination of notification and data. Currently I have this for both android and iOS:
```
{
  notification: {
    title,
    body,
    icon,
    color
  },
  data: {
    title,
    body
  }
}

**Comment by Yuripetusko** [comment]
Thanks, too late to try for me as I am happily using other plugin now, but might help others in future. :)

**Comment by write2sv** [comment]
Hi @amritk 

I am still facing the issue with icon.

Notification.color seems to be working!! but the icon is still square. Do you mind sharing the icon you are using. I just want to ensure it has nothing to do with the image itself. I have used notification icon generator from https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit

Here is the payload:
 notification: {
                title: 'something here',
                icon: "notification_icon",
                color: "#ec4882"
            },
            data: {
                title: 'something here'            
            }

Any other suggestions?

Thanks,
Surya.

**Comment by amritk** [comment]
![notification_icon](https://user-images.githubusercontent.com/2039539/34699685-c42bf1ca-f4ac-11e7-9a3f-8385f407a8d2.png)

**Comment by write2sv** [comment]
Thanks! Will give it a try

**Comment by write2sv** [comment]
Hi @amritk I still have the same issue :( May I know whats your target android version for the app.

**Comment by amritk** [comment]
@write2sv 27

**Comment by jonasbark** [comment]
https://stackoverflow.com/questions/48137775/fcm-default-icon-uses-invalid-gradient
same issue I guess

**Comment by AMerkuri** [comment]
![image](https://user-images.githubusercontent.com/969989/35440447-1c67a2e0-02a8-11e8-835a-b6a7831e0494.png)
I have same issue on OnePlus3 Oreo. minSdkVersion=21, targetSdkVersion=27

**Comment by write2sv** [comment]
Just want to update here. I started seeing the icon after the latest 8.1 update on my Nexus 5x. The issue might still exist on the older version.
My Payload is still:
notification: {
title: 'something here',
icon: "notification_icon",
color: "#ec4882"
},
data: {
title: 'something here'
}

Thanks!

**Comment by Yuripetusko** [comment]
I am on latest android Oreo nexus5x

**Comment by amritk** [comment]
Yea I think this has something to do with 8.1. But not on all devices.

**Comment by jonasbark** [comment]
Yes, it's a bug on the current version of the Firebase library. Please refer here, as mentioned earlier:
https://stackoverflow.com/questions/48137775/fcm-default-icon-uses-invalid-gradient

**Comment by Yuripetusko** [comment]
Cool @jonasbark  thanks for the info, yes this seems like exactly what was happening with me, will wait for firebase to fix it. But for now I am using push plugin

**Comment by soumak77** [comment]
closing as resolved

**Comment by almasmaris** [comment]
@Yuripetusko Hi, can you describe it for me how to use phonegap-plugin-push for firebase? should i remove firebase cordova plugin or not? I also encounter this issue.

**Comment by Yuripetusko** [comment]
@almasmaris yes you remove firebase cordova preferably. Then add `cordova-plugin-push` then you need to add firebase files to the root of your project `GoogleService-Info.plist` for ios and `google-services.json` for android - you can download them from your firebase dashboard

If you are using FCM for apple then yo udon't have to do anything, alternativly if you use APNS you can change `GoogleServices-info.plist` setting to say 

```
<key>IS_GCM_ENABLED</key>
<false></false>
```

**Comment by Yuripetusko** [comment]
I also had to specify this in my package.json

```
"phonegap-plugin-push": {
        "FCM_VERSION": "11.8.0"
      },
```

because on ios firebase version from Crashlytics plugin was clashing with push plugin firebace version

You then go through cordova-plugin-push guide on installing firebase to your projects, for ios it will require some work with Cocoapods.. not easy guide but it works well for me now

**Comment by almasmaris** [comment]
@Yuripetusko thank you for the response. 
What about notification callback when the app on foreground? i can't find the method to check it.

**Comment by Yuripetusko** [comment]
@almasmaris 

You can check payload fo notification to see if it was received while app was in foreground

```
push.on('notification', notification => {
      if (notification) {
        const {
            foreground,
            coldstart,
            dismissed,
        } = notification.additionalData;
        if (foreground) {
          alert(notification.message)
        }
      }
    });
```

**Comment by Yuripetusko** [comment]
@almasmaris 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback

**Comment by almasmaris** [comment]
@Yuripetusko i see. I thought i need another method for the foreground, thank you so much

**Comment by almasmaris** [comment]
@Yuripetusko hey, how could i get the firebase token?

**Comment by Yuripetusko** [comment]
@almasmaris you don't really need a token, you need to place those 2 files in root of your project, you you get them by downloading them from your firebase dashboard settings. Project settings `project/${yourappid}/settings/general/` under `Your apps` section on the right there's option to download file for ios and android

**Comment by Yuripetusko** [comment]
then when you install the push plugin or prepare the project it will use these files and copy them over to corresponding platform
