### ISSUE TITLE
Turn on / turn off Push Notification

### ISSUE THREAD

**Issue by wilfredonoyola** [arnesson/cordova-plugin-firebase#522]
I tried doing it with unregister method and then get a new token. I have also tried with subscribe / unsubscribe method, and both ways do not work correctly for me.

Anyone has any suggestions to implement turn off and turn on the notifications, I spent more than 10 hours trying different ways.

I am using the last version (cordova-plugin-firebase@0.1.25)

Thanks for you support!

**Comment by wilfredonoyola** [comment]
We have integrated a solution easy:
1. Added an end point /api/mute_push_notification, This one remove/add the token from our database. 
2. On the app we have toggle that turns it on and off.

Maybe, This is just a workaround.
What do you think ?

Thanks for your support.

**Comment by robertarnesson** [comment]
This is what I would suggest as well
