### ISSUE TITLE
Rich media iOS with images

### ISSUE THREAD

**Issue by jcarlosfern** [arnesson/cordova-plugin-firebase#523]
Does anyone have any sample of sending images with the notifications? I can't get any image with the push notifications. Thank you.

**Comment by kurtiev** [comment]
Hi @jcarlosfern !
Did you find any solutions?

**Comment by briantq** [comment]
@jcarlosfern @kurtiev FCM does not provide the ability to do such a thing.  What it does allow for is for you to specific custom fields (maybe with photo urls) that you can handle on the client when a notificaton is recieved. Check out this [comment ](https://github.com/arnesson/cordova-plugin-firebase/issues/838#issuecomment-419942151) for more information.
