### ISSUE TITLE
Firebase Crash Reporting OR Crashlytics?

### ISSUE THREAD

**Issue by pvandrunen** [arnesson/cordova-plugin-firebase#524]
I'm using firebase solely for the purpose of crash reporting, we've already implemented a myriad functions (notifications, analytics, etc) using other plugins/services.

Can someone walk me through the steps of getting this running on my ionic/cordova app?

What I've done thus far:
1. Install plugin
2. Add .plist file
3. run $ ionic cordova prepare ios
4. Added this code, which made my "firebase not setup" error message in the log go away
  #import <FirebaseCore/FIRApp.h>
   [FIRApp configure];

In the firebase website/console my only option is to setup Crashlytics.

Do I need to do something with cocoa pods? Do I need to download an configure symbol file so that I can get readable crash reports? Do I need to make the app crash? Do I need to install the firebase SDK?

I'm not seeing anything on the firebase website that indicates I have crashlytics or crash reporting setup. Analytics is populated with some stuff. No error messages in the console.

Also, when this plugin is installed I get a pop-up that asks for a password [Environment: Sandbox] It seems like it's triggering a bunch of in-app purchase code that we've temporarily disabled — I haven't looked into that yet.

**Comment by pvandrunen** [comment]
Additional information, in iOS I see bugs in the debug panel, but they are truncated, only show the first few characters.  They don't show up anywhere else.

```javascript
window.onerror = function(message,url,line){
      FirebasePlugin.logEvent(`${message}, ${url}, ${line}`);
    };
```

**Comment by joshbabb** [comment]
Also watching this issue...  Same problem, except on Android.  No indication that I'm set up whatsoever, but promises return success messages.  I just can't see anything in the Firebase console.

**Comment by jcyh0120** [comment]
Want to know this, too.

**Comment by pvandrunen** [comment]
@joshbabb @jcyh0120 I've abandoned firebase and moved to rollbar for my ionic/cordova app. Setup was lightening fast and we're so relieved to finally have reporting on iOS and Android. 
 This supports javascript error reporting, we're now paying customers.  https://rollbar.com

**Comment by jcyh0120** [comment]
@pvandrunen thanks! For hybrid app like ionic, it's always confusing to use Javascript SDK or Native SDK with cordova. Any suggestion for using rollbar with ionic using JS/Native SDK?

**Comment by pvandrunen** [comment]
@jcyh0120 Why not both!? 
I have both the ng-rollbar installed and the cordova plugin. Javascript is very useful but I kinda forgot that I had installed the cordova plugin, I never was able to simulate a crash.  I seem to get pretty comprehensive reports in rollbar, I couldn't say if the cordova plugin has much to do with the reports that I'm seeing. Sorry I can't be more help.

**Comment by jcyh0120** [comment]
@pvandrunen Great idea! I've been using Firebase CrashReport to log my JS error. But it's really not that handy for JS. I never think of using both before. They have different roles. Maybe I should log my JS error with ng-rollbar and  log my crash with native SDK.  Thanks for reply.

**Comment by soumak77** [comment]
closing in favor of https://github.com/arnesson/cordova-plugin-firebase/issues/548
