### ISSUE TITLE
Error :The default Firebase app has not yet been configured iOS

### ISSUE THREAD

**Issue by premtemp** [arnesson/cordova-plugin-firebase#535]
Hello,
 I am getting the following error..

[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization

I am using  the command -->cordova plugin add cordova-plugin-firebase@0.1.25 --save

cordova 6.5
 android 6.3.0
  ios 4.5.4

I have no issue with android

Please advise..

Thanks

**Comment by premtemp1** [comment]
I installed the version from the  master and error seems to go away
cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --save

Not sure if this is the correct approch

**Comment by kylesziv** [comment]
I installed like you did above and it still doesn’t work for me.

**Comment by robertarnesson** [comment]
new release coming up

**Comment by chrisid** [comment]
same happens to me @ 2.0.2 iOS 12
tried several things, new blank App, removed and reinstalled the plugin, and I'm being sure Google.plist is always correct, none works.

The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

**Comment by briantq** [comment]
@chrisid Can you open a new issue?  I know it is working in my application using v2.0.2 on iOS 11.  I wonder if it's a iOS 12 issue... That being said I haven't seen anything related to Firebase not working with iOS 12.  By opening a new issue, we can see if others are encountering the same thing.
