### ISSUE TITLE
Warning message : [Firebase/Analytics][I-ACS025018] Event not logged.

### ISSUE THREAD

**Issue by premtemp** [arnesson/cordova-plugin-firebase#536]
Hello,
  I just install the latest version in my cordova app but I not seeing any event in firebase,,, I turn on debug on Xcode and this is what I see

Jan 16 18:53:51 [9081] <Warning>: [Firebase/Analytics][I-ACS025018] Event not logged. Call +[FIRApp configure]: page_view

this is my test log statement
window.FirebasePlugin.logEvent("page_view", {page: 'testpage'});

How can I get my app to save an event

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
