### ISSUE TITLE
BUG - the notification "flow" is broken in the latest IOS version

### ISSUE THREAD

**Issue by tryadelion** [arnesson/cordova-plugin-firebase#537]
currently, per documention, the notification flow is the next:

Notification flow:

> App is in foreground:
> User receives the notification data in the JavaScript callback without any notification on the device itself (this is the normal behaviour of push notifications, it is up to you, the developer, to notify the user)
> App is in background:
> User receives the notification message in its device notification bar
> User taps the notification and the app opens
> User receives the notification data in the JavaScript callback
> 

I've got reports from users, and have been able to verify them by checking the logs, that on some IOS devices running 11.2,  iphone X and iphone 6s to be concrete, the "App is in background" doesn't apply. the notifications are shown on the status bar, quickly dissapear and the avaScript callback is executed even when the application hasn't yet been opened, causing the user to miss the notification completely until he opens the app. even the badge dissapears.

I haven't been able to reproduce it in android or in the ios emulators.

**Comment by leyenda** [comment]
Hello, I have the same issue, Iphone 6 IOS 11.2 .   Have you been able to solve it?

**Comment by nekrodomus** [comment]
I have the same issue, **Iphone 6 IOS 11.1.2**

**Comment by tryadelion** [comment]
i had to disable background modes on XCODE but that is just a bad workaround, we should have more control on when a notification is displayed or not

**Comment by Hanzofm** [comment]
Someone solve this?

**Comment by Michazzz** [comment]
Same here, iPhone 6s, IOS: 11.2.6

**Comment by nekrodomus** [comment]
if (this.platform.is('ios')) {
      this.firebase.grantPermission();
}

**Comment by Michazzz** [comment]
@nekrodomus Yeah, universal solution for every developer. No, it is not. I already have this in my code and problem still occures.

**Comment by kyleamadio** [comment]
Could I ask someone post their main AppDelegate.m file from IOS?

I am very confused as to what is supposed to go into this file. My reading of the docs suggests just installing the Plugin should be enough. I should not have to modify AppDelegate.m

**Comment by kyleamadio** [comment]
Have a look at this https://github.com/arnesson/cordova-plugin-firebase/issues/577

I did get it working with these changes and files

**Comment by tryadelion** [comment]
disabling background modes did fix it without having to change stuff, but it's not an option, what if i had to track user's geolocation?

**Comment by Hanzofm** [comment]
Finally, I managed to solve the problem. In my case the problem was due to a incompatibility with `cordova-plugin-local-notifications`

This plugin captures the event of ondidreceived of ios and disables the normal flow

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
