### ISSUE TITLE
after_prepare.js broken when more than one app exists in google-services.json

### ISSUE THREAD

**Issue by nikmartin** [arnesson/cordova-plugin-firebase#539]
If you have multiple android apps in a firebase project, google-services.json contains an array of client_info objects. after_prepare.js just grabs the first one. At a minimum, the README should note this and specify that the user must edit google-services.json for each project.

**Comment by robertarnesson** [comment]
can you please try this PR? https://github.com/arnesson/cordova-plugin-firebase/pull/552

**Comment by soumak77** [comment]
closing in favor of https://github.com/arnesson/cordova-plugin-firebase/issues/791
