### ISSUE TITLE
Hanging on launch

### ISSUE THREAD

**Issue by hisshash** [arnesson/cordova-plugin-firebase#54]
Hey,

I built my app today and noticed it was hanging badly on start up.
If i wait long enough it would eventually load up (around 3 - 4 mins).

Removed all plugins & app worked fine added everything one by one and its this plugin that causes the hang.
Removed all other plugins bar firebase and still get a hang

I have latest android SDK's
up to date Cordova
I've updated this plugin to .12 and still getting it

This plugins worked 100% up until today. Any ideas?

Cheers

**Comment by robertarnesson** [comment]
what platform? what does the log say

**Comment by madebydavid** [comment]
Which version of Android? I began noticing a similar issue today where my cordova app using this plugin would hang after I upgraded to 7.0.

From my logcat:
```
...
E ActivityManager: ANR in com.myapp.beta
E ActivityManager: PID: 19251
E ActivityManager: Reason: Broadcast of Intent { act=com.google.firebase.INSTANCE_ID_EVENT flg=0x10 cmp=com.myapp.beta/com.google.firebase.iid.FirebaseInstanceIdInternalReceiver (has extras) }
E ActivityManager: Load: 8.07 / 8.52 / 8.37
E ActivityManager: CPU usage from 591963ms to -1ms ago (2016-09-14 22:34:56.967 to 2016-09-14 22:44:48.931):
...
```

One of the only references I could find was [on StackOverflow](https://stackoverflow.com/questions/37594710/timeout-of-broadcast-broadcastrecord-using-firebase-crash-services)

Maybe unrelated, but my symptoms are similar, just posting incase it's helpful.

**Comment by hisshash** [comment]
This is happening on Android 6.0.1 & also 7.0

```
...
09-15 09:50:27.383   779   795 E ActivityManager: ANR in co.runawaypets.runawaypets
09-15 09:50:27.383   779   795 E ActivityManager: PID: 7013
09-15 09:50:27.383   779   795 E ActivityManager: Reason: Broadcast of Intent { act=com.google.firebase.INSTANCE_ID_EVENT flg=0x10 cmp=co.runawaypets.runawaypets/com.google.firebase.iid.FirebaseInstanceIdInternalReceiver (has extras) }
09-15 09:50:27.383   779   795 E ActivityManager: Load: 9.43 / 8.29 / 4.42
09-15 09:50:27.383   779   795 E ActivityManager: CPU usage from 137350ms to -1ms ago:
...
```

These are the only kind of errors im seeing in my catlog, not sure if they're related though

```
...
09-15 09:50:27.383   779   795 E ActivityManager:   5.5% 779/system_server: 2.7% user + 2.7% kernel / faults: 15520 minor 19 major
09-15 09:50:27.383   779   795 E ActivityManager:   1.5% 220/adbd: 0.2% user + 1.3% kernel / faults: 3055 minor
09-15 09:50:27.383   779   795 E ActivityManager:   0.9% 212/sensors.qcom: 0.3% user + 0.5% kernel / faults: 70 minor
...

...
09-15 09:50:28.236  7013  7125 D FirebasePlugin: Starting Firebase plugin
09-15 09:50:28.254  7013  7013 I cr_Ime  : ImeThread is not enabled.
09-15 09:50:28.254   790   790 W Binder_2: type=1400 audit(0.0:98): avc: denied { ioctl } for path="socket:[46098]" dev="sockfs" ino=46098 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-15 09:50:28.254   790   790 W Binder_2: type=1400 audit(0.0:99): avc: denied { ioctl } for path="socket:[46098]" dev="sockfs" ino=46098 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-15 09:50:28.280   779   789 D ConnectivityService: listenForNetwork for Listen from uid/pid:10186/7013 for NetworkRequest [ id=13, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
09-15 09:50:28.306  7013  7124 I OpenGLRenderer: Initialized EGL, version 1.4
09-15 09:50:28.526  7013  7138 E libEGL  : validate_display:255 error 3008 (EGL_BAD_DISPLAY)
09-15 09:50:28.533   779   800 I ActivityManager: Displayed co.runawaypets.runawaypets/.MainActivity: +1m3s432ms
09-15 09:50:28.581  1669  1692 W SearchService: Abort, client detached.
...
```

I only use firebase for the push notifications & was running `.10` fine with no problems, seemed like it happened overnight after i did some minor HTML changes and published. Tried to update to the latest -v `.12` and still getting the same.
Double checked the json files, their in the platform with the correct info.

Im not fully sure what to look out for though so i put the whole log in a gist up until the phone crashed [here](https://gist.github.com/hisshash/2fc35c098139df96c9d4df82c641a610).

**Comment by robertarnesson** [comment]
what if you go back to .10, does it work?

**Comment by hisshash** [comment]
No that doesn't work

**Comment by hisshash** [comment]
Just reading up on @madebydavid [Firebase crash](http://stackoverflow.com/a/39488884/1893067) post. Perhaps it could be something due to this? If i wait for long enough my app eventually does start then after that the app will start normally? I cant actually remove the dependency as it keeps getting re-injected, but what do you think?

**Comment by hisshash** [comment]
Hey @robertarnesson I just got it to work.
In `platforms/android/project.properties` I removed the line `cordova.system.library.6=com.google.firebase:firebase-crash:+`.

Seems like we'l need to wait untill Google releases a fixed version of the GPS before enabling Firebase Crash again

**Comment by guyromb** [comment]
I have the same issue on Android 4.4.4

**Comment by Venkat-TTapp** [comment]
Hello,

I would like to integrate firebase in my phonegap build app for iOS and Android. I am very apprehensive to use this because of this issue. 

I find this issue to be fixed in Firebase Status Dashboard (Check below link). I would like to get confirmation from you if you find this issue to be resolved.

https://status.firebase.google.com/incident/Crash%20Reporting%20%28Beta%29/16003

Waiting for your response.

Regards,
Venkat
