### ISSUE TITLE
Plugin not working on iOS

### ISSUE THREAD

**Issue by premtemp1** [arnesson/cordova-plugin-firebase#541]
Hello,
 Please let me know the steps to get it working on iOS.. I am not doing push notificatiion, just want to install SDK and see the default data written to firebase console.  Android app is working but iOS is not.. This is what I have done

1: create the app in firebase . for android and iOS ( different package name)
2: download the .json and .plist file
3: place the file at the root of my project
4: install the plugin from main..
5: verify that file are copied correctly in the respective platform
6: open my app

7 go the firebase console -- debug screen
    I see the data for android
   no information for android

no error in the xcode console , enable debug flag

Am i missing a something?...

**Comment by soumak77** [comment]
@premtemp1 please try again with version 1.0

**Comment by soumak77** [comment]
closing as resolved
