### ISSUE TITLE
Notification in background doesn't launch the app when tapping it (Android)

### ISSUE THREAD

**Issue by ulisesvera** [arnesson/cordova-plugin-firebase#542]
I can receive the notification in my Android device, and if I have the app opened it works fine when I touch it. But if it's closed and I tapped the notification, it does nothing. The app is not launched.

Any idea? 
Thanks

**Comment by ulisesvera** [comment]
I have just noticed that it was an issue of my server side config (I was udpdating from FCMPlugin and I had to remove 'click_action' option).

Sorry for opening this issue, and thanks for the plugin.

**Comment by metractive** [comment]
Solved my problem too, thank you @ulisesvera

**Comment by darshantejani007** [comment]
Hi!
I am facing the same problem even after removing `click_action`.
Can anyone guide me as to what I should change next?

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
