### ISSUE TITLE
In-App subscriptions statistics for Android Apps are ignored

### ISSUE THREAD

**Issue by SMH17** [arnesson/cordova-plugin-firebase#544]
I have various in-app subscriptions, the Google Play account is linked correctly and also fingerprint certificate is configured, but purchase events aren't counted in statistics that show only AdMob earning totally ignoring in-app purchase earning source. 
The App uses the latest firebase lib available.

NOTE
I have added the in-app purchase this year but the App was already linked before to Google Play... if his info could be in some way useful to get a clue of the possible culprit of the issue.

**Comment by robertarnesson** [comment]
A better place for this might be the firebase support. The plugin doesnt fiddle with the tracking at all but simply calls the corresponding native methods

**Comment by soumak77** [comment]
closing as non-actionable
