### ISSUE TITLE
How to store notification even If user Discard/Swipes notification

### ISSUE THREAD

**Issue by Prashant454** [arnesson/cordova-plugin-firebase#545]
Im using this plugin in Ionic 3 and it works well too.
I found a problem with a case where
if a notification received in the background the it will show up in system tray
but if a user swipes notification then notification callback doesn't called 
so am unable to store the notification received due to this.

what is correct method to every push that may be received in foreground or background

**Comment by robertarnesson** [comment]
not an issue with the plugin itself. there are many ways you can store the information. one being saving it on the backend

**Comment by StefanoMartella** [comment]
@robertarnesson 
Hello
Can you please give an example on backend management of discarded notification?
Thank you

**Comment by c06645232f8919554d4df3c88e101e38** [comment]
just save your personal details and all that have used with it so it make your easy to solved
