### ISSUE TITLE
No Push-Notification on Google Pixel with Oreo if App is in Background with Ionic

### ISSUE THREAD

**Issue by wo-github** [arnesson/cordova-plugin-firebase#547]
There is no notification on a Pixel Smartphone with Android 8, if the App is in background. If the App is in foreground the message is received with the onNotificationOpen() function.
The expected behaviour is a notification in the statusbar if a message is received.

**Comment by niteshplenar** [comment]
I am facing the same issue on Oneplus 5 with Android 8.
If i disable the battery optimization setting for app then i receive the FCM push notification while app is closed.

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
