### ISSUE TITLE
after_prepare.js broken PLATFORM.ANDROID.stringsXml

### ISSUE THREAD

**Issue by tarsomatos** [arnesson/cordova-plugin-firebase#549]
Error on line 52.20 from file after_prepare.js
The folder path to compile looks like it has changed in Cordova-android 7.0 for
'app \ src \ main \ res \ values' error occurred while generating PLATFORM.ANDROID.stringsXml

**Comment by RafaelAdao** [comment]
Same problem here

**Comment by ulisesvera** [comment]
Same problem!

**Comment by RafaelAdao** [comment]
For now, in my case, I decided to adjust the version of Android to 6.3.0

`ionic cordova platform add android@6.3.0`

This version did not have this problem.

**Comment by ulisesvera** [comment]
The downgrade also works for me.

**Comment by m6246** [comment]
Changing this line
stringsXml: ANDROID_DIR + '/res/values/strings.xml'
to
stringsXml: ANDROID_DIR + '/app/src/main/res/values/strings.xml'

will fix the issue. There should be a check on the cordova version so the path can be set accordingly as indeed the folder structure is changes as of 7.0.0:
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by akshgods** [comment]
same problem here

**Comment by gandhirajan** [comment]
Please check out this pull request - https://github.com/arnesson/cordova-plugin-firebase/pull/570 It contains the fix to install the plugin for cordova android 7.0.0

**Comment by robertarnesson** [comment]
Trying to fix this in #039e29e. please test!
