### ISSUE TITLE
Support iOS 10

### ISSUE THREAD

**Issue by BugsBunnyBR** [arnesson/cordova-plugin-firebase#55]
Update the iOS sdk to better support iOS 10
https://firebase.google.com/support/release-notes/ios#3.6.0

**Comment by chemerisuk** [comment]
+1

**Comment by robertarnesson** [comment]
20cf365d889de1b50c3c98924365ca3c03c42fbe

also looks like this needs to be implemented for notifications on ios 10: https://firebase.google.com/docs/reference/ios/firebasemessaging/protocol_f_i_r_messaging_delegate-p

**Comment by bocodigital** [comment]
Any luck on getting this working in IOS 10?

**Comment by robertarnesson** [comment]
update to 0.1.14. open a new ticket for any remaining issue
