### ISSUE TITLE
Always show notification in device notification bar

### ISSUE THREAD

**Issue by mishkeTz** [arnesson/cordova-plugin-firebase#550]
Is it possible to always show the notifications in its device notification bar even when the application is opened not just when the application is running in background. 

I always want this behavior (if app is in foreground or background): 
2. App is in background:
     i. User receives the notification message in its device notification bar
     ii. User taps the notification and the app opens
     iii. User receives the notification data in the JavaScript callback

**Comment by Michazzz** [comment]
@mishkeTz Try to use another plugin to show notification when application is in foreground: 
[https://github.com/katzer/cordova-plugin-local-notifications](Local Notifications)

**Comment by mishkeTz** [comment]
Ok, I saw that plugin few days ago and I'll probably it.

Thank you.
