### ISSUE TITLE
getToken return undefined

### ISSUE THREAD

**Issue by sutineeangs** [arnesson/cordova-plugin-firebase#555]
this is my code. 
`onDeviceReady: function () {
        app.receivedEvent('deviceready');
        console.log(window);

        console.log(FirebasePlugin);

        FirebasePlugin.getToken(function (token) {
            // save this server-side and use it to push notifications to this device
            console.log('token ', token);
            
        }, function (error) {
            console.error(error);
        });

    },`

![image](https://user-images.githubusercontent.com/29113665/35849551-95e0bc6a-0b54-11e8-9bcb-b3884d44a878.png)

**Comment by robertarnesson** [comment]
you can not get a token in a browser. notifications works only for ios/android

**Comment by Chiff** [comment]
is there any workaround? it doesnt have to be real token just some hardcoded string mby. is that possible?
