### ISSUE TITLE
No known class method for selector 'setScreenName:screenClass:'

### ISSUE THREAD

**Issue by ganiru** [arnesson/cordova-plugin-firebase#557]
I'm building an Ionic V3 app, using this plugin as well as cordova-plugin-fcm for handling push notifications. It works fine on Android, but in iOS, when I build in Xcode (version 9.0.1 on macOS High Sierra), I get the error "**No known class method for selector 'setScreenName:screenClass:**'" on line 286 of FirebasePlugin.m. I've searched all over Google for solutions, but no luck.

Please help!

Thanks.

**Comment by robertarnesson** [comment]
can you try to install the plugin from master?

**Comment by kierandesmond** [comment]
Getting the same issue. Any updates?

**Comment by serdartaylan** [comment]
I am taking a similar problem
what is the solution?
@robertarnesson @kierandesmond @ganiru

**Comment by ganiru** [comment]
Sorry I can’t remember how I got around it, but I know I downgraded some of the plugins I used, thinking there was some conflict. I’d recommend you remove all plugins (especially Google ones) and add them one at a time & build. Might help in isolating the issue. Hope it helps.

**Comment by soumak77** [comment]
closing as resolved
