### ISSUE TITLE
Broken with cordova-android 7.0.0

### ISSUE THREAD

**Issue by benny-medflyt** [arnesson/cordova-plugin-firebase#558]
This plugin is broken with [cordova-android 7.0.0](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)

`getToken` returns an empty string("")

Works great with 6.4.0.

**Comment by graphicgeek** [comment]
This seems to be related to issue #549 

I was able to fix it by altering scripts/after_prepare.js

changing line 51 from:

stringsXml: ANDROID_DIR + '/res/values/strings.xml'

to:

stringsXml: ANDROID_DIR + '/app/src/main/res/values/strings.xml'

**Comment by ph-eh** [comment]
Hi, in /plugins.xml , lines 23 and 26, does the xml location also have to be changed there to?

**Comment by MEELB777** [comment]
Hi, thanks for the plugin.

Any news about this issue. I can't update to cordova-android 7.0.0 until this problem is solved. 

I have to downgrade to 6.4.0.

Thanks

**Comment by adadgio** [comment]
Any fix on this ?

**Comment by gandhirajan** [comment]
@adadgio  Please check out this pull request - https://github.com/arnesson/cordova-plugin-firebase/pull/570 It contains the fix to install the plugin for cordova android 7.0.0

**Comment by robertarnesson** [comment]
Trying to fix this in commit 039e29e. please test!

**Comment by fdambrosio** [comment]
thanks @robertarnesson the fix  works! 
plugins/cordova-plugin-firebase/scripts/after_prepare.js line 51
node_modules/cordova-plugin-firebase/scripts/after_prepare.js line 51
```
-        stringsXml: ANDROID_DIR + '/res/values/strings.xml'
+        stringsXml: fileExists(ANDROID_DIR + '/app/src/main/res/values/strings.xml') ? ANDROID_DIR + '/app/src/main/res/values/strings.xml' : ANDROID_DIR + '/res/values/strings.xml'
```

**Comment by Vivek-abstract** [comment]
I'm still facing this issue :sob:

**Comment by briantq** [comment]
@Vivek-abstract what version of the plug-in are you using?

**Comment by Vivek-abstract** [comment]
Hey, so sorry for that message. I was running the app without internet and didn't realize it. Turning on the internet fixed the problem for me. :blush:

**Comment by dupiesdupreez** [comment]
How is this STILL an issue...
