### ISSUE TITLE
  Custom-URL-scheme does not work after installing this plugin

### ISSUE THREAD

**Issue by premtemp** [arnesson/cordova-plugin-firebase#560]
Hello,
  I have the EddyVerbruggen/Custom-URL-scheme install and working,, However, after installing  the firebase plugin the Custom-URL-scheme is not working. If I remove it then the custom url works again,,,

Can you give me some suggestion on how to resolve this issue?. I really need both plugin to work in my app,, 

Thanks

**Comment by premtemp** [comment]
Thanks for looking into this issue..

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.
