### ISSUE TITLE
Get data from notification

### ISSUE THREAD

**Issue by netinkumar** [arnesson/cordova-plugin-firebase#562]
How can we get data send in the notification using this plugin. Is there is any function for it.

**Comment by nekrodomus** [comment]
this.firebase.onNotificationOpen()
      .subscribe(dataNotification => {...});

**Comment by netinkumar** [comment]
Thanks for the quick response. I was able to send and receive the content of "notification", but I did not receive "data" at all. Please see the code below. 
"notification": {
              "title": "City added", 
              "body": "your Requested city Hasbeen added Successfully.",
              "sound": "default",
 },
"data": {
          "param1": "value1",
           "param2": "test"
 }

What if I want to send a custom payload separately out of the 'notification' block? Is that possible to do that with firebase? I was able to do that with FCM but not with this plugin.

**Comment by nekrodomus** [comment]
Yes, It is posible. I have this plugin and receive custom data.
"notification": {
"title": "City added",
"body": "your Requested city Hasbeen added Successfully.",
"sound": "default",
},
"data": {
"param1": "value1",
"param2": "test"
}


    that.firebase.onNotificationOpen()
      .subscribe(notification => {

.....
              console.log(notification.param1); // --> Print 'value1'
});

**Comment by darshantejani007** [comment]
@nekrodomus Hi, 
I tried your solution,
`window.FirebasePlugin.onNotificationOpen().subscribe((noti) => {..})`
and it throws error that `Cannot read property subscribe of undefined`. 
Am I doing something wrong here? Will you please help me out?

**Comment by signalpoint** [comment]
I was able to access the `data` like this...

**Android 6**
```
window.FirebasePlugin.onNotificationOpen(function(notification) {
  console.log(notification.param1);
  console.log(notification.param2);
});
```

It looks like this plugin consolidates the `notification` and potential `data` down into this single `notification` object.
