### ISSUE TITLE
On Click notification in status bar app does not open

### ISSUE THREAD

**Issue by amyogiji** [arnesson/cordova-plugin-firebase#564]
Hi, i am using this plugin and receiving notification successfully but on click notification in status bar app does not open.

plz, let me know if more information is required.

**Comment by Michazzz** [comment]
Hi @amyogiji, which platform do you have problem? In my case I have problem with iOS platform. When I tap notification on iOS, application starts but no callback to onNotificationOpen method. On android everythings works fine, as expected.

**Comment by amyogiji** [comment]
Hi i have this issue in Android , when the app is closed I can receive the notification but when i click the push notification it doesn't open the app

**Comment by FavoriteFave** [comment]
I still do have this issue. Is there any solution?

**Comment by KishanIos007** [comment]
I am having the same issue. +1

**Comment by ikaro1970** [comment]
Hi, anyone founded some solution?, thanks
