### ISSUE TITLE
FCM push notifications are not appearing in background in android 8.0 Oreo device.

### ISSUE THREAD

**Issue by sarmadzaki** [arnesson/cordova-plugin-firebase#568]
i've installed and configured all the requirements of fcm on client and server(node-fcm) both and sending push notification successfully whenever i want  in all devices but when i'm sending to Android 8.0 device its coming within app when app is opened while not coming in background when app is closed. kindly anyone who can help me in this or tell if fcm has updates for oreo or not. or this is a bug. 
Thanks

**Comment by asifswinjit** [comment]
I have updated my device to android oreo. Now I am not receiving the notification on android Oreo.
before updating , it was working.

**Comment by thisIsChetan** [comment]
Facing the same issue. Any update on it?

**Comment by sarmadzaki** [comment]
not yet

**Comment by asifswinjit** [comment]
Please update , also i m searching and trying the same.

**Comment by seowzhenjun** [comment]
I am also facing the same problem, appreciate if anyone can help.

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by soumak77** [comment]
Closing for cleanup.  Please test with the latest version and reopen if it is still an issue.

**Comment by Birowsky** [comment]
@soumak77 this problem happens in iOS. 

`window.FirebasePlugin.onNotificationOpen` does not fire when app is in background.
I also tried the github version.

**Comment by Birowsky** [comment]
@diegodambra easy bro, try iOS.

**Comment by diegodambra** [comment]
@Birowsky I need it to work on both platforms!

iOS requires tiresome setup. Seems legit to go with Android first.

**Comment by madhudashore** [comment]
Please use handel intent in firebase messaging service class 

    compile 'com.google.firebase:firebase-messaging:11.0.4'
and use this in dependency

**Comment by bnfrnz** [comment]
May this be related to the notification channels ([introduced in Oreo](https://developer.android.com/distribute/best-practices/develop/target-sdk#preoreo))?

This plugin would need to expose a way of [creating notification channels](https://developer.android.com/training/notify-user/channels#CreateChannel) in order to be able to send messages to these channels.

I believe [#603](https://github.com/arnesson/cordova-plugin-firebase/pull/603) is addressing this.
