### ISSUE TITLE
ERROR_APP_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by prantikv** [arnesson/cordova-plugin-firebase#572]
I am trying to use phone auth.

I have sha-1 keys for the **debug.keystore** add to my firebase project.

I keep getting the following.

```
ERROR Error: Uncaught (in promise): unknown error verifying number Error instance: com.google.firebase.auth.FirebaseAuthException Error code: ERROR_APP_NOT_AUTHORIZED
    at c (polyfills.js:3)
```

Note here that I am using a free account in firebase. I am able to receive otp when using the same account for a web app using angularfire2.

 Just getting this error when using it with the plugin.

Any help regarding this is appreciated.

**Comment by emilianoglucero** [comment]
I'm having the same problem.
Did you solve it?

**Comment by prantikv** [comment]
the debug key store does not work. You have to use sign your app with a real key and use it for this to work.

**Comment by pablogarciamiranda** [comment]
@prantikv I wasn't able to make it work. Signing the release app with my key I am getting the same error. I have also added the SHA1 key of the release key to the firebase console.

Any help?

**Comment by pablogarciamiranda** [comment]
Ok, I have fixed it.

Verify that the package name of your app matches the one specified in Firebase.

**Comment by KerryTucker** [comment]
having same problem, my package name matches too

**Comment by Khsed4** [comment]
having the same issue?
