### ISSUE TITLE
Tried calling Firebase.onTokenRefresh, but the Firebase plugin is not installed.

### ISSUE THREAD

**Issue by varogonz95** [arnesson/cordova-plugin-firebase#574]
Hi, I'm trying to make a simple app for receiving push notifications with Ionic 3.
When staring the app with Ionic DevApp on iOS, this warning launches and token is not received.

I'm added Firebase provider in app.module.ts and google-services.json/GoogleService-Info.plist are in project root (next to config.xml, package.json, etc...)

Am I missing something? I'm new to Ionic...

**Comment by mserravalle92** [comment]
I'm having same issue, how solved it?

**Comment by fabiusss** [comment]
+1
