### ISSUE TITLE
extend plugin in order to customize notification management

### ISSUE THREAD

**Issue by dennybiasiolli** [arnesson/cordova-plugin-firebase#578]
Hi @arnesson, thank you for this great plugin, it saved my life in more than one occasion!

I wonder if it's possible to extend this plugin, customising notification management.

To clarify: i need to customise notifications when an app receives a RemoteMessage with data only. Do you know if there is a "magic" possibility or the only solution is to fork the repo changing it in the way I need?

Thanks for your precious help

**Comment by robertarnesson** [comment]
you could either fork or - if I understand your use-case correctly - you could use this plugin in conjunction with e.g. local notifications

**Comment by soumak77** [comment]
Closing for cleanup.  PRs are welcome to add the desired functionality.
