### ISSUE TITLE
I am only getting google.sent_time, from, google.message_id, collapse_key with firbasePlugin.on

### ISSUE THREAD

**Issue by abmnukmr** [arnesson/cordova-plugin-firebase#579]
When the app is in foreground, everything working properly. I am getting a notification plus the data message inside the onMessageReceived method.

But when app is in background, I am getting notification in system tray. And when I click on the control, it goes to the main activity. And When I parse intent.getExtras();, I am getting only this key data - google.sent_time, from, google.message_id, collapse_key.

**Comment by quangpdt** [comment]
@abmnukmr : I had the same problem and after 2hrs looking on Google, finally I found the problem:

The message to send to Firebase API should be something like this:

`
const content = {
    data: {
        title: title,
        body: message
    },
    notification: {
        title: title,
        body: message
    },
    token: token.value
};
`

The `data` property will be acted as data payload when user tap on the notification and the `notification` is for displaying data when app in foreground.

Hope this help!

**Comment by soumak77** [comment]
closing as resolved
