### ISSUE TITLE
Getting Null token from FCM

### ISSUE THREAD

**Issue by akshaysatav1020** [arnesson/cordova-plugin-firebase#584]
Even after updating to latest plugin version i am getting null token for my device. The author has closed the issue i request to open it again

**Comment by fjckls** [comment]
Yes, same here on Android

**Comment by robertarnesson** [comment]
are you installing from git master? the plugin has not been updated on npm just yet..

**Comment by akshaysatav1020** [comment]
yup..

**Comment by agil-NUBBA** [comment]
@robertarnesson Yes, installing via:

`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase --save`

same error

**Comment by fjckls** [comment]
This is what worked for me - remove platform & plugin and add anew:
```
cordova plugin remove cordova-plugin-firebase
cordova platform remove ios
cordova plugin add https://github.com/arnesson/cordova-plugin-firebase --save
cordova platform add ios
```
also had to delete this inside ---info.plist file: **FirebaseAppDelegateProxyEnabled = NO**

**Comment by simlevesque** [comment]
This plugin does not work. From master or from npm. On Android Cordova.

**Comment by akshaysatav1020** [comment]
Any updates? @robertarnesson

**Comment by denernun** [comment]
Same error....alternatives ?

**Comment by akshaysatav1020** [comment]
Any fixes, patches or update in plugin?

**Comment by DannyS121** [comment]
@fjckls This did not work for me, still getting nothing on cordova android.

**Comment by soumak77** [comment]
closing as resolved
