### ISSUE TITLE
iOS/Android analytics StreamView only showing London location

### ISSUE THREAD

**Issue by ph-eh** [arnesson/cordova-plugin-firebase#596]
I've been testing this plugin with Phonegap and have followed installation instructions, created a custom private repository etc. Everything seems to work apart from when viewing the StreamView page on the google firebase analytics site as it always shows the location is London. I have tried being connected to wifi and just the mobile signal and it still shows me being in London. I am in the UK but definitely nowhere near London, any ideas why this is happening? Thanks.

**Comment by ph-eh** [comment]
Anybody else experiencing this, or is it just me? Any news or info would be grateful, thanks.

**Comment by newuser44** [comment]
Not much help here. We are just getting started with the plugin and testing things out on our test phones.  For us it seems like all the locations are Washington DC.  I'm in Utah.  All our phones connected to the same wifi and sometimes we had to use a VPN.   Still not sure why we see that.  I was able to finally get Utah to show up when I turned off the wifi.   Sounds similar to your problem.

**Comment by ph-eh** [comment]
Thanks @newuser44. We've tried all sorts of things but now our app is live and users are actually showing up all over the place. So I can only presume it had something to do with all our test devices.

I think this issue can now be closed as I don't think its a code problem :)
