### ISSUE TITLE
[Critical] Google will drop Firebase Crash Report, plugin should integrate F. Crashlytics

### ISSUE THREAD

**Issue by tryadelion** [arnesson/cordova-plugin-firebase#598]
As per the Firebase console ( just enter in yours to see the translated error, my browser is in spanish):

![captura de pantalla 2018-03-14 a las 8 27 45](https://user-images.githubusercontent.com/3778474/37388645-a0c1f8a0-2761-11e8-8b64-47c718e06c9e.png)

That means that this plugin should integrate as soon as possible the firebase crashlytics SDK if it wants to keep logging errors.
https://firebase.google.com/docs/crashlytics/upgrade-from-crash-reporting

**Comment by BluebambooSRL** [comment]
+1

**Comment by paulstelzer** [comment]
Would be great - any infos about this?

**Comment by soumak77** [comment]
No one is currently working on this.  PRs are welcome.

**Comment by soumak77** [comment]
closing in favor of https://github.com/arnesson/cordova-plugin-firebase/issues/548
