### ISSUE TITLE
Error while verifying phone number

### ISSUE THREAD

**Issue by davisbra** [arnesson/cordova-plugin-firebase#599]
when I use window.FirebasePlugin.verifyPhoneNumber in my cordova app in android it return this error:
unknown error verifying number Error instance: com.google.firebase.FirebaseException
How can I solve this problem?
I configure SHA and google-service.json in my app and I enabled phone authentication in firebase console.

**Comment by emilianoglucero** [comment]
I'm having the same problem.
Did you solve it?

**Comment by soumak77** [comment]
@davisbra please try again with version 1.0

**Comment by soumak77** [comment]
should be fixed by version 1.0.2

**Comment by felaray** [comment]
Hi,
I have same problem

>cordova -v
8.1.2 (cordova-lib@8.1.1)

>cordova platform
Installed platforms:
  android 7.1.4

>cordova plugin
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"

**Comment by fatenHd** [comment]
I am facing the same issue after recent update any solution???

**Comment by Khsed4** [comment]
having the same issue

**Comment by jeroternero** [comment]
having the same issue. anyone?
