### ISSUE TITLE
Data callback?

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [arnesson/cordova-plugin-firebase#6]
Is there a way to get the data/message from the notification to the app via a callback?

The normal flow for notifications are:

1. App In Background/ App Off
 - Show Notification in toolbar
 - When notification is clicked, receive callback with data.
2. App in Foreground:
 - Receive callback with data.

**Comment by tgensol** [comment]
+1 ?

**Comment by robertarnesson** [comment]
onNotificationOpen is implemented on android (its missing in the readme though)

**Comment by neolectron** [comment]
thanks, just need it for iOS to close this ticket :p

**Comment by robertarnesson** [comment]
see #36 

made a first pass on this for ios. you can try it by installing the plugin from github master

**Comment by robertarnesson** [comment]
integrated in 0.1.11
