### ISSUE TITLE
Build android fails

### ISSUE THREAD

**Issue by BeliliFahem** [arnesson/cordova-plugin-firebase#604]
Hi, When I build for android, I have this error : 

`
:mergeDebugResources
:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/xxxx/Android/Sdk/build-tools/27.0.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.29 secs
Error: /home/xxxx/Dev/Mobility/xxx/apps/ionic/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/xxx/Android/Sdk/build-tools/27.0.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

`

**Comment by tonysumi** [comment]
I'm facing similar issue:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

After new Release as on 20/03/2018, Not able to build apk.
https://firebase.google.com/support/releases
https://developers.google.com/android/guides/releases

**Comment by codesundar** [comment]
Worked for me
https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)
