### ISSUE TITLE
Error: ENOENT: no such file or directory, open  myPath\string.xml

### ISSUE THREAD

**Issue by sharifullahsh** [arnesson/cordova-plugin-firebase#607]
I want to use cordova-plugin-firebase for phone verification.
I add the plugin as ionic doc, add google-service.json to my project, but when build for android it gives me the following error. I can build the project but when I call verifyPhoneNumber(phoneNumber, timeoutDuration) function, my app crash in my android device.

Preparing Firebase on Android
{ Error: ENOENT: no such file or directory, open 'D:\node\ionic\smsVerification\platforms\android\res\values\strings.xml'

**Comment by Shals08** [comment]
After downloading the plugin change the ANDROID_DIR  variable in the after_prepare.js file,  which is in the scripts folder. 
From ANDROID_DIR = 'platforms/android' TO ANDROID_DIR = 'platforms/android/app/src/main'.

**Comment by cesarcruzm** [comment]
thanks @Shals08 your solution did the trick!

**Comment by geekyguy18** [comment]
@Shals08 Thanks

**Comment by mongedecristo** [comment]
ALLOW ME TO USE CAPITAL LETTERS:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! YOU SAVED THE DAY, MAN !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by soumak77** [comment]
please try again with version 1.0

**Comment by ARSHAD0141786** [comment]
Thanks @Shals08
