### ISSUE TITLE
App is crashing while calling the varifyPhoneNumber() function 

### ISSUE THREAD

**Issue by JeetuChoudhary** [arnesson/cordova-plugin-firebase#609]
I have installed and configured the plugin in the application. When I run the application on
 my device then it crashes on varifyPhoneNumber() functions.  The following image has the crash Report:

https://user-images.githubusercontent.com/22294704/37700482-b68f97c2-2d11-11e8-9cd8-68c051429871.jpg

**Comment by zyzmoz** [comment]
I found the problem! You should install the version 0.1.25 
`cordova plugin add cordova-plugin-firebase@0.1.25 --save`
Installing without refer that exact version the error occurs ! So you'll need also set the path to strings xml

**Comment by soumak77** [comment]
@JeetuChoudhary please try again with version 1.0

**Comment by soumak77** [comment]
closing as resolved
