### ISSUE TITLE
iOS remote config

### ISSUE THREAD

**Issue by BugsBunnyBR** [arnesson/cordova-plugin-firebase#61]
Hi, I found this `PR`-> https://github.com/fechanique/cordova-plugin-fcm/pull/54/files that adds remote config to iOS, maybe you can take a look at the code and implement iOS remote config in your plugin.
Thanks for the great work.

**Comment by malah-code** [comment]
I support your opinion. 
Please consider it.

**Comment by appastair** [comment]
It doesn't appear to be fully-implemented in fechanique/cordova-plugin-fcm but without testing, it seems like it fetches whatever config is already set.

https://firebase.google.com/docs/remote-config/use-config-ios#set-in-appdefault-parameter-values

**Comment by elliotstokes** [comment]
This is a feature that we are looking for. Would you be happy to take a pull request?

**Comment by robertarnesson** [comment]
@elliotstokes yes for sure

**Comment by elliotstokes** [comment]
Ive created a pr with the iOS remote config support. It works for my use case. Still have the timeout stuff to implement but comments welcome.

https://github.com/arnesson/cordova-plugin-firebase/pull/144
