### ISSUE TITLE
Android: After new Release of Google Play services as on 20/03/2018, Not able to build apk.

### ISSUE THREAD

**Issue by tonysumi** [arnesson/cordova-plugin-firebase#610]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms.license'

After new Release as on 20/03/2018, Not able to build apk.
https://firebase.google.com/support/releases
https://developers.google.com/android/guides/releases

**Comment by Willey1986** [comment]
Same here the problem seems to be that the plugin just uses + as dependency versions.

```
dependencies {
    compile 'me.leolin:ShortcutBadger:1.1.4@aar'
    compile 'com.google.firebase:firebase-crash:+'
    compile 'com.google.firebase:firebase-auth:+'
}
```
Can we change this to 11.+ ?

**Comment by tonysumi** [comment]
As plugin is using "+" to get the latest libraries and Prior to current release of 12.0.0, the stable version 11.8.0 should work.

**Comment by YounesM** [comment]
Same here, is there any workaround to solve this problem ?

**Comment by tonysumi** [comment]
on changing inside gradle and plugin.xml, it worked for me
-----------------gradle----------------
compile 'com.google.firebase:firebase-crash:11.8.0'
compile 'com.google.firebase:firebase-auth:11.8.0'
------------------plugin.xml-----------------
		<framework src="com.google.firebase:firebase-core:11.8.0" />
		<framework src="com.google.firebase:firebase-messaging:11.8.0" />
		<framework src="com.google.firebase:firebase-crash:11.8.0" />
		<framework src="com.google.firebase:firebase-config:11.8.0" />
		<framework src="com.google.firebase:firebase-perf:11.8.0" />

**Comment by wo-github** [comment]
Same problem here.
"cordova run android" runs in the error above.
I see in my console, that there are some files was downloaded. The download wasn`t triggered from my site.

Download https://maven.google.com/com/android/support/support-v4/28.0.0-alpha1/support-v4-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.pom
Download https://maven.google.com/com/android/support/cardview-v7/27.0.2/cardview-v7-27.0.2.pom
Download https://maven.google.com/com/android/support/customtabs/27.0.2/customtabs-27.0.2.pom
Download https://maven.google.com/com/android/support/support-vector-drawable/27.0.2/support-vector-drawable-27.0.2.pom
Download https://maven.google.com/com/android/support/animated-vector-drawable/27.0.2/animated-vector-drawable-27.0.2.pom
Download https://maven.google.com/com/android/support/support-media-compat/28.0.0-alpha1/support-media-compat-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/support-compat/28.0.0-alpha1/support-compat-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/collections/28.0.0-alpha1/collections-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/support-core-utils/28.0.0-alpha1/support-core-utils-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/documentfile/28.0.0-alpha1/documentfile-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/loader/28.0.0-alpha1/loader-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/localbroadcastmanager/28.0.0-alpha1/localbroadcastmanager-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/print/28.0.0-alpha1/print-28.0.0-alpha1.pom
Download https://maven.google.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.pom
Download https://maven.google.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.pom
Download https://maven.google.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.pom
Download https://maven.google.com/com/android/support/support-core-ui/28.0.0-alpha1/support-core-ui-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/customview/28.0.0-alpha1/customview-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/viewpager/28.0.0-alpha1/viewpager-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/coordinatorlayout/28.0.0-alpha1/coordinatorlayout-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/drawerlayout/28.0.0-alpha1/drawerlayout-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/slidingpanelayout/28.0.0-alpha1/slidingpanelayout-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/interpolator/28.0.0-alpha1/interpolator-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/swiperefreshlayout/28.0.0-alpha1/swiperefreshlayout-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/asynclayoutinflater/28.0.0-alpha1/asynclayoutinflater-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/cursoradapter/28.0.0-alpha1/cursoradapter-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/support-fragment/28.0.0-alpha1/support-fragment-28.0.0-alpha1.pom
Download https://maven.google.com/com/android/support/support-annotations/28.0.0-alpha1/support-annotations-28.0.0-alpha1.pom
Download https://maven.google.com/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.pom
Download https://maven.google.com/android/arch/lifecycle/common/1.1.0/common-1.1.0.pom
Download https://maven.google.com/android/arch/core/common/1.1.0/common-1.1.0.pom
Download https://maven.google.com/com/android/support/support-annotations/28.0.0-alpha1/support-annotations-28.0.0-alpha1.jar
Download https://maven.google.com/com/android/support/collections/28.0.0-alpha1/collections-28.0.0-alpha1.jar
Download https://maven.google.com/android/arch/lifecycle/common/1.1.0/common-1.1.0.jar
Download https://maven.google.com/android/arch/core/common/1.1.0/common-1.1.0.jar
Download https://maven.google.com/android/arch/lifecycle/runtime/1.1.0/runtime-1.1.0.aar
Download https://maven.google.com/com/android/support/support-compat/28.0.0-alpha1/support-compat-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-media-compat/28.0.0-alpha1/support-media-compat-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/documentfile/28.0.0-alpha1/documentfile-28.0.0-alpha1.aar
Download https://maven.google.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar
Download https://maven.google.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
Download https://maven.google.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
Download https://maven.google.com/com/android/support/loader/28.0.0-alpha1/loader-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/localbroadcastmanager/28.0.0-alpha1/localbroadcastmanager-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/print/28.0.0-alpha1/print-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-core-utils/28.0.0-alpha1/support-core-utils-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/customview/28.0.0-alpha1/customview-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/viewpager/28.0.0-alpha1/viewpager-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/coordinatorlayout/28.0.0-alpha1/coordinatorlayout-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/drawerlayout/28.0.0-alpha1/drawerlayout-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/slidingpanelayout/28.0.0-alpha1/slidingpanelayout-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/interpolator/28.0.0-alpha1/interpolator-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/swiperefreshlayout/28.0.0-alpha1/swiperefreshlayout-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/asynclayoutinflater/28.0.0-alpha1/asynclayoutinflater-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/cursoradapter/28.0.0-alpha1/cursoradapter-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-core-ui/28.0.0-alpha1/support-core-ui-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-fragment/28.0.0-alpha1/support-fragment-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-v4/28.0.0-alpha1/support-v4-28.0.0-alpha1.aar
Download https://maven.google.com/com/android/support/support-vector-drawable/27.0.2/support-vector-drawable-27.0.2.aar
Download https://maven.google.com/com/android/support/animated-vector-drawable/27.0.2/animated-vector-drawable-27.0.2.aar
Download https://maven.google.com/com/android/support/appcompat-v7/27.0.2/appcompat-v7-27.0.2.aar
Download https://maven.google.com/com/android/support/cardview-v7/27.0.2/cardview-v7-27.0.2.aar
Download https://maven.google.com/com/android/support/customtabs/27.0.2/customtabs-27.0.2.aar

**Comment by gcremalin** [comment]
@tonysumi did you have to remove and re-add platform android after that?

**Comment by tonysumi** [comment]
I'm not sure with cache mechanism for Libraries so I removed android platform and re-aded with above mentioned changes

**Comment by rahulsapkal23** [comment]
I am also facing same issue.
I made the above changes as tonysumi described but No luck.
I am still getting same error not able to build

**Comment by gcremalin** [comment]
Ya same here the above hasn't resolved the issue for me. Any ideas?

**Comment by digitalagencyguy** [comment]
Yup, same scenario here. Already tried @tonysumi 's changes but no dice unfortunately

**Comment by ComeBurguburu** [comment]
In order to complete @tonysumi solution, you have to force version 11.8.0 when a dependencie start with com.google.android.gms or com.google.firebase in build.gradle and project.properties

**Comment by jeremycastelli** [comment]
in platform/android/build.gradle add this

`configurations.all {
   resolutionStrategy {
       force "com.google.android.gms:play-services-ads:11.8.0"
       force "com.google.android.gms:play-services-base:11.8.0"
       force "com.google.android.gms:play-services-gcm:11.8.0"
       force "com.google.android.gms:play-services-analytics:11.8.0"
       force "com.google.android.gms:play-services-location:11.8.0"
       force "com.google.android.gms:play-services-basement:11.8.0"
       force "com.google.android.gms:play-services-tagmanager:11.8.0"
       force 'com.google.firebase:firebase-core:11.8.0'
       force 'com.google.firebase:firebase-crash:11.8.0'
       force 'com.google.firebase:firebase-auth:11.8.0'
       force 'com.google.firebase:firebase-common:11.8.0'
       force 'com.google.firebase:firebase-config:11.8.0'
       force 'com.google.firebase:firebase-messaging:11.8.0'
   }
}`
if that doesn't work, search in your project the string '12.0.0' and add in the list above the missing library

**Comment by gcremalin** [comment]
@jeremycastelli that's a nice solution and it works!

Although as @ComeBurguburu mentioned you might need to search through your dependencies prefixed with either com.google.android.gms or com.google.firebase and add them to the force list with the 11.8 version number appended.

**Comment by AlexMota** [comment]
I tried to put '11' in the dependencies but dont work for me.
Then I opened the folder /platforms/android/ in android studio
and I updated the gradle version 
and the android studio builded the project

After in cmd I was able to generate apk.

**Comment by predorock** [comment]
@jeremycastelli 
You can use cordova hook `before_build` like this:
```javascript

module.exports = function(context) {
	var fs = require('fs');
	var path = require('path');

	var rootdir = context.opts.projectRoot;

	var platformDir = 'platforms/android';
        //change the path to your external gradle file
	var srcFile = path.join(rootdir, 'src/android/build-extras.gradle');
	var destFile = path.join(rootdir, platformDir, 'build-extras.gradle');

	console.log("copying "+srcFile+" to "+destFile);
	fs.createReadStream(srcFile).pipe(fs.createWriteStream(destFile));
}
```


```groovy
//build-extras.gradle
configurations.all {
   resolutionStrategy {
       force "com.google.android.gms:play-services-ads:11.8.0"
       force "com.google.android.gms:play-services-base:11.8.0"
       force "com.google.android.gms:play-services-gcm:11.8.0"
       force "com.google.android.gms:play-services-analytics:11.8.0"
       force "com.google.android.gms:play-services-location:11.8.0"
       force "com.google.android.gms:play-services-basement:11.8.0"
       force "com.google.android.gms:play-services-tagmanager:11.8.0"
       force 'com.google.firebase:firebase-core:11.8.0'
       force 'com.google.firebase:firebase-crash:11.8.0'
       force 'com.google.firebase:firebase-auth:11.8.0'
       force 'com.google.firebase:firebase-common:11.8.0'
       force 'com.google.firebase:firebase-config:11.8.0'
       force 'com.google.firebase:firebase-messaging:11.8.0'
   }
}
```

**Comment by smv-kepler** [comment]
Are there any known fixes for Phonegap Build? I tried setting the version as some suggested
```
		<framework src="com.google.gms:google-services:+" />
		<framework src="com.google.android.gms:play-services-tagmanager:11.8.0" />
		<framework src="com.google.firebase:firebase-core:11.8.0" />
		<framework src="com.google.firebase:firebase-messaging:11.8.0" />
		<framework src="com.google.firebase:firebase-crash:11.8.0" />
		<framework src="com.google.firebase:firebase-config:11.8.0" />```
but it doesn't seem to work

**Comment by sfaizanh** [comment]
@dvcroft 
```xml
<platform name="android">
        <hook src="fixFirebasePlugin.js" type="before_run" />
</platform>
```
https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/

**Comment by ejaz47** [comment]
**@dvcroft , @jeremycastelli**

The above solutions didn't work for me as i was using **"cordova-plugin-googleplus"**
So i added 2 more dependencies in @jeremycastelli 's answer
```
configurations.all {
   resolutionStrategy {

       force "com.google.android.gms:play-services-auth:11.8.0"
       force "com.google.android.gms:play-services-identity:11.8.0"

       force "com.google.android.gms:play-services-ads:11.8.0"
       force "com.google.android.gms:play-services-base:11.8.0"
       force "com.google.android.gms:play-services-gcm:11.8.0"
       force "com.google.android.gms:play-services-analytics:11.8.0"
       force "com.google.android.gms:play-services-location:11.8.0"
       force "com.google.android.gms:play-services-basement:11.8.0"
       force "com.google.android.gms:play-services-tagmanager:11.8.0"
       force 'com.google.firebase:firebase-core:11.8.0'
       force 'com.google.firebase:firebase-crash:11.8.0'
       force 'com.google.firebase:firebase-auth:11.8.0'
       force 'com.google.firebase:firebase-common:11.8.0'
       force 'com.google.firebase:firebase-config:11.8.0'
       force 'com.google.firebase:firebase-messaging:11.8.0'
   }
}
```

**Comment by tonysumi** [comment]
Note: Even after changing the version to 11.8.0 , some of you might get the same error due to OneSignal library.

**Comment by Emperorlou** [comment]
@smv-kepler did you end up finding a solution yet? I too need a solution that works with phonegap build...

**Comment by ozexpert** [comment]
i'm getting the same error with having + replaced with `11.8.0`

**Comment by tonysumi** [comment]
Add this if OneSignal is used along with FCM Under build.gradle:

`buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:3.1.0'
    }
}
repositories {
    mavenCentral()
    maven {
        url "https://maven.google.com"
    }
}
dependencies {
    compile 'me.leolin:ShortcutBadger:1.1.4@aar'
    compile 'com.google.firebase:firebase-crash:11.8.+'
    compile 'com.google.firebase:firebase-auth:11.8.+'
}

// ## Align gms and support group versions on all dependencies 

def versionGroupAligns = [
    // ### Google Play Services library
    'com.google.android.gms': [
        'version': '11.8.+'
    ],

    // ### Google Firebase library
    // Firebase has some dependencies on gms
    // If present, ensuring they are aligned
    'com.google.firebase': [
        'version': '11.8.+'
    ],

    // ### Android Support Library
    'com.android.support': [
        'requiredCompileSdkVersion': 26,
        'version': '26.1.+',
        'omitModules': ['multidex', 'multidex-instrumentation'],

        // Can't use 26 of com.android.support when compileSdkVersion 25 is set
        // The following error will be thrown if there is a mismatch here.
        // "No resource found that matches the given name: attr 'android:keyboardNavigationCluster'"
        'versionFallback': '25.+'
    ]
]


def resolveVersion(def versionOverride) {
    def curCompileSdkVersion = android.compileSdkVersion.split('-')[1].toInteger()
    def requiredCompileSdk = versionOverride['requiredCompileSdkVersion']
    if (curCompileSdkVersion < requiredCompileSdk)
        return versionOverride['versionFallback']
    return versionOverride['version']
}

configurations.all { resolutionStrategy {

    // Enable to find root causes of any remaining version mismatches
    // failOnVersionConflict()

    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def versionOverride = versionGroupAligns[details.requested.group]
        if (!versionOverride)
            return

        def omitModules = versionOverride['omitModules']
        if (omitModules && omitModules.contains(details.requested.name))
            return

        details.useVersion(resolveVersion(versionOverride))
    }
}}`

**Comment by codesundar** [comment]
Worked for me
https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404

**Comment by ozexpert** [comment]
@tonysumi no i'm not using OneSignal (yet, but i plan too)

```
cc.fovea.cordova.purchase 7.1.3 "Purchase"
cordova-clipboard 1.1.1 "Clipboard"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-velda-devicefeedback 0.0.2 "DeviceFeedback"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Comment by wenbinke** [comment]
Hi @arnesson

Can you also update the npm?

**Comment by ComeBurguburu** [comment]
@soumak77 Can we have this commit add to this project (in order to solve all the issues related to Google play services 12.0 0) ?

**Comment by ph-eh** [comment]
In Phonegap, still unable to build for Android........

BUILD FAILED

Total time: 0.906 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/project/build.gradle' line: 254

* What went wrong:
A problem occurred evaluating root project 'project'.
> Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by ph-eh** [comment]
Hi, yes @soumak77 that gradle release plugin fixed that error, but now its failing with this......

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: FirebasePluginMessagingService.java

**Comment by dronzer92** [comment]
> in platform/android/build.gradle add this
> 
> ```
> configurations.all {
>    resolutionStrategy {
>        force "com.google.android.gms:play-services-ads:11.8.0"
>        force "com.google.android.gms:play-services-base:11.8.0"
>        force "com.google.android.gms:play-services-gcm:11.8.0"
>        force "com.google.android.gms:play-services-analytics:11.8.0"
>        force "com.google.android.gms:play-services-location:11.8.0"
>        force "com.google.android.gms:play-services-basement:11.8.0"
>        force "com.google.android.gms:play-services-tagmanager:11.8.0"
>        force 'com.google.firebase:firebase-core:11.8.0'
>        force 'com.google.firebase:firebase-crash:11.8.0'
>        force 'com.google.firebase:firebase-auth:11.8.0'
>        force 'com.google.firebase:firebase-common:11.8.0'
>        force 'com.google.firebase:firebase-config:11.8.0'
>        force 'com.google.firebase:firebase-messaging:11.8.0'
>    }
> }
> ```
> 
> if that doesn't work, search in your project the string '12.0.0' and add in the list above the missing library

after searching for hours finally this resolve my issue, Thanks
just add following code in build-extras.gradle in my cordova project

```
configurations.all {
    resolutionStrategy {
        force "com.google.firebase:firebase-core:16.0.8"
        force "com.google.firebase:firebase-messaging:17.6.0"
        force "com.google.firebase:firebase-config:16.5.0"
        force "com.google.firebase:firebase-perf:16.2.5"
    }
}
```
