### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by sharifullahsh** [arnesson/cordova-plugin-firebase#611]
I did as documentation, but when I run app in Android it gives me the Error of (Invalid Phone number). 
I entered the valid phone number with country code which work in firebase ui phone auth.
I don not know what is missed,but I tried every possible way for firebase phone auth for last two week. I do not know what to do with it.If any implemented it for android and ios in ionic 3.

**Comment by sadjous** [comment]
I faced the same issue, and I finally solve it. You have to add '+' before the country code. the error i faced it was that i have two phone number, with the first one, whitout the '+' before the country code it work nicely? But with the second one when i wrote the number with the country code without '+' it doesn't work. Then i added '+' before the number and it work

**Comment by sharifullahsh** [comment]
Thanks sadjous from your replay. I have + sign in front of country code as follow
'+93079xxxxxxx' , but it is still not working.

**Comment by sadjous** [comment]
for **android** apps

window.FirebasePlugin.verifyPhoneNumber(+93079xxxxxxx,60, function(credential) {
    console.log(credential);

    // ask user to input verificationCode:
    var code = inputField.value.toString();

    var verificationId = credential.verificationId;

    var signInCredential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);
    firebase.auth().signInWithCredential(signInCredential);
}, function(error) {
    console.error(error);
});

**Comment by sharifullahsh** [comment]
This is my code
 
try{
      (<any>window).FirebasePlugin.verifyPhoneNumber('+93079xxxxxxx',60,(crdential)=>{
        // alert('SMS send Successfully');
        console.log(msCredentials);
        console.log("send sms");
      },(error)=>{
        console.error("error in faild block is ",error);
      })
    }catch(error){
      console.log("Error is >>>>>>>>>>>>>",error);
    }

**Comment by sharifullahsh** [comment]
What about google tag manager

**Comment by sadjous** [comment]
with me i don't have any probleme with google tag manager
have tried it with another number ?

**Comment by sharifullahsh** [comment]
Thanks, sadjous it work.

**Comment by sadjous** [comment]
what really was the problem ?
is it the "+" before the country code or some thing else.

**Comment by soumak77** [comment]
closing as resolved

**Comment by kurtiev** [comment]
@sharifullahsh what is the issue was there? 
I also stack on it, but my code wasn't changed, it just trow "Invalid phone number" in error method:
`
 window.FirebasePlugin.verifyPhoneNumber("+" + this.phoneNumber, this.timeout, (credential) => {
    }, function (error) {
      console.log("==>>", JSON.stringify(error));
    })
`

**Comment by sharifullahsh** [comment]
The plugin has been changed since the time I used it, but what worked for me was I did as the documentation of the plugin was.

**Comment by Khsed4** [comment]
@sharifullahsh Can you provide your codes? since I had face the same issue recently.
