### ISSUE TITLE
cordova plugin firebase error more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by pradipexicube** [arnesson/cordova-plugin-firebase#614]
last day it work absolutely fine. 
but now error showing more than one library with package name 'com.google.android.gms.license'.
.i don't do anything with my code

**Comment by elrafael** [comment]
same here

`cordova create firebaseTest`
`cd firebaseTest`
`cordova build android`

Creates the apk file with no error

then:

`cordova plugin add cordova-plugin-firebase@0.1.25 --save`
`cordova build android`

shows that error (more than one library....)

**Comment by codesundar** [comment]
Worked for me
https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404

**Comment by pradipexicube** [comment]
thanks @codesundar 
this solution worked for me

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)
