### ISSUE TITLE
Removing plugin DELETED the whole Android platform!!!

### ISSUE THREAD

**Issue by ragcsalo** [arnesson/cordova-plugin-firebase#618]
I had problems with the plugin, because it added unwanted PERMISSIONS to the Manifest file... I decided to delete the plugin, and then came the shock: removing the plugin DELETED the whole Android platform of my project!!! How could this happen???!!! :-((((

**Comment by soumak77** [comment]
@ragcsalo logs are needed before anything can be done with this

**Comment by soumak77** [comment]
closing as non-actionable

**Comment by ragcsalo** [comment]
**command:** cordova plugin remove cordova-plugin-firebase

**output:**
```
Uninstalling cordova-plugin-firebase from android
Android Studio project detected
missing file :: app/src/main
Error during processing of action! Attempting to revert...
(node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Uh oh!
ENOENT: no such file or directory, open 'C:\Android\Apps\2018\mentalpainter\plat
forms\android\AndroidManifest.xml'
```

**result:** Almost EVERYTHING is deleted from platforms/android/app/src directory!!!!!!!!

**PLEASE** try to remove this Firebase plugin from your Android Studio project via CLI, and see what happens... it is a **NIGHTMARE!!!!!!**
