### ISSUE TITLE
What about android instant verification

### ISSUE THREAD

**Issue by Hirbod** [arnesson/cordova-plugin-firebase#623]
https://github.com/arnesson/cordova-plugin-firebase/blob/58c55c39f27f3b9628beccf6117a1b4b592d42db/src/android/FirebasePlugin.java#L673

do we have to cover this case? Creating a own callback for this should not be a big deal, but can we make sure that instant verification isn't active for us?

Currently my whole UI depends on showing an custom SMS Code Input field, but should this case really happen, we need to make sure to cover.

**Comment by Hirbod** [comment]
ping @soumak77

**Comment by soumak77** [comment]
any PRs are welcome

**Comment by Hirbod** [comment]
Well.. shit.

PhoneAuthCredential only has 

```
getProvider()
getSmsCode()
```

And get getSmsCode can be null if verified instantly (which will never happen, as we're using the js-sdk to finalize the auth process)... but onVerificationCompleted can still be called if the SMS-Code was fetched automatically, but It won't pass back the verificationId which is imporant for us to create a credential.

**Comment by Hirbod** [comment]
After digging into this whole shit for two days, I finally managed a hacky workaround without breaking my app.

I've added a simple callback to the onVerificationComplete (with verificationId set to false) and another key, "instantActivation: true" (onCodeSent I've set this to false).

This will at least trigger the registered callback, but you can't do really anything with it, but at this exception, I will call my server for a custom token and instead of creating a credential based on verificationId and  code, I sign in with "signInWithCustomToken". This is really the only way to get things work. 

This could help some ppl out there. I will provide some bundled PRs, they are not a solution to the whole problem (this can't be managed with this plugin, maybe a real "native" solution could fix this, but at least it makes it possible to incorporate a workaround/fallback)

**Comment by Hirbod** [comment]
PR is out
