### ISSUE TITLE
Anticipated timeframe for next release?

### ISSUE THREAD

**Issue by adamduren** [arnesson/cordova-plugin-firebase#625]
First off I want to thank you for your work on this project. I noticed that the last release was over 4 months ago and since then it seems like many fixes have been introduced such as support for cordova-android@7.0.0.

Is there a timeframe for the next release? It would be good if we could see more incremental releases along as well as a pathway to ensure backwards compatible changes can be more quickly incorporated while delaying breaking changes to expected intervals.

I would like to hear thoughts as well as help out where I can.

**Comment by soumak77** [comment]
I see issues get created or commented on every day for fixes that are apparently in master, yet no new version has been released.  Everyone trying out this library for the first time is getting a horrible experience being the version they are installing doesn't even work.  It only takes a couple minutes to push a new patch release. What is the hold up?

**Comment by s3ppo** [comment]
would be cool to get a new release.. my app actually isnt buildable :(

**Comment by soumak77** [comment]
@robertarnesson can you please add someone else to the list of maintainers so a new release can get published?

**Comment by adamduren** [comment]
@soumak77 That's a great idea. Far too often I see cordova plugins abandoned which I really think hurts the ecosystem as a whole.

**Comment by soumak77** [comment]
@adamduren agreed.  If we don't get a resolution to this in the coming weeks, we may want to think about creating a fork which can be maintained by the community.  It would be unfortunate to have to go down that route, but not having a release in 3 months is unacceptable.

**Comment by robertarnesson** [comment]
any volunteer maintainers? a donation would also do \o/

the intermediate solution is to add the plugin from git (rather than npm) in your project

**Comment by adamduren** [comment]
As mentioned in thread I'm interested in contributing. I'm fairly new to this particular project but have experience maintaining private repos as well as cordova plugins.

**Comment by adamduren** [comment]
This is an aside but related to the donation. It would be nice if Firebase had official support for Cordova or were willing to sponsor projects to advance the platform.

**Comment by soumak77** [comment]
@robertarnesson please add me as a maintainer

**Comment by soumak77** [comment]
@robertarnesson Is there any objection to publishing a new major release (i.e. version 1.0) to follow proper semver rules?  If not, I'll work on getting a prerelease created for testing sometime next week.

**Comment by robertarnesson** [comment]
@soumak77 thats fine with me - its about time I guess :)

**Comment by soumak77** [comment]
@robertarnesson if you haven't done so already, please add me as an owner to the npm package so that I can publish new releases

**Comment by soumak77** [comment]
@robertarnesson I pushed a new version to github, but I still need publishing permissions for the npm package

**Comment by fdambrosio** [comment]
I have the same problem, thanks

**Comment by soumak77** [comment]
version 1.0 has been released
