### ISSUE TITLE
iOS - Notifications clicked from notification drawer are identical to foreground notifications

### ISSUE THREAD

**Issue by skdavies** [arnesson/cordova-plugin-firebase#628]
This whole issue relates to iOS. There are two situations that produce identical data but should be handled separately. When the user has the app open and a new notification comes through, it is not shown (as expected). However, when a user has the app open and opens the notification drawer in the foreground and clicks a notification, nothing happens (not expected). This is because the notifications in these two cases are identical. Both notifications, when returned from the plugin have the "tap" boolean as false. This makes it impossible to handle these situations differently. I would think that a user clicking a notification from the notification drawer (even with the app open) would have a tap value of true (which it does when the app isn't open).

**Comment by soumak77** [comment]
fixed via https://github.com/arnesson/cordova-plugin-firebase/pull/680
