### ISSUE TITLE
No notifications on iOS when app is in background

### ISSUE THREAD

**Issue by pixelbreaker** [arnesson/cordova-plugin-firebase#63]
I've followed all the instructions I could find, and am a loss.
I'm receiving notifications in the app (in both XCode console and JavaScript with the `onNotificationOpen` handler.

Once I switch apps on the iPhone, XCode logs `2016-09-29 17:53:49.538 Burp[1715:2558636] Disconnected from FCM` and when I send another notification, nothing happens.

Once I bring the app to the foreground, it then receives the notification.

What am I missing?

PS thanks for all the work on this!

**Comment by bocodigital** [comment]
Since pulling notifications no longer work at.

**Comment by robertarnesson** [comment]
did you run grantPermission? this will promt the user to allow notifications.

**Comment by pixelbreaker** [comment]
@robertarnesson yes I did. I think it's a certificate issue, haven't had time to dig deeper yet.
