### ISSUE TITLE
Problem with android 8

### ISSUE THREAD

**Issue by fabiorave** [arnesson/cordova-plugin-firebase#631]
Push notifications are not being recieved in android 8. 

Does anybody know how can we solve it?

P.S.: This is my first time sending an issue in GitHub

**Comment by Kakiho** [comment]
Hey.
More details, please.
When do you have a bug?
If the application is closed, notifications may not be displayed (known problem).

Translate by Google =)

**Comment by fabiorave** [comment]
Simply nothing happens in the phone.

We send the message for the app through the Firebase Console. All phones recieve the push, except the Android 8 one.

Firebase console doesn't display any problems with the message. It shows that the message was delivered.

No erros are shown in anywere. So it's difficult to identify the problem.

**Comment by Kakiho** [comment]
Have you tried looking at the logs Android Studio?

**Comment by soumak77** [comment]
@fabiorave please test again with version 1.0

**Comment by fabiorave** [comment]
@soumak77 still not working :(

**Comment by soumak77** [comment]
please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by briantq** [comment]
@fabiorave It seems to be working for me.  If you are still seeing problem, please reopen the issue and we can see what we can do to help.
