### ISSUE TITLE
Ionic3 Android Firebase verifyPhoneNumber issue: "Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference"

### ISSUE THREAD

**Issue by EricSky1204** [arnesson/cordova-plugin-firebase#633]
Get Issue  in android real device.

**Attempt to invoke virtual method 'com.google.android.gms.tasks.Task
com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference**

-Here is my environment,

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.10.0
    npm   : 5.6.0 
    OS    : macOS Sierra
    Xcode : Xcode 9.2 Build version 9C40b 

-My code:  

     let number = "+65**********"
    (<any>window).FirebasePlugin.verifyPhoneNumber(number, 60, function (credential) {
    let prompt = this.alertCtrl.create({
      title: 'Enter the Confirmation code',
      inputs: [{ name: 'confirmationCode', placeholder: 'Confirmation Code' }],
      buttons: [
        { text: 'Cancel',
          handler: data => { console.log('Cancel clicked'); }
        },
        { text: 'Send',
          handler: data => {
            let loader =  this.loadingCtrl.create({
                content: 'Please wait...'
            });
            loader.present();
            var verificationId = credential.verificationId;
            var signInCredential = firebase.auth.PhoneAuthProvider.credential(verificationId, data.confirmationCode);
            firebase.auth().signInWithCredential(signInCredential).then(function(user){
              alert("Ok");
            }).catch(function(error){
              alert('error 2' + error);
            })
          }
        }
      ]
    });
    prompt.present();
    }, function (error) {

      console.error(error);
    });
   

What is "null object reference" meaning? Please help me as soon as possible.

**Comment by soumak77** [comment]
please test with version 1.0.2

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by EricSky1204** [comment]
Thank you.
