### ISSUE TITLE
Change android notification icon

### ISSUE THREAD

**Issue by michelsondan** [arnesson/cordova-plugin-firebase#634]
The Notification Icon that is showing is of Cordova, not my icon.
I use cordova-firebase-plugin 0.1.25
with Quasar.

1.
I have put all icons in src-cordova\platforms\android\app\src\main\res\drawable-X
(I named the icon's to "notification_icon.png")

![image](https://user-images.githubusercontent.com/22793811/38609524-f9747f28-3d86-11e8-8327-cb6836839537.png)

2.
Change in src-cordova\platforms\android\app\src\main\AndroidManifest.xml -

![image](https://user-images.githubusercontent.com/22793811/38609386-97319a8a-3d86-11e8-998b-67ccb56a279a.png)
 

3.
I even try to change in server side - 
notification = new
                    {
                        body = myBody,
                        title = myTitle,
                        sound = "Enabled",
                        **icon = "notification_icon"**
                    }

Not working.

Notice - In version 0.1.24 it worked perfect !

Please help
Thanks

**Comment by michelsondan** [comment]
Someone? at least can someone write from where the default icon location (Cordova icon) so I can try to overwrite it...

**Comment by jackvial** [comment]
+1 Would be good to get something in the docs on this.

**Comment by almasmaris** [comment]
@jackvial hello any update for this?

**Comment by Zvika88** [comment]
BTW this used to work with the icons pngs in the drawable folders as descrived above when on my Node.js server I used fcm-node package and put the 'icon' property in my notification object. 

However now that I switched to admin.messaging() , (because fcm-node is outdated and no longer supports desktop push), this is no longer working. Help is much needed here, thanks!

**Comment by almasmaris** [comment]
try this [https://github.com/arnesson/cordova-plugin-firebase/issues/426#issuecomment-334193721](url) just add the config in androidmanifest.xml. It's works for me

**Comment by marcelledi** [comment]
Any news?

**Comment by almasmaris** [comment]
@marcelledi add this `<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />` inside application tag works for me

**Comment by kpshinde** [comment]
Any update on this issuee?

**Comment by monn1** [comment]
@kpshinde Try to do what @almasmaris said. It worked for me.

**Comment by soumak77** [comment]
closing as resolved per @almasmaris's comment

**Comment by mrtaltnn** [comment]
My problem is continuing.

My plugin version: 1.0.5 (I use this version for issue #899  problem)
Cordova android version: 6.3.0 

**Config.xml**
![image](https://user-images.githubusercontent.com/40419928/46534339-82db2780-c8b0-11e8-9d51-f34495fae9fb.png)

**Folder**
![image](https://user-images.githubusercontent.com/40419928/46535878-5bd32480-c8b5-11e8-8f89-07237a483728.png)

**Payload**
`{"tap":true,"body":"testPanel","date":"1538738092","icon":"notification_icon","pnid":"2441","alert":"testPanel","notId":"29134","title":"TEST","deeplink":"{\"parameters\":{\"contentType\":\"announcement\",\"referenceId\":95},\"pageName\":\"content-detail\"}"}]`

**Statusbar**
![image](https://user-images.githubusercontent.com/40419928/46536865-6f33bf00-c8b8-11e8-8b94-19f4c5dace50.png)


**Problem**
![image](https://user-images.githubusercontent.com/40419928/46534603-5bd12580-c8b1-11e8-808c-29410e0ce5f9.png)

**Comment by Farrukhbek11** [comment]
Try to build apk, in apk working with original icon. I think problem in in emulator
