### ISSUE TITLE
After installing the Plugin I received an error on build - cordova-build error : ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font

### ISSUE THREAD

**Issue by emostackfm** [arnesson/cordova-plugin-firebase#640]
Hi All,
After installing the Plugin using Visual Studio- Cordova Type of Application I received the following errors.
Do you know how I can solve them? I read everything on the net but without success. Thanks in advance

1>MSBUILD : cordova-build error : ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
1>MSBUILD : cordova-build error : ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
1>MSBUILD : cordova-build error : ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
1>MSBUILD : cordova-build error : ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex

**Comment by tomLadder** [comment]
same issue

**Comment by soumak77** [comment]
@BluebambooSRL please test with version 1.0

**Comment by tomLadder** [comment]
i am using version 1.0.0 but still get this error

**project.properties**
`
target=android-25
android.library.reference.1=CordovaLib
cordova.gradle.include.1=phonegap-plugin-push/messenger-push.gradle
cordova.system.library.1=com.android.support:support-v4:23+
cordova.system.library.2=com.google.android.gms:play-services-gcm:+
cordova.gradle.include.2=cordova-plugin-crosswalk-webview/messenger-xwalk.gradle
cordova.gradle.include.3=cordova-hot-code-push-plugin/messenger-chcp.gradle
cordova.gradle.include.4=cordova-plugin-firebase/messenger-build.gradle
cordova.system.library.3=com.google.gms:google-services:+
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-crash:+
cordova.system.library.8=com.google.firebase:firebase-config:+
cordova.system.library.9=com.google.firebase:firebase-perf:+`

**Comment by tomLadder** [comment]
actually its a conflict between two plugins. i think they use different versions of the google services.

In my case: **"cordova-plugin-crosswalk-webview" spec="~2.2.0"** and **"cordova-plugin-firebase spec="~1.0.0"**

**Comment by tomLadder** [comment]
I just fixed the problem.
Solution: force a specific com.android.support version

add the following in build.gradle (below buildscript)
`
configurations.all {
resolutionStrategy {
    force 'com.android.support:support-v4:24.0.0'
}}
`

**Comment by BluebambooSRL** [comment]
It working! Thanks

**Comment by tomLadder** [comment]
i am using vscode and i have not had this issue..

connect your smartphone to your dev machine and execute `adb logcat ActivityManager:I MyApp:V -e INFO:CONSOLE*` in your favourite shell. It should print out the error causing the crash.

**Comment by emostackfm** [comment]
Thanks Tom. I will try this now. My steps were:
1 Install cordova-plugin-firebase
2 Put your script - configurations.all { resolutionStrategy { force 'com.android.support:support-v4:24.0.0' }} in the gradle file
3 Add google-services.json in my root solution 

I will try to connect my device now. Thanks again for your help

**Comment by tomLadder** [comment]
@emostackfm 

There is an error @com.android.support - ArrayList in 24.0.0. 
Just try another version like:

`
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:25.1.1'
    }
}
`

**Comment by shikelong** [comment]
some issue with version 1.0.0

**Comment by emostackfm** [comment]
Thank you very much Tom Ladder! This solved my issue!
