### ISSUE TITLE
No records for Firebase Analytics: values.xml is note generated

### ISSUE THREAD

**Issue by BluebambooSRL** [arnesson/cordova-plugin-firebase#641]
Hi there! Many thanks for this plugin.
I wonder to know if I must use this plugin with cordova-plugin-google-services or other. 
I set the google-services.json in the root path. When I add the plugin it copied into /platform/android... but when I check the records in Firebase Analytics (Android) there is no information (iOS works fine).
It seems that the plugin is not generating the /platforms/android/build/generated/res/google-services/debug/values.xml that should contained the keys for tracking.

I use this command: ionic cordova platform build android --prod

Is there any plugin or command line missing?

Thanks in advance
Federico

**Comment by BluebambooSRL** [comment]
Hi @blakek! Perhaps you can iluminate me! Thanks in advance

**Comment by soumak77** [comment]
@BluebambooSRL please test with version 1.0

**Comment by soumak77** [comment]
closing as resolved, please reopen if this is still an issue with the latest version
