### ISSUE TITLE
get error when building the app

### ISSUE THREAD

**Issue by arselan-7** [arnesson/cordova-plugin-firebase#645]
I get this problem after building my app yesterday.
Any suggestions, how to solve it ?
thanks in advance.

`BUILD FAILED
 in 3s
38 actionable tasks: 36 executed, 2 up-to-date

(node:4035) UnhandledPromiseRejectionWarning: Error: /home/belkacemi/Modèles/HCH-PROTECTION/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/belkacemi/Modèles/HCH-PROTECTION/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:49: error: cannot access zzbgl
        Map<String, String> data = remoteMessage.getData();
                                                ^
  class file for com.google.android.gms.internal.zzbgl not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
`

**Comment by mknnaren** [comment]
Same here.
Logs:

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:22: error: package com.google.firebase.perf does not exist
import com.google.firebase.perf.FirebasePerformance;

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:23: error: package com.google.firebase.perf.metrics does not exist
import com.google.firebase.perf.metrics.Trace;

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:739: error: cannot find symbol
    private HashMap<String, Trace> traces = new HashMap<String, Trace>();

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:747: error: cannot find symbol
                    Trace myTrace = null;

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:753: error: cannot find symbol
                        myTrace = FirebasePerformance.getInstance().newTrace(name);

platforms/android/src/org/apache/cordova/firebase/FirebasePlugin.java:779: error: cannot find symbol
                    if (myTrace != null && myTrace instanceof Trace) {

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by kapilSoni101** [comment]
@soumak77 sir why this issue is closed this issue is still here please open above issue,i have already installed above plugin but not working?
