### ISSUE TITLE
PLUGIN_NOT_INSTALLED (ANDROID)

### ISSUE THREAD

**Issue by leoassiscosta** [arnesson/cordova-plugin-firebase#646]
Steps:
npm install -g ionic cordova
npm install firebase angularfire2 --save
ionic start authApp blank
ionic cordova platform add android
ionic cordova plugin add cordova-plugin-firebase
npm install --save ionic-native/firebase
Copy google-services.json

ionic cordova buld android --release
Assign the App
Register app in firebase.
Install app in android device

When i execute getVerificationID function show me a error in device
PLUGIN_NOT_INSTALLED
Exception java.lang.Exception: plugin_not_installed
org.apache.cordova.firebase.FirebasePlugin$13.run (FirebasePlugin.java:445)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

PS: in same button i invoke getToken(), and returns normally

  public sendPhone(phoneNumber: number){
    try{
      this.firebase.getToken().then(token => this.toast.show(`The token is ${token}`));
      this.firebase.getVerificationID("+5551999999999").then(value =>{
        this.toast.show(value);
      })
      .catch((error) => {
        **this.toast.show(error);** ERROR
        this.firebase.logError(error);
      });
    }
    catch(error)
    {
      this.toast.show(error.message);
    }
  }

**Comment by Unkn0wn0x** [comment]
You should take a close look at the Ionic-Documentation.
- https://ionicframework.com/docs/native/firebase/

Section "getVerificationID" says, it's only supported for Apple iOS, not Google Android.

So it's not a Bug.

Cheers
Unkn0wn0x

**Comment by soumak77** [comment]
@leoassiscosta please use [verifyPhoneNumber](https://github.com/arnesson/cordova-plugin-firebase#verifyphonenumber)

This method should be working in android with version 1.0 and will work with iOS in the next release (see https://github.com/arnesson/cordova-plugin-firebase/pull/636)

**Comment by leoassiscosta** [comment]
i change by verifyPhoneNumber, and show the same error. (PLUGIN_NOT_INSTALLED)

 this.firebase.verifyPhoneNumber("+5551999999999",5000).then(value =>{
        this.toast.show(value);
      })
      .catch((error) => {
        this.toast.show(error);
        this.firebase.logError(error);
        //console.error("SMS não enviado", error);
      });

**Comment by Jaylton** [comment]
Você conseguiu resolver isso?
