### ISSUE TITLE
iOS Permission Dialog Appearing On Launch Instead of When grantPermission() is Called

### ISSUE THREAD

**Issue by maxmatthews** [arnesson/cordova-plugin-firebase#648]
I'm trying to delay the popup on iOS to not appear until it's better in our user flow as opposed to the first time the user opens the app. Any suggestions on how to accomplish this?

**Comment by soumak77** [comment]
@maxmatthews I recently updated the Firebase iOS SDK to the latest version.  Please install the plugin via github and see if it helps with anything.

**Comment by maxmatthews** [comment]
Still the same problem. Just removed and readded the cordova plugin from the git repo and still the same issue. Even without calling `window.FirebasePlugin` anywhere in my code base, as soon as I still in the plugin and run on iOS, I get the grant permission dialog.

**Comment by soumak77** [comment]
@maxmatthews agreed, a new variable should be added to the plugin to configure this functionality.  The README should be updated to include this new variable with a note that it is only used for ios.  If possible, it should also be used for android.

```
<plugin name="cordova-plugin-firebase" spec="^1.0.0" />
    <variable name="AUTO_SHOW_NOTIFICATION_DIALOG" value="false"/>
</plugin>
```

**Comment by maxauger** [comment]
@soumak77 does this solution work fine for you ? It still ask permission on launch for me... Shame for my UX scheme ^^

**Comment by maxmatthews** [comment]
@maxauger I think that was more a spec on how it should be implemented. The plugin hasn’t been updated yet to use that config line.

**Comment by Hirbod** [comment]
This Issue introduced since the upgrades.. did not happen while I was on 0.1.25.. Could this be fixed asap?

**Comment by Hirbod** [comment]
No need for a config file
https://github.com/arnesson/cordova-plugin-firebase/issues/664

This lines should be deleted asap. It's a unnecessary BC. Whoever wants to have a instant prompt dialog can just call "grantPermission" on deviceready. This is a useless overhead

**Comment by Hirbod** [comment]
It‘s fixed, please close @soumak77

Just use grantPermission() if you want to have it at startup

**Comment by maxauger** [comment]
Thanks a lot you for your efficiency !!

**Comment by shriharip** [comment]
It still asks for permissions on startup even after removing everything. It is such a bad experience

**Comment by Hirbod** [comment]
Its not. You may have not installed the right version

**Comment by shriharip** [comment]
@Hirbod  here is the details of my install .. I have @ionicNative-firebase which is ^4.9.0 and my cordova-plugin-firebase is spec ^1.0.3. Is this not right?

**Comment by Hirbod** [comment]
As far as I can see from the commit history, my changes were integrated into version 1.0.4

**Comment by shriharip** [comment]
yeah, i updated to the latest version and i don't have the issue now
