### ISSUE TITLE
onNotificationOpen is not firing on Ios (No push notification received)

### ISSUE THREAD

**Issue by hussain-github** [arnesson/cordova-plugin-firebase#650]
onNotificationOpen is not firing at all weather the app in foreground or background. I spent days trying every solution suggested on the threads. I do not get any push notification.
Please note that everything is working (subscribe, hasPermission, grantPermission, getToken) except for  onNotificationOpen. I also did not use Firebase Console as instructed by the plugin owner. I used the http request from server and it's submitted successfully. Kindly any suggestions?

**Comment by maxauger** [comment]
I have the same issue and spent days too ! Have you find a solution ?

**Comment by hussain-github** [comment]
Yes. It's working now. Actually the plugin works perfectly. If you implement the plugin instructions precisely then the problem is most probably with your configuration. 

Here are the the configurations that you need check carefully:
- You must create a private fork of this plugin and replace **package.json** & **plugin.xml** with your own settings. (in case you're using Phonegap Build) 
- Firebase configuration file (**info.plist**) must be added to your app prject root.
- Apple certificates. This was my problem. I thought that generating **.P8** from Apple Developer and then uploading it to Firebase is enough. However, it turned out that your application must have a push notification certificate from Apple too (push notification enabled). 
In deed, I had one but the problem was in the Apple developer it said it's Configurable. This is exactly was my issue: **Configurable certificate**. This will not work with you until you regenerate the certificates again so this Configurable word turns to enabled (green circle)

I hope this would help.

**Comment by maxauger** [comment]
it was my certificates that were not available ! :-) thank you
