### ISSUE TITLE
I cant build th app.Is this plugin conflict with geolocation?

### ISSUE THREAD

**Issue by ce1011** [arnesson/cordova-plugin-firebase#651]
When I buld the app.I get this error:
`error: cannot access zzbfm
        ResultCallback<LocationSettingsResult> {
                      ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: H:\Parking\platforms\android\app\src\main\java\cordova\plugins\Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.`

**Comment by t2wu** [comment]
I'm having a similar problem after I specify all com.google.firebase:* to version 11.8.0, but it's with a different file:FirebasePluginMessagingService.java. 

Just curious, which Geofence library are you using? I'm using Geofence as well, and I'm changing the firebase lib version due to a conflict with the Geofence lib, too.

**Comment by ce1011** [comment]
I m using the cordova-plugin-cordova.You solve the problem by changing the firebase lib version?

**Comment by ComeBurguburu** [comment]
The solution is here 
https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404

**Comment by hvaughan3** [comment]
I also solved a similar problem (I am using Cordova only) by running `cordova clean` and then attempting to rebuild.

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)
