### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']    > For input string: "+"

### ISSUE THREAD

**Issue by sagarkul** [arnesson/cordova-plugin-firebase#652]
I have installed "cordova-plugin-firebase": "^1.0.0"
I am getting an error while building the app.
 ionic cordova build --release android
```

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\app\platforms\android\cordova-support-google-services\in-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   >

BUILD FAILED

Total time: 2.196 secs
For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
(node:5292) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\app\platforms\android\cordova-support-google-services\in-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Picked up _JAVA_OPTIONS: -Xmx512M
(node:5292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by soumak77** [comment]
@sagarkul the error doesn't seem related to this plugin.  Try installing https://github.com/dpa99c/cordova-android-support-gradle-release or https://github.com/dpa99c/cordova-android-play-services-gradle-release to fix the gradle build.

**Comment by sagarkul** [comment]
The problem was conflict with OneSignal package.
I removed OneSignal and completely switched to firebase for notification.. 
Also removed Firebase Analytics package.

**Comment by ClaudineiOlSantos** [comment]
tenho o mesmo problema usando o ionic 3:
* Where:
Script 'C:\Users\claudinei\projetos\risa-app\risa-app-novo\platforms\android\cordova-support-google-services\risashop-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

my ambient:


Ionic:

   ionic (Ionic CLI)  : 4.10.3 (C:\Users\claudinei\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
