### ISSUE TITLE
When app is killed, notification will not fire.

### ISSUE THREAD

**Issue by joe-scotto** [arnesson/cordova-plugin-firebase#655]
If the app is killed and a notification is launched, nothing will happen.

**Comment by remisture** [comment]
Same issue for me. Is there a way to keep the app alive to avoid this?

**Comment by soumak77** [comment]
@joe-scotto @remisture please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by joe-scotto** [comment]
@remisture @soumak77 I was actually able to fix this by removing the local notification plugin.

**Comment by remisture** [comment]
Only Android changes in #222, so that will probably not fix my iOS issues.
