### ISSUE TITLE
Add plugin FAIL

### ISSUE THREAD

**Issue by leoassiscosta** [arnesson/cordova-plugin-firebase#658]
ionic cordova plugin add https://github.com/arnesson/cordova-plugin-firebase

(node:1648) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/arnesson/cordova-plugin-firebase via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

OR

cordova plugin add cordova-plugin-firebase --save 
stay stuck

OR

npm install cordova-plugin-firebase
Stuck Here "extract:fsevents: sill pacote fsevents@1.2.2 extracted to..."

And my connection is OK.

**Comment by leoassiscosta** [comment]
AND 
npm install cordova-plugin-firebase
Stuck Here "extract:fsevents: sill pacote fsevents@1.2.2 extracted to..."

**Comment by pegasx** [comment]
Finally I had no problem:

cordova plugin add cordova-plugin-firebase@1.0.2 --save

**Comment by soumak77** [comment]
closing as resolved

**Comment by Anujmoglix** [comment]
still showing issue 
> (node:2501) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin cordova-plugin-firebase@1.0.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm WARN @angular/http@4.0.0 requires a peer of @angular/core@4.0.0 but none was installed.
npm WARN @angular/http@4.0.0 requires a peer of @angular/platform-browser@4.0.0 but none was installed.
npm WARN @ionic-native/transfer@3.14.0 requires a peer of @ionic-native/core@^3.6.0 but none was installed.

npm ERR! code EINTEGRITY
npm ERR! sha1-SFwMaF6cwyJtdco+L7l9xiDNB+Q= integrity checksum failed when using sha1: wanted sha1-SFwMaF6cwyJtdco+L7l9xiDNB+Q= but got sha1-QWCJLAk+6IfRUYulxXVroPIqNa0=. (13187910 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-05-02T11_28_41_711Z-debug.log
(node:2501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pegasx** [comment]
Now the version is 1.0.4. Each time you change the version, a connection problem occurs.

@Anujmoglix you can try cordova plugin add cordova-plugin-firebase@1.0.2 --save

**Comment by DanielRiera** [comment]
Same problem with 1.0.4 version

cordova-plugin-firebase@1.0.2 --save 

it working

**Comment by guyman** [comment]
cordova plugin add cordova-plugin-firebase hangs stuck
And all the specific versions mentioned here are stuck too.

I'm using latest Cordova and latest Android SDK

**Comment by timsar2** [comment]
still stuck on it
many time used Ctrl+c
C:\Drive D\test\ionic\fcmDemo>ionic cordova plugin add cordova-plugin-firebase
> cordova plugin add cordova-plugin-firebase --save

C:\Drive D\test\ionic\fcmDemo>

C:\Drive D\test\ionic\fcmDemo>ionic cordova plugin add cordova-plugin-firebase
> cordova plugin add cordova-plugin-firebase --save

C:\Drive D\test\ionic\fcmDemo>

C:\Drive D\test\ionic\fcmDemo>ionic cordova plugin add cordova-plugin-firebase
> cordova plugin add cordova-plugin-firebase --save

C:\Drive D\test\ionic\fcmDemo>

C:\Drive D\test\ionic\fcmDemo>ionic cordova plugin add cordova-plugin-firebase@1.0.2
> cordova plugin add cordova-plugin-firebase@1.0.2 --save

C:\Drive D\test\ionic\fcmDemo>ionic cordova plugin add cordova-plugin-firebase@1.0.2
> cordova plugin add cordova-plugin-firebase@1.0.2 --save

**Comment by timsar2** [comment]
yes, with latest nodejs and waiting over 10 min,it's done.
