### ISSUE TITLE
iOS notification are not working with 0.1.13

### ISSUE THREAD

**Issue by Krisa** [arnesson/cordova-plugin-firebase#66]
Like mentioned in this thread https://github.com/arnesson/cordova-plugin-firebase/issues/57, it seems that iOS notifications are not working with the latest version of this plugin.

To be exact, the notifications, generated by a token of the version 0.1.12 **are** working on the version 0.1.13. However, after a fresh install (i.e. by **removing** before the app from the device), a new token is generated, and this token will not send the notification to the device, even so the response from fcm is a success. Downgrading the application to 0.1.12 by making a simple update and using the 0.1.13 token will also fail... Therefore my bet would be that there must be something wrong when the token is generated on the version 0.1.13.

**Comment by achuinard** [comment]
Did I break it with this PR? https://github.com/arnesson/cordova-plugin-firebase/pull/60

How are you getting the token? There was never a good way before I added that PR. When were you calling getInstanceId? It could be null...it's useless to just call it once.

**Comment by Krisa** [comment]
I cannot say if this PR is breaking it, but my code is quite simple:
```
var app = {
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
        window.FirebasePlugin.grantPermission(); 
        window.FirebasePlugin.getInstanceId(
            function(token) {
                console.error(token);
            },
            function(error) {
                console.error(error);
            }
        );

        window.FirebasePlugin.onNotificationOpen(
            function(success) {
                console.log('SucessNotification:' + success);
            }, function(error) {
                console.error(error);
            }
        );
    }
};

app.initialize();
```

Anything not correct here?

On 0.1.12, this works well (including iOS10), or at least I never experienced any issue. The only specific config I apply is in the `Capabilities` tab, I toggle `Push Notifications` and `Background Modes` to on, and in `Background Modes`, I check `Remote notifications`.
![image](https://cloud.githubusercontent.com/assets/1253866/19219388/fa52a508-8e11-11e6-805c-47dbc35979dd.png)
![image](https://cloud.githubusercontent.com/assets/1253866/19219383/e3f1a6ba-8e11-11e6-81c4-2a931e13e9e4.png)

That's really all I can tell ...

**Comment by rossi256** [comment]
I am having the same issue...
didn't work on 0.1.13 - after reading this went to 0.1.12 and works.
even though there are a bunch of warnings/erros in Xcode console
Unable to connect to FCM. Error Domain=com.google.fcm Code=501 "(null)"
same with code 1001
and code 2001

**Comment by EricHigdon** [comment]
@achuinard It wasn't you. It broke in #20cf365 with the sdkupgrade. The latest version that works is 0.1.12. However, background notifications still don't work there, so that was probably the reason for upgrading the sdk.

**Comment by achuinard** [comment]
@EricHigdon glad to hear. so what is the fix?

**Comment by EricHigdon** [comment]
@achuinard Good question. The closest I have come is getting foreground notifications to work. Background still doesn't work for me. I've been working at it, but Objective-C is completely new to me so I'm not making much progress.

**Comment by AlexKvazos** [comment]
Will this plugin not work on iOS 10, I am not sure wether to use Firebase or to manually handle push notifications myself.

**Comment by jpduckwo** [comment]
I'm also having these issues, however I'm new to the plugin so I can't verify it was working before. Using 0.1.13 with Xcode 8 and iOS 10. Manually updating capabilities is something I had to figure out too, I think this should be done automatically by the plugin. I'm just going to check the remote notifications one too.

**Comment by Vunovati** [comment]
Since it is not mentioned anywhere in the issue, let me just add that the current version (0.1.13) is not working on iOS10 but is working on the iOS9 (both in foreground and in background).

**Comment by achuinard** [comment]
Yes, iOS 9 works fine, iOS 10 doesn't.

**Comment by robertarnesson** [comment]
update to 0.1.14

**Comment by dherre3** [comment]
iOS still  not working for me, I have version 0.1.15, iOS 10, it registers fine with a proper ID but I cannot receive any notification in the foreground or background, I would appreciate any pointers!
Thanks!

**Comment by chanphillip** [comment]
+1
not working on iOS10 but Android

**Comment by AlexKvazos** [comment]
It is working in iOS. You have to check your configuration with Firebase, make sure your APNS certificates are valid, and that you've placed the google services properties list file on the xcode project.

**Comment by Krisa** [comment]
Closing the issue as it seems for me working on 0.1.17.
