### ISSUE TITLE
IOS: Notification tap property is always false when tap on notification in foreground

### ISSUE THREAD

**Issue by erik881** [arnesson/cordova-plugin-firebase#660]
cordova-firebase-plugin 1.0.2

Steps:
1. receive 2 notifications in background
2. tap on first notification -> Application is opened onNotificationOpen is executed with notification.tap = true
3. tap on second notification -> onNotificationOpen is executed with notification.tap = false 

Expected: notification.tap should always be true when user taps on notification to open.
Android: everything works ok.

Could you please review and suggest workarounds if any?

Thanks

**Comment by soumak77** [comment]
fixed via https://github.com/arnesson/cordova-plugin-firebase/pull/680
