### ISSUE TITLE
In PhoneGap Build, getting Error: more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by jamminjames** [arnesson/cordova-plugin-firebase#661]
I'm trying to get this working in an Android App I have built with PhoneGap Build. I'm aware of the "hooks" issue, but want to try a solution for that [I found suggested](https://stackoverflow.com/questions/39754798/firebase-push-notifications-with-phonegap-build-using-cordova-plugin-fcm) that uses a resource file line in the platform section of the config.xml file, like so:
`<resource-file src="google-services.json" target="app/google-services.json" />`
...and including the .json file in the root of the project.

However, I can't get far enough to test that, as I am getting the 'com.google.android.gms' error: more than one library with package name 'com.google.android.gms'. I've seen elsewhere that the solution for this is editing the /android/build.gradle file in a build, but since mine is a PhoneGap Build project, that won't work. Is there any solution to this for us Build users? 

Thanks for any help.

**Comment by soumak77** [comment]
this appears to be fixed by installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)
