### ISSUE TITLE
It is reciving notigfications in forground but not in background

### ISSUE THREAD

**Issue by DevelopedByAnurag** [arnesson/cordova-plugin-firebase#665]
the app has stopped receiving notifications in the background and receives notification only when app is open

**Comment by soumak77** [comment]
@anuragbatra please see if PR #222 fixes this issue.  Install the plugin from github to test.

**Comment by Birowsky** [comment]
@soumak77 I tried it, `window.FirebasePlugin.onNotificationOpen` does not fire the handler.

**Comment by briantq** [comment]
@DevelopedByAnurag @Birowsky Which playforms are you having issues on Android and/or iOS?

**Comment by Birowsky** [comment]
@briantq I was testing iOS

**Comment by briantq** [comment]
@Birowsky I had a similar problem when I started using Firebase.  I can confirm that it is working with both the latest v1 and v2 versions of the plugin, so I think it is something with your configuration.  

That being said, I found this article to be incredibly helpful when trying to debug push notifications, https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html  

Also, you want to check the Capabilities on your XCode project file.  I have found that when I use `cordova prepare` that Push Notifications doesn't get checked all the time.  This actually happened to me previously as I had push notifications stop working randomly, and found this was my issue.

If you find something that points back to the plugin, please reopen this issue.
