### ISSUE TITLE
Getting Phonegap build error

### ISSUE THREAD

**Issue by ph-eh** [arnesson/cordova-plugin-firebase#669]
Im getting the following error when running Phonegap build (cli-6.5.0) :

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: FirebasePluginMessagingService.java

Just now I updated this firebase plugin to get all the latest changes and still have this error. Builds fine for iOS. I also tried changing Phonegap config to use cli-7.0.1 and still it errors.

The error log produces this info.....

BUILD FAILED

Total time: 3.557 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:3: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/project/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:175: error: cannot find symbol
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                                                                                  ^
  symbol:   variable O
  location: class VERSION_CODES
/project/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:176: error: cannot find symbol
              NotificationChannel channel = new NotificationChannel(channelId,
              ^
  symbol:   class NotificationChannel
  location: class FirebasePluginMessagingService
/project/src/org/apache/cordova/firebase/FirebasePluginMessagingService.java:176: error: cannot find symbol
              NotificationChannel channel = new NotificationChannel(channelId,
                                                ^
  symbol:   class NotificationChannel
  location: class FirebasePluginMessagingService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.

**Comment by Hlaphoneo** [comment]
Was this issue resolved ? , I've been experiencing this for the past 7 hours.

**Comment by ph-eh** [comment]
The issue is still there. I've just updated all my files with the latest changes and still gives me this build error for Android, still works fine in iOS.

**Comment by ph-eh** [comment]
Just thought I'd also mention that I have just created a fresh Phonegap project, with no other plugins and only this firebase plugin installed. The same build error occurs for Android. I did this as a test to make sure it wasnt conflicting with any other plugins I had, and it clearly isn't in this scenario.

**Comment by Hlaphoneo** [comment]
Okay I see. I'm on ionic framework, I resolved this issue by removing Android platform 6.2.3 with the latest one, and the project built without any problems.

**Comment by ph-eh** [comment]
Unfortunately I've managed to break my entire build. So I've made a backup and going to start from a fresh updated Phonegap project, trying to use all the latest versions etc. Will check back in here when I've done.

**Comment by ph-eh** [comment]
Update: I now have this running using Phonegap cli-7.1.0, had to add this in the config.xml:
<preference name="phonegap-version" value="cli-7.1.0" />

I did try to go to cli-8.0.0 but introduced many other errors with other plugins that are not yet compatible.

**Comment by soumak77** [comment]
closing as fixed per the [above comment](https://github.com/arnesson/cordova-plugin-firebase/issues/669#issuecomment-390625352)
