### ISSUE TITLE
How to open specific pages using dynamic links?

### ISSUE THREAD

**Issue by ibrahimAboelsuod** [arnesson/cordova-plugin-firebase#67]
I don't think this plugin support dynamic links-or is it?
If it does, how to open a specific page after user clicks a dynamic link and open the app?
Thanks

**Comment by shahbazcool98** [comment]
see this [my answer](http://stackoverflow.com/a/39873647/4685284) . I had the same issue. Please upvote my answer if it is helpful.

**Comment by ibrahimAboelsuod** [comment]
Thanks, let me test it and get back to you.

**Comment by mathieu21** [comment]
anyone ?

**Comment by ibrahimAboelsuod** [comment]
I ended up using another plugin for universal URLs with this one to get the desired result

**Comment by mathieu21** [comment]
but how did you pass the url into the notification ? or did you use the data ?

**Comment by ibrahimAboelsuod** [comment]
I didn't need to use the notification, I was keeping track of the number of timer the url is used

**Comment by mathieu21** [comment]
but you were still calling the user with the notification and then regarding the time the app is open, redirect in the app ? Or you are using something else.

Because I am stuck with the right way to do this and still cant find something efficient yet :(

**Comment by ibrahimAboelsuod** [comment]
I didn't use a notification at all :D I have no idea how it interacts with the whole thing, I can help if you explained more what you want to do

**Comment by mathieu21** [comment]
I see, actually what I am looking to do is quite simple juste open a notification and depending of the notification go into a special page in the app, but I have read everything and can't find any solution to make it happen, any idea ?

**Comment by ibrahimAboelsuod** [comment]
I don't think firebase has your a solution, I suggest searching about a cordova plugin that would do specifically that .

**Comment by ibrahimAboelsuod** [comment]
The plugin I used with this for future reference: https://github.com/nordnet/cordova-universal-links-plugin
