### ISSUE TITLE
Firebase build issue

### ISSUE THREAD

**Issue by TysonMot** [arnesson/cordova-plugin-firebase#670]
anyone, can i be assisted please

Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\New folder\BlankCordovaApp4\BlankCordovaApp4\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java:3: error: cannot find symbol	BlankCordovaApp4		1	
Severity	Code	Description	Project	File	Line	Suppression State
Error		 if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) 	BlankCordovaApp4		1

**Comment by TysonMot** [comment]
Managed to solve it..

**Comment by PrithiviRajG** [comment]
@TysonMot How did you solve the issue? I am also facing the same issue.
