### ISSUE TITLE
Ionic build error google version does not matched

### ISSUE THREAD

**Issue by cedrickbae** [arnesson/cordova-plugin-firebase#678]
Error from fresh install cordova-firebase

Here are the errors

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
> > Could not find any version that matches com.google.android.gms:play-services-flags:12.+.
>   Versions that do not match:
>       15.0.1
>       15.0.0
> Required by:
>       project :app > com.google.firebase:firebase-crash:15.0.2
>       project :app > com.google.firebase:firebase-auth:15.1.0
> Could not find any version that matches com.google.android.gms:play-services-measurement-base:12.+.
>   Versions that do not match:
>       15.0.2
>       15.0.0
> Required by:
>       project :app > com.google.firebase:firebase-crash:15.0.2
>       project :app > com.google.firebase:firebase-crash:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2
>       project :app > com.google.firebase:firebase-auth:15.1.0 > com.google.firebase:firebase-analytics:15.0.2
>       project :app > com.google.firebase:firebase-core:15.0.2 > com.google.firebase:firebase-measurement-connector-impl:15.0.0
> > Could not find any version that matches com.google.android.gms:play-services-phenotype:12.+.
>   Versions that do not match:
>       15.0.1
>       15.0.0
> Required by:
>       project :app > com.google.firebase:firebase-config:15.0.2
>       project :app > com.google.firebase:firebase-perf:15.1.0
> > Could not find any version that matches com.google.android.gms:play-services-clearcut:12.+.
>   Versions that do not match:
>       11.0.4
>       11.0.2
>       11.0.1
>       11.0.0
>       10.2.6
>       + 13 more
> Required by:
>       project :app > com.google.firebase:firebase-perf:15.1.0
> > Could not find any version that matches com.google.android.gms:play-services-ads-identifier:12.+.
>   Versions that do not match:
>       15.0.1
>       15.0.0
>  Required by:
>       project :app > com.google.firebase:firebase-crash:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2
> > Could not find any version that matches com.google.android.gms:play-services-stats:12.+.
>   Versions that do not match:
>       15.0.1
>       15.0.0
> Required by:
>       project :app > com.google.firebase:firebase-crash:15.0.2 > com.google.firebase:firebase-analytics-impl:15.0.2
>       project :app > com.google.firebase:firebase-crash:15.0.2 > com.google.firebase:firebase-iid:15.1.0
>       project :app > com.google.firebase:firebase-auth:15.1.0 > com.google.firebase:firebase-analytics:15.0.2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 17s
> (node:3740) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.

**Comment by cedrickbae** [comment]
I have also tried [612](https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-375248132) and [this](https://github.com/arnesson/cordova-plugin-firebase/issues/612#issuecomment-376217404) but still does not work

**Comment by guilhermehtk** [comment]
I'm having the same error, I already tried `cordova-android-play-services-gradle-release` in various ways and changes in gradle. The problem occurs according to the other installed plugins, in my case, when I install `intercom-cordova` and add` <preference name = 'intercom-android-push-type' value = "FCM" /> `to config. xml this error appears.

**Comment by soumak77** [comment]
Try adding `cordova-android-firebase-gradle-release` per the [README](https://github.com/arnesson/cordova-plugin-firebase#google-play-services).  This newly created plugin was required to get android tests to pass for this repo.
