### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by hector-oviedo-dev** [arnesson/cordova-plugin-firebase#679]
\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java:3: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java:175: error: cannot find symbol
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                                                                                  ^
  symbol:   variable O
  location: class VERSION_CODES
\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java:176: error: cannot find symbol
              NotificationChannel channel = new NotificationChannel(channelId,
              ^
  symbol:   class NotificationChannel
  location: class FirebasePluginMessagingService
\platforms\android\src\org\apache\cordova\firebase\FirebasePluginMessagingService.java:176: error: cannot find symbol
              NotificationChannel channel = new NotificationChannel(channelId,
                                                ^
  symbol:   class NotificationChannel
  location: class FirebasePluginMessagingService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by nikhil91** [comment]
Are you using any other Google plugin in your app?

**Comment by juandxce** [comment]
Check this [answer](https://stackoverflow.com/questions/46155562/android-studio-cannot-resolve-symbol-notificationchannel):
Basically this plugin tries to use a class that was added in the SDK 26 of android, you can solve it by increasing the target SDK in your build.gradle to 26.

**Comment by soumak77** [comment]
closing as resolved per the above comment

**Comment by tallcoder** [comment]
It's happening to me and my `defaultTargetSdkVersion` is set to 27. This is so frustrating. Been trying to fix for hours.
