### ISSUE TITLE
iOS standard topics all and iOS not working

### ISSUE THREAD

**Issue by rossi256** [arnesson/cordova-plugin-firebase#68]
tested on iOS 10 xcode 8, plugin version 0.1.12 (0.1.13 not working)

i have a lot of errors in Xcode console at startup - we are guessing those are from attempts to subscribe those standard topics, but don't know.
its like 

2-3 times <FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"
1 time same error with code 501
3-5 times error with code 2001

if i subscribe to all or iOS in code manually, it works, however, if not manually subscribing, only way to reach out is with token, or another manually subscribed topic.

**Comment by rossi256** [comment]
subscribing to multiple topics works - 
however, if i subscribe to 3 topics, i see 5x the warning 

<FIRMessaging/WARNING> Failed to subscribe to topic Error Domain=com.google.fcm Code=5 "(null)"

still, it is subscribed and i can send notifications to all 3 topics (ios, all, custom)

**Comment by robertarnesson** [comment]
not really sure what the problem is. the plugin does not subscribe to any topics by itself, you always have to do that manually.

**Comment by achuinard** [comment]
I think the latest Firebase docs say that users will be auto-subscribed to
certain topics.

**Comment by robertarnesson** [comment]
that would be nice. it makes no difference for the plugin though

**Comment by achuinard** [comment]
I'd be inclined to think if there was some generic init method for the
Firebase SDK, that it might be doing that for you in the background.
Firebase likes to do a lot of magic for you.
