### ISSUE TITLE
Android LogEvent is not getting tracked.

### ISSUE THREAD

**Issue by bhumika** [arnesson/cordova-plugin-firebase#69]
mFirebaseAnalytics.logEvent(name, bundle);  -FILE FirebasePlugin.java
Above line is called but not able to see logged events in firebase console.

iOS is working fine.

**Comment by mathieu21** [comment]
Same for me no events are created in the console

**Comment by robertarnesson** [comment]
are you logging custom events or any of the built in ones? For custom events you have to upgrade your firebase account and enable bigquery, the data shows up there

**Comment by mathieu21** [comment]
I was logging custom events but didnt show anything for 2 days, now everything has appeared without using the bigquery feature ( but to see the parameter yes you need bigquery )
