### ISSUE TITLE
handling instantVerification in verifyPhoneNumber method

### ISSUE THREAD

**Issue by sollaattam** [arnesson/cordova-plugin-firebase#693]
Hi,

I see that verifyPhoneNumber just returns 'instantVerification' as true incase of  instantVerification/auto-verify scenarios in Android.
Can't it be changed such that it does sign-in and returns back 'idToken'? By this way, we can send this idToken to server and generate customIdToken after verifying idToken's value.

-Thanks
Ganesh

**Comment by soumak77** [comment]
this has been fixed in [v2.0.3](https://github.com/arnesson/cordova-plugin-firebase/blob/master/CHANGELOG.md#features) via https://github.com/arnesson/cordova-plugin-firebase/pull/861
