### ISSUE TITLE
Using Phonegap Build cli 8.0.0, getting this error: "Error: ENOENT: no such file or directory, open '/AndroidManifest.xml'."

### ISSUE THREAD

**Issue by jamminjames** [arnesson/cordova-plugin-firebase#699]
Using Phonegap Build, I tried updating to cli 8.0.0, as advised, to get cordova-plugin-firebase working properly. However, I am now getting this build error: "Error: ENOENT: no such file or directory, open '/AndroidManifest.xml'."

Any ideas on how to fix this issue in Phonegap Build? Or, since my main objective is to get any admob and firebase push notifications working together properly, whether in Phonegap Build cli 8.0.0 or cli 7.1.0, alternate suggestions for that would be appreciated.

Thanks for any help.

Here is the error in the build log:

```
Android Studio project detected
"plugman-151 install --platform android --project  --plugin cordova-plugin-firebase --nohooks=.": Fetching plugin "cordova-plugin-firebase" via npm
Installing "cordova-plugin-firebase" at "1.0.5" for android
Failed to install 'cordova-plugin-firebase': Error: ENOENT: no such file or directory, open '/AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.parseElementtreeSync (/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:364:24
    at _fulfilled (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54)
ENOENT: no such file or directory, open '/AndroidManifest.xml'
```

**Comment by jessicastorm1986** [comment]
same error , any solution ?

**Comment by markterrill** [comment]
Android 7.0+ changed the AndroidManifest location. it seems most plugins don't know how to look for it in its new location 
I tried symlinking it:
`ln -s platforms/android/app/src/main/AndroidManifest.xml platforms/android/AndroidManifest.xml`
Ended up working, but then the next error is any plugin adds/deletes triggers a .gradle invalid error

**Comment by soumak77** [comment]
@jamminjames is this still an issue with the latest version?

**Comment by jamminjames** [comment]
@soumak77 I don't know, I resorted to using Pushwoosh.

**Comment by diogeneshamilton** [comment]
@soumak77 I can confirm it is an issue with the latest version.
