### ISSUE TITLE
Separate Push Notification Setup From applicationDidFinishLaunching()

### ISSUE THREAD

**Issue by Chuckv01** [arnesson/cordova-plugin-firebase#7]
On iOS we're getting permission prompts on first launch of apps requesting permission to send push notifications.

To improve user experience what do you think about moving `registerForRemoteNotifications` into its own function outside of `applicationDidFinishLaunching()`. That way we do not get these permission prompts on first run.

**Comment by robertarnesson** [comment]
Yes definitively. e2ca65c looks ok?

**Comment by Chuckv01** [comment]
Awesome! No longer seeing prompts on startup :)  (I haven't tested the subscribe method yet)
