### ISSUE TITLE
iOS Pods Error

### ISSUE THREAD

**Issue by cincaw** [arnesson/cordova-plugin-firebase#70]
Hi, i've got an error when i build my project in Xcode. Here is my errors:
1. Diff:/../Podfile.lock: No such file or directory
2. Diff:/../Manifest.lock: No such file or directory
3. The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation

I already install cocoapods and follow this tutorial [https://firebase.google.com/docs/ios/setup](url) , but still not working.
Same for the 3rd error, i already trys 'pod install' and update my cocoapods but still got the same 3 error

Can someone help me to resolve this error pls?
Thank you

**Comment by ansaries** [comment]
@cincaw Can you tell us that how you resolved this issue. As I am also having the same error.

**Comment by minto5050** [comment]
@ansaries  Did you fix this issue man? Can you share it to me how? Thanks
