### ISSUE TITLE
using ionic cli getting error: cp: copyFileSync: could not write to dest file (code=ENOENT):F:\D\IONIC\mobile-upload-android-vipul\platforms\android\app\src\main\res\xml\config.xml

### ISSUE THREAD

**Issue by jessicastorm1986** [arnesson/cordova-plugin-firebase#701]
> [17:43:26]  lint finished in 13.12 s
> Android Studio project detected
> 
> cp: copyFileSync: could not write to dest file (code=ENOENT):F:\D\IONIC\mobile-upload-android-vipul\platforms\android\app\src\main\res\xml\config.xml
> 
> Parsing F:\D\IONIC\mobile-upload-android-vipul\platforms\android\app\src\main\res\xml\config.xml failed
> (node:6696) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'F:\D\IONIC\mobile-upload-android-vipul\platforms\android\app\src\main\res\xml\config.xml'

**Please suggest how can we resolve this bug which comes when we try to do - ionic cordova build android**

**Comment by Nikhilmaheshwari22** [comment]
same issue

**Comment by mohanbalasubramani** [comment]
i'm also facing same problem..@jessicastorm1986 have u find any solution??...

**Comment by brunodombidau** [comment]
I'm also facing the same issue.

> cp: copyFileSync: could not write to dest file (code=ENOENT):B:\pushTest\platforms\android\res\xml\config.xml

**Comment by JaredBrown138** [comment]
It is a structure problem. Cordova Android 7.0.0 changed the file structure.

https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

I have tested and found this is a problem in both Cordova android@7.0.0 and android@7.1.0. I will try to figure out how to fix this, it may be a simple matter of correcting file paths, but it may be more difficult, and in that case I don't have any experience with Cordova plugins and I will probably be at a loss. 

In the meantime, downgrading to 6.4 will solve the issue, but obviously this needs to be fixed to work with 7.0.0 and 7.1.0+

**Comment by soumak77** [comment]
@jessicastorm1986 is this still an issue with the latest version?

**Comment by soumak77** [comment]
Closing as fixed.  Please reopen if this issue persists with the latest version.

**Comment by nessroman** [comment]
@brunodombidau  I solved this problem with this steps:

1) ionic cordova platform add android@6.4.0
2) remove platform folder manually with file explorer
3) ionic cordova platform android 

And the message says: installing cordova-android@6.4.0  and  it works! 

After this, I have the JAVA SDK error... I forgot install Java SDK for:  build android.
