### ISSUE TITLE
Something wrong on with remoteMessage.getData() in FirebasePluginMessagingService.java 

### ISSUE THREAD

**Issue by t2wu** [arnesson/cordova-plugin-firebase#704]
I'm using [cordova-plugin-firebase][1]. To be compatible with a the version of location library I'm using, I manually edit plugin.xml in the firebase plugin like the following:

```
    <framework src="com.google.gms:google-services:3.1.1" />
    <framework src="com.google.android.gms:play-services-tagmanager:11.8.0" />
    <framework src="com.google.firebase:firebase-core:11.8.0" />
    <framework src="com.google.firebase:firebase-messaging:11.8.0" />
    <framework src="com.google.firebase:firebase-crash:11.8.0" />
    <framework src="com.google.firebase:firebase-config:11.8.0" />
    <framework src="com.google.firebase:firebase-perf:11.8.0" />
```
When I build it the error is:

```
: error: cannot access zzbfm
        Map<String, String> data = remoteMessage.getData();
                                                ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
```

What is the error? Is there a plugin version I can use Google API 11.8.0 with?

  [1]: https://github.com/arnesson/cordova-plugin-firebase

**Comment by markterrill** [comment]
I can't even get that far, having a nightmare upgrading ionic / cordova / plugins today. out of interest, are you happening to run ionic? If so, what do you have in your build.gradle and base project config.xml ?

**Comment by markterrill** [comment]
To the project folk, do you have a firebase and google-services version list of what actually works together and compiles?  (cordova platform version, firebase plugins, google plugins)

 basically if you have a seed project you could provide it would be immensely appreciated as I'm pretty good at resolving project dependencies but I've spent 12 hours so far and every time i take a step forward i find another library conflict

**Comment by brainchild115** [comment]
@markterrill I feel your pain. I'm not using Ionic though.

**Comment by thorvx** [comment]
any news?same problem

**Comment by soumak77** [comment]
have you tried the solution specified in the [README](https://github.com/arnesson/cordova-plugin-firebase#google-play-services)

**Comment by soumak77** [comment]
Closing as fixed per my previous comment.  Please reopen if this issue persists with the latest version.

**Comment by kapilSoni101** [comment]
@soumak77 not working for me i have tried ?
