### ISSUE TITLE
Plugin uninstall removes everything but this plugin

### ISSUE THREAD

**Issue by Salcci** [arnesson/cordova-plugin-firebase#706]
I'm also facing issue #705 . While trying to solve it I uninstalled this plugin. 
Uninstallation removed all but this plugin from my platforms/android/ directory.

<pre>
$ cordova plugin remove cordova-plugin-firebase
Uninstalling cordova-plugin-firebase from android
Error during processing of action! Attempting to revert...
Error: Uh oh!
AndroidStudio.js:inAndroidStudioProject root does not exist: /Users/xxx/git/yyy/local/platforms/android
$ ls platforms/android/
google-services.json	res			src
$ ls platforms/android/src/
org
</pre>

Cordova 6.5.0
Platform Android 6.3

**Comment by shikelong** [comment]
+1

**Comment by gyss** [comment]
I'm having at this moment the same error message and the cordova-plugin-firebase is not installed / in config.xml. 95% sure this problem is not related with this plugin

**Comment by hvaughan3** [comment]
@gyss Was it ever installed? If so, I would suggest removing and re-adding the platform as plugin files can stick around after being "removed".

**Comment by gyss** [comment]
@hvaughan3 yes, I have it installed. But after removing the whole platforms folder + removed the plugin from package.json / config.xml, I'm testing the whole process again and have the same error. I'm investigating if upgrading cordova-android solves this issue

**Comment by hvaughan3** [comment]
@gyss You can verify if the plugin is actually installed by looking at `platforms/android/android.json` after re-adding the platform.

**Comment by gyss** [comment]
@hvaughan3 this is the log when I run `cordova prepare`

```
Discovered platform "android@6.3.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@6.3.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.company.staging
	Name: Company_Staging
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Installing "cordova-plugin-inappbrowser" for android
Installing "cordova-plugin-intercom" for android
Subproject Path: CordovaLib
Installing "cordova-plugin-network-information" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-statusbar" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Installing "ionic-plugin-keyboard" for android
Discovered platform "android@6.4.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@6.4.0
Error: Platform android already added.
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Error during processing of action! Attempting to revert...
Error: Uh oh!
AndroidStudio.js:inAndroidStudioProject root does not exist: /Users/project/platforms/android
```

After running the command there's no file `platforms/android/android.json`. You can see that there's no firebase plugin around

**Comment by soumak77** [comment]
closing as resolved per the above comment

> Try upgrading to cordova-android 6.4.0

**Comment by salouri** [comment]
I have Cordova CLI 8.0.0, Cordova-Android 7.0.0 and when I tried to remove the plugin (to update it) I got the same error.

**Comment by briantq** [comment]
@salouri the 1.0.5 version of the plugin does not include any install scripts, simply references snippets to be included in the AndroidManifest and files to copy.  All the features we use are well documented in Cordova.  As far as I know, it should be Android 7.X compliant.  If you find changes are required, definitely comment back.  There are no full time developers on this plugin so maybe someone in the community can help to make the change.

**Comment by aniket143** [comment]
try this

cordova platforms remove android
cordova plugin remove cordova-plugin-firebase
cordova platforms add android
