### ISSUE TITLE
Getting attribution url

### ISSUE THREAD

**Issue by guylando** [arnesson/cordova-plugin-firebase#709]
Is it possible to get the url which the user used to enter the store when he installed the app, using this library?
I would like to send this url to our server. Is it possible?

**Comment by soumak77** [comment]
Closing as duplicate of https://github.com/arnesson/cordova-plugin-firebase/issues/809

**Comment by guylando** [comment]
@soumak77  although I opened the issue 3 months before him

**Comment by soumak77** [comment]
@guylando you're correct I should have closed the other issue.  I just understood the other issue more clearly using the term "Install Referrer" and felt others might as well, which would be easier to find when they searched open issues.
