### ISSUE TITLE
Tapping notification does not open app 

### ISSUE THREAD

**Issue by anuj-njoshi** [arnesson/cordova-plugin-firebase#712]
When notification received and tap on notification app does not start.I am using cordova firebase plugin.

**Comment by webtanar** [comment]
I have almost the same issue: when I tap on the notification, the app does start, but immediately goes to the background... Then I open the running apps (multitask manager) and I see that the app is indeed running, so I open it again and then it works normal. So the question is: why does the app go immediately to the background when opened by tapping the notification?

**Comment by ragcsalo** [comment]
Same issue here!!!!! Please investigate!! :-)

**Comment by wslaghekke** [comment]
PR #733 Should fix this

**Comment by ragcsalo** [comment]
I've added a few lines to OnNotificationOpenReceiver.java and now the problem is solved:

```
        Intent it = new Intent("intent.my.action");
        it.setComponent(new ComponentName(context.getPackageName(), MainActivity.class.getName()));
        it.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.getApplicationContext().startActivity(it);
```

**Comment by davidanaya** [comment]
Any update on this? the PR has been sitting there for almost 2 months
