### ISSUE TITLE
FirebaseApp is not initalized

### ISSUE THREAD

**Issue by alemdg** [arnesson/cordova-plugin-firebase#715]
After building a new release to submit to the store I am now getting the following error appear when I call 'getToken'

Default FirebaseApp is not initialized in this process processName Make sure to call FirebaseApp.initializeApp(Contect) first.

This is only happening on android the same build is working on IOS, also this error was not present on the last build I did last year.

Dont know why you closed this issue, IS STILL HAPPENING with the last version .

cordova plugin ls
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.11 "Ionic's WKWebView Engine"
cordova-plugin-local-notification 0.8.4 "LocalNotification"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

target=android-26
cordova.gradle.include.1=cordova-plugin-badge/dnd-badge.gradle
cordova.gradle.include.2=cordova-plugin-firebase/dnd-build.gradle
cordova.system.library.1=com.google.gms:google-services:+
cordova.system.library.2=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.3=com.google.firebase:firebase-core:+
cordova.system.library.4=com.google.firebase:firebase-messaging:+
cordova.system.library.5=com.google.firebase:firebase-crash:+
cordova.system.library.6=com.google.firebase:firebase-config:+
cordova.system.library.7=com.google.firebase:firebase-perf:+
cordova.system.library.8=com.android.support:support-v4:24.1.1
android.library.reference.1=CordovaLib

Ionic version: 3.19.0

**Comment by alemdg** [comment]
There was several versions of cordova-plugin-firebase, 

1 with 0.1.4 and 2 with 1.0.5

**Comment by dsaillard** [comment]
Hello
May be you have an conflic with cordova-plugin-local-notification 0.8.4 "LocalNotification"
Remove it, remove  and add the platform (iOS or Android) and finaly build your project
