### ISSUE TITLE
iOS can't receive PN. FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by gyss** [arnesson/cordova-plugin-firebase#727]
Hi, I've repeated several times the setup of this plugin in my Cordova project.
Android works fine, but in iOS I can't get any push notification. Debugging on XCode I get:

```
Starting Firebase plugin
[CDVTimer][firebaseplugin] 0.484943ms
4.13.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
4.13.0 - [Firebase/Crash][I-CRA000004] Successfully initialized
4.13.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40200000 started
4.13.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
4.13.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
4.13.0 - [Firebase/Messaging][I-FCM002023] The object <AppDelegate: 0x102357ab0> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
2018-06-09 10:03:25.144498+0200 PS-Staging[1198:318633] THREAD WARNING: ['FirebasePlugin'] took '10.833984' ms. Plugin should use a background thread.
*** FIREBASE PUSH TOKEN: xxx
4.13.0 - [Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x1017a13c0> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
4.13.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
4.13.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
```

Every time I trigger a PN from Firebase I get this log in XCode: `FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`

My setup is:
XCode 9.4
iOS 11.4
Cordova 7.1.0
cordova-ios 4.5.4
ios-deploy 1.9.2
cordova-plugin-firebase 1.0.5

**Comment by pdxwebdev** [comment]
@gyss Check out my PN, it's easy to integrate on your own.

**Comment by gyss** [comment]
Hi @pdxwebdev,

I've uninstalled the cordova-plugin-firebase in my project and installed it again from your fork (master). I've double checked that your new commit its in my node_modules/cordova-plugin-firebase. Build/run the project, trigger a push notification and nothing changed.

These are the logs:

```
Starting Firebase plugin
[CDVTimer][firebaseplugin] 0.501990ms
4.13.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
4.13.0 - [Firebase/Crash][I-CRA000004] Successfully initialized
4.13.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
4.13.0 - [Firebase/Messaging][I-FCM002023] The object <AppDelegate: 0x137e61d10> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
4.13.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40200000 started
4.13.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2018-06-10 23:02:53.563701+0200 PS-Staging[1667:429797] THREAD WARNING: ['FirebasePlugin'] took '16.478027' ms. Plugin should use a background thread.
2018-06-10 23:02:53.577807+0200 PS-Staging[1667:429797] THREAD WARNING: ['FirebasePlugin'] took '13.659912' ms. Plugin should use a background thread.
4.13.0 - [Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x137e50120> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
2018-06-10 23:02:53.673085+0200 PS-Staging[1667:429797] *** FIREBASE PUSH TOKEN: el50WGjMoSc:APA91bHhdufjyOQ7wWYv3bKgbraw3h1PmRN0L8QC1BlJ-GqyiWk0zB86cT6hnD2sAGVMGY8lLEaVKCSyr2gjiJKTSafFknIMB3YRo49V5CoOrCNrnIscL9GohL0xDtdsj5oB_zyQpQVS
4.13.0 - [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
```

I cannot see the new log you put `NSLog(@"deviceToken1 = %@", deviceToken);`

**Comment by pdxwebdev** [comment]
@gyss One sneaky thing that isn't in the main documentation is this:

Are you calling grantPermission() in your code?

It may be asking for permission already, but the grantPermission() call actually runs through a bunch of routines needed to make everything work.

**Comment by gyss** [comment]
Thanks for your help @pdxwebdev 
I'm already executing that function. This is my code example

```
$ionicPlatform.ready(function() {
  // Enable PUSH in iOS Devices
  if (ionic.Platform.isIOS()) {
    try {
      window.FirebasePlugin.grantPermission(); 	// Firebase PUSH
    } catch (error) {
      console.log("Couldn't enable PUSH in iOS. Is this a real device? ", error);
    }
  }

  try {
    window.FirebasePlugin.onTokenRefresh(function(token) {
      console.log("*** FIREBASE PUSH TOKEN:", token);
    }, function(error) {
      console.error(error);
    });
    
    // Subscribe to company announcements
    window.FirebasePlugin.subscribe("mytopic");
  }
  catch (error) {
      console.log("Couldn't get PUSH token. Is this a real device? ", error);
  }
});
```
Can you see any problem here?

**Comment by pdxwebdev** [comment]
In xcode, put a breakpoint in the 
`didRegisterForRemoteNotificationsWithDeviceToken`  in `AppDelegate+FirebasePlugin.m`
Does it stop there?
If not. The next step is to make sure `grantPermission` is being called in `FirebasePlugin.m`
`grantPermission` will execute this line:
`[[UIApplication sharedApplication] registerForRemoteNotifications];`
That should cause `didRegisterForRemoteNotificationsWithDeviceToken` to be called later.

Also, if `grantPermission`  in `AppDelegate+FirebasePlugin.m` is not called then your permissions for the app will be wrong as well. You'll see in notification settings for your app that only badge is available.

**Comment by gyss** [comment]
I can confirm that 

- `didRegisterForRemoteNotificationsWithDeviceToken` in `AppDelegate+FirebasePlugin.m` doesn't gets triggered at all (even after firing a push notification from Firebase)
- `registerForRemoteNotifications` in `FirebasePlugin.m` (line 123) gets triggered after launching the app. 

Looks like the `didRegisterForRemoteNotificationsWithDeviceToken` event is not registered or something?

**Comment by pdxwebdev** [comment]
`didRegisterForRemoteNotificationsWithDeviceToken` will fire after `registerForRemoteNotifications` without a push notification. I should ask, are you even receiving data messages from firebase? If not then you may have other issues.

**Comment by gyss** [comment]
Unfortunately the communication with Firebase works smoothly. I can login and fetch data.
I will try to rebuild the platforms folder / certificates. I'll keep this post up-to-date

**Comment by gyss** [comment]
Solved. The reason why the function `didRegisterForRemoteNotificationsWithDeviceToken` was not being called is because a connectivity problem. My router was blocking the app to get the deviceToken and send it to FCM. Really weird since the app could login/logout get data from Firebase (and get the FCM token) from the beginning.
