### ISSUE TITLE
Source/Campaign & dynamic_link_first_open / dynamic_link_app_open not tracked

### ISSUE THREAD

**Issue by Venkat-TTapp** [arnesson/cordova-plugin-firebase#73]
I have added this plugin into my phonegap build app. I am not seeing any tracking for source/campaign or dynamic_link_first_open / dynamic_link_app_open.

I would like to know whether we can track source/campaign & dynamic_link_first_open with this plugin? or this feature is not supported by this plugin?

I can see below events are tracked in my firebase console:
first_open
session_start
page_view
app_remove

Events Screenshot: [http://i.imgur.com/t1sHAnZ.jpg]

**Comment by BugsBunnyBR** [comment]
Hi @Venkat-TTapp , as far as I know, this is not something the plugin itself handles. The Firebase sdk should do it together with your app, but this plugin does not have support to it.

**Comment by Venkat-TTapp** [comment]
Thanks for your reply BugsBunnyBR!

Firebase documentation clearly states this as **automatically tracked events**, and when I can see other automatically tracked event but source is not tracked for both i-OS and Android. I have used below plugin to handle custom url provided during dynamic link creation in Firebase Console.

https://github.com/EddyVerbruggen/Custom-URL-scheme.

I am clueless and not sure If I have made any implementation mistake.

**Comment by BugsBunnyBR** [comment]
Most likely you do have a problem with your URL... I don`t have any experience with dynamic links, so I can`t help much... Look at the documentation https://firebase.google.com/docs/dynamic-links/android in the "Create a Dynamic Link programmatically" section... and check your parameters...

**Comment by robertarnesson** [comment]
closing for now, reopen if still an issue with the latest version of the plugin
