### ISSUE TITLE
Not recive push ios by topic (or how subscribe for ios topic)

### ISSUE THREAD

**Issue by snikesv** [arnesson/cordova-plugin-firebase#731]
Hi,
my project on ionic 3

I can recive push on **iOS** if i send from firebase to ios
and can recive push on android by topic
but on ios i can't recive push by topic
i don't know what wrong in my code

My code :
`    let topic = "/topics/" + APP_CONF.CUSTOMER + "-User_" + APP_CONF.ARTICLE_RELEASE_TOPIC;

    if (this.platform.is('ios')) {
      //topic = "/topics/" + APP_CONF.CUSTOMER + "-User_" + APP_CONF.ARTICLE_RELEASE_TOPIC + '_ios';
      this.firebase.hasPermission().then(data => {
        if (!data.isEnabled) {
          this.firebase.grantPermission();
        }
      });

    }

    this.firebase.subscribe(topic);

    this.firebase.getToken()
      .then(token => {
        this.globalVars.userData.userServiceInfo.gmsToken = token;
      }) // save the token server-side and use it to push notifications to this device
      .catch(error => console.error('Error getting token', error));      

    this.firebase.onTokenRefresh()
      .subscribe((token: string) => {
        this.globalVars.userData.userServiceInfo.gmsToken = token;
      });`

**Comment by snikesv** [comment]
If for you interested (i strongly recommend write to readme)
problem was in topic
for android topic like     /topics/blabla_bla-bla  is good
but for iOS you need topic without /topics/
example: blabla_bla-bla

**Comment by soumak77** [comment]
closing as resolved per the above comment
