### ISSUE TITLE
iOS crash on boot

### ISSUE THREAD

**Issue by japochino** [arnesson/cordova-plugin-firebase#732]
I have installed cordova-plugin-firebase. In the root folder of my app I have zipped www folder, config.xml, google-services.json and GoogleService-Info.plist. I use this file in phonegap build and it builds fine for ios. I have installed the app in a iPhone 7, but when I run the app it crashes.

In the plugin page I can read (https://www.npmjs.com/package/cordova-plugin-firebase#important-notes):

"IMPORTANT NOTES

This plugin uses a hook (after prepare) that copies the configuration files to the right place, namely platforms/ios/\/Resources for ios and platforms/android for android.

Firebase SDK requires the configuration files to be present and valid, otherwise your app will crash on boot or Firebase features won't work.

PhoneGap Build

Hooks does not work with PhoneGap Build. This means you will have to manually make sure the configuration files are included. One way to do that is to make a private fork of this plugin and replace the placeholder config files (see src/ios and src/android) with your actual ones, as well as hard coding your app id and api key in plugin.xml."

So I think what is happening is that GoogleService-Info.plist and google-services.json are not placed in the right place.

But, how can I fix this? I don't understand the solution about making a private fork?!?

Any help? Thanks

**Comment by MafricaLucas** [comment]
Same problem, please help us

**Comment by japochino** [comment]
Important Notes were really important, you must not use PhoneGap Build for this. You have to use phonegap cli...

Good luck!
