### ISSUE TITLE
Wrong code on Phone Auth crashes the app on iOS

### ISSUE THREAD

**Issue by derTuca** [arnesson/cordova-plugin-firebase#737]
When typing in the wrong code recieved via SMS for Phone Authentication on an iOS device, the app crashes, logging the following message in Xcode:

`
Assertion failed: (NO), function -[FirebasePlugin logError:]_block_invoke, file /Users/alex/Projects/Bday/platforms/ios/Bday/Plugins/cordova-plugin-firebase/FirebasePlugin.m, line 288.
`

**Comment by Flucadetena** [comment]
Hi did you get it to work? I´m trying to use the phone auth, but i can not get it to work on ios. Android is working fine. Could you share some code, mostly of the verifyPhoneNumber function.

Thanks

**Comment by derTuca** [comment]
Hi, and sorry for the late response. The following code uses Ionic Native, but the basic principle is the same with the base Cordova plugin: 
```
        let credential = await this.firebaseModule.verifyPhoneNumber(phoneNumber, 0);
        if (this.platform.is('android')) return credential.verificationId;
        return credential;
```
However, when using iOS the app crashes when you input the wrong code due to an assertion in the native code. I have created a pull request to fix it (see #738), but until it is merged, I suggest you use my branch instead.

**Comment by Flucadetena** [comment]
Hi derTuca, thanks a lot for the response. My problem is that when i invoke the "verifyPhoneNumber" function, the sms is not sent, and the error displayed in xcode says:

ERROR: Method 'verifyPhoneNumber:' not defined in Plugin 'FirebasePlugin'
FAILED pluginJSON = ["FirebasePlugin40635822","FirebasePlugin","verifyPhoneNumber",["thePhoneNumber",30]]

This is my code( below ), if you have any idea what could be wrong it would really help me. I know i have to differentiate between Ios and android in the return of the credentials, but as I can not get the sms to be sent I haven't than that yet. 

It is a function to which you pass the prefix of the phone, the number and new phone parameter you can ignore it, is just to now if the user is already registered or not.

sendVerfCode( phnPrfx: String, phoneNumber: String, newPhone?: boolean): Promise<any> { //Devuelve todas las credenciales
    return new Promise(resolve => {

      this._fire.verifyPhoneNumber(phnPrfx.toString() + phoneNumber, 30).then( credential => {
        console.log("SMS succesful: ", credential);
        if (!credential.instantVerification)
          return resolve(credential.verificationId);
        else
          this.userVerified.emit({ resp: true, newPhone: newPhone });
      }, function (error) {
        console.error(error);
        return resolve(false);
      });
    });
  }

Thanks A LOT!!

**Comment by derTuca** [comment]
Please check whether you are using the latest version of the Cordova plugin and you have the latest version of Ionic Native (I suppose you are using Ionic Native by the syntax), as the method was originally called `getVerificationId` on iOS, but in one of the recent updates, `verifyPhoneNumber` was updated to work on iOS (actually, all it does on iOS is call `getVerificationId`). To see whether this is the problem, try running `getVerificationId` when running on iOS and checking whether it works or not.

**Comment by Flucadetena** [comment]
Hi, derTuca, thanks once more. I've check and have the latest versions. I tried the "getVerficactionID()" method but it doesn't exist in ionic native. I've tried calling it like this: 
`(<any>window).FirebasePlugin.getVerificationId( phnPrfx.toString() + phoneNumber).then( ...`
but when I run it, i get: 

`ERROR: ERROR Error: Uncaught (in promise): TypeError: window.FirebasePlugin.getVerificationId is not a function. (In 'window.FirebasePlugin.getVerificationId(phnPrfx.toString() + phoneNumber)', 'window.FirebasePlugin.getVerificationId' is undefined)`

I found this plugin, but I think it is an older version of this one. But the readme has the getVerificationID, and it is well documented.

¿Do you know if it is the same plugin? ¿should I try that version? My only concern is that it is a very early version, and doesn't look like it is being updated.

**Comment by derTuca** [comment]
You haven't linked to any plugin, but from what I know, there are a few older versions lurking, but I strongly recommend against them. If I were you, I would try reinstalling cordova-plugin-firebase (ionic cordova plugin rm cordova-plugin-firebase && ionic cordova plugin add cordova-plugin-firebase), and if that does not work I would try setting a breakpoint somewhere in the app and checking window.FirebasePlugin to see if it defines verifyPhoneNumber or getVerificationId.

**Comment by Flucadetena** [comment]
I had tried all that, but finally I got it to work!!
The clue was on the finding the definition in xcode and see if it had defined does functions. The 
"verifyPhoneNumber" doesn't appear for some reason I don't know. But the "getVerificacionID" was there but the end was "ID" not "Id".

With that change I got it to work. In case anyone has the same problem I leave my final code here:

`sendVerfCode(phnPrfx: String, phoneNumber: String): Promise<any> {
    return new Promise(resolve => {
      if (this.platform.is("ios")) {
        (<any>window).FirebasePlugin.getVerificationID(phnPrfx.toString() + phoneNumber, function (verificationId){
          return resolve(verificationId);
        }, function (error) {
          console.error(error);
          return resolve(false);
        });

      } else
        this._fire.verifyPhoneNumber(phnPrfx.toString() + phoneNumber, 0).then(credential => {
          if (!credential.instantVerification) // To check the instant verification
            return resolve(credential.verificationId);
          else
            this.userVerified.emit({ resp: true, newPhone: newPhone });
            
        }, function (error) {
          console.error(error);
          return resolve(false);
        });
    });
  }`

They Should ad this to the README. THANKS A LOT @derTuca. I was really starting to think of changing the hole registry process. Thanks a lot!

**Comment by derTuca** [comment]
Glad I could help. I do suggest triple-checking the versions and deleting the `platforms` folder, since I use `verifyPhoneNumber` on both Android and iOS (even though on iOS it just calls `getVerificationID`:
```
- (void)verifyPhoneNumber:(CDVInvokedUrlCommand *)command {
    [self getVerificationID:command];
}
```

**Comment by soumak77** [comment]
closing as resolved
