### ISSUE TITLE
iOS Failed to fetch default token

### ISSUE THREAD

**Issue by imbrendino** [arnesson/cordova-plugin-firebase#74]
Hi, I have this error:

<FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=0 "(null)"

But when I do window.FirebasePlugin.getInstanceId at the beginning, it gives me the token... 

Could you help me?

Thanks

**Comment by arivanbastos** [comment]
Same issue here.
My device runs ios 10 and I'm using version 0.1.14.

**Comment by robertarnesson** [comment]
not really a problem with the plugin but rather with firebase itself. can you recieve notifications?

**Comment by arivanbastos** [comment]
I can't. Android works fine.

**Comment by c4software** [comment]
If its like me, its a problem on Google side. I got this error until I sign my app in production...

It's strange because everything seems correctly set but it's fail ... In dev

**Comment by arivanbastos** [comment]
What I done:
1) Created the DEV/PROD provisioning profiles on developer.apple.com. Checked my developer/team certificates when creating the provisioning profiles.
2) Created the DEV/PROD APS certificates on developer.apple.com. 
3) Installed developer/team certificates on dev machine.
4) Installed DEV/PROD certificates on dev machine.
5) Installed provisionig profiles in dev machine.
6) Installed plugin with cordova plugin add cordova-plugin-firebase@0.1.14.
7) Added code to my app:
```
window.FirebasePlugin.grantPermission();
window.FirebasePlugin.getInstanceId(
  function(token) {
      thiss.saveToken(token);
  },
  function(error) {
      console.log(error);
  }
);

window.FirebasePlugin.onNotificationOpen(
  function(notification) {                  
    //alert("Yeahh!");
  }, 
  function(error) {
    //alert("Error");
  }
);
```
8) Created Google GCM/Google Firebase Account.
9) Added my app to Firebease with iOS/Android platforms.
10) Added APS certificates to "Cloud Messaging" section on firebase project settings.
11) Downloaded GoogleService-Info.plist e google-service.json and placed them in my app root folder.
12) Build the app
13) In XCode enabled "Push Notifications" and "Background Modes: Remove notifications".

I already:
1) Checked the app bundle.
2) Updated cordova.
2) Removed and reinstall iOS platform.

What I didn't:
1) Deploy the app to apple store. I'm running the app in DEBUG mode.

**Comment by robertarnesson** [comment]
running in debug is the problem I believe. see https://github.com/arnesson/cordova-plugin-firebase/issues/45

**Comment by c4software** [comment]
Definitely looks like the same « problem ».. try to upload a test version on Apple store.

**Comment by imbrendino** [comment]
Maybe I found the problem but I haven't tried yet.
I did all the certificate for the push notifications. Now the console doesn't show the error.

**Comment by imbrendino** [comment]
I've tried. the problem is the same

**Comment by BugsBunnyBR** [comment]
If your app was working before you updated your XCode to Xcode 8.0, try to downgrade to XCode 7.3. This is a **workaround**, since XCode 8.0 the way it signs the app changed.
Link do download XCode 7.3 : http://stackoverflow.com/questions/10335747/how-to-download-xcode-4-5-6-7-8-and-get-the-dmg-or-xip-file

**Comment by rklus16** [comment]
I'm only able to get the token right when the app initializes. otherwise the the getToken method returns null on both iOS and Android.

**Comment by arivanbastos** [comment]
Adding priority="high" solves the problem! Thank you all!

**Comment by brobx** [comment]
I also have the same issue, doesnt work on ios.

**Comment by chanphillip** [comment]
I'm getting the same problems.

> Failed to fetch APSN token Error Domain=com.firebase.iid Code=1001 "(null)"

And also this

> Unable to connect to FCM. Error Domain=com.google.fcm Code=501 "(null)"

**Comment by Shakti-Sharma** [comment]
The Same issue is resolved on the following link.

[https://github.com/firebase/quickstart-ios/issues/111](url)

Regards
Shakti

**Comment by faustoct** [comment]
IT was working but stopped at certain point
https://github.com/arnesson/cordova-plugin-firebase/issues/89
