### ISSUE TITLE
Notification not causing vibration on device

### ISSUE THREAD

**Issue by diegosiao** [arnesson/cordova-plugin-firebase#740]
Hi,

I have configured the default sound for notification in Android as officially documented on my Firebase REST requests:

{
  "title": string,
  "body": string,
  "icon": string,
  "sound": string,
  "tag": string,
  "click_action": string,
  "..."
}

The sound is played normally, but **device does not vibrate** if in 'Silent mode' as expected.

**Comment by gubbigubbi** [comment]
For me I get a vibration in silent mode, this is my payload:

  const payload = {
      notification: {
        title: `New message: ${message.jobName}`,
        body: `${user.name}: ${message.message}`,
        icon: 'https://goo.gl/Fz9nrQ',
        sound: "default",
      },
    };

I noticed that i needed to add - sound: default for it to vibrate on Android. Gang gang.

**Comment by soumak77** [comment]
closing as resolved per the above comment
