### ISSUE TITLE
Firebase Performance

### ISSUE THREAD

**Issue by mattmacf98** [arnesson/cordova-plugin-firebase#741]
I am trying to integrate a custom trace for my ionic app, However Visual studio code says that the startTrace and stopTrace functions are not part of the Firebase plugin and I get a similar issue when trying to deploy on my device via the command line. Is this feature implemented yet?

**Comment by MumblesNZ** [comment]
Hey, did you make any progress with this? I can call startTrace and stopTrace fine without error, but I can't see my traces coming through.

**Comment by mattmacf98** [comment]
I haven't tried start and stop trace recently. I just wanted it to measure
app latency for my API calls. Instead I just created an event and kept
track of the time difference before and after the event. Not as much data
but got the job done.

**Comment by soumak77** [comment]
closing as resolved
