### ISSUE TITLE
Conflict with cordova-plugin-local-notifications

### ISSUE THREAD

**Issue by dmeij** [arnesson/cordova-plugin-firebase#748]
Is this a known issue of just bad implementation from my part?

Android is working perfectly, IOS notifications while the app is in the background also work perfectly.

**Comment by dmeij** [comment]
I also have the cordova-plugin-local-notifications plugin installed.

**Comment by ylno** [comment]
I had the same problem. The notifications will not be delivered in onNotificationOpen if you have cordova-plugin-local-notifications installed. After removing cordova-plugin-local-notifications it works like expected. Thank you for this hint.

**Comment by dmeij** [comment]
@ylno do you use another plugin to show the local notifications? If yes, which?

**Comment by windwp** [comment]
@dmeij  i have same issue i need use local notifcation too.:(

**Comment by masimplo** [comment]
How did you discover the conflict? What are they conflicting upon?

**Comment by masimplo** [comment]
Was wondering if anyone got down to what exactly is conflicting between the two plugins.

**Comment by Mikhail2222** [comment]
There is a similiar a thread:
https://github.com/katzer/cordova-plugin-local-notifications/issues/1626

**Comment by sebastian-zarzycki-es** [comment]
Same problem here. As soon as local-notification is removed, listening for notifications (`.onNotificationOpen();`) works again.

**Comment by soumak77** [comment]
closing as this appears to not be fixable via the plugin

**Comment by sebastian-zarzycki-es** [comment]
What?

**Comment by soumak77** [comment]
@sebastian-zarzycki-es I could easily be wrong, but based on what I've read from the community, I'm not sure how any changes to this repo could fix this problem.  Issues which can't be fixed should be closed.  The discussion can still continue on closed issues for those that might be able to help out with the root problem.  If you or anyone else finds a solution, I'll gladly accept a PR which either provides a code change or updates the README with instructions on how to solve the problem.

**Comment by sebastian-zarzycki-es** [comment]
Did you see this? https://github.com/katzer/cordova-plugin-local-notifications/issues/1626#issuecomment-406992891
Can you confirm that this plugin is not registering in the same was as described phonegap plugin?

**Comment by soumak77** [comment]
I'm not sure as I don't use phonegap.  Hopefully someone from the community can provide more details.
