### ISSUE TITLE
"Plugin not installed" ... but it is. Install again, same error. - iOS

### ISSUE THREAD

**Issue by Levy4u** [arnesson/cordova-plugin-firebase#749]
I get the following message in console:

[14:17:38]  console.warn: Native: tried calling Firebase.getToken, but the Firebase plugin is not installed. 
[14:17:38]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase' 
[14:17:38]  console.warn: Native: tried calling Firebase.onNotificationOpen, but the Firebase plugin is not installed. 
[14:17:38]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase'

So i install the firebase plugin as instruction by running  ionic cordova plugin add cordova-plugin-firebase in the terminal. Then after I rebuild the app and test, same exact error. I've tried pretty much everything... different firebase plugins, removing, reinstalling, putting the google plist file everywhere. Nothing is working.

I am working in the ionic 3 framework, and i've tried removing the iOS platform, adding it back, building in Xcode and testing on device... same errors.

**Comment by alonso01** [comment]
Did you follow Ionic's guide? https://ionicframework.com/docs/native/firebase/

I am running into the same issue as you, but on Ionic 2.

**Comment by Levy4u** [comment]
Yes I followed it. It seemed to be working last week but I have no idea what I did to break it. I believe it’s listed in all plugin folders like it should be and it’s still not working.  I just don’t know what to check since there are so many moving parts with things installinging and building and running and generating platforms... everything else works fine though

**Comment by alonso01** [comment]
I was struggling with this problem for many days and I was able to solve it today. I was not following the install based on the Ionic's guide, only instructions posted on the main page of this plugin. Basically, I had to follow that guide and add before any firebase action, inside the platform.ready event:
` this.firebase.grantPermission();`

...That way the getToken() method stopped returning the plugin_not_installed error and I could start receiving messages successfully. Otherwise, you should verify your @ionic-native/firebase dependencies, package.json or config.xml, or see the actual ios build to see if the plugins are getting added correctly.

Let me know if there's anything I can help you with.

**Comment by Levy4u** [comment]
Sadly i've tried the grant permission and no matter what i get the error. No matter what i do, the first thing comes back with the error. I'm going to try uninstalling and reinstalling again to see if anything changes.

[07:43:18]  console.log: platform ready 
[07:43:18]  console.warn: Native: tried calling Firebase.grantPermission, but the Firebase plugin is not installed. 
[07:43:18]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase' 
[07:43:18]  console.warn: Native: tried calling Firebase.getToken, but the Firebase plugin is not installed. 
[07:43:18]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase' 
[07:43:18]  console.warn: Native: tried calling Firebase.onNotificationOpen, but the Firebase plugin is not installed. 
[07:43:18]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase'

**Comment by Levy4u** [comment]
So I am able to generate tokens and retrieve them, after the app is running. For example, on the loading screen, it asks the user for permission, and you hit allow the app proceeds as normal. But in the database, it isn't getting to the code that actually saves the info. 

But I put a button on a hidden page that runs the same exact code and if i click it, the token gets saved with the userID.

```
import { HttpClient } from '@angular/common/http';
import * as firebase from 'firebase/app';

import { Injectable } from '@angular/core';
import { Firebase } from '@ionic-native/firebase';
import { Platform } from 'ionic-angular';
import { AngularFirestore } from 'angularfire2/firestore';

@Injectable()
export class FcmProvider {

  userID: string;

  constructor(public http: HttpClient,
    public firebaseNative: Firebase,
    public afs: AngularFirestore,
    private platform: Platform
  ) {
    console.log('Hello FcmProvider Provider');
    this.userID = firebase.auth().currentUser.uid;
    console.log('UserID - ', this.userID)
  }

// Get permission from the user
async getToken() {
  
  let token;

  if (this.platform.is('android')) {
    token = await this.firebaseNative.getToken()
  } 

  if (this.platform.is('ios')) {
    //await this.firebaseNative.grantPermission();
    token = await this.firebaseNative.getToken();
    console.log('ios token', token)
    await this.firebaseNative.grantPermission();
  } 
  
  if (this.platform.is('browser')) {
    token = await this.firebaseNative.getToken()

  } 

  //console.log('token is -- ', token)
  return this.saveTokenToFirestore(token)
}

// Save the token to firestore
private saveTokenToFirestore(token) {
  if (!token) return;

  const devicesRef = this.afs.collection('devices')

  const docData = { 
    token,
    userId: this.userID,
  }

  return devicesRef.doc(token).set(docData)
}

// Listen to incoming FCM messages
listenToNotifications() {
  return this.firebaseNative.onNotificationOpen()
}

}
```

**Comment by metalojiqTee** [comment]
@Levy4u How did you manage to solve the issue of "Native: tried calling Firebase.grantPermission, but the Firebase plugin is not installed." ?

**Comment by soumak77** [comment]
closing as resolved since the original issue is fixed per the creator

**Comment by kirax999** [comment]
it's really painful that when people find the answer it does not give their way to do: / I have the same problem :(

**Comment by Jaylton** [comment]
could not solve this problem, so I decided not to use the firebase and I
used the onesignal, that is better. sorry for my english.

Em qua, 23 de jan de 2019 às 21:32, Alexandre Richet <
notifications@github.com> escreveu:

**Comment by Levy4u** [comment]
It's been awhile but I believe I had to build the app and then view it natively on the device. also check to make sure you don't have "cordova firebase" and "firebase". One of them will work while the other spits out the error. I think...

**Comment by kirax999** [comment]
indeed I tried and realized that despite the error it worked correctly ...

The mysteries of the debug message

**Comment by JamesPoel** [comment]
You need to wait for the platform to be ready before calling onNotificationOpen:

`this.platform.ready().then(() => {`

**Comment by gokhandilek** [comment]
In my case, I had to do` ionic cordova plugin add cordova-plugin-firebase` in the Mac terminal and rebuild the iOS app.

**Comment by kapilSoni101** [comment]
Anybody fix above error plz help me?

**Comment by enrolo** [comment]
> Anybody fix above error plz help me?

I think the solution of @JamesPoel   is the best one, and I used that.
