### ISSUE TITLE
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0

### ISSUE THREAD

**Issue by faralimite** [arnesson/cordova-plugin-firebase#753]
Hello

I have installed Cordova Plugin Firebase and when I'm trying to compile the code with https://bluid.phonegap.com I'm getting this error:

> Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: FirebasePluginMessagingService.java

Is a new empty project using phonegap 8.0.0. 
Firebase Plugin is 1.0.5. 
Android Platform 7.0.0

phonegap build android works.

Someone can help me?

Thank you

**Comment by TimmyRB** [comment]
I am getting this error as well and have tried changing versions but sadly to no avail. Anyone else having this or have any suggestions?

**Comment by faralimite** [comment]
Hi. I found the issue. You have to play with phonegap-version and pgb-builder-version in config.xml.

My working config:
<preference name="phonegap-version" value="cli-7.1.0" />
<preference name="pgb-builder-version" value="2" />
<engine name="android" spec="7.0.0" />

Also, please check: https://build.phonegap.com/current-support

Regards,
Radu

**Comment by soumak77** [comment]
closing as resolved
