### ISSUE TITLE
Backend for verifyPhoneNumber() - no need ?

### ISSUE THREAD

**Issue by fikretkurtiiev** [arnesson/cordova-plugin-firebase#756]
From docs:

> "Android supports auto-verify and instant device verification. Therefore in that case it doesn't make sense to ask for an sms code as you won't receive one. Also, verificationId will be false in this case. In order to sign the user in you need to check credential.instantVerification, if it's true, skip the SMS Code entry, call your backend server (sorry, it is the only way to succeed with this plugin) and pass the phone number as param to identify the user (via ajax for example, using any endpoint to your backend)."

So, got twice calling method: 
`window.FirebasePlugin.verifyPhoneNumber()`

First manual, by user click and second Android call itself, like was mentioned in docs.
On second times, the param `credential.verificationId` equal to `bool: false.`

But i implemented check for type of this param and string only is using further:
 ```
if (typeof credential.verificationId === 'string') {
        this.verificationId = credential.verificationId;
      }
```
so previous  param with type string, is saved and auth is working good.
Maybe i'm something don't understand, but for a what we need server side and custom tokens?

**Comment by YaMo97** [comment]
The flow of Firebase Phone Auth is first to verify the phone number (using the OTP) and then to sign-in the user (change the AuthState).

We used to do this using the following algorithm: - 

1. call `verifyPhoneNumber()` to send OTP/Code via SMS
2. call `signInWithCredential()` with the `verificationId` and OTP/Code

The `verifyPhoneNumber()` uses the following verification callbacks (as per the Firebase docs): - 

> #### 1. `onVerificationCompleted(PhoneAuthCredential)`
> This method is called in two situations:
> - Instant verification: in some cases the phone number can be instantly verified without needing to send or enter a verification code.
> - Auto-retrieval: on some devices, Google Play services can automatically detect the incoming verification SMS and perform verification without user action. (This capability might be unavailable with some carriers.)
> 
> #### 2. `onVerificationFailed(FirebaseException)`
> 
> This method is called in response to an invalid verification request, such as a request that specifies an invalid phone number or verification code.
> 
> 
> #### 3. `onCodeSent(String verificationId, PhoneAuthProvider.ForceResendingToken)`
> 
> This method is called after the verification code has been sent by SMS to the provided phone number.
> 
> When this method is called, most apps display a UI that prompts the user to type the verification code from the SMS message. (**At the same time, auto-verification might be proceeding in the background**.) Then, after the user types the verification code, you can use the verification code and the verification ID that was passed to the method to create a PhoneAuthCredential object, which you can in turn use to sign in the user. However, some apps might wait until onCodeAutoRetrievalTimeOut is called before displaying the verification code UI (not recommended).

The case you are facing is the **Auto Retrieval** case under the `onVerificationCompleted()` : -

1. OTP is sent to your device and you receive `{ verificationId: **some string**, instantVerification: false }` from plugin, which you store in a variable,
2. Then Auto retrieval kicks in and the user is verified and you receive the `{ instantVerification: true, verificationId: false }` from the Plugin,
3. And then you use the stored verification ID and the Code to sign-in... 

This method also handles the `onCodeSent()` case which is the usual case but what we are not handling is the **Instant Verification** case under `onVerificationCompleted()`.
In this case, the OTP is never sent in the first place, thus no Verification ID. But the user is authenticated at Firebase end. 

So, to handle this case we need the custom token for signing in, which I am still figuring out how to implement it using the Firebase Cloud Functions as I am not using any backend other than Firebase.

**Comment by YaMo97** [comment]
@manuelsc I agree with you. I proposed a similar solution for the issue #718

**Comment by Hirbod** [comment]
@manuelsc would you mind to post your whole file or provide a PR? I would change the README as soon as we got your nice workaround. As I have absolutely no clue with android development, my approach was kinda hacky and also a security breach, as contacting the server on a public API isn't the real deal.

**Comment by Hirbod** [comment]
I also had the same idea as @manuelsc but never got an answer to it until now:
https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/23

So this could be the way to go and to prevent issues with instant verification.

**Comment by manuelsc** [comment]
@Hirbod I just created a pull request https://github.com/arnesson/cordova-plugin-firebase/pull/861
As mentioned there might be even a better way but I would need feedback from a javascript dev for that.
