### ISSUE TITLE
iOS Permission Dialog Appearing On Launch

### ISSUE THREAD

**Issue by shriharip** [arnesson/cordova-plugin-firebase#757]
Even after I do not call the grantPermission there is a dialog appearing on Launch. I cannot find anywhere as to how I can delay this dialog. I am using it in an Ionic app v3. cordova -8 .

**Comment by Hirbod** [comment]
Update to version 1.0.4 at least.

**Comment by shriharip** [comment]
Hi,
I had opened this issue following the issue #648 being closed and still facing the problem.
But as @Hirbod replied to my earlier message of maybe the package being wrong. I am trying to uninstall it 
viz  ionic cordova plugin remove cordova-plugin-firebase

I get UnhandledPromiseRejection because of no such file or directory.

/users/name/app/platforms/android/AndroidManifest.xml
whereas the AndroidManifest is not in that path but a different path.

**Comment by shriharip** [comment]
Also, just a side note, when I installed the plugin my cordova version was 8 and the platform android was 7 and above. I have come to known that the cordova 8 has the manifest file at a different location than the later one. So @Hirbod do you suggest I go and delete the folders and the config.xml and plugin.xml manually?

**Comment by shriharip** [comment]
Ok. I removed Android platform, then removed the plugin and then added the latest version of the plugin and the notifications at startup is removed.
