### ISSUE TITLE
Subscribe Topic no appear in Firebase Console

### ISSUE THREAD

**Issue by ikki-lim** [arnesson/cordova-plugin-firebase#758]
Hi all,

I'm trying to subscribe to topic "gos" using the code below, however I have tried for few times and waited for few days but still doesn't appear in FCM topic search. The FCM is working if sending using target app or token from console. 

window.FirebasePlugin.subscribe("gos");

Appreciate if anyone can help me on above issue. Thanks.

**Comment by snikesv** [comment]
+1
I still not recive answer:(
https://github.com/arnesson/cordova-plugin-firebase/issues/731
if you undarstand why, please write here
if i undarstand i write:)

**Comment by snikesv** [comment]
Hi, this is my example of code, this work with topics on Android and iOS
_**Function for coll after device ready**_
` registrPushFn(): boolean {
    if (!this.platform.is('cordova')) {
      console.warn('Push notifications not initialized. Cordova is not available - Run in physical device');
      return true;
    }
    if (this.platform.is('ios')) {
      this.firebase.hasPermission().then(data => {
        if (!data.isEnabled) {
          this.firebase.grantPermission().then(data => {
            return this.getTokenPush();
          })
            .catch(error => {
              console.error('Error getting permissions', error);
              return false;
            });
        } else {
          return this.getTokenPush();
        }
      });
    } else {
      return this.getTokenPush();
    }
  }`

**_Function for Get tocken_**

`  private getTokenPush() {
    this.firebase.getToken()
      .then(token => {
        this.globalVars.userData.userServiceInfo.gmsToken = token;
      }) // save the token server-side and use it to push notifications to this device
      .catch(error => console.error('Error getting token', error));

    this.firebase.onTokenRefresh()
      .subscribe((token: string) => {
        this.globalVars.userData.userServiceInfo.gmsToken = token;
      });

    // this.firebase.onNotificationOpen().subscribe(data => { });    
       
       this.setTopicPush();
    return true;
  }
`

**_And function for subscribe to topic_ (Attention!!! for  android good topic with /topics/blabla_bla-bla  but  for iOS must be without /topics/ example blabla_bla-bla)**

`  private setTopicPush() {
    let topic = "/topics/MyTopic-User_ENGLISH";
    if (this.platform.is('ios')) {
      topic = "MyTopic-User_ENGLISH"
    }    
    this.firebase.subscribe(topic);
  }`

**Comment by ikki-lim** [comment]
@snikesv Thanks Snikesv, I will try it out with your code.

**Comment by soumak77** [comment]
closing as resolved
