### ISSUE TITLE
How do i detect if the notification is from foreground or background

### ISSUE THREAD

**Issue by NightWarrior** [arnesson/cordova-plugin-firebase#759]
Great plugin, it works really well, but i'm kind of stuck due to there being relatively little documentation. So there is only one callback for when a notification comes. How do i differentiate between if the app was foreground or background?

> User receives the notification data in the JavaScript callback.

This point is a common point in both foreground and background flows. So is there a way to detect the difference?

I've tried cordova events like onResume and onPause, but the notification callback is occurring after onResume, so back to square one.

**Comment by davidavdav** [comment]
For me, it really is `data.tap` and not `data.wasTapped`.  

But more of an issue IMHO is #754.  The structure of the notification object seems to vary greatly with whether or not the message is received in background of foreground, and worst of all, the payload seems to be missing in the case of background.  

 - background:
```javascript
{
  collapse.key: ...
  from: ...
  google.message_id: ...
  google.sent_time:
  google.ttl: ...
  tap: true
}
```
 - foreground:
```javascript
{
  body: ...
  tap: false
}
```
This is what it is on Android 8, but I don't even want to think about how variable this might be for different versions of Android and for iOS...

**Comment by NightWarrior** [comment]
Ahhh your right... now i see it, its in the notification body. tap = 0; or tap = 1; Thank you
