### ISSUE TITLE
plugin is not installing

### ISSUE THREAD

**Issue by husseinelhussein** [arnesson/cordova-plugin-firebase#760]
Hello
I can install any plugin but when i try to install this plugin it just hangs there for hours saying:
` cordova plugin add cordova-plugin-firebase --save`
i tried this command:
`ionic cordova plugin add cordova-plugin-firebase`
and this:
 `cordova plugin add cordova-plugin-firebase`,  
and tried adding it to config.xml, and the issue still remain

**ionic info:**

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\android_sdk

Misc:

    backend : legacy

**Comment by timsar2** [comment]
confitm.
also try to install 
$ ionic cordova plugin add cordova-plugin-firebase@1.0.2
but still stuck

**Comment by timsar2** [comment]
yes, with latest nodejs and waiting over 10 min,it's done.

**Comment by Jaylton** [comment]
Can you solve this?
