### ISSUE TITLE
set badge number

### ISSUE THREAD

**Issue by masrooj** [arnesson/cordova-plugin-firebase#77]
I have to set badge number in firebase plugin. when i try to use 
window.FirebasePlugin.grantPermission()
window.FirebasePlugin.setBadgeNumber(n),
outside device ready function its always give error. What should  i do?

![to](https://cloud.githubusercontent.com/assets/7861852/19557978/96f8dfae-96e5-11e6-8758-d8dfe6e2d813.PNG)

**Comment by robertarnesson** [comment]
what do you mean outside device ready? you have to make sure device ready is fired first, then you can call the plugin

**Comment by masrooj** [comment]
I have to call this function in another controller not in app js
window.FirebasePlugin.setBadgeNumber(n)

**Comment by masrooj** [comment]
Badge No set in ios but not set in Android. What do i do

**Comment by blckshrk** [comment]
Actually on Android stock you can't have badge number functionality. This is added by overridden ROM like Samsung or HTC ones.
