### ISSUE TITLE
Plugin not installing in IOS

### ISSUE THREAD

**Issue by matthitachi** [arnesson/cordova-plugin-firebase#776]
```
ionic cordova plugin add cordova-plugin-firebase
npm install --save @ionic-native/firebase
```
 not working, it just waits for a pretty long time and does not finally install.
i even created a new blank project and tried it but same problem.
Ran `npm cache clean --force` and updated my npm, still no  change.
This is my environment information. Any help would be appreciated.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v8.11.3
    npm        : 6.2.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

config.xml
   ```
<plugin name="cordova-plugin-nativegeocoder" spec="^3.0.0" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    <plugin name="cordova-plugin-google-analytics" spec="^1.8.3" />
    <plugin name="cordova-plugin-firebase-analytics" spec="^1.0.0">
        <variable name="FIREBASE_CORE_VERSION" value="16.0.+" />
    </plugin>
    <plugin name="cordova-plugin-headercolor" spec="^1.0.0" />
    <plugin name="cordova-plugin-firebase" spec="^1.0.5" />
    <engine name="android" spec="7.0.0" />
```

Error:
Failed to restore plugin "cordova-plugin-firebase" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-firebase@^1.0.5 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
WARN tarball tarball data for cordova-plugin-firebase@^1.0.5 (sha1-s3swFRRnCbvMwN/IGEYZCbOM7Io=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for cordova-plugin-firebase@^1.0.5 (sha1-s3swFRRnCbvMwN/IGEYZCbOM7Io=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting cordova-plugin-firebase@^1.0.5:
npm ERR! Verification failed while extracting cordova-plugin-firebase@^1.0.5:
npm ERR! sha1-s3swFRRnCbvMwN/IGEYZCbOM7Io= integrity checksum failed when using sha1: wanted sha1-s3swFRRnCbvMwN/IGEYZCbOM7Io= but got sha512-mujaYm0Rbfjk9F29lpBgQwvKmJN8P08+LFc5pk35b0w4Q9ehgpI2NGn8EercP5mD+CmGHR0RvlagmTP/8CcLnA== sha1-gFPVKdx0sEA2430ige9i24QGl7U=. (5700340 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-07-19T13_57_22_775Z-debug.log

**Comment by Flucadetena** [comment]
Have you tried adding it through URL. Some people say that helps with some problems.

**Comment by ThonyFD** [comment]
Same issue, and I tried using the url, but doesn't work, some people say that the installation process finish ok after long time #760

**Comment by Flucadetena** [comment]
Have you tried to clone it and installed locally? Maybe an older version?

**Comment by matthitachi** [comment]
Try the ‘npm install --save @ionic-native/firebase’ first before running ‘ionic cordova plugin add cordova-plugin-firebase’.
It worked for me.
