### ISSUE TITLE
Why icon not showing on popup notification? 

### ISSUE THREAD

**Issue by aacassandra** [arnesson/cordova-plugin-firebase#778]
I've followed the instructions [here](https://github.com/arnesson/cordova-plugin-firebase/issues/426). and all went well. but the icon does not appear in the headsup if anyone missed it?

thanks to you for creating this plugin. 

icon not showing on popup:
![screenshot_2018-07-20-14-17-39](https://user-images.githubusercontent.com/29236058/42989118-147ac7b4-8c29-11e8-9c3e-54657311791a.png)

but icon can showing on here:
![asdasdasd](https://user-images.githubusercontent.com/29236058/42989126-19bcc574-8c29-11e8-83ca-1f79a6a84b0a.png)

please help me

**Comment by pvillaverde** [comment]
Hey there! Are you sending the icon property on the notification object?

On Firebase Console I dont see the option. But if you send the notification throught the API, you have to set which icon uses to display, or it defaults to the "launcher icon"(well, it paints all in white, so if you have a white circle arround the icon.. you get a gray circle :disappointed: . Hope it helps! :smile: 

From: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?hl=es-419#AndroidNotification
```
icon | string

The notification's icon. Sets the notification icon to _myicon_ for drawable resource _myicon_. If you don't send this key in the request, FCM displays the launcher icon specified in your app manifest.

```




Docs: 
https://firebase.google.com/docs/cloud-messaging/concept-options?hl=es-419

**Comment by aacassandra** [comment]
sorry i'm not so good at understanding your point. I tried to send a message via firebase console and it was fine but when I try to send a message via php script 

```
<?php
// API access key from Google API's Console
define( 'API_ACCESS_KEY' , 'MY_API_ACCES_KEY' );
$registrationIds = array( $_GET['id'] );
// prep the bundle
$msg = array
(
	'body' 	=> 'This is a body messages asdasd',
	'title'	=> 'This is a Title messages',
	'icon' => 'notification_icon'
);
$fields = array
(
	'registration_ids' 	=> $registrationIds,
	'data'			=> $msg
);
 
$headers = array
(
	'Authorization: key=' . API_ACCESS_KEY,
	'Content-Type: application/json'
);
 
$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );
echo $result;
?>
```

I get the error as above


what should i do, can you help me? thank you

**Comment by pvillaverde** [comment]
I've just tested your code and it does work well. I only changed "registration_ids" by "to"  in order to send to topic.  But the notification_icon was displayed correctly. I have no clue right now...

Does your notification icon have that bike with the grey circle? I use an icon with only alpha background.  One thing you could do is debug "onNotificationOpen" when your app gets the notification and see if the icon is set.

**Comment by pvillaverde** [comment]
I'm currently using Android 7.1.1 on my phone and cordova platform android 6.4.0 too.

As far as I Know problem with this notification icon could be with android < 21(5.0 Lollipop), but who knows.. I'll check if someone arround has an Android with Marshmallow to test it!

**Comment by soumak77** [comment]
closing as resolved
