### ISSUE TITLE
How implement Push Notification "init" method in cordova-plugin-firebase?

### ISSUE THREAD

**Issue by clebersonfalk** [arnesson/cordova-plugin-firebase#786]
Hi, I'm migrating my App from the `phonegap-plugin-push` to the `cordova-plugin-firebase` and I have some doubts.
For example, in the phonegap plugin push we have the method `init` where we inform the `senderID` and then we call the `on` method to register the device token, but I did not find how to implement this logic of the `init` method through the plugin of `cordova-plugin-firebase`.

Since `cordova-plugin-firebase` reads the` google-services.json` file, maybe this `init` method code will be implemented in the background, but I have not found anything to confirm this information and I am not sure how to proceed.

**My code:**
```
// After login we init Push Notifications plugin
var push = PushNotification.init({
    android: {
        senderID: "xxxxxxxxxxxx",
        icon: "push"
    },
    browser: {
        pushServiceURL: 'http://push.api.phonegap.com/v1/push'
    }
});

push.on('registration', function(data) {
    var id_desk = localStorage.getItem('id_desk');
    var userData = localStorage.getItem('user');
    userData = JSON.parse(userData);

    $.post('https://my-domain.com/mobile/android/save-android-token/id_desk/'+id_desk, {
        id_user: userData.id_user,
        device: data.registrationId
    }).then(function(data2){
        window.plugins.spinnerDialog.hide();
        window.location = 'index.html';
    });
});
```

**Plugin version:**
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"

**Info:**
Cordova version: 8.0.0
`<engine name="android" spec="^7.0.0" />`

Please, help me.
Thanks.

**Comment by CWollinger** [comment]
You can init with the method initFirebase and request the token with getToken after the deviceready:

> window.FirebasePlugin.initFirebase();
> window.FirebasePlugin.getToken(function(token) {
>     // save this server-side and use it to push notifications to this device
>     console.log(token);
> }, function(error) {
>     console.error(error);
> });
