### ISSUE TITLE
ERROR: Method 'verifyPhoneNumber:' not defined in Plugin 'FirebasePlugin' (IOS)

### ISSUE THREAD

**Issue by Flucadetena** [arnesson/cordova-plugin-firebase#787]
Hi, I'm running into this issue in the PhoneAuth in IOS. In android works perfectly and I've already tested the FCM in both and work correctly. I've search everywhere but cannot find anyone with the same problem. The whole log a get is this:

 ERROR: Method 'verifyPhoneNumber:' not defined in Plugin 'FirebasePlugin'
 FAILED pluginJSON = ["FirebasePlugin40635822","FirebasePlugin","verifyPhoneNumber",["thePhoneNumber",60]]

Thanks!

**Comment by Flucadetena** [comment]
I GOT IT TO WORK, Thanks to @derTuca.

The problem is that for some reason, the plugin is not defying the "verifyPhoneNumber" function in IOS, so the clue is to use their older function that is specific for Ios "getVerificationID(PhoneNumber)". It is not present in the README, so I leave here my code in case anyone faces the same error.

For android I'm using the "verifyPhoneNumber" directly from "ionic-native", imported like this: 
```
import { Firebase } from '@ionic-native/firebase';

constructor(private _fire: Firebase){}
```

```
sendVerfCode(phnPrfx: String, phoneNumber: String): Promise<any> {
    return new Promise(resolve => {
      if (this.platform.is("ios")) {
        (<any>window).FirebasePlugin.getVerificationID(phnPrfx.toString() + phoneNumber, function (verificationId){
          return resolve(verificationId);
        }, function (error) {
          console.error(error);
          return resolve(false);
        });
      } else
        this._fire.verifyPhoneNumber(phnPrfx.toString() + phoneNumber, 0).then(credential => {
          if (!credential.instantVerification) // To check the instant verification
            return resolve(credential.verificationId);
          else
            this.userVerified.emit({ resp: true, newPhone: newPhone });
        }, function (error) {
          console.error(error);
          return resolve(false);
        });
    });
  }
```

**Comment by soumak77** [comment]
closing as resolved
