### ISSUE TITLE
[Feature] Facebook/Twitter/GitHub/... authentication.

### ISSUE THREAD

**Issue by dannywillems** [arnesson/cordova-plugin-firebase#79]
Thanks for the job already done.

Is it planned to add Facebook/Twitter/GitHub/... authentication (and other available features in Firebase)?
Are you looking for contributors?

**Comment by robertarnesson** [comment]
No thats not really in the scope of this plugin. For facebook you can use https://github.com/jeduan/cordova-plugin-facebook4
there are also plugins for twitter etc.

Anyone can contribute, just submit a PR :)

**Comment by DavidFrahm** [comment]
Isn't Firebase Auth part of the Firebase SDK?

https://firebase.google.com/docs/auth/

We use it via the Firebase JS SDK, but now having added this cordova/firebase plugin would like to migrate that for two reasons:

* achieve simpler codebase by doing all Firebase things through the same library/SDK
* to have native views for auth, as is being required by Google (discussed on Ionic's blog: http://blog.ionic.io/google-oauth-changes/)

**Comment by robertarnesson** [comment]
As far as I know firebase auth only provides some backend support, there is no front-end included. I.e. you still need to obtain facebook tokens etc some other way. This is what the other plugins (e.g. facebook plugin) are for. The Facebook SDK is not part of Firebase and never will, nor will it part of this plugin

**Comment by DavidFrahm** [comment]
I've only used the JS SDK for Auth, but the docs mention "ready-made UI libraries" for example in this part:

> Firebase Authentication provides backend services, easy-to-use SDKs, and ready-made UI libraries to authenticate users to your app. It supports authentication using passwords, popular federated identity providers like Google, Facebook and Twitter, and more.

Regardless, there's nothing wrong with your position of not adding support for this to the plugin.

**Comment by robertarnesson** [comment]
Well in the actual docs for ios/android there is no such thing. They require you to pull in facebook sdk etc on your own, which makes it too complicated to include in this plugin. You can easily solve the problem by using existing facebook/twitter/whatever plugins to get the UI, and then do the rest with firebase auth
