### ISSUE TITLE
iOS build link error

### ISSUE THREAD

**Issue by Nisha-Ann-Mathew** [arnesson/cordova-plugin-firebase#793]
Am getting link error in iOS. Can't build my app
All issues are link error failures of FIR Diagnositic, FIR With etc..
Please somebody help

**Comment by briantq** [comment]
It might be more productive if you post some of the log file with the error.

**Comment by soumak77** [comment]
Closing as non-actionable.  [Tests](https://travis-ci.org/arnesson/cordova-plugin-firebase) verify that builds are working on iOS.

**Comment by ASHFAQPATWARI** [comment]
I am also getting a lot of linker errors.
