### ISSUE TITLE
Cordova build or run app error

### ISSUE THREAD

**Issue by Aleziii** [arnesson/cordova-plugin-firebase#794]
Hi,

when trying to generate the application build or try to run on device the following error occurs:
`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find any version that matches com.google.firebase:firebase-measurement-connector:[10.2.1,12.1.0[.
  Versions that do not match:
      17.0.0

      16.0.0
      15.0.0

  Required by:
      project :app > com.google.firebase:firebase-messaging:17.0.0

`
I already tried to add the url in the build.gradle file but it did not resolve, like here:

`       jcenter { 
            url "http://jcenter.bintray.com/"
         }
        maven {
            url "https://maven.google.com"
        }`

I do not undestand what the problem is.

**Comment by dmastag** [comment]
Could you try again? The OneSignal guys fixed the Gradle plugin which has resolved the issue for me. Look at https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/405#issuecomment-411517670 for details

**Comment by Aleziii** [comment]
I've run command 
`cordova clean`

and returned to normal operation. Thanks @dmastag
