### ISSUE TITLE
credential.verificationId is getting false!

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [arnesson/cordova-plugin-firebase#797]
When using own mobile number **credential.verificationId** is getting false!
Why is it so? Please help it's very urgent!

window.FirebasePlugin.verifyPhoneNumber(number, timeOutDuration, function(credential) {
    console.log(credential);

    // ask user to input verificationCode:
    var code = inputField.value.toString();

    var verificationId = credential.verificationId;

    var credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);

    // sign in with the credential
    firebase.auth().signInWithCredential(credential);
    
    // call if credential.instantVerification was true (android only)
    firebase.auth().signInWithCustomToken(customTokenFromYourServer);

    // OR link to an account
    firebase.auth().currentUser.linkWithCredential(credential)
}, function(error) {
    console.error(error);
});

**Comment by HanSoRyong** [comment]
metoo

**Comment by YaMo97** [comment]
Please read the VerifyPhoneNumber section in the API doc...

[verifyPhoneNumber()](https://github.com/arnesson/cordova-plugin-firebase/blob/master/docs/API.md#verifyphonenumber)

**Comment by soumak77** [comment]
this has been fixed in [v2.0.3](https://github.com/arnesson/cordova-plugin-firebase/blob/master/CHANGELOG.md#features) via https://github.com/arnesson/cordova-plugin-firebase/pull/861
