### ISSUE TITLE
Error with grantPermission for iOS

### ISSUE THREAD

**Issue by rolinger** [arnesson/cordova-plugin-firebase#802]
Using the following code to ask for user permission for push notifications:

```
          window.FirebasePlugin.grantPermission(function(data) {
            console.log(data) ;
            refreshToken($q,doReg) ; 
          }, function(error) {
            console.error('Error getting FCM permissions',error);
          });
```

I never get a popup window asking user...or anything...and the `console.error` msg outputs to console..

My app requests push notifications at initial startup.  If user declines permissions, later in the app if the user activates a specific feature that requires PUSH notifications to be enabled the grantPermission() is called again.  So this `grantPermission` is being called from within the app, not at app startup.

Thoughts?

**Comment by briantq** [comment]
If I understand, the issue you are having is that the user delicense the permission at startup and then when you try to prompt again the dialog is not displayed, correct?  If so, that is working as the Apple documentation specifies, https://developer.apple.com/library/archive/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42  It is best practice to ask for permissions in the context of the user taking an action so they are more likely to grant the permission when they do something relevant.

**Comment by soumak77** [comment]
closing as resolved per the above comment
