### ISSUE TITLE
Build error with Proguard enabled

### ISSUE THREAD

**Issue by Hanzofm** [arnesson/cordova-plugin-firebase#807]
Hi, 

I am trying to use this library with Proguard enabled, when I try to build the project it returns this error:

`
BUILD FAILED in 30s
43 actionable tasks: 43 executed
(node:12773) UnhandledPromiseRejectionWarning: Error: /Users/user/ionic/Frontend/MyProject/myproject/MyProject/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/user/ionic/Frontend/MyProject/myproject/MyProject/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.google.gms.googleservices.GoogleServicesPlugin: can't find superclass or interface org.gradle.api.Plugin
Warning: com.google.gms.googleservices.GoogleServicesPlugin: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$1: can't find superclass or interface org.gradle.api.artifacts.DependencyResolutionListener
Warning: com.google.gms.googleservices.GoogleServicesPlugin$1: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$1$_afterResolve_closure1: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$1$_afterResolve_closure1: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$GoogleServicesPluginConfig: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$PluginType: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$Version: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$VersionRange: can't find superclass or interface groovy.lang.GroovyObject
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure1: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure1: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure2: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure2: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure3: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_apply_closure3: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_countSlashes_closure10: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_countSlashes_closure10: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_failOnVersionConflictForGroup_closure12: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_failOnVersionConflictForGroup_closure12: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_failOnVersionConflictForGroup_closure12$_closure14: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_failOnVersionConflictForGroup_closure12$_closure14: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_getJsonLocations_closure11: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_getJsonLocations_closure11: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_handleVariant_closure9: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_handleVariant_closure9: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_handleVariant_closure9$_closure13: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_handleVariant_closure9$_closure13: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure4: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure4: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure5: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure5: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure6: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure6: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure7: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure7: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure8: can't find superclass or interface groovy.lang.Closure
Warning: com.google.gms.googleservices.GoogleServicesPlugin$_setupPlugin_closure8: can't find superclass or interface org.codehaus.groovy.runtime.GeneratedClosure
Warning: com.google.gms.googleservices.GoogleServicesTask: can't find superclass or interface org.gradle.api.DefaultTask
Warning: com.google.gms.googleservices.GoogleServicesPlugin: can't find referenced class org.gradle.api.Plugin
Warning: com.google.gms.googleservices.GoogleServicesPlugin: can't find referenced class groovy.lang.GroovyObject
..........
Warning: there were 887 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesAndResourcesWithProguardForDebug'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
    at ChildProcess.whenDone (/Users/user/ionic/Frontend/MyProject/myproject/MyProject/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:12773) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**This is my Proguard custom rules:**

# To enable ProGuard in your project, edit project.properties
# to define the proguard.config property as described in that file.
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in ${sdk.dir}/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the ProGuard
# include property in project.properties.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
#-dontshrink
#-dontoptimize
#-dontobfuscate

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class android.webkit.WebView {
#   public *;
#}

#-injars      bin/classes
#-injars      libs
#-outjars     bin/classes-processed.jar

# Using Google's License Verification Library 
-keep class com.android.vending.licensing.ILicensingService

# Specifies to write out some more information during processing. 
# If the program terminates with an exception, this option will print out the entire stack trace, instead of just the exception message.
-verbose

# Annotations are represented by attributes that have no direct effect on the execution of the code. 
-keepattributes *Annotation*

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keepattributes InnerClasses
-keep class **.R
-keep class **.R$* {
    <fields>;
}

# These options let obfuscated applications or libraries produce stack traces that can still be deciphered later on 
-renamesourcefileattribute SourceFile    
-keepattributes SourceFile,LineNumberTable

# Enable proguard with Cordova

-keep class org.apache.cordova.** { *; }
-keep public class * extends org.apache.cordova.CordovaPlugin

-keep class com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader { java.lang.ClassLoader sClassLoader; }
-keep class com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags.ModuleDescriptor { int MODULE_VERSION; }
-keep class com.google.android.gms.dynamite.descriptors.com.google.android.gms.flags.ModuleDescriptor { java.lang.String MODULE_ID; }

-keep class org.apache.cordova.CordovaBridge { org.apache.cordova.PluginManager pluginManager; }
-keep class org.apache.cordova.CordovaInterfaceImpl { org.apache.cordova.PluginManager pluginManager; }
-keep class org.apache.cordova.CordovaResourceApi { org.apache.cordova.PluginManager pluginManager; }
-keep class org.apache.cordova.CordovaWebViewImpl { org.apache.cordova.PluginManager pluginManager; }
-keep class org.apache.cordova.ResumeCallback { org.apache.cordova.PluginManager pluginManager; }
-keep class org.apache.cordova.engine.SystemWebViewEngine { org.apache.cordova.PluginManager pluginManager; }

-keep class com.google.gson.internal.UnsafeAllocator { ** theUnsafe; }
-keep class me.leolin.shortcutbadger.ShortcutBadger { ** extraNotification; }
-keep class me.leolin.shortcutbadger.impl.XiaomiHomeBadger { ** messageCount; }
-keep class me.leolin.shortcutbadger.impl.XiaomiHomeBadger { ** extraNotification; }

-dontnote org.apache.harmony.xnet.provider.jsse.NativeCrypto
-dontnote sun.misc.Unsafe

-keep class com.worklight.androidgap.push.** { *; }
-keep class com.worklight.wlclient.push.** { *; }

# Enable proguard with Google libs
-keep class com.google.** { *; }
-dontwarn com.google.common.**
-dontwarn com.google.ads.**

# apache.http
-optimizations !class/merging/vertical*,!class/merging/horizontal*,!code/simplification/arithmetic,!field/*,!code/allocation/variable

-keep class net.sqlcipher.** { *; }
-dontwarn net.sqlcipher.**

-keep class org.codehaus.** { *; }
-keepattributes *Annotation*,EnclosingMethod

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Remove debug logs in release build
-assumenosideeffects class android.util.Log {
    public static *** d(...);
}

# These classes contain references to external jars which are not included in the default MobileFirst project.
-dontwarn com.worklight.common.internal.WLTrusteerInternal*
-dontwarn com.worklight.jsonstore.**
-dontwarn org.codehaus.jackson.map.ext.*
-dontwarn com.worklight.androidgap.push.GCMIntentService
-dontwarn com.worklight.androidgap.plugin.WLInitializationPlugin

-dontwarn android.support.v4.**
-dontwarn android.net.SSLCertificateSocketFactory
-dontwarn android.net.http.*

# These clases contain references to google maps

-keep class plugin.google.maps.** { *; }
-keep public class * extends plugin.google.maps.MyPlugin
-keepclassmembers public class plugin.google.maps.GoogleMaps {*; }
-keepclassmembers public class * extends plugin.google.maps.MyPlugin { *; }

# References with google services

-keep class org.gradle.api.** { *; }
-keep interface org.gradle.api.** { *; }

-keep class groovy.lang.** { *; }
-keep interface groovy.lang.** { *; }

-keep class sun.misc.** { *; }
-keep interface sun.misc.** { *; }

-keep class org.codehaus.groovy.runtime.** { *; }
-keep interface org.codehaus.groovy.runtime.** { *; }

-keep class org.codehaus.groovy.reflection.** { *; }
-keep interface org.codehaus.groovy.reflection.** { *; }

-keep class com.google.gson.** { *; }
-keep interface com.google.gson.** { *; }

# JSR 305 annotations are for embedding nullability information.
-dontwarn javax.annotation.**

# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# OkHttp platform used only on JVM and when Conscrypt dependency is available.
-dontwarn okhttp3.internal.platform.ConscryptPlatform

`

**This is my Ionic Info:**

`Ionic:

   ionic (Ionic CLI)  : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.9.0 (/usr/local/bin/node)
   npm               : 5.7.1
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/juanramos/Library/Android/sdk

**Firebase plugin version:** 1.0.5

Is there any way to enable Proguard with this plugin installed?

**Comment by soumak77** [comment]
please confirm whether this issue still persists with v1.1.3

**Comment by briantq** [comment]
@Hanzofm can you test PR#841 by doing the following:
`cordova plugin remove cordova-plugin-firebase` (uninstall current firebase plugin)
`cordova plugin add https://github.com/briantq/cordova-plugin-firebase.git#google-services` (install the proposed fix)

Based on your stack trace it complains about Google Play Service and I think this might resolve your issue.

**Comment by soumak77** [comment]
Closing as out-dated.  Please reopen if issue still persists with latest version.
