### ISSUE TITLE
Impossible to install plugin

### ISSUE THREAD

**Issue by nhernandez2** [arnesson/cordova-plugin-firebase#808]
I am trying to install the plugin but the process does not progress, it is there.

`$ ionic cordova plugin add cordova-plugin-firebase`
`> cordova plugin add cordova-plugin-firebase --save`

`Ionic:`

   `ionic (Ionic CLI)  : 4.1.0 (/usr/local/lib/node_modules/ionic)`
  ` Ionic Framework    : ionic-angular 3.9.2`
  ` @ionic/app-scripts : 3.1.11`

`Cordova:`

   `cordova (Cordova CLI) : 8.0.0`
   `Cordova Platforms     : android 7.0.0`
   `Cordova Plugins       : cordova-plugin-ionic 5.0.1, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.0.3, (and 5 other plugins)`

`System:`

   `ios-deploy : 1.9.2`
   `NodeJS     : v8.10.0 (/usr/local/bin/node)`
   `npm        : 5.6.0`
   `OS         : macOS High Sierra`
   `Xcode      : Xcode 9.4.1 Build version 9F2000`

**Comment by dimalahbal** [comment]
me too , i have the same issue

**Comment by mateuszgwozdz** [comment]
Did you create Firebase project and copied google-service.json to the root directory?

**Comment by nhernandez2** [comment]
@mateuszgwozdz Yes, but that does not have to see if I can not install the plugin, what I did was install a specific version and it worked.

**Comment by soumak77** [comment]
closing as resolved
