### ISSUE TITLE
Events reported to wrong Firebase app

### ISSUE THREAD

**Issue by axelcostaspena** [arnesson/cordova-plugin-firebase#813]
We have a dual release app, it's the same codebase but we change a few files and we compile it and release it as com.example.a (let's call it A) and com.example.a.b (let's call it AB). When we compile app A we overwrite config.xml, package.json, icons and firebase configuration files with theirs. When we compile AB we do the same with its files. But all data is going into the Firebase consola as coming from app A (both apps are on the same Firebase project). How can this be happening if we rightly place the AB Firebase configuration files? Is it defaulting always to the first created app on the developer console? How can we debug what's happening? Regards.

**Comment by soumak77** [comment]
This doesn't sound like an issue with this repo.  I am guessing that you are not updating the necessary files properly in every case.  I do the exact same thing, using one firebase app for debug and one for production (same code base).  My scripts update the necessary files similar to what you describe and the data goes in the right place.  I can try to help out, but without more info I'll need to close this for now.
