### ISSUE TITLE
App crashing / not starting

### ISSUE THREAD

**Issue by redeleon** [arnesson/cordova-plugin-firebase#819]
Anyway, I have installed this plugin in my cordova project, built the app using the web phonegap build (build.phonegap.com) but when I started the app, it just crashes.

I have the config files and were in the root folder.

thanks!

**Comment by redeleon** [comment]
sorry, the form submitted right before I enter the issue details.

Anyway, I have installed this plugin in my cordova project, built the app using the web phonegap build (build.phonegap.com) but when I started the app, it just crashes.

I have the config files and were in the root folder.

thanks!

**Comment by DomCostantino** [comment]
I'm experiencing the same issue with Angular 6 + Cordova 8 and Onsen UI 2 project.

**Comment by soumak77** [comment]
If this is happening on Android, I believe this might be related to https://github.com/arnesson/cordova-plugin-firebase/issues/816.  Closing for now, but reopen if the issue still persists with v1.1.3 and provide crash reports so that the issue can be properly investigated.
