### ISSUE TITLE
Unable to handle Device 'backbutton' after plugin install

### ISSUE THREAD

**Issue by DomCostantino** [arnesson/cordova-plugin-firebase#825]
Hello  everyone, i'm experiencing a strange behavior in my app backbutton  handler.
Console shows this error while pressing the button and trying to pop a page or to exit the app: 

`Uncaught Error`
`at Object.get (onsenui.min.js:2)`
`at t.value (onsenui.min.js:2)`
`at t.value (onsenui.min.js:2)`
`at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)`
`at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)`
`at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)`
`at invokeTask (zone.js:1540)`
`at HTMLDocument.globalZoneAwareCallback (zone.js:1577)`
`at DeviceBackButtonDispatcher.fireDeviceBackButtonEvent (onsenui.js:1841)`
`at Object.push../node_modules/onsenui/js/onsenui.js.ons$1.fireDeviceBackButtonEvent (onsenui.js:7037)`

Debugging linked files i've found that for some reason the 'deviceBackButtonHandlerId' changed to an invalid value.
Is anyone experiencing this issue or i'm the only one? What i'm supposed to do now?

I'm developing with:
- Cordova 8
- Angular 6
- Onsen UI 2

**Comment by BrainOverflown** [comment]
Can you confirm that upon plugin uninstallation, the backbutton is getting back to normal behavior ?

**Comment by DomCostantino** [comment]
I've solved the issue, i accidentally copy-pasted Onsen UI components during test, i'm glad it was not a problem connected to the plugin.
