### ISSUE TITLE
PhoneGap application ios build in background 

### ISSUE THREAD

**Issue by Pikadili83** [arnesson/cordova-plugin-firebase#83]
Android build works as expected (Firebase notification received when in foreground and when in background (placed in notification tray))

iOS build gets notification when in foreground. But when in **background**, notification is received but not shown in notification tray (I know it's received because it is shown when app is brought to the foreground).

{
  "to":"/topics/-----",
  "priority":"high",
  "content-available": true,
  "notification":{
    "title":"Notification title",  
    "body":"Notification body"
  }
}

Help please....

**Comment by robertarnesson** [comment]
try to not set content_available. https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by Pikadili83** [comment]
I already tried that, no difference... I tried adding"data" tag, changed priority, set icon and sound...
nothing helps

When iOS in background notification is just not added to notification tray...

**Comment by Pikadili83** [comment]
Did you have similar scenario as I decribed that worked? This is a basic scenario, not doing nothing advanced, I just want notification to be shown in notification tray when iOS app in background (this should be normal behavior handled by iOS system)... Do you have any working example that I can see...
It's very important for me to get this thing working so please help me if you can... 
Thanks

**Comment by robertarnesson** [comment]
see #45 and #74

**Comment by umarrasheedmebest** [comment]
@robertarnesson , I am facing same issue Push notification working fine for Android in all cases but in IOS case only notification trigger when the app is in the foreground but not when in the background or closed .
Please guide me about this issue.
