### ISSUE TITLE
bulid errors with firebase android

### ISSUE THREAD

**Issue by razvang10** [arnesson/cordova-plugin-firebase#831]
when i try to build my app i get this 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
    at ChildProcess.whenDone (D:\Aplications\saioda-ra-maps\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:1568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Plugins Used:
*cordova-plugin-actionsheet 2.3.3 "ActionSheet"
*cordova-plugin-android-permissions 1.0.0 "Permissions"
*cordova-plugin-apprate 1.3.0 "AppRate"
*cordova-plugin-camera 4.0.3 "Camera"
*cordova-plugin-camera-preview 0.9.0 "cordova-plugin-camera-preview"
*cordova-plugin-crop 0.3.1 "CropPlugin"
*cordova-plugin-datepicker 0.9.3 "DatePicker"
*cordova-plugin-device 1.1.4 "Device"
*cordova-plugin-dialogs 2.0.1 "Notification"
*cordova-plugin-file 6.0.1 "File"
*cordova-plugin-file-transfer 1.7.1 "File Transfer"
*cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
*cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
*cordova-plugin-geolocation 4.0.1 "Geolocation"
*cordova-plugin-globalization 1.11.0 "Globalization"
*cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
*cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
*cordova-plugin-request-location-accuracy 2.2.2 "Request Location Accuracy"
*cordova-plugin-splashscreen 4.0.3 "Splashscreen"
*cordova-plugin-statusbar 2.4.1 "StatusBar"
*cordova-plugin-vibration 3.1.0 "Vibration"
*cordova-plugin-whitelist 1.3.1 "Whitelist"
*cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
*cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
*cordova.plugins.diagnostic 3.9.2 "Diagnostic"
*es6-promise-plugin 4.2.2 "Promise"
*ionic-plugin-keyboard 2.2.1 "Keyboard"
*uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"

Cordova version:
$ cordova --version
8.0.0

Ionic version:
$ ionic --version
4.1.2

**Comment by briantq** [comment]
@razvang10 why do you think this is related to the firebase plugin?  The version of the plugin you are using was released months ago and we have many people who have been able to build successfully since then.

**Comment by briantq** [comment]
@razvang10 I don't know the code behind any of the other plugins in your project. Without more detailed information with a conflict, I can't be much help as I don't know where to even start looking.

**Comment by razvang10** [comment]
@briantq I've fixed it all I had to do is to update one plugin thanks for your time :S
