### ISSUE TITLE
Cordova 8 and Android 7 build failed

### ISSUE THREAD

**Issue by andyepx** [arnesson/cordova-plugin-firebase#833]
`cordova run android` fails because it can't find `com.google.gms.google-services` when running in Cordova 8 with `cordova-android 7.1.1`

Had to update my app to Android 7 and the latest version of `cordova-plugin-firebase` doesn't seem to work with it. Any hints on how to solve this issue?

```
[cordova]  FAILURE: Build failed with an exception.
[cordova]
[cordova]  * Where:
[cordova]  Script '***/app/platforms/android/cordova-plugin-firebase/app-build.gradle' line: 27
[cordova]
[cordova]  * What went wrong:
[cordova]  A problem occurred evaluating project ':app'.
[cordova]  > Plugin with id 'com.google.gms.google-services' not found.
[cordova]
[cordova]  * Try:
[cordova]  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[cordova]
[cordova]  * Get more help at https://help.gradle.org
[cordova]
[cordova]  BUILD FAILED in 0s
[cordova]  (node:82096) UnhandledPromiseRejectionWarning: Error: ***/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
[cordova]  FAILURE: Build failed with an exception.
[cordova]
[cordova]  * Where:
[cordova]  Script '***/app/platforms/android/cordova-plugin-firebase/app-build.gradle' line: 27
[cordova]
[cordova]  * What went wrong:
[cordova]  A problem occurred evaluating project ':app'.
[cordova]  > Plugin with id 'com.google.gms.google-services' not found.
```

Thanks!

**Comment by andyepx** [comment]
Temporarily resolved by adding `classpath 'com.google.gms:google-services:4.1.0'` to `android/app/build.gradle` and `<framework src="com.google.gms:google-services:4.1.0" />` to  `plugin.xml` within `cordova-plugin-firebase`.

Hopefully you'll be able to resolve this soon 👍

**Comment by briantq** [comment]
@andyepx What version of the cordova-plugin-firebase plugin are you using? That plugin was recently removed in a Pull Request that removed Firebase Crash and replaced it with Crashlytics as it was believed that reference was no longer necessary. You might see if uninstalling and reinstalling the plugin resolves your issues also
`cordova plugin rm cordova-plugin-firebase`
`cordova plugin add cordova-plugin-firebase`

**Comment by andyepx** [comment]
Thanks @briantq.

I've updated to the latest version of the plug-in, v2.0.0, that was release earlier today, I started from a clean version of my setup - removed all the plugins and platforms and installed them all again.

You can actually still see the plug-in here https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/android/build.gradle

**Comment by mvergarair** [comment]
I had the same problem, erased platforms and plugins folders and it worked.

**Comment by soumak77** [comment]
closing as fixed
