### ISSUE TITLE
[Android] Notification callback is not the same in foreground/background.

### ISSUE THREAD

**Issue by Cirivas** [arnesson/cordova-plugin-firebase#838]
**Describe the bug**

I'm sending push notifications to an Android with the following structure:

```
{
	"notification": {
		"title": "My Title",
		"body": "My Message",
		"sound": "default"
	},

	"to": "<Device Token>",
	"priority":"high",
	"content_available": true
}
```

When the app is open, the callback is this:

```
{
    "tap":false,
    "body":"My Message",
    "title":"My Title"
}
```

But when the app is closed or background, the callback received when you tap the notification is the following:

```
{
    "google.sent_time":1536590283524,
    "google.ttl":2419200,
    "tap":true,
    "from":"<CODE>",
    "google.message_id":"0:1536590283530183%dafe50fedafe50fe",
    "google.priority":"high",
    "collapse_key":"<App identifier>"
}
```

Note that `body` and `title` field are completely missing from callback, and I need those fields to display a message inside the application.

**To Reproduce**

Send a push notification to an Android device and log its callback.

**Expected behavior**

I would expect to receive at least `body` and `title` field in both cases.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.4

**Smartphone (please complete the following information):**
 - Device: Samsung A7 and Huawei P7
 - OS: Android 6.0.1

**Additional context**

I'm currently using Ionic 3. Tested with version 2.0.0 of this plugin.

**Comment by briantq** [comment]
Are you trying to differentiate your notifications based on the title/body?  If so, you might consider the best practice of passing a url or other unique data in the data section of the notification and key off of that.  I know for a fact that works with the plugin as I use that myself.

By doing this, you can also avoid any issues you may have during translations when the title/body represent that same text but are actually different. 

You can see the documentation here on how to add the extra property to your notification you create, https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload

**Comment by Cirivas** [comment]
Hi @briantq 

Thanks for your advice. I was expecting the same behavior because in the past I used phongap-push-notifications, and that gave me always the same callbacks. 

Thanks again, additional fields worked fine in android and ios, and in both modes (foreground and background).

**Comment by briantq** [comment]
@Cirivas I am glad it worked.  I have only been working with Cordova for less than a month, much of my effort on push notifications so I have been trying to find all the best practices I can.  If I can save others time and head ache, I am more than happy to help!
