### ISSUE TITLE
Not use Push Notifications

### ISSUE THREAD

**Issue by newuser44** [arnesson/cordova-plugin-firebase#846]
We haven't setup push notifications.  Only use Analytics.
When pushing to the app store we got a warning.  

> Missing Push Notification Entitlement
> Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement
. 

Not sure anything we can do about that?

**Comment by briantq** [comment]
@newuser44 I think this goes back to your request about turning off push notifications in issue #800.  If you would like to submit a fix to do that, we would happily work with you to merge it in.
