### ISSUE TITLE
Remove plugin fails no build.gradle

### ISSUE THREAD

**Issue by newuser44** [arnesson/cordova-plugin-firebase#849]
**Describe the bug**
When I try to remove the cordova-plugin-firebase with ionic   I get this.  

> cordova plugin remove cordova-plugin-firebase --save
Error: ENOENT: no such file or directory, open 'platforms/android/build.gradle'

[ERROR] An error occurred while running cordova plugin remove cordova-plugin-firebase --save (exit code 1).

It seems like that removing the plugin removes a lot of the android files.  

**To Reproduce**
run    ionic cordova plugin remove cordova-plugin-firebase

**Expected behavior**
I would not expect removing the plugin to remove a lot of the android files. 

**Plugin Version**
Trying 1.0.5 I think.

**Desktop (please complete the following information):**
Linux

Seems like removing the plugin it deleting extra files.  
The solution is to remove android,  then remove the plugin, then add android back.

**Comment by briantq** [comment]
I have seen this from time to time also.  I am not sure what is causing it.  I don't think we explicitly delete any system files when we install/uninstall.  

What I have found as a work around is to delete the platform/android folder, delete the plugin then run `cordova prepare android` so it recreates all the Android files.

**Comment by mohamedsharaf** [comment]
i can confirm the error exist
also for cordova cli 6 and cordova android 6.4 this error is not exist

**Comment by soumak77** [comment]
This should be fixed in v2.0.3 as we've changed which hooks we use for plugin configuration.  See https://github.com/arnesson/cordova-plugin-firebase/issues/869

**Comment by fsalazarsch** [comment]
i dont understand gradle has a lot of bugs, is there another system?
