### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by shawns582** [arnesson/cordova-plugin-firebase#851]
**Describe the bug**
I am getting a build link error in ios on my Ionic 3 app. I tried v2.0.1 and v1.1.4 of the plugin. It works fine on android. Below is what I am getting (with some of the path removed):

`/platforms/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
#import <GoogleUtilities/GULAppEnvironmentUtil.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
.....
The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/SoulSence-advbkxgddogbosgxnofvgcwiickp/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseCore.build/Objects-normal/x86_64/FIRLogger.o FirebaseCore/Firebase/Core/FIRLogger.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
(node:82540) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/platforms/ios/cordova/build-debug.xcconfig,-workspace,SoulSence.xcworkspace,-scheme,SoulSence,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/platforms/ios/build/sharedpch
`

I tried with and without adding pod 'Firebase/Core' to my podFile and doing 'pod install'

Would appreciate any help.

**Comment by briantq** [comment]
This plugin does not work with pods.  There is a feature request open to implement that functionality.  You should remove remove all Firebase pods and any plugins that reference Firebase/Google pods from your project as I imagine that will generate an error.  

What version of the plugin are you using

Also, can you list the plugins in your project `cordova plugin list` to see if there are any suspected conflicts

**Comment by shawns582** [comment]
thanks @briantq I tried with v2.0.1 and 1.1.4 of the plugin.   Below is my current list of plugins for my project:

com.oauthio.plugins.oauthio 0.2.4 "OAuth.io"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-badge 0.8.6 "Badge"
cordova-plugin-camera 3.0.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-firebase 2.0.1 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.2.1 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-music-controls 2.1.4 "MusicControls"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-sqlite-storage 2.2.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"
twitter-connect-plugin 0.6.0 "Twitter Connect"

Below is my ionic info: 

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.7

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 27 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v9.4.0 (/usr/local/bin/node)
   npm        : 5.6.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000


Also after removing pods and reinstalling I now get this:

`Undefined symbols for architecture x86_64:
  "_FABNetworkMaximumRetryCount", referenced from:
      ___51-[CLSBetaController loadUpdateWithCompletionBlock:]_block_invoke in Crashlytics(CLSBetaController.o)
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
      objc-class-ref in FirebasePerformance(FPRSelectorInstrumentor_533cb9fc17c76e86c2a8deed3bf3bb8e.o)
      objc-class-ref in FirebasePerformance(FPRProxyObjectHelper_3a51514a260cac11ea82400beaac4a87.o)
  "_GULLogInfo", referenced from:
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLogError", referenced from:
      +[APMAnalytics startWithAppID:origin:options:] in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
  "_kGULNetworkHTTPStatusCodeNotModified", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_kGULNetworkHTTPStatusCodeNotFound", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_kGULNetworkHTTPStatusCodeUnavailable", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_OBJC_CLASS_$_GULObjectSwizzler", referenced from:
      objc-class-ref in FirebasePerformance(FPRObjectInstrumentor_f65d32035cadef24185912716f0b12f9.o)
      objc-class-ref in FirebasePerformance(FPRNetworkTrace_3053ec2ab59f2fcfec4b18c29e4b4cec.o)
      objc-class-ref in FirebasePerformance(FPRNSURLConnectionInstrument_5611d225f62417fa73742554b6a45401.o)
  "_kGULNetworkHTTPStatusNoContent", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_kGULNetworkHTTPStatusCodeCannotAcceptTraffic", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLogWarning", referenced from:
      -[APMUserDefaults objectForKey:] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      -[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      +[APMMeasurement sharedInstance] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
  "_kGULNetworkHTTPStatusOK", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLogBasic", referenced from:
      -[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement(APMASLLogger_466efed35a5f23968c22566c7d73d056.o)
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseInstanceID(FIRMessagingLog_4bce424a95932f9cf38ffaf7cadd24a8.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_b8d2083bbf595e32a15f4c92bf56379b.o)
      objc-class-ref in FirebaseAuth(FIRAuth.o)
      objc-class-ref in FirebaseAuth(FIRAuthAPNSTokenManager.o)
      objc-class-ref in FirebaseAuth(FIRAuthAppDelegateProxy.o)
      objc-class-ref in FirebaseAuth(FIRAuthDefaultUIDelegate.o)
      objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_22e23cfa4b36fa0d65a3f7296e546bb7.o)
      ...
  "_OBJC_CLASS_$_GULMutableDictionary", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMRemoteConfig_c5400480091348d9d0507d500ca1b5e8.o)
      objc-class-ref in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
      objc-class-ref in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      objc-class-ref in GoogleAppMeasurement(APMAppDelegateInterceptor_8eccbb425d76703bd931c4581a5d7ff0.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_39f37e7cc81dbdcb1b22721b95a40297.o)
  "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging.o)
  "_GULIsLoggableLevel", referenced from:
      -[APMMonitor isLoggableLevel:] in GoogleAppMeasurement(APMMonitor_ef678926ed29a8789c2a47d143bcb03c.o)
  "_GULSetLoggerLevel", referenced from:
      -[APMMonitor setDebugModeEnabled:] in GoogleAppMeasurement(APMMonitor_ef678926ed29a8789c2a47d143bcb03c.o)
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 warnings only

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/SoulSence.app/SoulSence normal x86_64
(1 failure)
(node:94122) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/platforms/ios/cordova/build-debug.xcconfig,-workspace,SoulSence.xcworkspace,-scheme,SoulSence,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/platforms/ios/build/sharedpch
(node:94122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by briantq** [comment]
@shawns582 you should definitely take out Google Analytics as that is already in this plugin. I have to imagine including both would cause problems. If that doesn't resolve your problem I would try removing other Google dependencies like Google plus to see the there is a conflict there. 

Feel free to tag me in a comment if you have more questions as I'm going to close this since it's specific to your configuration and not a problem with the plug-in

**Comment by shawns582** [comment]
@briantq thanks for your help. I tried removing Google Analytics and Google plus but still had a problem. Since I am only using firebase analytics at the moment (plan to use push notifications, crashlytics etc in the future), I was able to get cordova-plugin-firebase-analytics v0.13.0 working. 

I will try again later to get cordova-plugin-firebase working after this app release. Hopefully I have better luck then.

**Comment by Nabarun** [comment]
Getting this similar error , has anyone got any solution

```
Undefined symbols for architecture x86_64:
  "_GULLoggerInitializeASL", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_GULLoggerEnableSTDERR", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
      objc-class-ref in FirebasePerformance(FPRSelectorInstrumentor_533cb9fc17c76e86c2a8deed3bf3bb8e.o)
      objc-class-ref in FirebasePerformance(FPRProxyObjectHelper_3a51514a260cac11ea82400beaac4a87.o)
  "_GULLogInfo", referenced from:
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
  "_GULLoggerForceDebug", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_kGULNetworkHTTPStatusCodeNotModified", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_kGULNetworkHTTPStatusCodeNotFound", referenced from:
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_kGULNetworkHTTPStatusCodeCannotAcceptTraffic", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLogWarning", referenced from:
      -[APMUserDefaults objectForKey:] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      -[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
      +[APMMeasurement sharedInstance] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement(UIViewController+APMScreenClassName_9656c83908820df5d5741a22364bcbc3.o)
  "_kGULNetworkHTTPStatusNoContent", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLoggerRegisterVersion", referenced from:
      ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
  "_kGULNetworkHTTPStatusCodeUnavailable", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_kGULNetworkHTTPStatusOK", referenced from:
      -[APMMeasurement networkUploadCompletionHandlerWithResponse:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      -[APMMeasurement networkRemoteConfigFetchCompletionHandler:data:error:] in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_GULLogBasic", referenced from:
      -[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement(APMASLLogger_466efed35a5f23968c22566c7d73d056.o)
      _FIRLogBasic in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULObjectSwizzler", referenced from:
      objc-class-ref in FirebasePerformance(FPRObjectInstrumentor_f65d32035cadef24185912716f0b12f9.o)
      objc-class-ref in FirebasePerformance(FPRNetworkTrace_3053ec2ab59f2fcfec4b18c29e4b4cec.o)
      objc-class-ref in FirebasePerformance(FPRNSURLConnectionInstrument_5611d225f62417fa73742554b6a45401.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseInstanceID(FIRMessagingLog_4bce424a95932f9cf38ffaf7cadd24a8.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRDiagnostics_b8d2083bbf595e32a15f4c92bf56379b.o)
      objc-class-ref in FirebaseAuth(FIRAuth.o)
      objc-class-ref in FirebaseAuth(FIRAuthAPNSTokenManager.o)
      objc-class-ref in FirebaseAuth(FIRAuthAppDelegateProxy.o)
      objc-class-ref in FirebaseAuth(FIRAuthDefaultUIDelegate.o)
      objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_22e23cfa4b36fa0d65a3f7296e546bb7.o)
      ...
  "_OBJC_CLASS_$_GULMutableDictionary", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMRemoteConfig_c5400480091348d9d0507d500ca1b5e8.o)
      objc-class-ref in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
  "_OBJC_CLASS_$_GULNetwork", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
      objc-class-ref in GoogleAppMeasurement(APMMeasurement_9c6a590e800f6e58020a35af1caeae59.o)
      objc-class-ref in GoogleAppMeasurement(APMAppDelegateInterceptor_8eccbb425d76703bd931c4581a5d7ff0.o)
      objc-class-ref in FirebaseCoreDiagnostics(FIRClearcutLogger_39f37e7cc81dbdcb1b22721b95a40297.o)
  "_GULIsLoggableLevel", referenced from:
      -[APMMonitor isLoggableLevel:] in GoogleAppMeasurement(APMMonitor_ef678926ed29a8789c2a47d143bcb03c.o)
  "_GULLogError", referenced from:
      +[APMAnalytics startWithAppID:origin:options:] in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement(APMUserDefaults_a6b5b26129a36e9a7f47684f0883c824.o)
  "_GULSetLoggerLevel", referenced from:
      -[APMMonitor setDebugModeEnabled:] in GoogleAppMeasurement(APMMonitor_ef678926ed29a8789c2a47d143bcb03c.o)
      _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
  "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging.o)
  "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_b5e839cb4c33d04514600afcd61d2def.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by mesqueeb** [comment]
Just in case anyone comes looking here.
It worked when I did this:
```
cordova platform rm ios
cordova platform rm android
cordova platform add ios
cordova platform add android
```

and it started working and didn't have the above error anymore.

It's often because of a conflicting plugin (like `phonegap-plugin-push`). But even if you remove that plugin you'd need to remove and add the platforms once.

**Comment by murilobeltrame** [comment]
Thanks @mesqueeb ,
In my case I just uninstalled `phonegap-plugin-push`.

**Comment by gabygarro** [comment]
I had this problem and my conflict was `cordova-plugin-firebase-config`. I removed it and my build suceeded.

**Comment by hiepxanh** [comment]
@mesqueeb  thank you so much, I just facing the same problem `npm uninstall --save phonegap-plugin-push` and `ionic cordova platform rm ios` then `ionic cordova platform add ios` just work
