### ISSUE TITLE
conflicts with other plugins - ionic pro

### ISSUE THREAD

**Issue by appnativeitalia** [arnesson/cordova-plugin-firebase#856]
Hello,
I can not complete the package with IONIC PRO. The process fails with this error:

`
The library com.google.android.gms:play-services-base is being requested by various other libraries at [[11.0.4,11.0.4], [15.0.1,15.0.1]], but resolves to 15.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
`
I use this plugin together with "cordova-plugin-admob-free". I can not resolve the conflict. I have specified the libraries for Google Play Service in the config.xml file. But the error is always the same.
I also tried to install the employee plugin Cordova Admob Sdk (latest version) and then Admob Free. But the same mistake.

Is not there a way to include Admob scripts using just the firebase plugin without installing the Admob plugin?
Or there is a way to resolve the conflict. Remember I use IONIC PRO (deploy & package). So I can only configure the config.xml file. 

Thanks in advance

**Comment by soumak77** [comment]
Have you followed the [README](https://github.com/arnesson/cordova-plugin-firebase/blob/master/README.md#google-play-services) with respect to Google play services?

**Comment by appnativeitalia** [comment]
Yes,
I used the following commands:

```
cordova plugin add cordova-android-play-services-gradle-release  --variable 
PLAY_SERVICES_VERSION=15.+
cordova plugin add cordova-android-firebase-gradle-release  --variable FIREBASE_VERSION=15.+
```

The error is always the same

**Comment by soumak77** [comment]
Could you try using "+" instead of "15.+". I had to do this in our
automated tests to get them to pass. If that works for you I'll update the
README.

**Comment by appnativeitalia** [comment]
Now it seems to work.
Replace "15. +" with "+".
I tried with Android. There should not be any problems with IOS.
Thank you so much, I lost several days ... :)
You can update the README please, and instructions.

**Comment by soumak77** [comment]
README has been updated
