### ISSUE TITLE
window.FirebasePlugin.onTokenRefresh

### ISSUE THREAD

**Issue by laychar** [arnesson/cordova-plugin-firebase#860]
I want to get new token whenever I request. But even though I call the function - window.FirebasePlugin.onTokenRefresh my app just get token which is same to older one.
What should I do to get new token?

**Comment by briantq** [comment]
@laychar Firebase uses the one token for a period of time.  The `window.FirebasePlugin.onTokenRefresh` is the callback that happens when FIrebase rotates it's token for this particular device.

That being said, if you have an user log out and need to change the token, you can call `window.FirebasePlugin.unregister()` followed by `window.FirebasePlugin.getToken` to get a new Token.

**Comment by laychar** [comment]
What means the sentence "firebase rotates" ?
Then token will be changes someday?

2018년 9월 20일 (목) 오후 11:06, Brian Bauman <notifications@github.com>님이 작성:

**Comment by briantq** [comment]
@laychar Yes, Firebase rotates their tokens periodically, hence the reason to know when they change.  It is documented in the Android Firebase documentation.  You should look there for more information.

**Comment by laychar** [comment]
I got it, thanks!
Then should I call the function refresh token whenever firebase rotates?

2018년 9월 20일 (목) 오후 11:15, Brian Bauman <notifications@github.com>님이 작성:

**Comment by briantq** [comment]
@laychar that method is called whenever the token is updated, you only need to register it once. When I receive this even I then call get token and then upload it to my server so it has the proper token.

**Comment by laychar** [comment]
Sorry, I can not understand your words. I am a korean.
so, even I just call getToken, refreshToken will be called when firebase rotates token?

**Comment by laychar** [comment]
+) My app call refreshToken whenever I turn on my app to be immune to firebase's rotating token.
So I use following function whenever I turn on my app.
var chtk= function(){
    alert('2');
  window.FirebasePlugin.onTokenRefresh(function(token) {
      alert('22');
    var data={};
    data.tk = token;
    window.localStorage['tk']=token;
    data._id = window.localStorage['_id'];
    data.id=window.localStorage['id'];
    data.name=window.localStorage['name'];  
    $.ajax({
      type:'POST',
      data: JSON.stringify(data),
      contentType: 'application/json',  
      url:url+'/stk',
      success:function(output){
        if(output.status==100){  
            alert(token);            
        }else if(output.status==500){
          alert('token update failed1');
        }else{
          alert('token update failed1');  
        }      
      }  
    });
  }, function(error) {
    console.error(error);
  });    
}
And When I should get new token I call following function.
var nwtk= function(){
  window.FirebasePlugin.unregister(function(){
      window.FirebasePlugin.getToken(function(token) {
          alert('11');
        var data={};
        data.tk = token;
        window.localStorage['tk']=token;
        data._id = window.localStorage['_id'];
        data.id=window.localStorage['id'];
        data.name=window.localStorage['name'];  
        $.ajax({
          type:'POST',
          data: JSON.stringify(data),
          contentType: 'application/json',  
          url:url+'/stk',
          success:function(output){
            if(output.status==100){
                alert(token);
            }else if(output.status==500){
              alert('token update failed1');
            }else{
              alert('token update failed1');  
            }      
          }  
        });
      }, function(error) {
        console.error(error);
      });       
  });        
}
I have a stange problem.
when I call "nwtk" function refreshToken which is in "chtk" function is called too!!

**Comment by briantq** [comment]
@laychar it should be 

// to be notified when token rotates
window.FirebasePlugin.onTokenRefresh(…) {
    // upload token to server
}

// to get the token on startup/right away
window.FirebasePlugin.getToken((token) => {
   // upload token to server
});

This should get you the right token.

If you need to change the token (which most likely happens on log out

window.FirebasePlugin.unregister();

then when the user signs in again, get the token using 
window.FirebasePlugin.getToken((token) => {
   // upload token to server
});

**Comment by laychar** [comment]
I use token for security of image upload.
So I should change token right after I upload image.
For this reason I call getToken function as a callback for unregister.
But I have a problem. When I call unregister refreshToken function is
called too.

2018년 9월 21일 (금) 오전 12:04, Brian Bauman <notifications@github.com>님이 작성:

**Comment by briantq** [comment]
@laychar I am not sure how to help you as it sounds like you are using the token for an unintended purpose.  If you have issues you might look at Firebase support.

**Comment by laychar** [comment]
Ok, thank you for your help!

2018년 9월 21일 (금) 오전 12:20, Brian Bauman <notifications@github.com>님이 작성:
