### ISSUE TITLE
App goes removed from Play Store because of Advertising Id? 

### ISSUE THREAD

**Issue by newuser44** [arnesson/cordova-plugin-firebase#862]
We had four apps, been pushing them out with Analytics,  actually pushed them out with version 1.0.?  seemed like some data was missing so we re-pushed them out with 2.0.1 plugin.  

Today we got a notice that one of our apps had been taken off the play store for this reason.

> Issue: Violation of Usage of Android Advertising ID policy and section 4.8 of the Developer Distribution Agreement
> 
> Google Play requires developers to provide a valid privacy policy when the app requests or handles sensitive user or device information. We’ve identified that your app collects and transmits the Android advertising identifier, which is subject to a privacy policy requirement. If your app collects the Android advertising ID, you must provide a valid privacy policy in both the designated field in the Play Console, and from within the app.

We don't have any ads in our app so I'm kind of assuming this is Firebase analytics.  I was reading about how Firebase knows gender and stuff.  It seems like it uses some ad network to figure that information out.    
Any way to turn that off?  or what is the best solution.

**Comment by soumak77** [comment]
Do you have a website for your apps? You can find precreated privacy policies online and just add an html page to your website with the policy. Then add that url to the app store.

The only other solution is to add a configuration option to this plugin which disables analytics.

**Comment by newuser44** [comment]
That is what I am wondering.   Firebase Analytics means Advertising id which means you will have to have a privacy policy?   I wish that was explained somewhere.  We don't have ads in our app so no where was there a concern that our app could be taken down. 
There is no way to turn off or take out the Advertising id?

**Comment by soumak77** [comment]
Check out this article: https://support.google.com/firebase/answer/6318039?hl=en

Seems the advertising ID is required to make analytics and performance data work with firebase. Therefore your only fix is to include the privacy policy as mentioned or update this plugin to allow disabling those feautres.

**Comment by newuser44** [comment]
Thanks for the link.  Yeah still scrambling.   I noticed pushing out an iOS app it asks if the app uses any advertising.  I always select no,  I clicked yes just to see what are the options.  Pretty much the options is really that the app is using ads for a good purpose? something like that.  But nothing about using ads for analytics.   I'm guessing on ios devices this isn't a problem.

**Comment by newuser44** [comment]
They do seem to have a setting (in Firebase) to turn off Advertising Id  
<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />

It doesn't look like that is part of the plugin.

**Comment by soumak77** [comment]
You would have to manually update those files for now to disable analytics as a quick fix. Ideally we would introduce those same variables so that they make their way into the necessary files during the plugin build.

**Comment by newuser44** [comment]
We are trying to find a good privacy policy.   I do find it strange that the stuff you read about firebase analytics they tell you the data they are collecting but doesn't really seem to warn you that you should disclose it or update any PP document.   Kind of playing a little innocent.   On the Android side they are a big stickler for make sure you disclose everything, and allow people to opt out.   One side plays it down and the other side plays it up.  And they are the same company.

**Comment by galrom** [comment]
[check FireBase analytics docs](https://firebase.google.com/support/guides/disable-analytics)

You need to disable collecting of Advertising ID, by adding the following line under application tag in Manifest file:

<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />

I am trying to upload a version with this fix to Google play - crossing fingers.

**Comment by nitinjadhav** [comment]
Is that worked or not ?

**Comment by galrom** [comment]
Yes, it worked, my app was approved.

**Comment by rahulecomp** [comment]
Will I be able to have crash reporting statistics if we disable collecting of Advertising ID. Does this affect only analytics?

**Comment by exzizt** [comment]
How does removing the collection of the advertising ID affect Firebase Analytics? Anyone?

**Comment by VamshidharRaoKotha** [comment]
After fixing and submitting advertising ID issue, again how much time did google take to publish.

**Comment by galrom** [comment]
A couple of hours.
However in some cases the Advertiser ID was not the problem.
I was missing a privacy policy from the app and from Google Play

Make sure it's not your case as well

Good luck

בתאריך שבת, 6 ביולי 2019, 10:04, מאת VamshidharRaoKotha ‏<
notifications@github.com>:

**Comment by VamshidharRaoKotha** [comment]
Thanks galrom, for responding within 2 min. I have submitted with a privacy policy today 4 hours back, may be because of weekend still they are not approving . I'll wait till Monday.
