### ISSUE TITLE
Probable wrong dependency name in android>build.gradle

### ISSUE THREAD

**Issue by campagna91** [arnesson/cordova-plugin-firebase#863]
Hi Team.

Is there maybe a wrong dependency name in file (as title) **build.gradle** inside "src/android/build.gradle" for key " **cdvPluginPostBuildExtras.add * " as apply ?

At current version (2.0.2), name is like:

"com.google.gms.google-services" 

instead "com.google.gms:google-services" (with ":" between 'gms' and 'google')

Thanks for the attention

**Comment by briantq** [comment]
@campagna91 thanks for keeping a close eye on things. There are 2 build.gradle files  in an Android project. The build.gradle inside src/android/ augments the app build.gradle, not the project build.gradle. 

It's easy to read the [Firebase install directions](https://firebase.google.com/docs/android/setup) amd miss that (I did the first time I read it). If you look at the app build.gradle modifications it is correct. 

The dependency that has the semi colon goes in the project's build.gradle. That is handled in an install script as there's no built in way to augment that file.

Thanks for checking!
