### ISSUE TITLE
migration guide from v1 to v2

### ISSUE THREAD

**Issue by StephanMeijer** [arnesson/cordova-plugin-firebase#868]
**Describe the bug**
Version 2 has been release, but I do not know how to migrate from version 1 to version 2. Following semantic versioning, version 2 breaks some thing from version 1. I want to know exactly what things and how to migrate.

**To Reproduce**
Read the README

**Expected behavior**
Migration guide in README

**Plugin Version**
2.x.x

**Comment by soumak77** [comment]
There shouldn't be any breaking changes from v1. What issues are you
encountering?

**Comment by soumak77** [comment]
To be specific, v2 was released because originally v1.1.x was breaking a
lot of apps due to an incomplete PR that was merged. I released v2 to
ensure we didn't break apps that we're still on v1. Now that v2 has
stabilized, you shouldn't need to do anything to upgrade from v1.

**Comment by StephanMeijer** [comment]
Is there any way to test Crashlytics working?

**Comment by soumak77** [comment]
@briantq has done a lot to get it working in iOS and Android so I don't
think you'll have issues. Though if do please open a new issue.

**Comment by briantq** [comment]
@StephanMeijer I have not found a good way to test it and unfortunately I write perfect code so my app never crashes ;)  If you have some good way to test it, I would love to be able to confirm it works.

**Comment by StephanMeijer** [comment]
see #871
