### ISSUE TITLE
Can't use notification_icon.png in Android

### ISSUE THREAD

**Issue by jackyy415** [arnesson/cordova-plugin-firebase#87]
Hi, I am using cordova local build for my Android build. I've added the notification_icon.png to the platforms\android\res\drawable* folders manually before building the apk. It turns out the notification icon is still using the app icon.

May I know what is the proper way to add the notification_icon.png to the phonegap/cordova build?

**Comment by prantikv** [comment]
+1

**Comment by device68** [comment]
Use the built in application for creating icons. It's called Android Asset Studio https://developer.android.com/studio/write/image-asset-studio.html

**Comment by robertarnesson** [comment]
icons have been refactored in 0.1.20. see readme
