### ISSUE TITLE
Can't add plugin to my project

### ISSUE THREAD

**Issue by CellanceDeveloppement** [arnesson/cordova-plugin-firebase#877]
**Describe the bug**
That the first time i try to use this plugin.

I try from my Mac and my PC. Install stop every time on the plugin.

Is there some wrong with de publish version of the plugin on npm ? or do I made a mistake on the install procedure ?

Thanks

**To Reproduce**
I can't add the plugin to my project whatever i try to install it from theses commands :
cordova plugin add cordova-plugin-firebase --save
npm i -D cordova-plugin-firebase
yarn add --dev cordova-plugin-firebase

**Expected behavior**
Installation done

**Screenshots**

**Plugin Version**
version 2.0.2 ; 2.0.1 ; 2.0.0

**Desktop (please complete the following information):**
Windows 10 : node 10.09 and 10.11
MacOS : 10.13
Cordova iOS 4.5.5

**Comment by soumak77** [comment]
Please provide the console logs so we can investigate this issue

**Comment by CellanceDeveloppement** [comment]
It seems that it was definitively a bug in a DNS from my area. I tried to change it by CloudFare 1.1.1.1 a work perfectly this morning.

I think you can consider this issue close.

Thanks for your job.
