### ISSUE TITLE
Failed to install 'cordova-plugin-firebase': Error: ENOENT: no such file or directory, open '/**/***/***/platforms/android/AndroidManifest.xml'

### ISSUE THREAD

**Issue by dmeij** [arnesson/cordova-plugin-firebase#878]
**Describe the bug**
Can't install the plugin with the command: cordova plugin add cordova-plugin-firebase

**To Reproduce**
1. Go to 'command line'
2. Execute command 'cordova plugin add cordova-plugin-firebase'
3. See error

**Plugin Version**
Latest for Android

**Comment by Repox** [comment]
This looks like a local issue and not an issue with the plugin. Can you install other plugins without this issue?

**Comment by soumak77** [comment]
Please provide console logs so we can investigate this issue.  You can also try testing out a proposed fix via PR #872.  You can check our [contributing doc](https://github.com/arnesson/cordova-plugin-firebase/blob/master/CONTRIBUTING.md#need-to-test-a-pr) for info on how to test a PR.

**Comment by dmeij** [comment]
I'm using a newer cordova version which has a different path for the Manifest and source files. Installing this patch: https://gist.github.com/joeljeske/68121fa6d643e0937f50458d0172e16e fixed my problem.
