### ISSUE TITLE
[Android] App icon not used on

### ISSUE THREAD

**Issue by SebT** [arnesson/cordova-plugin-firebase#88]
Hi,

I upgraded to 0.1.18 but I'm still having a blank icon for notifications on android.

Whereas the app icon is correctly set and displayed on the phone launcher.

**Comment by jackyy415** [comment]
Same problem here

**Comment by robertarnesson** [comment]
related #53

**Comment by robertarnesson** [comment]
icons have been refactored in 0.1.20. see readme
