### ISSUE TITLE
[iOS] Not receiving notifications

### ISSUE THREAD

**Issue by SebT** [arnesson/cordova-plugin-firebase#89]
Hi,

I have a problem on iOS with the Firebase notifications. 

If I send a notification with the app in the foreground, I don't see any notification but onNotificationOpen is called correctly (=normal behavior).

If the app is in the background and I send a notification, **I don't see any notification** but when I go back to the app, onNotificationOpen is called correctly. Which is pretty strange.

And last but not least, if I send a notification while the app is closed, I NEVER receive the notification.

Any help please ? I'm using an iPhone 5C with iOS 10.0.2.

**Comment by robertarnesson** [comment]
maybe related to #85? did you ever give the app permission to push notifications?

**Comment by SebT** [comment]
I did give permission yes. In the phone's settings, everything is allowed.

BUT. It seems this is only happening when using the development APNS certificate. If I use the distribution one (via exporting the app for Ad Hoc), everything seems to work fine.

**Comment by robertarnesson** [comment]
yeah this is a known issue as well. #74
