### ISSUE TITLE
Invalid registration token. Check the token format.

### ISSUE THREAD

**Issue by goodspeed666** [arnesson/cordova-plugin-firebase#892]
Hi,

I got the FCM token as below.
`dwX2_FRVt6E:APA91bFiHXejEA9PdmSNnj4MsxtP_FtknzARYfjwtPVtxWZFY3e0rIxyJRUKEgD71ryBfrD3fncIS_870BvmhRxgIXbGGStESJwUHqfnpTp98qWBVdaWo8XK72uSa28jeQX1YDq`

And I can push the notification in the firebase for all user or all platforms successfully.
But when I use the FCM token to push notification, it will shown as `Invalid registration token. Check the token format.`.

cordova cli@8.1.0
cordova-plugin-firebase@2.0.3
meteor@1.7.0.5

Thank you.

**Comment by wjsm93** [comment]
Im facing the same issue, how could you solved it? @goodspeed666

**Comment by goodspeed666** [comment]
Hi @wjsm93,

After I checked the code, I found the problem.
I replace the token with "-" to empty.
The token should be contained with the "-" character.

I hope it's helpful to you.
