### ISSUE TITLE
class file for com.google.android.gms.internal.zzbfm not found

### ISSUE THREAD

**Issue by madhurakhal** [arnesson/cordova-plugin-firebase#900]
**Describe the bug**
`platforms/android/app/src/main/java/com/marianhello/bgloc/ActivityRecognitionLocationProvider.java:68: error: cannot access zzbfm
        if (lastActivity.getType() == DetectedActivity.STILL) {
                        ^
  class file for com.google.android.gms.internal.zzbfm not found`

**To Reproduce**
install plugin and run 
`ionic cordova run android`

**Expected behavior**
Should run smothly, Should run android

**Console Logs**
`:app:javaPreCompileDebug
platforms/android/app/src/main/java/com/marianhello/bgloc/ActivityRecognitionLocationProvider.java:68: error: cannot access zzbfm
        if (lastActivity.getType() == DetectedActivity.STILL) {
                        ^
  class file for com.google.android.gms.internal.zzbfm not found`

**Plugin Version**
`cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.4 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"` 

**Smartphone (please complete the following information):**
 - Android

**Additional context**
I am using it on ionic app

**Comment by briantq** [comment]
@madhurakhal The class you reference is not from this plugin.  It appears to be from a geolocation plugin (found a matching class name here: https://github.com/QuintechDevOps/cordova-plugin-quintech-background-geolocation/blob/master/android/src/main/java/com/marianhello/bgloc/ActivityRecognitionLocationProvider.java).  I suggest you open an issue in their repository as you will likely get a faster resolution.

**Comment by madhurakhal** [comment]
@briantq Thanks a lot. You save my hours of time.
