### ISSUE TITLE
Question (This Plugin + JS SDK = good or bad ?)

### ISSUE THREAD

**Issue by philipphalder** [arnesson/cordova-plugin-firebase#92]
Is it possible to use the plugin - together with the Firebase JS SDK?
because we already implemented a lot of Realtime Database Connections. 
thanks for your amazing work :)

**Comment by khayalan-mathew** [comment]
Same question here :)

**Comment by robertarnesson** [comment]
see https://github.com/arnesson/cordova-plugin-firebase/issues/102
