### ISSUE TITLE
iOS crashlytics logs don't show any crashes when the app crashing

### ISSUE THREAD

**Issue by AhsanAyaz** [arnesson/cordova-plugin-firebase#924]
**Describe the bug**
Crashlytics not sending reports on iOS crashes

**To Reproduce**
1. Build the ios project.
2. Install `cordova plugin add cordova-app-crash` (I built it for force crashing)
3. Force a crash using the methods on the [repository](https://github.com/AhsanAyaz/cordova-app-crash)
4. Check firebase console

**Expected behavior**
It should show the crashes for iOS as well.

**Screenshots**
-

**Console Logs**
-

**Plugin Version**
```
cordova-plugin-firebase 2.0.5
```

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome
 - Version 70

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: 10.2
 - Browser Safari
 -

**Comment by briantq** [comment]
@AhsanAyaz what was the final resolution?  It would be good to post it in case others encounter similar problems.

**Comment by AhsanAyaz** [comment]
Hi @briantq 
I had to add the Pods file for crashlytics to work on iOS. I assumed this would be a simple plugin installation thing but didn't know the Crashlytics and Fabric Pods had to be installed.
I guess this information is missing from the readme. I'll raise a PR for this.
