### ISSUE TITLE
[iOS] Crash on logEvent

### ISSUE THREAD

**Issue by SebT** [arnesson/cordova-plugin-firebase#93]
Greetings,

I have a huge issue with this plugin. On my iPhone (iOS 10.1.1) at start up I have the following message : 
```<FIRInstanceID/WARNING> Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"```

This happened in development mode in XCode. 

Then as soon as I call `logEvent`, the app crashes with the following stack : 
```
2016-11-14 12:23:48.356873 Meteojob Beta[738:507444] -[NSNull count]: unrecognized selector sent to instance 0x38737ba0
2016-11-14 12:23:48.358342 Meteojob Beta[738:507444] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x38737ba0'
*** First throw call stack:
(0x1bc76e07 0x1aed7077 0x1bc7c515 0x1bc7a589 0x1bb9ff08 0x131289 0x131cd9 0x15ada1 0x15ab61 0x502d67 0x50eed9 0x506215 0x510de1 0x510be9 0x1b4d2937 0x1b4d248c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I have no idea if that stack trace has meaning to you, I don't know how to get a human readable stack from xcode. It came from the thread FIRAnalyticsQueue and the problematic line of code is `[FIRAnalytics logEventWithName:name parameters:parameters];`

This is a recent problem as I could logEvent without problems before updating the plugin.

**Comment by SebT** [comment]
Ok my bad, I was calling `logEvent` without any data (second parameter was `undefined`).

I'm not sure this should throw an exception though. Maybe this should be fixed.

**Comment by ValentinKlinghammer** [comment]
Thanks man, I was scratching my head on this one.

**Comment by philipphalder** [comment]
Does anyone know a good tutorials, best-practice documentation on "Tracking Events" with Firebase Analytics? thank you :)
