### ISSUE TITLE
App Crash on IOS 9.3 

### ISSUE THREAD

**Issue by fx69005** [arnesson/cordova-plugin-firebase#94]
Hello, I use your plugin for my ionic project. It's works perfectly on android device but crash at start on IOS device. I don"t know why. I insert my GoogleService-info.plist like google-services.json. Can u help me please . the only information missed on Firebase App is my App Store ID
 because i work on dev app .

Best regards

**Comment by SebT** [comment]
Related to #93 ?

**Comment by fx69005** [comment]
No sorry , but my App crash on SplashScreen . its not a problem to logEvent() function.

**Comment by SebT** [comment]
What does the XCode console say about the crash ?

**Comment by fx69005** [comment]
I dont use xcode. My porject is on windows.  But. I will try to install my
porject on osx fot test soon
