### ISSUE TITLE
Invalid or incorrect token

### ISSUE THREAD

**Issue by wjsm93** [arnesson/cordova-plugin-firebase#947]
Im using the getToken() method, but this method is always returning de Instance Id, for example: "f1jO_Zh7SXQ:APA91bHKLzTeEcqwccrthnBJlIFWf2IhAHYzsJhuUTblZA2v5TZwnqQ4jvtMx6A-RCFB5VQxEoePTrFmgq2QrU0FoK2w2Gb_xaACYYV60UnKkic2bDx2e-RDVqJb_4IPycDB1YOF3O2T" then, when i try to send a push notification from my server to that token it always fail.

PD: When i send push notifications from Firebase Console it's working!

1. Install plugin
2. Call getToken() method

**Screenshots**
![captura de pantalla 2018-11-15 a la s 18 56 07](https://user-images.githubusercontent.com/16049195/48584328-2f74e400-e908-11e8-8487-aa24d3d8504e.png)

**Plugin Version**
2.0.5

**Smartphone):**
 - OS: iOS
 - Browser: Native device
 - Version: iOS 12.0.1

**Comment by briantq** [comment]
@wjsm93 Did you say that it is working when you push from the FB console?  If so, doesn't that suggest there is something incorrect in your server code?  Are you using the Firebase Admin SDK?  I found using that eliminated some hiccups I was having.

**Comment by wjsm93** [comment]
Hi @briantq you were right! Thanks!
