### ISSUE TITLE
Custom events on Ionic framework does not work.

### ISSUE THREAD

**Issue by ColDrekken** [arnesson/cordova-plugin-firebase#96]
Hi, first of all, thx for this nice plugin. It works perfect for me on a non Ionic framework based app but after i switch to work with Ionic and Angular i was not able to get custom events running by using LogEvent().

If i try on browser i get : Uncaught TypeError: Cannot read property 'logEvent' of undefined

But also in Android Emu it does not work. 

The automatic events from Firebase are working.

To be honest, im just a beginner in Javascript or angular. I tried to figure it out and will go on but some help would be really nice. 

Did anybody get this running?

Many Thx in advanced

**Comment by ValentinKlinghammer** [comment]
You will probably need to wait for the deviceReady event.

```typescript
this.platform.ready().then(() => {
  window.FirebasePlugin.logEvent('Device is ready');
});
```

**Comment by robertarnesson** [comment]
event tracking is working. two other pointers are to read the firebase docs carefully, because there are pre-defined events you can use and there are true custom events. Custom events require you to enable bigquery (and billing) to view the event data
