### ISSUE TITLE
How to push notification to specific user (username)?

### ISSUE THREAD

**Issue by psmump** [arnesson/cordova-plugin-firebase#97]
For example user login ,after the user successfully login i will assign it the topics as the username : window.FirebasePlugin.subscribe(localStorage.getItem('username_email')); , but i cant add new the topics so that i can send the push notification to specific user(username). Any suggestion so i can fix this problem ? i already use all verison from 0.0.13 untill 0.0.18 .. but until now it still not work

**Comment by robertarnesson** [comment]
use the device token, targeting a single user/device is what they are for. read the documentation
