### ISSUE TITLE
[Feature] implement logging of current screen

### ISSUE THREAD

**Issue by NoelDeMartin** [arnesson/cordova-plugin-firebase#98]
Although the logEvent method is available and the example in the documentation is the following:

`window.FirebasePlugin.logEvent("page_view", {page: "dashboard"});`

There is a specific method in the Firebase SDK to log a page view. This method is called setCurrentScreen and is available both in [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#setCurrentScreen(android.app.Activity,%20java.lang.String,%20java.lang.String)) and [iOS](https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#/c:objc(cs)FIRAnalytics(cm)setScreenName:screenClass:).

**Comment by robertarnesson** [comment]
I'll happily take a PR on this

**Comment by NoelDeMartin** [comment]
@robertarnesson I could do it for Android but I haven't done any programming in iOS. I could to the Android part and have it on standby until someone can complete the iOS part.

**Comment by robertarnesson** [comment]
You can go ahead and make a PR for the android bit, me or someone else can fix ios later
