### ISSUE TITLE
GoogleService-Info.plist alredy exist

### ISSUE THREAD

**Issue by fer1994** [arnesson/cordova-plugin-firebase#982]
good morning

I have the following problem, when I compile a project in ios, I miss the error that I left in the image, someone knows what may be happening.

regards

![image](https://user-images.githubusercontent.com/12781105/50591106-9b85ba00-0e6c-11e9-9a45-0315638d6e51.png)

**Comment by WeihangTang** [comment]
I'm having the same issue when I tried to run
```ionic cordova platform add ios```
or
```ionic cordova plugin add cordova-plugin-firebase```
Any idea how to solve this issue ?
