### ISSUE TITLE
Crashlytics found an invalid API key: null

### ISSUE THREAD

**Issue by Vane101** [arnesson/cordova-plugin-firebase#989]
I have been getting the flowing error recently, and I don't know why its suddenly an issue.
"Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance."

I have the google-services.json in the right places. What API key do they want? 
I did update Android Studio to version 3.3 not sure if that has an effect.

**Comment by Vane101** [comment]
This worked for me: https://stackoverflow.com/questions/52614015/invalid-crashlytics-api-key-error-when-upgrading-to-android-gradle-plugin-3-3-0

**Comment by adipascu** [comment]
@Vane101 Please reopen, this is not fixed in cordova-plugin-firebase .
Does anybody have a workaround that can live inside config.xml ?

**Comment by paulsUsername** [comment]
I'm getting this whenever I run an instrument test. Any idea on how to solve it?

**Comment by IgorGanapolsky** [comment]
What is the solution?  I am seeing this error in android samples on github?
