### ISSUE TITLE
Wrong and Misleading Notifications Icons Docs

### ISSUE THREAD

**Issue by guylando** [arnesson/cordova-plugin-firebase#994]
Those docs: https://github.com/arnesson/cordova-plugin-firebase/blob/master/docs/NOTIFICATIONS.md
seem to be totally wrong.
Both style.xml and colors.xml are not used at all.
The style.xml is not copied at all to the cordova android platform folder after build, and same for the icons under /res/native/android/res/..
The colors.xml which appears in the cordova android platform folder comes from /plugins/cordova-plugin-firebase/src/android/colors.xml and the /res/native/android/res/values/colors.xml is again unused.
Any thoughts on this?

Using cordova-plugin-firebase version 0.1.25.
android 7.1.4.
cordova 8.1.2.

**Comment by briantq** [comment]
I concur.  I imagine the documentation matched the code at some point but no longer works...

**Comment by briantq** [comment]
I updated the documentation after experimenting with my plugin.  @guylando let me know if the new documentation makes sense or not.  I can definitely make changes if something is confusing.
