### ISSUE TITLE
FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by soulemanou** [arnesson/cordova-plugin-firebase#996]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by soulemanou** [comment]
Hello guys i have being having these issue for a long time .I don't really know how to solve it .i tried so many things but nothing works.its being a real nightmare for me .please please please someone help me .

**Comment by RobinGiel** [comment]
I am having the same problem since yesterday, I'm working on getting a solution for this problem, if I have a fix or work around I will post it, in any case hopefully someone else has a solution before me.

**Comment by soulemanou** [comment]
thank you for  answer @RobinGiel . i am currently trying it out. but i had one question tho . Does push notification work on Xcode 10 simulator ? cause i have being trying on it

**Comment by soulemanou** [comment]
sorry to distrub you again @RobinGiel  but it still doesn't work. i am using ionic framework  and more precisely cordova-plugin-firebase for push notification .

**Comment by soulemanou** [comment]
@brainssolutions  the method is implemented in my AppDelegate+FirebaseFile.m file but is not called for some reason.

**Comment by soulemanou** [comment]
@brainssolutions  did you find anything?

**Comment by brainssolutions** [comment]
@soulemanou 

Turning between the various reports I found a person who a long time ago I had the same problem, I turn the answer that worked for him:

`Check the Capabilities tab in Xcode before you build the app. Even though my App ID had notifications enabled, this was turned off in Xcode after my last Xcode update. I had to turn it on there, then remove and re-add the iOS cordova platform in my app. After that, it started working. 

Firstly I changed the build system to Legacy in File -> Project Settings.
Secondly, I used an Authentication APN Key (not Certificate as mentioned in the Medium guide, see https://firebase.google.com/docs/cloud-messaging/ios/certs).
add to config.xml
<platform name="ios">
  <config-file target="*-Info.plist" parent="UIBackgroundModes">
      <array>
        <string>remote-notification</string>
      </array>
    </config-file>
</platform>
Didn't do anything else of your guide but this still fixed it for me.
Thanks so much. `

at the moment I can not try these suggestions but tomorrow I will try to verify. 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by soulemanou** [comment]
@brainssolutions thank you for your answer . i have just tried all the suggestions above but had no luck . none of them worked for me. hope you have better luck

**Comment by soulemanou** [comment]
@brainssolutions  please if you find anything else just let me know

**Comment by RobinGiel** [comment]
@soulemanou I'm currently not using the emulator to receive push notification, only devices. 
If your building the ionic app using Xcode 10 remember to use the legacy build going to the menu at File -> project settings and select the Build system - Legacy Build System and try building it again

**Comment by RobinGiel** [comment]
@soulemanou  check out this article about the legacy build[]( https://ionic.zendesk.com/hc/en-us/articles/360009511574-2018-09-21-Building-Locally-using-Xcode-10)

**Comment by brainssolutions** [comment]
@soulemanou Can you post the log that you see in debug?

**Comment by soulemanou** [comment]
**FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented**  . this is the error i recieve on the iphone simulator everytime i recieve a notification on it.

**Comment by soulemanou** [comment]
@brainssolutions the thing is that i have implemented this method  in my Appdelegate.m file  and it is even  already implemented in my AppDelegate+FirebasePluginFile.m file but its not being called .Is there something else  i have to do after that?

**Comment by brainssolutions** [comment]
Hello
I'm sorry for late.

I solved the problem by implementing this code in my Cordova config file.

https://github.com/arnesson/cordova-plugin-firebase/issues/997#issuecomment-461957604

**Comment by DavidSousa** [comment]
Hey @soulemanou I managed to solve this while also fixing the issue I opened some while ago #990 

Noticed that the problem is in the function grantPermission in FirebasePlugin.m

Changed its implementation to the one you can find in my [fork](https://github.com/TruewindIT/cordova-plugin-firebase/blob/master/src/ios/FirebasePlugin.m) and it's now working as intended.

Also, just to clarify, this is my notification flow for iOS:

* Call hasPermission and based on its result:
  * true - call getToken
  * false - call grantPermission and getToken afterwards

From this moment on I can now send notifications and data messages without getting the error FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by JoseGeorges8** [comment]
@DavidSousa Hey David, I implemented the grantPermission snippet you provided, and indeed I receive the data now, however I'm not getting a notification bar. Have you encounter this?

**Comment by edytavares14** [comment]
In my case, solve the problem this way :
1 Open the file ** AppDelegate+FirebasePlugin.m** (usualy is in the folder Plugins)
2 Find the method ** swizzledDidFinishLaunchingWithOptions** under the ** [FIRApp configure];**
put this **[FIRMessaging messaging].delegate = self;**
