### ISSUE TITLE
Offline ios device that turns online didn't receive message

### ISSUE THREAD

**Issue by gihangt** [arnesson/cordova-plugin-firebase#999]
**Describe the bug**
At the moment I’m having a problem with some of the iOS devices when the device is offline. Base on firebase documentation device should receive notification when it back to online. Android is working perfectly fine but ios device is not working most of the time even payload has apns.expiration set. Not sure what’s wrong. I have created a support ticket in Firebase but I got the following feedback.

"Firebase currently doesn't have official support for Cordova, and as such, issues related to integrating Firebase with third-party libraries or tools are out of our scope of support. We can only be helpful for troubleshooting issues specific to using Firebase"

**To Reproduce**
- Create a payload set aspn-expirations 1h or more (add 1h or more to current utc) 
   * same issue without aspn-expiratoins
- Set all iOS device to offline 
- Send notification (I’m sending notification through cloud function)
- Set all iOS device to online after 10 or 15 min. 

**Expected behavior**
Receive notification to all iOS devices

**Plugin Version**
2.0.5

**Smartphone (please complete the following information):**
Scenario: - All Devices are offline (Expiry 1h)
                  Turn on after 15min
                 - iPhone 7 (iOS 12.1) **Not** Received
                 - iPhone 6s (IOS 12.1) Received
                 - iPhone se (iOS 11.4.1) Received
                 - iPad 4 (10.3.3) **Not** Received

**Additional context**
Payload
const payload = {
          notification: {
            title: ‘All Offline’,
            body: ‘All devices are offline. Turn them on after 15min’,
          },
          condition: condition,
          android: {
            ttl: ‘3600000’,
            priority: ‘high’,
            notification: {
              sound: 'default',
              icon: 'notification_icon',
            },
          },
          apns: {
            headers: {
              'apns-expiration': ‘1549382358’,
              'apns-priority': ‘10’,
            },
            payload: {
              aps: {
                sound: 'default',
              },
            },
          },
        };

**Comment by brainssolutions** [comment]
@gihangt I solved the problem by implementing this code in my Cordova config file.

https://github.com/arnesson/cordova-plugin-firebase/issues/997#issuecomment-461957604

**Comment by gihangt** [comment]
@brainssolutions Awesome it worked. Tested on iPhone 7 (iOS 12.1) and iPad4 ( iOS 10.3.3). 
Cheers
